### ISSUE TITLE
Error enter ctl11

### ISSUE THREAD

**Issue by Infernaljason** [TechnicPack/TechnicLauncher#1006]
It appears that when I walk:
Stack Trace:
Exception:IndexOutOFBoundsException
Message:Index:0, Size: 0
Trace : 
         java.util.arraylist.rengecheck(unknow Source)
         java.util.arraylist.get(unknow Source)
         org.sputcraft.launcher.skin.newscomponent.setuparticles(newscomponent.java:60)
         org.spoutcraft.launcher.skin.newscomponent.loadarticles(newscomponent.java:46)
         org.spoutcraft.launger.Launcher$2.run(launcher.java:105)

**Comment by GuidoDGod** [comment]
yap '-'
plz help

**Comment by CannibalVox** [comment]
cracked launcher
