### ISSUE TITLE
Launcher Crashing Before Starts

### ISSUE THREAD

**Issue by Olionkey** [TechnicPack/TechnicLauncher#1007]
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439
    Selected Pack: null
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_67 64 bit
    Total Memory: 183 MB
    Max Memory: 2720 MB
    Memory Free: 144 MB
    CPU Cores: 8

**Comment by CannibalVox** [comment]
It looks like your launcher has failed to autoupdate to the change we made a few weeks ago.  Download the latest version from http://www.technicpack.net/

**Comment by Olionkey** [comment]
ok thanks
