### ISSUE TITLE
Laucher Error

### ISSUE THREAD

**Issue by Pascalwolf** [TechnicPack/TechnicLauncher#1008]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:112)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:201)
        org.spoutcraft.launcher.Launcher$3.run(Launcher.java:124)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 38 MB
    Max Memory: 247 MB
    Memory Free: 11 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
Cracked
