### ISSUE TITLE
Guncraft mod error

### ISSUE THREAD

**Issue by Master007hd** [TechnicPack/TechnicLauncher#101]
Stack Trace:
    Exception: MalformedURLException
    Message: no protocol: tekkit
    Trace:
        java.net.URL.<init>(Unknown Source)
        java.net.URL.<init>(Unknown Source)
        java.net.URL.<init>(Unknown Source)
        org.spoutcraft.launcher.util.Download.<init>(Download.java:55)
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:44)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:428)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

**Comment by Salynne** [comment]
I have no idea what is going on here. Can you give me more details?

**Comment by Master007hd** [comment]
Sorry but just tried to run guncraft and this error came up and it told me to copy it and paste It on the forums here. Sorry bout no info, any more probs just ask.
