### ISSUE TITLE
Unexpected Error!

### ISSUE THREAD

**Issue by rogelionarag** [TechnicPack/TechnicLauncher#1015]
Selected Pack: null
6.Stack Trace:
7.    Exception: IndexOutOfBoundsException
8.    Message: Index: 0, Size: 0
9.    Trace:
10.        java.util.ArrayList.rangeCheck(Unknown Source)
11.        java.util.ArrayList.get(Unknown Source)
12.        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
13.        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
14.        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)
15. 
16.System Information:
17.    Operating System: Windows 7
18.    Operating System Version: 6.1
19.    Operating System Architecture: x86
20.    Java version: 1.7.0_60 32 bit
21.    Total Memory: 46 MB
22.    Max Memory: 247 MB
23.    Memory Free: 15 MB
24.    CPU Cores: 3

**Comment by CannibalVox** [comment]
cracked launcher
