### ISSUE TITLE
minecaft crashes

### ISSUE THREAD

**Issue by bluemoboy** [TechnicPack/TechnicLauncher#1019]
Stack Trace:
Exception:  IndexOutOfBoundsException
Message:  Index:  0, Size:  0
Trace:
java. until.ArrayList.rangeCheck(Unknown  Source)
java.until.ArrayList.get (Unkown Source)
org.spoutcraft. launcher. skin. NewsComponent. setupArticles (NewsComponent.java:60
org. spoutcraft. Launcher. skin. NewsComponent. LoadArticles (NewsComponent.java: 46)
org. spoutcraft. launcher. Launcher$2. run (Launcher.java:105)

**Comment by CannibalVox** [comment]
cracked launcher
