### ISSUE TITLE
i cant open voltz 1.1.0.1

### ISSUE THREAD

**Issue by connordude2345** [TechnicPack/TechnicLauncher#102]
Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: voltz Minecraft version: 1.4.7
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.8.0-ea 64 bit
    Total Memory: 152 MB
    Max Memory: 2730 MB
    Memory Free: 68 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
The latest version of Voltz has been having some issues.
