### ISSUE TITLE
Https://github.com/TechnicPack/TechnicLauncher/issues

### ISSUE THREAD

**Issue by emir26** [TechnicPack/TechnicLauncher#1020]
Seçilen Paketi: Tekkit
Yığın İzleme:
     İstisna: IndexOutOfBoundsException
     Mesaj: Dizin: 0, Boyut: 0
     Trace:
         java.util.ArrayList.rangeCheck (Bilinmeyen Kaynak)
         java.util.ArrayList.get (Bilinmeyen Kaynak)
         org.spoutcraft.launcher.skin.NewsComponent.setupArticles (NewsComponent.java:60)
         org.spoutcraft.launcher.skin.NewsComponent.loadArticles (NewsComponent.java:46)
         org.spoutcraft.launcher.Launcher $ 2.run (Launcher.java:105)
 
Sistem Bilgisi:
     İşletim Sistemi: Windows 7
     İşletim Sistemi Sürümü: 6.1
     İşletim Sistemi Mimarisi: x86
     Java sürümü: 1.7.0_72 32 bit
     Toplam Bellek: 37 MB
     Maksimum Bellek: 247 MB
     Bellek Free: 7 MB
     CPU Çekirdek: 2

**Comment by CannibalVox** [comment]
cracked launcher
