### ISSUE TITLE
techinc

### ISSUE THREAD

**Issue by migas03** [TechnicPack/TechnicLauncher#1022]
java.util.ArrayList.RangeCheck (origem desconhecida )
        java.util.ArrayList.get (origem desconhecida )
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles ( NewsComponent.java:60 )
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles ( NewsComponent.java:46 )
        org.spoutcraft.launcher.Launcher $ 2.run ( Launcher.java:105 )

**Comment by CannibalVox** [comment]
cracked launcher
