### ISSUE TITLE
techinich launcher error report

### ISSUE THREAD

**Issue by dariomonster** [TechnicPack/TechnicLauncher#1024]
```
Selected Pack: Material Energy^3
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: x86
    Java version: 1.7.0_51 32 bit
    Total Memory: 47 MB
    Max Memory: 247 MB
    Memory Free: 18 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
cracked launcher

**Comment by dariomonster** [comment]
ok
