### ISSUE TITLE
CTL 15(Cracked Technich Launher) HELP ME!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Minepack3** [TechnicPack/TechnicLauncher#1025]
Help me!! errors:Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
Why would you come to us, the creators of the Technic Launcher, to help with your CRACKED technic launcher?
