### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hgaaaa** [TechnicPack/TechnicLauncher#1027]
Launcher Build: 431
    Selected Pack: null
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.RangeCheck(ArrayList.java:547)
        java.util.ArrayList.get(ArrayList.java:322)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.10
    Operating System Architecture: x86_64
    Java version: 1.6.0_65 64 bit
    Total Memory: 81 MB
    Max Memory: 252 MB
    Memory Free: 48 MB
    CPU Cores: 8

What do id do

**Comment by Hgaaaa** [comment]
Please help

**Comment by CannibalVox** [comment]
It looks like there was a problem updating your launcher to the new system!  Download the latest from http://www.technicpack.net/ to fix this.
