### ISSUE TITLE
Can't start my launcher

### ISSUE THREAD

**Issue by axzxc1236** [TechnicPack/TechnicLauncher#1028]
I can't open my technic launcher since yesterday, please help!
I just delete the folder which I have technic launcher and modpacks.
After I opened my launcher, I saw these things.
https://gist.github.com/axzxc1236/e005ca9598b5602060d3

**Comment by CannibalVox** [comment]
If you're going to delete the folder, you also need to delete %appdata%.technic

**Comment by CannibalVox** [comment]
let me know if that fixes it

**Comment by axzxc1236** [comment]
hmm....doesn't solve my problem.
After I login with my minecraft account, I got this.
(Freezed like 5 minutes before I am reporting this to you.)
http://i.minus.com/jbenIZ6dlQGp3v.png
And here is the new log.
Before I kill the program with task manager:
http://pastebin.com/CvntMPje
After I killed the launcher and restart it again and freeze again:
http://pastebin.com/ZuAvzUQF

And I noticed something like
[B#238] 2015/01/22 17:47:53 [警告] Unable to load news
net.technicpack.rest.RestfulAPIException: Timed out accessing URL [http://api.technicpack.net/news]

**Comment by axzxc1236** [comment]
I can open http://api.technicpack.net/news in my browser.

**Comment by axzxc1236** [comment]
I can see the login form but I can't use the launcher.

**Comment by axzxc1236** [comment]
I can use my technic launcher now.
