### ISSUE TITLE
Technic Launcher cracked

### ISSUE THREAD

**Issue by harceparcea** [TechnicPack/TechnicLauncher#1029]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Hexxit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 48 MB
    Max Memory: 247 MB
    Memory Free: 14 MB
    CPU Cores: 8

**Comment by CannibalVox** [comment]
cracked launcher

**Comment by harceparcea** [comment]
???

**Comment by CannibalVox** [comment]
This error report indicates that you are using a cracked launcher.  If that is not the case, download the latest technic launcher from http://www.technicpack.net/ because this one is badly out of date in addition to identifying itself as cracked.
