### ISSUE TITLE
Technic Launcher 

### ISSUE THREAD

**Issue by harceparcea** [TechnicPack/TechnicLauncher#1030]
Hexxit on premium works, but cracked will crash on start , cracked said to paste it here:

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 49 MB
    Max Memory: 247 MB
    Memory Free: 17 MB
    CPU Cores: 8

Or:
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
Cracked launcher

**Comment by harceparcea** [comment]
but what is with Cracked?

**Comment by CannibalVox** [comment]
what?

**Comment by harceparcea** [comment]
whats the problen

**Comment by harceparcea** [comment]
:(

**Comment by CannibalVox** [comment]
You're using a cracked launcher.

**Comment by harceparcea** [comment]
The problem is cracked?? [?]

**Comment by CannibalVox** [comment]
Yes.
