### ISSUE TITLE
Can't open the technic launcher

### ISSUE THREAD

**Issue by MaxPare** [TechnicPack/TechnicLauncher#1031]
When i open the launcher it immediately gives me an error:

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

I tried to delete .technic files but it still not working, please help D:

**Comment by CannibalVox** [comment]
Cracked launcher.
