### ISSUE TITLE
Technic Faliure

### ISSUE THREAD

**Issue by Jacko1015** [TechnicPack/TechnicLauncher#1033]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: amd64
    Java version: 1.7.0_65 64 bit
    Total Memory: 120 MB
    Max Memory: 835 MB
    Memory Free: 36 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Looks like your launcher has failed to update to the latest version for some reason.  Download it from http://www.technicpack.net/
