### ISSUE TITLE
My Issues Fix it pls

### ISSUE THREAD

**Issue by TEAndrei** [TechnicPack/TechnicLauncher#1034]
```
Selected Pack: null
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        sun.awt.shell.Win32ShellFolderManager2.createShellFolder(Unknown Source)
        sun.awt.shell.Win32ShellFolderManager2.getRecent(Unknown Source)
        sun.awt.shell.Win32ShellFolderManager2.get(Unknown Source)
        sun.awt.shell.ShellFolder.get(Unknown Source)
        sun.swing.WindowsPlacesBar$1.run(Unknown Source)
        sun.swing.WindowsPlacesBar$1.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        sun.swing.WindowsPlacesBar.<init>(Unknown Source)
        com.sun.java.swing.plaf.windows.WindowsFileChooserUI.updateUseShellFolder(Unknown Source)
        com.sun.java.swing.plaf.windows.WindowsFileChooserUI.installComponents(Unknown Source)
        javax.swing.plaf.basic.BasicFileChooserUI.installUI(Unknown Source)
        com.sun.java.swing.plaf.windows.WindowsFileChooserUI.installUI(Unknown Source)
        javax.swing.JComponent.setUI(Unknown Source)
        javax.swing.JFileChooser.updateUI(Unknown Source)
        javax.swing.JFileChooser.setup(Unknown Source)
        javax.swing.JFileChooser.<init>(Unknown Source)
        javax.swing.JFileChooser.<init>(Unknown Source)
        org.spoutcraft.launcher.skin.options.ImportOptions.initComponents(ImportOptions.java:149)
        org.spoutcraft.launcher.skin.options.ImportOptions.<init>(ImportOptions.java:99)
        org.spoutcraft.launcher.skin.ModpackSelector.action(ModpackSelector.java:225)
        org.spoutcraft.launcher.skin.ModpackSelector.actionPerformed(ModpackSelector.java:215)
        javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        java.awt.Component.processMouseEvent(Unknown Source)
        javax.swing.JComponent.processMouseEvent(Unknown Source)
        java.awt.Component.processEvent(Unknown Source)
        java.awt.Container.processEvent(Unknown Source)
        java.awt.Component.dispatchEventImpl(Unknown Source)
        java.awt.Container.dispatchEventImpl(Unknown Source)
        java.awt.Component.dispatchEvent(Unknown Source)
        java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        java.awt.Container.dispatchEventImpl(Unknown Source)
        java.awt.Window.dispatchEventImpl(Unknown Source)
        java.awt.Component.dispatchEvent(Unknown Source)
        java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        java.awt.EventQueue.access$200(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue$4.run(Unknown Source)
        java.awt.EventQueue$4.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue.dispatchEvent(Unknown Source)
        java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.run(Unknown Source)

**Comment by CannibalVox** [comment]
Cracked launcher.
