### ISSUE TITLE
Plz help i can't open a launcher

### ISSUE THREAD

**Issue by BlooderBG** [TechnicPack/TechnicLauncher#1037]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.Newhttp://pastebin.com/dQRCqipQ#sComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: amd64
    Java version: 1.8.0_05 64 bit
    Total Memory: 110 MB
    Max Memory: 1342 MB
    Memory Free: 60 MB
    CPU Cores: 4

**Comment by BlooderBG** [comment]
LoL

**Comment by CannibalVox** [comment]
Cracked launcher
