### ISSUE TITLE
mod menu not working

### ISSUE THREAD

**Issue by ninjaboss50** [TechnicPack/TechnicLauncher#1047]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Hack Slash Mine
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(ArrayList.java:635)
        java.util.ArrayList.get(ArrayList.java:411)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.9.5
    Operating System Architecture: x86_64
    Java version: 1.7.0_55 64 bit
    Total Memory: 128 MB
    Max Memory: 910 MB
    Memory Free: 73 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
cracked launcher
