### ISSUE TITLE
Launcher issue

### ISSUE THREAD

**Issue by Crazyking96** [TechnicPack/TechnicLauncher#105]

**Comment by Crazyking96** [comment]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )

##     Launcher Build: 195

Stack Trace:
    Exception: MalformedURLException
    Message: no protocol: Technic Modpacks
    Trace:
        java.net.URL.<init>(Unknown Source)
        java.net.URL.<init>(Unknown Source)
        java.net.URL.<init>(Unknown Source)
        org.spoutcraft.launcher.util.Download.<init>(Download.java:55)
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:44)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:428)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)

##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_15 32 bit
    Total Memory: 87 MB
    Max Memory: 989 MB
    Memory Free: 31 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
This is an issue with the modpack you tried installing. I have fixed it from crashing the launcher, it will tell them to fix their zip url on the website soon too.
