### ISSUE TITLE
Techniclauncher un expected error ım from turkish ı dont speak english sorry

### ISSUE THREAD

**Issue by blackrost** [TechnicPack/TechnicLauncher#1059]
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 221

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.technic.rest.RestAPI.shouldUsePatch(RestAPI.java:343)
        org.spoutcraft.launcher.technic.rest.RestAPI.getMinecraftMD5(RestAPI.java:326)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:45)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:325)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_09 64 bit
    Total Memory: 153 MB
    Max Memory: 1809 MB
    Memory Free: 109 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
This launcher is very, very old.  Please download the latest from http://www.technicpack.net/
