### ISSUE TITLE
technic launcher update error

### ISSUE THREAD

**Issue by AddisontheAzelf** [TechnicPack/TechnicLauncher#106]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 195

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:410)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:134)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_09 64 bit
    Total Memory: 118 MB
    Max Memory: 910 MB
    Memory Free: 72 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
What modpack were you trying to run when this happened?

**Comment by AddisontheAzelf** [comment]
yogsbox i think

**Comment by CoolisTheName007** [comment]
Same problem, Tekkit Lite modpack. Wanted to update to 0.5.7 from 0.5.6, but failed; resetting the modpack, and launching the modpack seems to have fixed it. report:
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )

##     Launcher Build: 199

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:410)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:134)

##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_10 64 bit
    Total Memory: 70 MB
    Max Memory: 989 MB
    Memory Free: 15 MB
    CPU Cores: 2

**Comment by rockyfighter** [comment]
i just had this problem to but with the  Glacacticraft mod pack ( based on my judgement i think it might be a serverside issue)

**Comment by Salynne** [comment]
This shouldn't be happening anymore on newer builds of the launcher, which are automatically distributed.
