### ISSUE TITLE
I cant play!

### ISSUE THREAD

**Issue by LraeCamama** [TechnicPack/TechnicLauncher#1060]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by LraeCamama** [comment]
Please make me play again :+1:

**Comment by LraeCamama** [comment]
I wonder how to repair it :(

**Comment by CannibalVox** [comment]
cracked launcher
