### ISSUE TITLE
Some kind of error that i don't know. 

### ISSUE THREAD

**Issue by blackbatman56** [TechnicPack/TechnicLauncher#1062]
Some kind of error that i don't know. It opens the launcher, and then show the following message. HELP!

Error message:

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Hexxit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: amd64
    Java version: 1.8.0_31 64 bit
    Total Memory: 220 MB
    Max Memory: 1799 MB
    Memory Free: 161 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
cracked launcher
