### ISSUE TITLE
Launcher crash report please help

### ISSUE THREAD

**Issue by olab-** [TechnicPack/TechnicLauncher#1065]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Attack of the B-Team
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_31 32 bit
    Total Memory: 53 MB
    Max Memory: 247 MB
    Memory Free: 18 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
cracked launcher

**Comment by olab-** [comment]
So because it's a cracked launcher I can't play it no more?

**Comment by CannibalVox** [comment]
I don't care what you do, but we didn't make the cracked launcher, so don't come crying to us when it doesn't work.

**Comment by olab-** [comment]
One it was a simple yes or no question. Two I wasn't crying. And three the launcher said to report it to you guys so I did, if don't have anything beneficial to say just so, I won't judge you to badly

**Comment by CannibalVox** [comment]
It says to report to us because it is our launcher, someone else cracked it and didn't take out the part that told you to come talk to us if there was a problem.  You should go talk to dropcrack or whoever you got it from.

**Comment by CannibalVox** [comment]
Just generally don't report issues when you're using cracked software, you create problems and give nothing back.
