### ISSUE TITLE
Erro do technic laucher 4.0

### ISSUE THREAD

**Issue by CauHRS20** [TechnicPack/TechnicLauncher#1066]
Esse é o erro Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
Cracked launcher.

**Comment by CauHRS20** [comment]
Então qual o novo lançador ?

**Comment by CannibalVox** [comment]
http://www.technicpack.net/download

**Comment by CauHRS20** [comment]
Qual é o do pirata ?

**Comment by CannibalVox** [comment]
Go away.

**Comment by CauHRS20** [comment]
Escrevi errado era qual é o pirata laucher ?

**Comment by CannibalVox** [comment]
We don't make pirate launchers.

**Comment by CannibalVox** [comment]
Buy minecraft.

**Comment by CauHRS20** [comment]
Até compraria mas minha situação na minha casa ta dificil
