### ISSUE TITLE
Cracked technic launcher issue

### ISSUE THREAD

**Issue by Majestic88** [TechnicPack/TechnicLauncher#1067]
```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.RangeCheck(ArrayList.java:547)
        java.util.ArrayList.get(ArrayList.java:322)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.7.5
    Operating System Architecture: x86_64
    Java version: 1.6.0_65 64 bit
    Total Memory: 81 MB
    Max Memory: 123 MB
    Memory Free: 49 MB
    CPU Cores: 4

please help its the cracked version i wanna play :(

**Comment by CannibalVox** [comment]
The issue is that you're using a cracked launcher.

**Comment by Majestic88** [comment]
i don't understand how thats the issue it does the same thing it crashes i have opened it before on snow leopard

**Comment by CannibalVox** [comment]
buy minecraft

**Comment by Majestic88** [comment]
i will soon lol  :D

**Comment by CannibalVox** [comment]
when you do, you can get the real launcher from http://www.technicpack.net/ and it will not crash.
