### ISSUE TITLE
downloaded aether pack and it won't work

### ISSUE THREAD

**Issue by carlosny** [TechnicPack/TechnicLauncher#107]
hey when i press add mod pack it always crashes and this time i added the aether pack and it said to report to here so i did but yeah it won't work

**Comment by Salynne** [comment]
You didn't actually give me the report it told you to send me. Please reopen and update this with the report information if you get any.

**Comment by carlosny** [comment]
this is with a different mod pack but it happens to all of them rake of kingdoms etc (Error retrieving information for selected pack: tale-of-dimentions

--- On Tue, 3/5/13, Dalton J Pelc notifications@github.com wrote:
