### ISSUE TITLE
my techinicpack not open

### ISSUE THREAD

**Issue by minebo** [TechnicPack/TechnicLauncher#1075]
Pacote Selecionado: null
Stack Trace:
    Exceção: IndexOutOfBoundsException
    Mensagem: Index: 0, Tamanho: 0
    Trace:
        java.util.ArrayList.rangeCheck (origem desconhecida)
        java.util.ArrayList.get (origem desconhecida)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles (NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles (NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher $ 2.run (Launcher.java:105)

Informações sobre o sistema:
    Sistema operacional: Windows 7
    Versão do sistema operacional: 6.1
    Sistema operacional Arquitetura: x86
    Java versão: 1.8.0_31 32 bit
    Memória Total: 53 MB
    Max Memória: 247 MB
    Memória livre: 24 MB
    Núcleo do processador: 2

**Comment by CannibalVox** [comment]
Download the latest launcher from http://www.technicpack.net/
