### ISSUE TITLE
Exception while launching TechnicLauncher

### ISSUE THREAD

**Issue by bennettmcelwee** [TechnicPack/TechnicLauncher#1078]
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439
    Selected Pack: null
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.RangeCheck(ArrayList.java:547)
        java.util.ArrayList.get(ArrayList.java:322)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.8.5
    Operating System Architecture: x86_64
    Java version: 1.6.0_65 64 bit
    Total Memory: 81 MB
    Max Memory: 252 MB
    Memory Free: 44 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
This version is super duper old and it didn't auto-update to the new one even though it was supposed to!  Please update to the latest launcher at http://www.technicpack.net/

**Comment by bennettmcelwee** [comment]
Thanks. Updated the launcher and now everything is awesome.
