### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by mario9991** [TechnicPack/TechnicLauncher#1088]
Hi.
I have got a problem with launch Technic Launcher

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)
Please help!

**Comment by CannibalVox** [comment]
Either your launcher is very old or you are on a cracked launcher.  Please go to http://www.technicpack.net/ to download a new one.

**Comment by mario9991** [comment]
Do I have the original minecraft ?!
Because I don´t have a original mc. Please help.
It is somewhere cracked launcher,that works?
