### ISSUE TITLE
Launcher Error

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#1092]
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439
    Selected Pack: null
Stack Trace:
    Exception: Error
    Message: posix_spawn is not a supported process launch mechanism on this platform.
    Trace:
        java.lang.UNIXProcess$1.run(UNIXProcess.java:105)
        java.lang.UNIXProcess$1.run(UNIXProcess.java:94)
        java.security.AccessController.doPrivileged(Native Method)
        java.lang.UNIXProcess.<clinit>(UNIXProcess.java:92)
        java.lang.ProcessImpl.start(ProcessImpl.java:130)
        java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        org.spoutcraft.launcher.entrypoint.Start.launch(Start.java:135)
        org.spoutcraft.launcher.entrypoint.Start.main(Start.java:46)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.9.5
    Operating System Architecture: x86_64
    Java version: 1.8.0_31 64 bit
    Total Memory: 123 MB
    Max Memory: 1820 MB
    Memory Free: 92 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
This launcher version is very old but for some reason it didn't auto-update.  You can get the latest version from http://www.technicpack.net/ and it does not have this problem.
