### ISSUE TITLE
Tehnic and Hexxit launcher Stack Trace error

### ISSUE THREAD

**Issue by CrazyCatLV** [TechnicPack/TechnicLauncher#1095]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
Looks like either the launcher is out of date and isn't updating for some reason, or it's a cracked launcher. In either case, get the latest from http://www.technicpack.net/
