### ISSUE TITLE
I don't know what''s going on with tekitt

### ISSUE THREAD

**Issue by Lapuotas** [TechnicPack/TechnicLauncher#1102]
Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.8.0_31 64 bit
    Total Memory: 119 MB
    Max Memory: 907 MB
    Memory Free: 48 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
This is a cracked launcher.  You didn't get it from us.
