### ISSUE TITLE
Help Pleaz!

### ISSUE THREAD

**Issue by DMinerz** [TechnicPack/TechnicLauncher#1106]
Selected Pack: Tekkit

6.Stack Trace:
1.    Exception: IndexOutOfBoundsException
2.    Message: Index: 0, Size: 0
3.    Trace:
4. ```
      java.util.ArrayList.rangeCheck(Unknown Source)
   ```
5. ```
      java.util.ArrayList.get(Unknown Source)
   ```
6. ```
      org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
   ```
7. ```
      org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
   ```
8. ```
      org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)
   ```

16.System Information:
1.    Operating System: Windows 8.1
2.    Operating System Version: 6.3
3.    Operating System Architecture: x86
4.    Java version: 1.8.0_31 32 bit
5.    Total Memory: 51 MB
6.    Max Memory: 247 MB
7.    Memory Free: 11 MB
8.    CPU Cores: 2

**Comment by CannibalVox** [comment]
This version is either very old and isn't autoupdating for some reason, or is a cracked launcher.  Please go to http://www.technicpack.net to get an updated launcher.
