### ISSUE TITLE
Please How To Fix This Error !!

### ISSUE THREAD

**Issue by kentjosh** [TechnicPack/TechnicLauncher#1107]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
Hi, either you're using an old version of the launcher that isn't auto-updating for some reason, or you're using a cracked launcher.  Please download the latest at http://www.technicpack.net/
