### ISSUE TITLE
Unexpected Error!

### ISSUE THREAD

**Issue by AndreYbm31** [TechnicPack/TechnicLauncher#1110]
This is the error:

Stack Trace:
            Exception: IndexOutOfBoundsException
            Message:  Index: 0, Size: 0
            Trace:
                  java.util.ArrayList.rangeCheck(Unknow Source)
                  java.util.ArrayList.get (Unknow Source)
                  org.spoutcraft.launcer.skin.NewsComponent.setupArticles (NewComponent.java:60)
                  org.spoutcraft.launcer.skin.NewsComponent.setupArticles (NewComponent.java:46)
                  org.spoutcraft.launcer.Launcer$2.run(Launcher.java:105)

What can i do? Please, help me.

**Comment by CannibalVox** [comment]
You either have a very old version which is not updating for some reason, or you have a cracked launcher.  In either case, visit http://www.technicpack.net/
