### ISSUE TITLE
Ubuntu 14.10 Technic won't launch

### ISSUE THREAD

**Issue by JohnDoe000** [TechnicPack/TechnicLauncher#1113]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(ArrayList.java:653)
        java.util.ArrayList.get(ArrayList.java:429)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Linux
    Operating System Version: 3.16.0-30-generic
    Operating System Architecture: amd64
    Java version: 1.8.0_31 64 bit
    Total Memory: 106 MB
    Max Memory: 823 MB
    Memory Free: 38 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
This is a cracked launcher.  You didn't get it from us.
