### ISSUE TITLE
What's happening ?

### ISSUE THREAD

**Issue by locani** [TechnicPack/TechnicLauncher#1114]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.8.0 64 bit
    Total Memory: 154 MB
    Max Memory: 1797 MB
    Memory Free: 100 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
This is a cracked launcher.  You didn't get it from us.
