### ISSUE TITLE
Launcher crashing while Launching 

### ISSUE THREAD

**Issue by Kosma222** [TechnicPack/TechnicLauncher#1115]
idk what but its broken that something while im lauching technicpack cracked tehers an error that crashes and i need to close it help ME!!!!! by teh way heres the problem

```
Launcher Build: 0

Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_40 32 bit
    Total Memory: 52 MB
    Max Memory: 247 MB
    Memory Free: 22 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
This is a cracked launcher.  You didn't get it from us.
