### ISSUE TITLE
Issue with updating voltz

### ISSUE THREAD

**Issue by skill4kill** [TechnicPack/TechnicLauncher#112]
Still having a problem with updating "latest"

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 195

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: voltz Minecraft version: 1.1
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_09 32 bit
    Total Memory: 69 MB
    Max Memory: 989 MB
    Memory Free: 30 MB
    CPU Cores: 2

**Comment by Saron** [comment]
having same problem, recommended build works fine, but choosing latest 1.0.13 and the launcher tries to download minecraft.jar, then mc-patch then repeats itself a few times then generates that error

**Comment by Salynne** [comment]
Voltz was fixed, 1.1 was a corrupt build.
