### ISSUE TITLE
Problems with Java in Technic Pack

### ISSUE THREAD

**Issue by xxmartinxx248** [TechnicPack/TechnicLauncher#1120]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

I don´t know what to do

**Comment by CannibalVox** [comment]
This is either a very out of date launcher which isn't autoupdating for some reason, or a cracked launcher.  Either way, head to http://www.technicpack.net/ to pick up the latest.
