### ISSUE TITLE
My Tecnhik Launcher dont open.

### ISSUE THREAD

**Issue by Eragon02** [TechnicPack/TechnicLauncher#1126]
My technik launcher dont open. Why?

Selected Pack: Tekkit
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_67 32 bit
    Total Memory: 39 MB
    Max Memory: 247 MB
    Memory Free: 7 MB
    CPU Cores: 4

**Comment by omrkh** [comment]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:40)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:40)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:40)

**Comment by omrkh** [comment]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
These are all either cracked launchers or very old versions of the launcher that are not autoupdating for some reason.  Head to http:///www.technicpack.net/ and download the latest
