### ISSUE TITLE
Socks Proxy Support

### ISSUE THREAD

**Issue by Salynne** [TechnicPack/TechnicLauncher#113]
-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=9999

Need to add something to allow these args to pass through to minecraft.

**Comment by Salynne** [comment]
Technically this is already possible using the arguments -debug and -relaunched on the launcher to prevent it from restarting the JVM.

**Comment by virtualdxs** [comment]
I'm getting unknown argument for both of these.
