### ISSUE TITLE
Help Me Please ! ! !

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#1130]
Error:

Stack Trace:
Exception: IndexOutOfBoundsException
Message: Index: 0, Size: 0
Trace:
java.util.ArrayList.rangeCheck(Unknown Source)
java.util.ArrayList.get(Unknown Source)
org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
You either have a very old launcher that didn't autoupdate for some reason or you have a cracked launcher.  If it's the first, head to http://www.technicpack.net/
