### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by SGrosser00** [TechnicPack/TechnicLauncher#1135]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Hexxit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.8.0_11 64 bit
    Total Memory: 145 MB
    Max Memory: 1639 MB
    Memory Free: 94 MB
    CPU Cores: 4

What should i doo ???

**Comment by CannibalVox** [comment]
This is a cracked launcher.  You didn't get it from us.  Go talk to whoever you got it from.
