### ISSUE TITLE
I was asked to submit this

### ISSUE THREAD

**Issue by jbwilliams** [TechnicPack/TechnicLauncher#1138]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.RangeCheck(ArrayList.java:547)
        java.util.ArrayList.get(ArrayList.java:322)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.9.5
    Operating System Architecture: x86_64
    Java version: 1.6.0_65 64 bit
    Total Memory: 81 MB
    Max Memory: 252 MB
    Memory Free: 36 MB
    CPU Cores: 8

**Comment by CannibalVox** [comment]
Hi, your launcher version is very old and isn't updating for some reason.  Get the new one from http://www.technicpack.net/

**Comment by jbwilliams** [comment]
OK, thanks!

Jon
