### ISSUE TITLE
Minecolony broken; MalformedURLException: no protocol: ConnorCox/Modpack.Minecolony

### ISSUE THREAD

**Issue by AlexKegel** [TechnicPack/TechnicLauncher#114]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 195

Stack Trace:
    Exception: MalformedURLException
    Message: no protocol: ConnorCox/Modpack.Minecolony
    Trace:
        java.net.URL.<init>(URL.java:585)
        java.net.URL.<init>(URL.java:482)
        java.net.URL.<init>(URL.java:431)
        org.spoutcraft.launcher.util.Download.<init>(Download.java:55)
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:44)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:428)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Linux
    Operating System Version: 3.2.0-38-generic-pae
    Operating System Architecture: i386
    Java version: 1.7.0_15 32 bit
    Total Memory: 194 MB
    Max Memory: 910 MB
    Memory Free: 66 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
This is an issue with the modpack you tried installing. I have fixed it from crashing the launcher, it will tell them to fix their zip url on the website soon too.
