### ISSUE TITLE
help

### ISSUE THREAD

**Issue by bosanacc1** [TechnicPack/TechnicLauncher#1141]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_40 32 bit
    Total Memory: 38 MB
    Max Memory: 247 MB
    Memory Free: 11 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
Looks like your launcher is old and isn't auto-updating for some reason.  Head to http://www.technicpack.net/ for a new one!

**Comment by bosanacc1** [comment]
I took this launcer for giving me the link of it and when I run it just me immediately closes and nothing happens
