### ISSUE TITLE
problem with the launcher

### ISSUE THREAD

**Issue by Lv-L** [TechnicPack/TechnicLauncher#115]
Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: tekketlite Minecraft version: 1.47
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecaftDownloadUtils.java:93)
org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)
org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:122)
org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

**Comment by Salynne** [comment]
This is from an outdated build of the launcher. The problem is being looked into, see issue #133
