### ISSUE TITLE
Cannot Launch: This error shows up

### ISSUE THREAD

**Issue by nickkvrgic** [TechnicPack/TechnicLauncher#1153]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

Please help.....thx

**Comment by CannibalVox** [comment]
This is either a cracked launcher or an old launcher that isn't auto-updating for whatever reason.  Get the latest from http://www.technicpack.net/
