### ISSUE TITLE
I can not open technic 2

### ISSUE THREAD

**Issue by vongoclananh321** [TechnicPack/TechnicLauncher#1162]
Selected Pack: Vanilla
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_45 32 bit
    Total Memory: 56 MB
    Max Memory: 247 MB
    Memory Free: 22 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
This is either a version old version that has not been auto-updated for some reason or a cracked launcher. Get the latest legit launcher from http://www.technicpack.net/
