### ISSUE TITLE
 plz help :Technic Launcher Error Report: ( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )     Launcher Build: 0       Selected Pack: Hexxit Stack Trace:     Exception: IndexOutOfBoundsException     Message: Index: 0, Size: 0     Trace:         java.util.ArrayList.rangeCheck(Unknown Source)         java.util.ArrayList.get(Unknown Source)         org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)         org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)         org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)   System Information:     Operating System: Windows 7     Operating System Version: 6.1     Operating System Architecture: x86     Java version: 1.8.0_40 32 bit     Total Memory: 49 MB     Max Memory: 247 MB     Memory Free: 22 MB     CPU Cores: 4

### ISSUE THREAD

**Issue by iufvgkhfghc** [TechnicPack/TechnicLauncher#1163]
plz help !!!!!!

**Comment by iufvgkhfghc** [comment]
any one help me plz

**Comment by Zombie1181** [comment]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:112)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:201)
        org.spoutcraft.launcher.Launcher$3.run(Launcher.java:124)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_71 32 bit
    Total Memory: 41 MB
    Max Memory: 247 MB
    Memory Free: 7 MB
    CPU Cores: 4Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:112)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:201)
        org.spoutcraft.launcher.Launcher$3.run(Launcher.java:124)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_71 32 bit
    Total Memory: 41 MB
    Max Memory: 247 MB
    Memory Free: 7 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
This is either a version old version that has not been auto-updated for some reason or a cracked launcher. Get the latest legit launcher from http://www.technicpack.net/
