### ISSUE TITLE
Technic Launcher is all white on Ubuntu 15.04

### ISSUE THREAD

**Issue by ajthemacboy** [TechnicPack/TechnicLauncher#1164]
Hai! I have an issue with the Launcher on Ubuntu 15.04.

I have the latest graphics drivers and have installed Java 8 JDK. The launcher is just blank when I open it. Sometimes I can click around and get the screen to 'update', but even then it's only partial, and sometimes it just won't update at all.

Here's an Imgur album with some screenshots: http://imgur.com/a/Y6BAT

The images are in order of launching. (1-3 are setting up, 2 and 3 are logging in, and the rest are just the launcher.)

I can launch just fine on Windows. This also happens using the Unity desktop, but in the pictures I am using Gnome.

**Comment by CannibalVox** [comment]
Mutter has serious issues in how it draws undecorated windows in java.  Changing to compiz will fix this issue but if you want to stay on gnome there's not much we can do to help.

**Comment by ajthemacboy** [comment]
Is this not a bug? Are you just going to ignore it? That is what the issues section is for, right?

**Comment by CannibalVox** [comment]
It's a bug in someone else's software, what do you want me to do about it?

**Comment by ajthemacboy** [comment]
I'm sorry, I didn't mean to be rude. But every other X11 Java window works just fine? Can't you just 'decorate' the window? (lol)

**Comment by CannibalVox** [comment]
Window decoration is when it has a standard OS border & the standard OS close/maximize/etc. buttons.  We'd rather make the window look how we choose.  There are a lot of windows managers for linux that work correctly, I'd really suggest you use one of them.

**Comment by Binero** [comment]
The problem gets fixed on a visual update for me. Rerendering it on launch would work?

**Comment by ghost** [comment]
Isn't there some way to force it to decorate the window? Maybe some tweak I can make to the .desktop file I use to launch it? I know it will look stupid, but at least that way it will be usable on Mutter.

**Comment by ajthemacboy** [comment]
I'm quite sure there's a way to fix it but I wasn't going to press the issue.
