### ISSUE TITLE
None of the mods seem to be loading on the launcher screen, and wont update when i try using someone else's files

### ISSUE THREAD

**Issue by mtkane** [TechnicPack/TechnicLauncher#117]
Stack Trace :
          Exception:NullPointerException
          Message : null
          Trace:
                org.spoutcraft.launcher.UpdateThread.updateModpack (updatethread.java:410
                org.spoutcraft.launcher.UpdateThread.runTasks (UpdateThread.java:134
                org.spoutcraft.launcher.UpdateThread.run (UpdateThread. java: 107

**Comment by Salynne** [comment]
Missing launcher build number, looks like an outdated issue from an old build that was resolved.
