### ISSUE TITLE
Technic Launcher

### ISSUE THREAD

**Issue by ZayedAlBraiki** [TechnicPack/TechnicLauncher#1171]
I can't play the Technic Launcher because of an error

**Comment by CannibalVox** [comment]
you need to get way more specific

**Comment by asd5555** [comment]
asd

**Comment by XicoSantos** [comment]
because this error 
![image](https://cloud.githubusercontent.com/assets/12582173/7787222/aadde7f8-01ef-11e5-831e-52797a2e3c77.png)?

**Comment by CannibalVox** [comment]
That's a cracked launcher.  Go away.
