### ISSUE TITLE
Help me here

### ISSUE THREAD

**Issue by TheBlondeAssasin** [TechnicPack/TechnicLauncher#1172]
1.Technic Launcher Error Report:

2.( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
1.    Launcher Build: 0
3.    Selected Pack: Tekkit

6.Stack Trace:
1.    Exception: IndexOutOfBoundsException
2.    Message: Index: 0, Size: 0
3.    Trace:
4. ```
      java.util.ArrayList.rangeCheck(Unknown Source)
   ```
5. ```
      java.util.ArrayList.get(Unknown Source)
   ```
6. ```
      org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
   ```
7. ```
      org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
   ```
8. ```
      org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)
   ```

**Comment by CannibalVox** [comment]
This is a cracked launcher.  You got it from someone other than us, and that's who you should talk to about issues which you encounter.
