### ISSUE TITLE
Erro no launcher

### ISSUE THREAD

**Issue by Anakin86708** [TechnicPack/TechnicLauncher#1175]
http://pastebin.com/QUSZshzh

Não consigo nem mesmo abrir o launcher.
Podem me ajudar?

**Comment by ronaldlin188** [comment]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by Katekile** [comment]
Não consigo abri o meu diz isso Stack Trace:
Exception: IndexOutOfBoundsException
Message: Index: 0, Size: 0
Trace:
java.util.ArrayList.rangeCheck(Unknown Source)
java.util.ArrayList.get(Unknown Source)
org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by Dezz1227** [comment]
Technic Relatar erro Launcher:
(Por favor envie esse relatório para https://github.com/TechnicPack/TechnicLauncher/issues)
     Lançador de construção: 0

     Pacote selecionado: null
Rastreamento de pilha:
     Exceção: IndexOutOfBoundsException
     Mensagem: Lista: 0, Tamanho: 0
     Seguir:
         java.util.ArrayList.rangeCheck (origem desconhecida)
         java.util.ArrayList.get (origem desconhecida)
         org.spoutcraft.launcher.skin.NewsComponent.setupArticles (NewsComponent.java:60)
         org.spoutcraft.launcher.skin.NewsComponent.loadArticles (NewsComponent.java:46)
         org.spoutcraft.launcher.Launcher $ 2.run (Launcher.java:105)

Informação do sistema:
     Sistema operacional: Windows 7
     Sistema Operacional Versão: 6.1
     Operando Arquitetura do Sistema: amd64
     Java versão: 1.8.0_51 64 bit
     Memória Total: 131 MB
     Max Memória: 896 MB
     Memória livre: 83 MB
     Núcleos de CPU: 4

**Comment by Dezz1227** [comment]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.8.0_51 64 bit
    Total Memory: 131 MB
    Max Memory: 896 MB
    Memory Free: 83 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
These are all cracked launchers
