### ISSUE TITLE
plz plz plz help me 

### ISSUE THREAD

**Issue by NoufAlRshidi** [TechnicPack/TechnicLauncher#1179]
http://pastebin.com/CyN3Z9Wj
I can't play or open techniclauncher

**Comment by fahadalrshidi** [comment]
hello

**Comment by fahadalrshidi** [comment]
i can't play

**Comment by CannibalVox** [comment]
This is a cracked launcher.  We didn't make it.

**Comment by Lukosiju1** [comment]
So?

2015-06-04 12:44 GMT+03:00 fahadalrshidi notifications@github.com:

**Comment by fahadalrshidi** [comment]
Hal
Lukosiju1
