### ISSUE TITLE
My friends cant download my (hidden) modpack

### ISSUE THREAD

**Issue by Riptide1999** [TechnicPack/TechnicLauncher#118]
Stack Trace:
    Exception: MalformedURLException
    Message: unknown protocol: c
    Trace:
        java.net.URL.<init>(Unknown Source)
        java.net.URL.<init>(Unknown Source)
        java.net.URL.<init>(Unknown Source)
        org.spoutcraft.launcher.util.Download.<init>(Download.java:55)
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:44)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:428)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

**Comment by Salynne** [comment]
"c" is not a valid link to a zip download.

**Comment by Riptide1999** [comment]
That really doesn't help me at all. If you could tell me how to fix the problem though, that would be great.

**Comment by fridtjof** [comment]
Oups, didn't meant to put the last e-mail at the end ;)

**Comment by fridtjof** [comment]
Well, you have to host the pack somewhere, you can't just type in "c". It's not a secret code thing, it's a box to put a web adress in.

Am 06.03.2013 um 09:27 schrieb Riptide1999 notifications@github.com:

**Comment by Salynne** [comment]
Indeed. Your pack on the platform has to have a location of a zip download for your modpack. We don't host modpacks for people nor create them for you. Simply putting the letter 'c' in the area on the platform for a URL to a zip download of your modpack will not work.
