### ISSUE TITLE
ERRO NO LAUNCHER

### ISSUE THREAD

**Issue by felipe1320** [TechnicPack/TechnicLauncher#1181]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by felipe1320** [comment]
meu launcher abre e 5 segundos depois aparece essa mensagem

**Comment by CannibalVox** [comment]
This is either a cracked launcher or an old launcher that isn't updating.  Go to http://www.technicpack.net/ to get the latest technic launcher.
