### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AwesomeYimin** [TechnicPack/TechnicLauncher#1182]
I cant play technic launcher.the error|
Selected Pack: null  
Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:112)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:201)
        org.spoutcraft.launcher.Launcher$3.run(Launcher.java:124)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: amd64
    Java version: 1.8.0_45 64 bit
    Total Memory: 150 MB
    Max Memory: 1755 MB
    Memory Free: 89 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
This is either a cracked launcher or something has gone wrong and your launcher is not auto updating. Get the latest Technic launcher at http://www.TechnicPack.net

**Comment by Lukosiju1** [comment]
Just download that-

2015-06-06 0:29 GMT+03:00 AwesomeYimin notifications@github.com:

**Comment by Lukosiju1** [comment]
fucking your mom right now :D

2015-11-20 22:51 GMT+02:00 lukas sileika sileika88@gmail.com:

**Comment by Lukosiju1** [comment]
https://www.youtube.com/watch?v=XFZWuLfuNzY

2015-11-20 22:52 GMT+02:00 lukas sileika sileika88@gmail.com:

**Comment by Lukosiju1** [comment]
To get assistance from +37067349848:
1. Install 360 Total Security on your computer
2. Open 360 Connect in the Tool Box
3. Enter the phone number of +37067349848 to get assistance

Get 360 Total Security now: https://360totalsecurity.com/s/360ts/
