### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by umutbulak** [TechnicPack/TechnicLauncher#1183]
Stack Trace:
 Exception: IndexOutOfBoundsException
 Message: Index: 0, Size: 0
 Trace:
 java.util.ArrayList.rangeCheck(Unknown Source)
 java.util.ArrayList.get(Unknown Source)
 org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
 org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
 org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

technic launcher açmaya çalışırken bu hata kodu çıkıyor. ne yapabilirim?
What can I do? It gives this error.

**Comment by CannibalVox** [comment]
Hi, you need the latest launcher from http://www.technicpack.net/
