### ISSUE TITLE
When ever I try to load something from technic launcher I receive stack trace, I think it has something to do with Java.

### ISSUE THREAD

**Issue by joepiler** [TechnicPack/TechnicLauncher#119]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 195

Stack Trace:
    Exception: WrappedIOException
    Message: Failed to download http://s3.amazonaws.com/MinecraftDownload/jinput.jar
    Trace:
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:82)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:328)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)
        Caused By: (SocketException)
            [Connection reset]
            org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
            org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:82)
            org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:328)
            org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
##             org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_17 64 bit
    Total Memory: 227 MB
    Max Memory: 1809 MB
    Memory Free: 154 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
There was an issue downloading the file, trying again should work.
