### ISSUE TITLE
Launcher Fails to Detect Solder on Enabled Modpacks

### ISSUE THREAD

**Issue by DeviPotato** [TechnicPack/TechnicLauncher#1192]
This is the relevant modpack (for your own testing): http://www.technicpack.net/modpack/dinomint.644115

This is a modpack I had linked to a solder server before today (and it worked flawlessly with the launcher). Today, I had to migrate my solder installation to a Digital Ocean droplet, which led to a change in my solder installation's hostname in my profile on the platform site.

After I changed the solder link to reflect this, the launcher (and the platform website, to an extent) started to behave oddly. The launcher didn't recognize the new data (like new builds) from my new Solder server. I tried to unlink and relink the modpack to no effect, so I tried deleting and relinking my account's solder configuration itself. After I relinked the pack to my solder install, the launcher no longer recognizes the pack as Solder-enabled, and attempts to download a full modpack zip file (popping up the error "Attempting to extract file dinomint-1.0.zip, but it did not exist"). The platform website correctly shows the pack as "solder enabled" (but isn't showing that the current recommended build should be 11, and not 9.)

I have tried fresh reinstalls of my launcher and modpack, but this issue remains.

In addition, the following appears in the log sometimes when i attempt to install the pack:

[B#301] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[B#301] SLF4J: Defaulting to no-operation (NOP) logger implementation
[B#301] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

There are no other related log entries from what I can see--it actually looks like it's failing to initialize the logger in the first place.

It seems like there are things being inappropriately cached somewhere and failing to pick up the changes, but that's my guess without real knowledge of what's happening. This is just what I've observed.

**Comment by DeviPotato** [comment]
Right, so this seems to have fixed itself. Guess it was a caching issue after all.

**Comment by CannibalVox** [comment]
It was- clicking "update modpack" in the pack's edit screen will force a data push to the API in the future if you're having problems.  It is also necessary to restart your launcher after making changes, since data is cached locally for some time.
