### ISSUE TITLE
Some error? 

### ISSUE THREAD

**Issue by Bchew32** [TechnicPack/TechnicLauncher#120]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 195

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:118)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0 64 bit
    Total Memory: 123 MB
    Max Memory: 910 MB
    Memory Free: 71 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
This is from an outdated build of the launcher. It has since been resolved.
