### ISSUE TITLE
WHAT SHOULD I DO?!

### ISSUE THREAD

**Issue by theSRJ** [TechnicPack/TechnicLauncher#1200]
1.Technic Launcher Error Report:
2.( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
3.    Launcher Build: 0
4. 
5.    Selected Pack: null
6.Stack Trace:
7.    Exception: IndexOutOfBoundsException
8.    Message: Index: 0, Size: 0
9.    Trace:
10.        java.util.ArrayList.rangeCheck(Unknown Source)
11.        java.util.ArrayList.get(Unknown Source)
12.        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
13.        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
14.        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)
15. 
16.System Information:
17.    Operating System: Windows 7
18.    Operating System Version: 6.1
19.    Operating System Architecture: amd64
20.    Java version: 1.7.0_51 64 bit
21.    Total Memory: 114 MB
22.    Max Memory: 891 MB
23.    Memory Free: 50 MB
24.    CPU Cores: 4

**Comment by theSRJ** [comment]
and the technic launcher consol write"Error accesing URL"

**Comment by CannibalVox** [comment]
This is a cracked launcher. We didn't make it
