### ISSUE TITLE
Technic Launcher Error Report

### ISSUE THREAD

**Issue by antu3996** [TechnicPack/TechnicLauncher#1203]
When I turned Technic Launcher appeared to me Unexpected error and then some text:

1.Technic Launcher Error Report:

Second (Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues)

3rd Launcher Build: 0

4th

Selected fifth Pack: Tekkit

6.Stack Trace:

7th Exception: IndexOutOfBoundsException

Eighth Message: Index: 0, Size: 0

9th Trace:

10th java.util.ArrayList.rangeCheck (Unknown Source)

11th java.util.ArrayList.get (Unknown Source)

12th org.spoutcraft.launcher.skin.NewsComponent.setupArticles (NewsComponent.java:60)

13th org.spoutcraft.launcher.skin.NewsComponent.loadArticles (NewsComponent.java:46)

14th org.spoutcraft.launcher.Launcher $ 2.run (Launcher.java:105)

15th

16.System Information:

17th Operating System: Windows 8.1

18th Operating System Version: 6.3

19th Operating System Architecture: x86

20th Java version: 1.8.0_45 32-bit

21st Total Memory: 39 megabytes

22nd Max Memory: 247 megabytes

23rd Free Memory: 5 MB

24th CPU Cores: 4

Could you advise me?

**Comment by CannibalVox** [comment]
This is a cracked launcher.
