### ISSUE TITLE
(Please Help) The Launcher Doesn't Open

### ISSUE THREAD

**Issue by TheLegendaryBroFist** [TechnicPack/TechnicLauncher#1208]
When I try to write my account it gives this error
Stack Trace:
       Exception:  IndexOutOfBoundsException
       Message:   Index:  0,  Size:  0
       Trace:
                 java.util.ArrayList.rangeCheck(Unknown Source)
                 java.util.ArrayList.get(Unknown Source)
                 org.spoutcraft.Launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
                 org.spoutcraft.Launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
                 org.spoutcraft.Launcher.Launcher$2.run(Launcher.java:105)

Please Help me

**Comment by CannibalVox** [comment]
This is either out of date or cracked. You can get a fresh launcher from http://www.technicpack.net

**Comment by TheLegendaryBroFist** [comment]
I downloaded this for like 3-4 times and than it finally worked
