### ISSUE TITLE
??????

### ISSUE THREAD

**Issue by dirthsj** [TechnicPack/TechnicLauncher#121]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 195

Stack Trace:
    Exception: MalformedURLException
    Message: no protocol: mindcrack
    Trace:
        java.net.URL.<init>(URL.java:567)
        java.net.URL.<init>(URL.java:464)
        java.net.URL.<init>(URL.java:413)
        org.spoutcraft.launcher.util.Download.<init>(Download.java:55)
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:44)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:428)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.7.4
    Operating System Architecture: x86_64
    Java version: 1.6.0_33 64 bit
    Total Memory: 81 MB
    Max Memory: 1531 MB
    Memory Free: 34 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
This is because someone put "mindcrack" as the URL download for a modpack zip. This is invalid and is no longer allowed on the website. So this error should be gone.
