### ISSUE TITLE
Error! Help!

### ISSUE THREAD

**Issue by HuzenLoo** [TechnicPack/TechnicLauncher#1212]
I havent played this mod for a while.
whats going on?
Here is the error. Pleaase help!

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Attack of the B-Team
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 54 MB
    Max Memory: 247 MB
    Memory Free: 24 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
You're using a cracked launcher

**Comment by HuzenLoo** [comment]
I know that. is that a bad thing?

**Comment by CannibalVox** [comment]
Yes, cracking our launcher and then coming to us for support us bad.
