### ISSUE TITLE
Technic Launcher will not open Mac

### ISSUE THREAD

**Issue by jeprose** [TechnicPack/TechnicLauncher#1217]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(ArrayList.java:653)
        java.util.ArrayList.get(ArrayList.java:429)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
Hi,

This is either a cracked launcher or one that is badly out of date and refusing to update.  Get the latest at http://www.technicpack.net/
