### ISSUE TITLE
1.Technic Launcher Error Report:

### ISSUE THREAD

**Issue by bobdenney** [TechnicPack/TechnicLauncher#1220]
Launcher Build: 0
2.    Selected Pack: Vanilla

6.Stack Trace:
1.    Exception: IndexOutOfBoundsException
2.    Message: Index: 0, Size: 0
3.    Trace:
4. ```
      java.util.ArrayList.rangeCheck(Unknown Source)
   ```
5. ```
      java.util.ArrayList.get(Unknown Source)
   ```
6. ```
      org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
   ```
7. ```
      org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
   ```
8. ```
      org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)
   ```

16.System Information:
1.    Operating System: Windows 8.1
2.    Operating System Version: 6.3
3.    Operating System Architecture: amd64
4.    Java version: 1.7.0_79 64 bit
5.    Total Memory: 75 MB
6.    Max Memory: 883 MB
7.    Memory Free: 31 MB
8.    CPU Cores: 2

**Comment by CannibalVox** [comment]
Cracked launcher
