### ISSUE TITLE
Opening Technic Launcher Error

### ISSUE THREAD

**Issue by lucaslg20** [TechnicPack/TechnicLauncher#1222]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
This is either a cracked launcher or a deeply out of date launcher that isn't updating. Get the latest from technicpack.net
