### ISSUE TITLE
My cracked crazycraft isn't working

### ISSUE THREAD

**Issue by Olive00000** [TechnicPack/TechnicLauncher#1226]
I downloaded a cracked crazy craft package from you and this error came up.
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

Please help me

**Comment by CannibalVox** [comment]
From us?  No, you didn't.
