### ISSUE TITLE
Issue when opening Technic Launcher

### ISSUE THREAD

**Issue by immiel** [TechnicPack/TechnicLauncher#1227]
Hello,

I would like to report an issue here. You see, I just downloaded the latest Technic Launcher, but I got this issue as soon after I opened it: http://pastebin.com/HpiDm5CN

I need to know how to fix this issue ... that, or when this issue will be fixed?

**Comment by CannibalVox** [comment]
That's not the latest technic launcher, that's a weird cracked launcher.  Get the latest technic launcher from http://www.technicpack.net/
