### ISSUE TITLE
Technic launcher error

### ISSUE THREAD

**Issue by Olive00000** [TechnicPack/TechnicLauncher#1228]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Vanilla
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_79 64 bit
    Total Memory: 74 MB
    Max Memory: 875 MB
    Memory Free: 31 MB
    CPU Cores: 2

Please tell me what this means

**Comment by CannibalVox** [comment]
It means pay for minecraft.
