### ISSUE TITLE
launcher crash

### ISSUE THREAD

**Issue by j2ghz** [TechnicPack/TechnicLauncher#124]
I just launch (big dig pack). It asked me if I want to update. selected yes.

**Comment by j2ghz** [comment]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )

##     Launcher Build: 200

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:410)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:134)

##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_09 64 bit
    Total Memory: 116 MB
    Max Memory: 1820 MB
    Memory Free: 58 MB
    CPU Cores: 4

**Comment by j2ghz** [comment]
![image](https://f.cloud.github.com/assets/1708197/239878/becfa914-88d8-11e2-8cd4-737f3c1472ec.png)
tried again

**Comment by Salynne** [comment]
The servers were having some issues over the weekend, this should be resolved.
