### ISSUE TITLE
my launcher keeps throwing this at me after i try to update tekkit lite to 0.5.9

### ISSUE THREAD

**Issue by Wipeout05** [TechnicPack/TechnicLauncher#125]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 200

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:118)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_01 64 bit
    Total Memory: 121 MB
    Max Memory: 1344 MB
    Memory Free: 65 MB
    CPU Cores: 4

**Comment by Wipeout05** [comment]
Or there is an error receiving information for the pack

**Comment by Salynne** [comment]
Our server had some issues over the weekend, this should be resolved.
