### ISSUE TITLE
Error retrieving information for selected pack: Tekkit

### ISSUE THREAD

**Issue by Arzbishop** [TechnicPack/TechnicLauncher#126]
Whenever I try to download Tekkit Classic through the launcher, I get a few errors saying "Error retrieving information for selected pack" and then finally it works and starts to down load but then gives me this:

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 200

Stack Trace:
    Exception: EOFException
    Message: null
    Trace:
        java.util.zip.GZIPInputStream.readUByte(Unknown Source)
        java.util.zip.GZIPInputStream.readUShort(Unknown Source)
        java.util.zip.GZIPInputStream.readHeader(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        org.spoutcraft.diff.JBPatch.bspatch(JBPatch.java:94)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:71)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_17 32 bit
    Total Memory: 56 MB
    Max Memory: 989 MB
    Memory Free: 20 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
We had some server issues over the weekend, this should be resolved.
