### ISSUE TITLE
Futurocoin-gt.exe Short cut

### ISSUE THREAD

**Issue by chondi** [TechnicPack/TechnicLauncher#1268]
Hello Every one 
i cannot run my Futurocoin core wallet because any time i want to open the wallet
i receive the erro " the item futurocoin-gt.exe  that this shortcut refers to has been changed or moved"

can you please help

Regards

**Comment by Pyker** [comment]
I'm sorry, but that has nothing to do with the Technic Launcher or Technic in general.
