### ISSUE TITLE
i cant't download any modpack

### ISSUE THREAD

**Issue by cloby147** [TechnicPack/TechnicLauncher#1272]
[B#590] java.lang.NoClassDefFoundError: org/eclipse/aether/impl/DefaultServiceLocator$ErrorHandler
[B#590] 	at net.technicpack.minecraftcore.install.tasks.HandleVersionFileTask.<init>(HandleVersionFileTask.java:60)
[B#590] 	at net.technicpack.launcher.launch.Installer.buildTasksQueue(Installer.java:282)
[B#590] 	at net.technicpack.launcher.launch.Installer$1.run(Installer.java:114)
[B#590] 	at java.lang.Thread.run(Unknown Source)
[B#590] Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.impl.DefaultServiceLocator$ErrorHandler
[B#590] 	at java.net.URLClassLoader.findClass(Unknown Source)
[B#590] 	at com.regexlab.j2e.Jar2ExeClassLoader.findClass(Unknown Source)
[B#590] 	at java.lang.ClassLoader.loadClass(Unknown Source)
[B#590] 	at java.lang.ClassLoader.loadClass(Unknown Source)
[B#590] 	... 4 more
[B#590] Unhandled Exception in Thread[Thread-45,6,main]

**Comment by Pyker** [comment]
This is a problem with the cracked launcher you're using.

**Comment by cloby147** [comment]
ok thank you
