### ISSUE TITLE
A question about Technic's login and authentication system

### ISSUE THREAD

**Issue by AdventureG147** [TechnicPack/TechnicLauncher#1277]
So this is how it goes (correct me if i'm wrong);

`LoginFrame.java` uses `LauncherCore` and `MinecraftCore` as dependencies to do the login and authentication, while also making the window itself (the buttons, hyperlinks, images, textfields, etc), right?

**Comment by Pyker** [comment]
Yes, but where is this question coming from?

**Comment by AdventureG147** [comment]
Thanks, wanted to know cause i'm helping a friend make his own launcher
He said your API would be open-source

**Comment by Pyker** [comment]
If you're making your own launcher, then this will resource will help you: https://wiki.vg/Main_Page, more specifically https://wiki.vg/Microsoft_Authentication_Scheme.

**Comment by AdventureG147** [comment]
thanks
