### ISSUE TITLE
Even more launcher issues

### ISSUE THREAD

**Issue by DurekuRyuu** [TechnicPack/TechnicLauncher#128]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 199

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:410)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:134)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_10 64 bit
    Total Memory: 152 MB
    Max Memory: 1799 MB
    Memory Free: 87 MB
    CPU Cores: 8

**Comment by Rob4001** [comment]
I have this problem as well i think it is due to the technicpack servers

**Comment by Salynne** [comment]
Correct, our servers were having some issues over the weekend. This has been resolved.
