### ISSUE TITLE
Launcher will not launch classical Technic.

### ISSUE THREAD

**Issue by gigatock** [TechnicPack/TechnicLauncher#129]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 200

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:118)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.6.0_17 64 bit
    Total Memory: 88 MB
    Max Memory: 910 MB
    Memory Free: 43 MB
    CPU Cores: 2

**Comment by Jonny3456q** [comment]
Yes I am having that same problem! Here is my error log: http://pastebin.com/svhvyuEd

**Comment by Salynne** [comment]
Our servers were having some issues over the weekend this has been resolved.
