### ISSUE TITLE
failed to download mincraft pack

### ISSUE THREAD

**Issue by merinthium** [TechnicPack/TechnicLauncher#130]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 201

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: voltz Minecraft version: 1.4.7
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_15 32 bit
    Total Memory: 38 MB
    Max Memory: 989 MB
    Memory Free: 5 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
There was an issue with our servers over the weekend, it has since been resolved.
