### ISSUE TITLE
Error...? (Plus-Pack)

### ISSUE THREAD

**Issue by Kareem-The-Cat** [TechnicPack/TechnicLauncher#131]
Stack Trace:
    Exception: WrappedIOException
    Message: Failed to download http://server.pluspluspack.com/downloads/PlusPlus.zip
    Trace:
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:429)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:130)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)
        Caused By: (ConnectException)
            [Connection timed out: connect]
            org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
            org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:429)
            org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:130)
            org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

Help! I really want to play this and I don't know what the Hell is going on

**Comment by Salynne** [comment]
There was an error downloading the pack, probably their hosting. Try again.
