### ISSUE TITLE
Can't Play Mods on Technic Launcher 

### ISSUE THREAD

**Issue by Jonny3456q** [TechnicPack/TechnicLauncher#132]
Here is the error: http://pastebin.com/svhvyuEd

**Comment by Jonny3456q** [comment]
![Screen Shot 2013-03-09 at 2 32 15 PM](https://f.cloud.github.com/assets/3783716/240552/be212844-8928-11e2-81c3-30173d17d501.png)

**Comment by Salynne** [comment]
There was an issue with our servers over the weekend, this has since been resolved.
