### ISSUE TITLE
Plus Pack server is temporarily down (IF YOU CANNOT DOWNLOAD PLUS PACK PLEASE READ)

### ISSUE THREAD

**Issue by commandhat** [TechnicPack/TechnicLauncher#133]
Something apparently decided to eat it's own insides in on the Plus Pack server's side, and the server decided to stop serving requests. Their webdev guy is out for the weekend so nobody knows when this issues is going to be fixed.

The Technic workers cannot fix this because it is not technic related.

This is not a bug, but a notice for people who think it is.

**Comment by Salynne** [comment]
Thanks for posting this, I doubt anyone read it. I think their stuff has been fixed. In the meantime I'm going to leave this open as an issue for me to remember to make the launcher not crash when 3rd party hosting goes out.

**Comment by Salynne** [comment]
Resolved in https://github.com/TechnicPack/TechnicLauncher/commit/6a4787f4334d88cadd526d085bc430d8b27c546f
