### ISSUE TITLE
Modpacks - Unable to launch!

### ISSUE THREAD

**Issue by CandaceJane** [TechnicPack/TechnicLauncher#134]
I really want to play other modpacks, such as TechItUp or JustEnoughMods, but every time I try to launch it, a new window pops up saying "Unexpected Error" and the following: 

Stack Trace:
    Exception: WrappedIOException
    Message: Failed to download https://dl.dropbox.com/s/wsmrdrg7w6snnsx/techitup.zip?token_hash=AAFiktGwxnvoXkpmziwoRisAPaW5zT6ieqsbWXOk1mrQKA&dl=1
    Trace:
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:429)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:130)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)
        Caused By: (DownloadException)
            [Unable to download file]
            org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
            org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:429)
            org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:130)
            org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

What do I do?!

**Comment by CandaceJane** [comment]
I also have reinstalled TechnicLauncher multiple times, but cannot seem to launch other modpacks.

**Comment by Salynne** [comment]
Their dropbox may have gone over capacity, try again or try other modpacks.
