### ISSUE TITLE
The technic launcher came up with an error when trying to load PLUS+ Pack

### ISSUE THREAD

**Issue by gnomeo337** [TechnicPack/TechnicLauncher#137]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 201

Stack Trace:
    Exception: WrappedIOException
    Message: Failed to download http://server.pluspluspack.com/downloads/PlusPlus.zip
    Trace:
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:429)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:130)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)
        Caused By: (SocketException)
            [Connection reset]
            org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
            org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:429)
            org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:130)
##             org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_10 64 bit
    Total Memory: 173 MB
    Max Memory: 910 MB
    Memory Free: 80 MB
    CPU Cores: 2

**Comment by Ionaru** [comment]
This is the same issue as #140

**Comment by Salynne** [comment]
Duplicate issue.
