### ISSUE TITLE
This Happens When Dowloading tekkit classic

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#139]
Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: tekkit Minecraft version: 1.2.5
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

**Comment by funinthesun187** [comment]
it's happened to me too!

**Comment by Ionaru** [comment]
This is the same issue as #140

**Comment by Salynne** [comment]
Duplicate issue
