### ISSUE TITLE
IOException/ Can not download modpack?

### ISSUE THREAD

**Issue by InkDragon** [TechnicPack/TechnicLauncher#140]
http://pastebin.com/zj01vrK2

**Comment by Gemannihilator** [comment]
I got this as well, looks like it may be having difficulty downloading the vanilla Minecraft stuff.

EDIT: Ah, Minecraft updated to 1.5, maybe that has something to do with it.

http://pastebin.com/hTfd4A9g

**Comment by Ionaru** [comment]
Yes, it's because Minecraft updated to 1.5. The Technic team needs to fix this.

**Comment by baranowb** [comment]
This might be a perfect place for "enchancement" - Im not keen on src, but from consoles it seems that MD5 checksum is different( yup 1.5 ) hence error, wouldnt it be better to allow user to choose minecraft.jar? So he can point proper URL ?

**Comment by Salynne** [comment]
This has been resolved, and shouldn't be a problem in future minecraft updates.
