### ISSUE TITLE
Please Help This Is Important

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#141]
I download any pack with the laucher it launches and instead of giving up the Mojang screen it crashes! Help!

**Comment by Ionaru** [comment]
This is the same issue as #140

**Comment by baranowb** [comment]
It seems to fail at random during launch, on two runs:
1. hackslashmine Minecraft version: 1.2.3
2. tekkit Minecraft version: 1.2.5
It failed on hackslashmine and on second, on tekkit.

**Comment by Salynne** [comment]
This was an error with 1.5, it should be resolved.
