### ISSUE TITLE
Help please!

### ISSUE THREAD

**Issue by xLordBluex** [TechnicPack/TechnicLauncher#142]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 201

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: tekkit Minecraft version: 1.2.5
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0 64 bit
    Total Memory: 231 MB
    Max Memory: 2723 MB
    Memory Free: 183 MB
    CPU Cores: 8

I get this error report every time I try to access tekkit classic, where my worlds happen to be saved. I can't even get it to launch the application, but can launch Voltz just fine. Can anyone provide any help? I also get this error report when trying to get yogbox:

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 201

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: yogbox Minecraft version: 1.2.3
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0 64 bit
    Total Memory: 231 MB
    Max Memory: 2723 MB
    Memory Free: 98 MB
    CPU Cores: 8

Again, I really need help with this issue. Any help anyone can provide will be awesome. Thanks for reading :)

**Comment by Ionaru** [comment]
This is the same issue as #140

**Comment by Salynne** [comment]
Duplicate issue
