### ISSUE TITLE
Help Please! No Updating!

### ISSUE THREAD

**Issue by lars66038** [TechnicPack/TechnicLauncher#143]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
## Launcher Build: 201

Stack Trace:
Exception: IOException
Message: Failed to download Minecraft! Pack: high-voltage Minecraft version: 1.4.7
Trace:
org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
## org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
Operating System: Windows 7
Operating System Version: 6.1
Operating System Architecture: amd64
Java version: 1.7.0_17 64 bit
Total Memory: 153 MB
Max Memory: 1820 MB
Memory Free: 66 MB
CPU Cores: 8

**Comment by Ionaru** [comment]
This is the same issue as #140

**Comment by Salynne** [comment]
Duplicate issue
