### ISSUE TITLE
Forge problems

### ISSUE THREAD

**Issue by ShadowOwl** [TechnicPack/TechnicLauncher#144]
Whenever I attempt to join a volts server, I am confronted with this message:

"Forge Mod Loader could not connect to this server
The mods and versions listed below could not be found
They are required to play on this server

ICBM|Contraption : 1.0.5
ICBM|Explosion : 1.0.5
Fluid_Mechanics : 0.2.7
ICBM|Sentry : 1.0.5
BasicComponents : 1.2.6
Mekanism : 5.4.0
ModularForceFieldSystem : 2.3.0
ElectricExpansion : 1.5.0
mmmPowersuits : 0.2.2-170
MekanismGenerators : 5.4.0
AtomicScience : 0.4.1
Railcraft : 6.17.0.0
MekanismTools : 5.4.0
AssemblyLine : 0.2.8"

This problem does not occur in single player.

**Comment by Ionaru** [comment]
The server has mods that you do not have in your modpack, try deleting and redownloading the pack, there might be an update.

**Comment by ShadowOwl** [comment]
I tried redownloading it several times, which resulted in not being able to open any of the modpacks without an "unexpected error".

Error Report:

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: voltz Minecraft version: 1.4.7
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)

##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.6.8
    Operating System Architecture: x86_64
    Java version: 1.6.0_33 64 bit
    Total Memory: 81 MB
    Max Memory: 1019 MB
    Memory Free: 49 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
There was issues with 1.5 in redownloading the modpack, compounding the problem. Try and reinstall it again and open this issue again if there are any more problems.
