### ISSUE TITLE
Failed to download Minecraft! Pack: hackslashmine Minecraft version: 1.2.3

### ISSUE THREAD

**Issue by baranowb** [TechnicPack/TechnicLauncher#145]
Technic Launcher Error Report:
##     Launcher Build: 201

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: hackslashmine Minecraft version: 1.2.3
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Linux
    Operating System Version: 3.5.0-17-generic
    Operating System Architecture: amd64
    Java version: 1.7.0_15 64 bit
    Total Memory: 137 MB
    Max Memory: 1717 MB
    Memory Free: 86 MB
    CPU Cores: 4

**Comment by Ionaru** [comment]
This is the same issue as #140

**Comment by baranowb** [comment]
Ops, sorry, Ive searched for message nad there was no result. Im not sure why, it seems that launcher fails on different artifacts. Latest attempt: tekkit Minecraft version: 1.2.5

**Comment by baranowb** [comment]
Closing.
