### ISSUE TITLE
THIS IS IMPORTANT 

### ISSUE THREAD

**Issue by camthekills** [TechnicPack/TechnicLauncher#146]
it said when i tried to open voltz 

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: voltz Minecraft version: 1.4.7
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

Please help and it said imeaditly send it here?

**Comment by Dribble** [comment]
Minecraft has recently updated to 1.5, and this is causing the issue. The Technic Team need to fix this on their end, so don't worry.

**Comment by camthekills** [comment]
Thanks!

**Comment by Salynne** [comment]
We fixed the launcher for 1.5. Sorry about that.
