### ISSUE TITLE
Idk why this keeps happening. It has never happened before

### ISSUE THREAD

**Issue by Link10101** [TechnicPack/TechnicLauncher#148]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 201

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: yogbox Minecraft version: 1.2.3
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.8.2
    Operating System Architecture: x86_64
    Java version: 1.6.0_43 64 bit
    Total Memory: 81 MB
    Max Memory: 1015 MB
    Memory Free: 23 MB
    CPU Cores: 4

**Comment by Dribble** [comment]
Minecraft has recently updated to 1.5, and this is causing the issue. The Technic Team need to fix this on their end, so don't worry.

**Comment by Link10101** [comment]
Ok thanks Dribble :+1: I just downloaded the pack on my sisters laptop and i didn't know what was wrong lol thx again :)

**Comment by Dribble** [comment]
You're welcome. :D
