### ISSUE TITLE
A problem with a mod pack called galacticraft.

### ISSUE THREAD

**Issue by johiah** [TechnicPack/TechnicLauncher#150]
1.
Technic Launcher Error Report:

 2.
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )

 3.
    Launcher Build: 201
##  4.

 5.
Stack Trace:

 6.
    Exception: IOException

 7.
    Message: Failed to download Minecraft! Pack: lapitos-galacticraft Minecraft version: 1.4.7

 8.
    Trace:

 9.
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)

 10.
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)

 11.
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)

 12.
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)
##  13.

 14.
System Information:

 15.
    Operating System: Windows 7

 16.
    Operating System Version: 6.1

 17.
    Operating System Architecture: x86

 18.
    Java version: 1.7.0_07 32 bit

 19.
    Total Memory: 40 MB

 20.
    Max Memory: 989 MB

 21.
    Memory Free: 16 MB

 22.
    CPU Cores: 4

**Comment by Dribble** [comment]
Minecraft has recently updated to 1.5, and this is causing the issue. The Technic Team need to fix this on their end, so don't worry.

**Comment by Salynne** [comment]
1.5 issues have been resolved.
