### ISSUE TITLE
help!!!!

### ISSUE THREAD

**Issue by benlang32** [TechnicPack/TechnicLauncher#152]
what does this mean when it comes up?????
  Exception: IOException
    Message: Failed to download Minecraft! Pack: tekkit Minecraft version: 1.2.5
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

please help i dont understand

**Comment by Dribble** [comment]
Minecraft has recently been updated to 1.5 and TechnicLauncher has not currently updated yet. The Technic Team I'm sure are already on this, so don't worry, it's not an error on your end.

**Comment by benlang32** [comment]
do you know when i can download it? friends downloaded it yesterday

**Comment by Dribble** [comment]
I'm not sure on the time it'll be ready for update, but until then, why not go onto Minecraft and try out the new stuff that has just recently come out! :smile:

I'm sure the TechnicLauncher will be updated real shortly.

**Comment by benlang32** [comment]
okay,thankyou:)

**Comment by Dribble** [comment]
You're welcome! :smile:

**Comment by Salynne** [comment]
1.5 issues with the launcher have been resolved.
