### ISSUE TITLE
Can't start/install any modpacks

### ISSUE THREAD

**Issue by Goostax** [TechnicPack/TechnicLauncher#153]
Here is the error:

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 201

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: voltz Minecraft version: 1.4.7
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: x86
    Java version: 1.7.0_17 32 bit
    Total Memory: 56 MB
    Max Memory: 989 MB
    Memory Free: 30 MB
    CPU Cores: 4

Minecraft itself is working fine, and java seems to be installed correctly.  I did a reinstall of java and a redownload of the technic launcher but nothing helped.  Not really sure how I'm getting an IOException here.

**Comment by Dribble** [comment]
Minecraft has recently been updated to 1.5 and TechnicLauncher has not currently updated yet. The Technic Team I'm sure are already on this, so don't worry, it's not an error on your end. You're fine. :D

**Comment by Salynne** [comment]
1.5 issues with the launcher have been resolved.
