### ISSUE TITLE
Technic Tekkit Lite Download Error

### ISSUE THREAD

**Issue by A3T3RNUS** [TechnicPack/TechnicLauncher#154]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 201

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: tekkitlite Minecraft version: 1.4.7
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_13 64 bit
    Total Memory: 138 MB
    Max Memory: 1354 MB
    Memory Free: 83 MB
    CPU Cores: 8

**Comment by Dribble** [comment]
Minecraft has recently been updated to 1.5 and TechnicLauncher has not currently updated yet. The Technic Team I'm sure are already on this, so don't worry, it's not an error on your end.

**Comment by Salynne** [comment]
1.5 issues have been resolved.
