### ISSUE TITLE
Techinc Spoutcraft Error

### ISSUE THREAD

**Issue by katybear** [TechnicPack/TechnicLauncher#155]
When I try to open my tekkit this message comes up, what should I do?
Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: tekkit Minecraft version: 1.2.5
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_13 32 bit
    Total Memory: 64 MB
    Max Memory: 989 MB
    Memory Free: 19 MB
    CPU Cores: 2

**Comment by Dribble** [comment]
I've sort of written this message about 6-8 times now, but just for you... :smile:

Minecraft has recently been updated to 1.5 and TechnicLauncher has not currently updated yet. The Technic Team I'm sure are already on this, so don't worry, it's not an error on your end.

**Comment by Dribble** [comment]
Today, about 02:26 PM. It's been manic with the amount of people receiving this error since then.

**Comment by Salynne** [comment]
1.5 issues have been resolved.
