### ISSUE TITLE
Error whilst downloading Tekkit [Mac OS X 10.7.5]

### ISSUE THREAD

**Issue by whonut** [TechnicPack/TechnicLauncher#156]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 201

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: tekkit Minecraft version: 1.2.5
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.7.5
    Operating System Architecture: x86_64
    Java version: 1.7.0_15 64 bit
    Total Memory: 148 MB
    Max Memory: 1212 MB
    Memory Free: 62 MB
    CPU Cores: 4

**Comment by Dribble** [comment]
Minecraft has recently been updated to 1.5 and TechnicLauncher has not currently updated yet. The Technic Team I'm sure are already on this, don't you worry, it's not an error on your end, everyone is getting this issue. :smile:

**Comment by whonut** [comment]
Is there any way to work around the issue for the time being?

**Comment by Salynne** [comment]
The issue has been resolved.
