### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by hardanders** [TechnicPack/TechnicLauncher#158]
Can't open tekkit lite.

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 203

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: tekkitlite Minecraft version: 1.4.7
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_17 64 bit
    Total Memory: 119 MB
    Max Memory: 910 MB
    Memory Free: 47 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
There was an issue with the 1.5 update. It has been resolved.
