### ISSUE TITLE
Error while running mcpatch for MC 1.5

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#159]
While trying out to use MC 1.5 for my modpack i ran into the following error. you can reproduce it just by choosing to download 1.5 in a custom modpack.

http://pastebin.com/cnM5EnGn

**Comment by Salynne** [comment]
1.5 May not be entirely supported yet. You can try out a Beta build of the launcher instead by setting the option to Beta builds in your launcher options, then exiting and restarting the launcher.

Let me know if it works after that.

**Comment by corbindavenport** [comment]
I have the same issue, my bug report says something about Gzip instead of 'unknown'.
http://pastebin.com/sFNy5cs7

**Comment by Salynne** [comment]
You're also on the stable build of the launcher. 

You can try out a Beta build of the launcher instead by setting the option to Beta builds in your launcher options, then exiting and restarting the launcher.

Let me know if it works after that.

**Comment by corbindavenport** [comment]
I tried the Beta version and it downloaded but still crashed. I looked at the log and it seems to be a problem with the CodeChickenCore plugin. Since this is for a modpack I'm developing, when will 1.5 be available in the stable version of the launcher?

**Comment by Salynne** [comment]
Yeah I have no control over problems with chickencore.

Very soon, a day or two, I needed some confirmation like yours that it was working properly in the beta stream first.

**Comment by corbindavenport** [comment]
Alright, thanks!

**Comment by Salynne** [comment]
I believe this is working, closing the issue.
