### ISSUE TITLE
I got an error while downloading Tekkit Lite from Technic Launcer

### ISSUE THREAD

**Issue by MrBioman28** [TechnicPack/TechnicLauncher#160]
This is the error

Stack Trace:
    Exception: FileNotFoundException
    Message: C:\Users\USER\AppData\Roaming.technic\cache\minecraft_1.4.7.jar (Sistem belirtilen yolu bulamıyor)
    Trace:
        java.io.FileOutputStream.open(Native Method)
        java.io.FileOutputStream.<init>(Unknown Source)
        java.io.FileOutputStream.<init>(Unknown Source)
        org.spoutcraft.launcher.util.Utils.copy(Utils.java:260)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:53)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

**Comment by Salynne** [comment]
Can you show me the launcher build that is in that error message? Have you tried to run it again?

**Comment by MrBioman28** [comment]
I tried to run it again but thanks for commenting I solved it by myself

**Comment by Salynne** [comment]
Okay great. Thanks for coming back to say it was solved.
