### ISSUE TITLE
PixleCraft??? help With the Error Report

### ISSUE THREAD

**Issue by LemoneFresh** [TechnicPack/TechnicLauncher#161]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 203

Stack Trace:
    Exception: WrappedIOException
    Message: Failed to download https://dl.dropbox.com/s/09l6dgfalx3ocll/pixelmon%20modpack.zip?token_hash=AAGXhVc6tpO2supmWXySFbRkDAiwBfuWi6a8kxqScmHYRA&dl=1
    Trace:
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:429)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:130)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)
        Caused By: (DownloadException)
            [Unable to download file]
            org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
            org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:429)
            org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:130)
##             org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.6.0_39 32 bit
    Total Memory: 44 MB
    Max Memory: 989 MB
    Memory Free: 21 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
https://dl.dropbox.com/s/09l6dgfalx3ocll/pixelmon%20modpack.zip?token_hash=AAGXhVc6tpO2supmWXySFbRkDAiwBfuWi6a8kxqScmHYRA&dl=1

If you go to the dropbox for this pack, you can see they have had it disabled due to extreme bandwidth usage.
