### ISSUE TITLE
mod wont work, what do i do?

### ISSUE THREAD

**Issue by cdss** [TechnicPack/TechnicLauncher#165]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 203

Stack Trace:
    Exception: WrappedIOException
    Message: Failed to download https://dl.dropbox.com/s/ntx6civ11olqaj4/The%20Solace%20Pack%20v0.7.zip?token_hash=AAHOhr9JohUomq3HHjGrVXXzGCYKBl1w6w4wfQtYOGOmCw&dl=1
    Trace:
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:429)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:130)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)
        Caused By: (DownloadException)
            [Unable to download file]
            org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
            org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:429)
            org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:130)
##             org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.6.0_24 64 bit
    Total Memory: 166 MB
    Max Memory: 1345 MB
    Memory Free: 58 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
https://dl.dropbox.com/s/ntx6civ11olqaj4/The%20Solace%20Pack%20v0.7.zip?token_hash=AAHOhr9JohUomq3HHjGrVXXzGCYKBl1w6w4wfQtYOGOmCw&dl=1

Going to the actual dropbox link you will see this modpack author has exceeded their dropbox bandwidth so their pack is unavailable. In the future I will add better safety handling.
