### ISSUE TITLE
Error when downloading a new pack

### ISSUE THREAD

**Issue by tower12346** [TechnicPack/TechnicLauncher#168]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 0

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: better-than-wolves Minecraft version: 1.4.7
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_13 64 bit
    Total Memory: 97 MB
    Max Memory: 910 MB
    Memory Free: 23 MB
    CPU Cores: 2

**Comment by TempestaWeb** [comment]
I've tried multiple times to create a modpack, including the bin/modpack.jar, mods/ and coremods/ folders (without minecraft.jar of course)... What is going on? This works fine in the old version

**Comment by Salynne** [comment]
@tower12346 This says your launcher build is 0. Please try downloading the launcher again from our website www.technicpack.net/download/

@cantchoos There is a guide up at http://technicpack.net/article/view/building-your-own-modpack.7
