### ISSUE TITLE
Unable to launch any pack except vanilla.

### ISSUE THREAD

**Issue by TokenTabs** [TechnicPack/TechnicLauncher#169]
I have had two separate issues (different error reports on build 203 and 210).

http://pastebin.com/0qn0wE5d - build 203
http://pastebin.com/suSUCRvP - build 210.

The root cause is that the launcher did not create a "cache" folder within the .technic install directory; so whenever the launcher downloads the minecraft jar files it crashes instead of just creating this dir and putting the files there. I wasn't able to fix it until build 210 released since the error message for 203 was entirely unhelpful.

I fixed this by manually creating the cache directory before launching any packs. I'm posting it here as a bug so that the devs can be aware of it and get it sorted so it doesn't affect anyone else.

Cheers.

**Comment by Salynne** [comment]
Oh thank you for figuring this out for me. I love you. Staring at code too long and I just was going wtf, how come it works for me and not some people.

**Comment by Salynne** [comment]
https://github.com/TechnicPack/TechnicLauncher/commit/5700ae4c86392a7661ff3e65d8109f8c4c131b7e

Can you do me a favor and try out beta stream (212) and delete the cache folder ahead of time and see if this resolves it? Thanks.

**Comment by TokenTabs** [comment]
Certainly :)

**Comment by TokenTabs** [comment]
I didn't check my emails until now, and 213 is now around. It seems that it fixed the problem though, I deleted the cache directory and the install directories of any modpacks and it downloaded and launched them all without issue.

**Comment by Salynne** [comment]
Excellent, thank you for the help.
