### ISSUE TITLE
Does not finish downloading

### ISSUE THREAD

**Issue by Oxron2** [TechnicPack/TechnicLauncher#171]
here's the error report

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 195

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: tekkit Minecraft version: 1.2.5
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_04 64 bit
    Total Memory: 150 MB
    Max Memory: 910 MB
    Memory Free: 92 MB
    CPU Cores: 2

What is happening?

**Comment by Salynne** [comment]
How are you still on build 195? The latest stable version of the launcher is 203 and it should auto update you to it. Maybe try restarting your launcher.

**Comment by Oxron2** [comment]
It is on 195 but I do not know how to force update it since I just opened it to check the build.

**Comment by Salynne** [comment]
I'm not sure why your auto updater isn't working. Try downloading the latest build from here:

http://technicpack.net/download

**Comment by Oxron2** [comment]
ok

**Comment by Oxron2** [comment]
Thanks!
