### ISSUE TITLE
tekkitlight  not loding

### ISSUE THREAD

**Issue by elischmitter** [TechnicPack/TechnicLauncher#174]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 200

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: tekkitlite Minecraft version: 1.4.7
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_09 32 bit
    Total Memory: 44 MB
    Max Memory: 989 MB
    Memory Free: 14 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
Try getting the latest version from www.technicpack.net/download
