### ISSUE TITLE
Trying to add and run Magicians Cookbook through custom mod...

### ISSUE THREAD

**Issue by dorn284** [TechnicPack/TechnicLauncher#175]
The mod seemed to add correctly, but when i tried to run it it crashed. The following is a link to the report:

http://pastebin.com/TGXisJ2a

**Comment by Salynne** [comment]
https://dl.dropbox.com/s/x2bfubtpujofe9d/magicpack%201.8.3.zip

The dropbox link has exceeded bandwidth, so the modpack author will need to fix it.
A future launcher build will prevent the launcher crashing when this happens.
