### ISSUE TITLE
Problem Launching Tekkit Classic

### ISSUE THREAD

**Issue by Ghosthacker** [TechnicPack/TechnicLauncher#176]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 201

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: tekkit Minecraft version: 1.2.5
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_13 32 bit
    Total Memory: 59 MB
    Max Memory: 989 MB
    Memory Free: 16 MB
    CPU Cores: 8

wat do?

**Comment by Salynne** [comment]
Try downloading the latest version of the launcher from www.technicpack.net/download
