### ISSUE TITLE
My Tekkit Launcher has an Error

### ISSUE THREAD

**Issue by Squiggles17** [TechnicPack/TechnicLauncher#177]
Can someone please tell me how to fix this?
http://pastebin.com/HUhyiaCG

**Comment by Salynne** [comment]
Yeah, try downloading the launcher again from www.technicpack.net/download

There is an issue with our server and Cloudflare where the launcher will not auto update unless you are on the version 203 or later, I already fixed your error but you aren't receiving the fix automatically.
