### ISSUE TITLE
Can't download Minecraft for Voltz

### ISSUE THREAD

**Issue by mondas-mania** [TechnicPack/TechnicLauncher#179]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 200

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: voltz Minecraft version: 1.4.7
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_13 64 bit
    Total Memory: 154 MB
    Max Memory: 1365 MB
    Memory Free: 92 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
Try downloading the latest launcher from www.technicpack.net/download
