### ISSUE TITLE
Spoutcraft Update prompt leads to crashes ingame

### ISSUE THREAD

**Issue by Kaosi** [TechnicPack/TechnicLauncher#18]
Started launcher, was prompted to download recent Spoutcraft update, clicked Yes, Launcher stalled for about 3 minutes and then the game proper started. Once ingame, the tutorial "Press I/E To Open Your Inventory" appeared. Upon doing so, the game goes to "Saving Chunks" and then white-screens. Am unable to run minecrafterrortest.bat for Launcher.

**Comment by luisantonioa** [comment]
there are logs in the logs directory.. if you can put those in pastebin.com where the exception occurs will be easy to go through!

**Comment by Kaosi** [comment]
http://pastebin.com/0FEWZ4FA

Log for crash.

**Comment by luisantonioa** [comment]
Fixes - mods were missing from modlibrary.yml
