### ISSUE TITLE
Failed to download Yogbox

### ISSUE THREAD

**Issue by buddysbuddy29** [TechnicPack/TechnicLauncher#181]
Spoutcraft Error Report:
##     Build: 1.4.7 b1990

Stack Trace:
    Exception: t
    Message: Rendering screen
    Trace:
        ban.b(EntityRenderer.java:946)
        net.minecraft.client.Minecraft.J(Minecraft.java:1043)
        net.minecraft.client.Minecraft.run(Minecraft.java:899)
##         java.lang.Thread.run(Unknown Source)

Minecraft Information:
    Texture Pack Res: 16x
    LWJGL Version: 2.4.2
System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.6.0_26 32 bit
    Total Memory: 310 MB
    Max Memory: 989 MB
    Memory Free: 200 MB
    CPU Cores: 6
    OpenGL Version: 4.1.10907 Compatibility Profile Context
    OpenGL Vendor: ATI Technologies Inc.

I don't know what this stuff means, but hopefully someone can figure it out.

**Comment by Salynne** [comment]
This actually looks like an error with yogbox itself but try downloading the latest launcher from www.technicpack.net/download
