### ISSUE TITLE
Launcher won't launch any packs

### ISSUE THREAD

**Issue by yoyo2134** [TechnicPack/TechnicLauncher#182]
```
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 203
----------------------------------------------------------------------
Stack Trace:
    Exception: WrappedIOException
    Message: Failed to download http://mirror.technicpack.net/Technic/mods/ue-mekanism/ue-mekanism-v5.2.0.zip
    Trace:
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:429)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:130)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)
----------------------------------------------------------------------
System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0 64 bit
    Total Memory: 202 MB
    Max Memory: 910 MB
    Memory Free: 97 MB
    CPU Cores: 4
```

It told me to send this to you so i am. Please try to help me i want to join a group of my friends but it won't let me launch and of the packs. :(

**Comment by Salynne** [comment]
If you enter this link in a browser, does it work? http://mirror.technicpack.net/Technic/mods/ue-mekanism/ue-mekanism-v5.2.0.zip

If so let me know, I'm trying to determine what could be the issue with the download.

**Comment by yoyo2134** [comment]
It opens a file but it won't go to any website

**Comment by Salynne** [comment]
Is the launcher still broken for you? There was some website hiccups yesterday.

**Comment by yoyo2134** [comment]
It launches Tekkit Classic but all the others say "Error retrieving selected pack:"and this is popping up for all the packs but tekkit classic

**Comment by yoyo2134** [comment]
I have also found that under each pack box in the chooser on the left it says "loading..." for all of them but tekkit classic

**Comment by Salynne** [comment]
There was some issues with the launcher and website, they should be resolved now.

**Comment by yoyo2134** [comment]
Thank you

**Comment by yoyo2134** [comment]
i am sorry to say this but Volts is still not working

**Comment by Salynne** [comment]
What sort of error are you getting?

**Comment by yoyo2134** [comment]
There is a pop up saying FML is updating your minecraft environment

**Comment by yoyo2134** [comment]
then all of a sudden a pop up comes up saying it failed at updating and this happens almost every time

**Comment by Salynne** [comment]
Oh I'm not sure about that error. This is an issue with FML or the modpack itself and not the launcher sorry. Try our forums at http://forums.technicpack.net for possible solutions to the modpack issues.

**Comment by yoyo2134** [comment]
ok thanks

**Comment by gingerninja1212** [comment]
On mine It wont launch anything. it doesn't  say anything is wrong with it. when I press play the launcher closes then about 2 seconds later it pops open again. please help!

**Comment by crsc3110** [comment]
Teechnic Classic works for  me, however any other mod-pack will get to the loading screen then i will get a pop up saying java binary is not responding. I have a high end PC, so it isn't the my specs. Anyone able to help?

**Comment by Matthew3838** [comment]
Olloth my problem is that I can press play on the bottom right corner, then the launcher vanishes after a few seconds of it loading stuff on the bottom of the launcher, then after 20 seconds of the launcher vanishing; it comes back and doesn't load my mod pack. What should I do. Email me at pradamatthew@gmail.com

**Comment by bigstepss** [comment]
hi my problem is that i launch attack of the b team and it downloads things then my launcher disappears then it pops back up but nothing happened can you please help it happens with all the modpacks email me at abdielito2012@gmail.com
