### ISSUE TITLE
Technic Launcher Error. :/

### ISSUE THREAD

**Issue by UltranDenied** [TechnicPack/TechnicLauncher#183]
This is basically what it says:

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 203

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: tekkit Minecraft version: 1.2.5
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_01 64 bit
    Total Memory: 157 MB
    Max Memory: 910 MB
    Memory Free: 113 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
Try switching to beta builds in the options and restarting your launcher. Let me know if that resolves the problem.

**Comment by Salynne** [comment]
There was some issues with the launcher and website, they should be resolved now.
