### ISSUE TITLE
issue with updating minecraft vanilla on launcher

### ISSUE THREAD

**Issue by qazdude12** [TechnicPack/TechnicLauncher#185]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 203

Stack Trace:
    Exception: EOFException
    Message: null
    Trace:
        java.util.zip.GZIPInputStream.readUByte(Unknown Source)
        java.util.zip.GZIPInputStream.readUShort(Unknown Source)
        java.util.zip.GZIPInputStream.readHeader(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        org.spoutcraft.diff.JBPatch.bspatch(JBPatch.java:94)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:71)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_10 32 bit
    Total Memory: 36 MB
    Max Memory: 989 MB
    Memory Free: 12 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
Try going into your launcher options, selecting beta build, and exiting and restarting the launcher.

Let me know how it goes.

**Comment by Salynne** [comment]
There was some issues with the launcher and website, they should be resolved now.
