### ISSUE TITLE
Minecraft Download fail!

### ISSUE THREAD

**Issue by missrosie9101** [TechnicPack/TechnicLauncher#186]
Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft!
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.8.3
    Operating System Architecture: x86_64
    Java version: 1.6.0_43 64 bit
    Total Memory: 81 MB
    Max Memory: 1015 MB
    Memory Free: 36 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
Please download the latest version of the launcher from www.technicpack.net/download

191 is an old build, and builds prior to 203 are not auto updating anymore due to an error.
