### ISSUE TITLE
HELP ME!!!

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#187]
Launcher Build: 191
##  4.

 5.
Stack Trace:

 6.
    Exception: IOException

 7.
    Message: Failed to download Minecraft!

 8.
    Trace:

 9.
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)

 10.
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)

 11.
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)

 12.
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)
##  13.

 14.
System Information:

 15.
    Operating System: Windows 7

 16.
    Operating System Version: 6.1

 17.
    Operating System Architecture: amd64

 18.
    Java version: 1.7.0_17 64 bit

 19.
    Total Memory: 162 MB

 20.
    Max Memory: 1354 MB

 21.
    Memory Free: 70 MB

 22.
    CPU Cores: 2

**Comment by Salynne** [comment]
Please download the latest version of the launcher from www.technicpack.net/download

191 is an old build, and builds prior to 203 are not auto updating anymore due to an error.
