### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dunkindonut99** [TechnicPack/TechnicLauncher#189]
I try to load tekkit lite and i got this error after trying it a few times from it refusing it. "Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:119)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)"

I also was attempting to add a new pack onto it and when i pasted the url from technic platform, it came up with "Error parsing platform response"

**Comment by Salynne** [comment]
Please download the latest version of the launcher from www.technicpack.net/download

You are on an old build, and builds prior to 203 are not auto updating anymore due to an error.
