### ISSUE TITLE
Launcher Error

### ISSUE THREAD

**Issue by RichSABACAB** [TechnicPack/TechnicLauncher#190]
I downloaded the new Technic Launcher, but whenever I try to launch any of the modpacks, I get this error.

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 203

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:119)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

---

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_07 64 bit
    Total Memory: 142 MB
    Max Memory: 1809 MB
    Memory Free: 59 MB
    CPU Cores: 8

**Comment by Salynne** [comment]
Sorry the website is currently having troubles keeping up with weekend demands for users. We'll get it fixed as soon as possible. In the meantime, I promoted an update so new errors will be on version 213 if you receive any, but it will still be broken until the website is back up and working properly.
