### ISSUE TITLE
Error 2*

### ISSUE THREAD

**Issue by Dunkindonut99** [TechnicPack/TechnicLauncher#191]
https://github.com/TechnicPack/TechnicLauncher/issues/189

I re-downloaded that version even though i already had it, and it is still saying Error parsing platform response when i try to put in this pack http://www.technicpack.net/modpack/details/nationsmc

**Comment by Salynne** [comment]
Sorry, NOW the website is broken. We'll get it fixed as soon as possible. Sorry about the trouble.

**Comment by Salynne** [comment]
There was some issues with the launcher and website, they should be resolved now.
