### ISSUE TITLE
Error when launching ANY mod pack

### ISSUE THREAD

**Issue by iamePPz** [TechnicPack/TechnicLauncher#192]
What I've tried so far: Reinstalling Java, Reinstalling Technic launcher, Reinstalling Minecraft

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 201

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: vanilla Minecraft version: 1.4.7
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_10 64 bit
    Total Memory: 256 MB
    Max Memory: 3632 MB
    Memory Free: 140 MB
    CPU Cores: 8

**Comment by Salynne** [comment]
Try downloading the latest launcher from www.technicpack.net/download
