### ISSUE TITLE
Tekkit lite Loading error

### ISSUE THREAD

**Issue by DasWolke** [TechnicPack/TechnicLauncher#194]
http://pastebin.com/A9DVZfyX
##     Launcher Build: 201

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: tekkitlite Minecraft version: 1.4.7
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_15 64 bit
    Total Memory: 2014 MB
    Max Memory: 4062 MB
    Memory Free: 1920 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
Try downloading the latest launcher from www.technicpack.net/download
