### ISSUE TITLE
no modpacks are loading

### ISSUE THREAD

**Issue by emufossum13** [TechnicPack/TechnicLauncher#195]
I've been having trouble loading any modpack through the new technic launcher. Most of the packs just freeze until it comes up with a box that says error retrieving information for selected pack, I got the url of a created modpack on the technic website and tried to run that, it came up with this error

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 213

Stack Trace:
    Exception: EOFException
    Message: null
    Trace:
        java.util.zip.GZIPInputStream.readUByte(Unknown Source)
        java.util.zip.GZIPInputStream.readUShort(Unknown Source)
        java.util.zip.GZIPInputStream.readHeader(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        org.spoutcraft.diff.JBPatch.bspatch(JBPatch.java:94)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.patchMinecraft(MinecraftDownloadUtils.java:62)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:50)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:325)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_17 64 bit
    Total Memory: 244 MB
    Max Memory: 3623 MB
    Memory Free: 148 MB
    CPU Cores: 8

I've tried allocating more ram, that doesn't work, I've tried re-installing technic launcher 3 times, that didn't work, I updated my java to the latest version, that didn't work. Didn't this version of technic just come out like 2 days ago? If so, is this probably just a beta bug?

**Comment by Salynne** [comment]
The website actually is having some severe issues due to the extreme popularity of the platform and it being the weekend.

**Comment by Salynne** [comment]
There was some issues with the launcher and website, they should be resolved now.
