### ISSUE TITLE
My error when trying to play anything but yogbox and voltz

### ISSUE THREAD

**Issue by letor1** [TechnicPack/TechnicLauncher#197]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 213

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:125)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: x86
    Java version: 1.7.0_17 32 bit
    Total Memory: 62 MB
    Max Memory: 989 MB
    Memory Free: 27 MB
    CPU Cores: 8

**Comment by Salynne** [comment]
There was some issues with the launcher and website, they should be resolved now.
