### ISSUE TITLE
Always happens

### ISSUE THREAD

**Issue by Astro4545** [TechnicPack/TechnicLauncher#198]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 201

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: aegis-recrux Minecraft version: 1.4.7
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_17 32 bit
    Total Memory: 53 MB
    Max Memory: 989 MB
    Memory Free: 12 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
Try downloading the latest launcher from www.technicpack.net/download
