### ISSUE TITLE
Error Retrieving Information for Selected Pack: [Insert Pack Here]

### ISSUE THREAD

**Issue by Aethrios** [TechnicPack/TechnicLauncher#199]
Thought I'd add my two cents, and my solution to the problem.

I was getting this error for about an hour, and I fiddled with the settings... what eventually "fixed" it for me was switching from using the recommended launcher build to the beta build. I have no idea why this worked, but it made it click.

Apologies if this isn't where you'd like it to be filed, but the issue with a theoretical fix (patching in your own caches manually) wasn't doing it for me, and was closed to comments. So perhaps you'll throwing this out there for the other people having the same problem?

Regards,

**Comment by Salynne** [comment]
I'm guessing it finally worked for you when you switched to beta very shortly after we promoted the beta build, but the beta build you switched to was tested for ~15 minutes and then promoted to stable so everyone has the build now.

Thanks though :)
