### ISSUE TITLE
Crash when logging in

### ISSUE THREAD

**Issue by XDStamos** [TechnicPack/TechnicLauncher#200]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 218

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:125)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_17 64 bit
    Total Memory: 123 MB
    Max Memory: 910 MB
    Memory Free: 73 MB
    CPU Cores: 4

I was doing the custom mod pack, Big Dig.

**Comment by Salynne** [comment]
Thanks for reporting, I'll try and prevent this error from happening in the future.

**Comment by Salynne** [comment]
I believe this is resolved.
