### ISSUE TITLE
Error on startup when adding new Mod Packs

### ISSUE THREAD

**Issue by aanndryyyy** [TechnicPack/TechnicLauncher#201]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 218

Stack Trace:
    Exception: MalformedURLException
    Message: no protocol:
    Trace:
        java.net.URL.<init>(Unknown Source)
        java.net.URL.<init>(Unknown Source)
        java.net.URL.<init>(Unknown Source)
        org.spoutcraft.launcher.util.Download.<init>(Download.java:55)
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:45)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:435)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:136)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows XP
    Operating System Version: 5.1
    Operating System Architecture: x86
    Java version: 1.7.0_17 32 bit
    Total Memory: 50 MB
    Max Memory: 989 MB
    Memory Free: 18 MB
    CPU Cores: 1

**Comment by Salynne** [comment]
Could you tell me which modpack was giving you this issue?

**Comment by aanndryyyy** [comment]
PlusMultiPack gives

**Comment by Salynne** [comment]
Thanks, I believe I have resolved this.
