### ISSUE TITLE
Error When Attempting to Launch Tekkit Lite

### ISSUE THREAD

**Issue by Alt-ae-r** [TechnicPack/TechnicLauncher#202]
```
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 218
----------------------------------------------------------------------
Stack Trace:
    Exception: EOFException
    Message: null
    Trace:
        java.util.zip.GZIPInputStream.readUByte(Unknown Source)
        java.util.zip.GZIPInputStream.readUShort(Unknown Source)
        java.util.zip.GZIPInputStream.readHeader(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        org.spoutcraft.diff.JBPatch.bspatch(JBPatch.java:94)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.patchMinecraft(MinecraftDownloadUtils.java:62)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:50)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:325)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)
----------------------------------------------------------------------
System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_17 32 bit
    Total Memory: 36 MB
    Max Memory: 989 MB
    Memory Free: 7 MB
    CPU Cores: 2
```

**Comment by Makeshift** [comment]
I'm getting the same error with Voltz, now trying other packs. Happens during update, when minecraft.jar finishes downloading. I'm assuming it's failing opening the .jar for modification.
Volts error:

Stack Trace:
    Exception: EOFException
    Message: null
    Trace:
        java.util.zip.GZIPInputStream.readUByte(Unknown Source)
        java.util.zip.GZIPInputStream.readUShort(Unknown Source)
        java.util.zip.GZIPInputStream.readHeader(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        org.spoutcraft.diff.JBPatch.bspatch(JBPatch.java:94)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.patchMinecraft(MinecraftDownloadUtils.java:62)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:50)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:325)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

**Comment by Spyroism** [comment]
Thats the error i get on tekkit lite too

Stack Trace:
    Exception: EOFException
    Message: null
    Trace:
        java.util.zip.GZIPInputStream.readUByte(Unknown Source)
        java.util.zip.GZIPInputStream.readUShort(Unknown Source)
        java.util.zip.GZIPInputStream.readHeader(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        org.spoutcraft.diff.JBPatch.bspatch(JBPatch.java:94)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.patchMinecraft(MinecraftDownloadUtils.java:62)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:50)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:325)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

**Comment by Spyroism** [comment]
Mine is working now, no idea why. But you know, gift horse and mouth...

**Comment by Salynne** [comment]
There must have been some kind of hiccup with the server, causing this problem for everyone temporarily.
It should be resolved now, and I'm leaving this issue open to handle the error appropriately in the future.

Thanks everyone for reporting.

**Comment by Salynne** [comment]
This should be resolved in builds 219+ of the launcher.
