### ISSUE TITLE
Voltz installation error?

### ISSUE THREAD

**Issue by Siuuke** [TechnicPack/TechnicLauncher#203]
First I'll try to install it, and it will say "Error Retrieving Information for selected pack : voltz"

then I'll try it again and it will give me the error report : 

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 218

Stack Trace:
    Exception: EOFException
    Message: null
    Trace:
        java.util.zip.GZIPInputStream.readUByte(Unknown Source)
        java.util.zip.GZIPInputStream.readUShort(Unknown Source)
        java.util.zip.GZIPInputStream.readHeader(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        java.util.zip.GZIPInputStream.<init>(Unknown Source)
        org.spoutcraft.diff.JBPatch.bspatch(JBPatch.java:94)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.patchMinecraft(MinecraftDownloadUtils.java:62)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:50)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:325)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_01 64 bit
    Total Memory: 144 MB
    Max Memory: 1703 MB
    Memory Free: 67 MB
    CPU Cores: 4

**Comment by Siuuke** [comment]
Well I can see everyone is having this issue lately, but It's working now for me. I'm not sure if I even did anything or if it was just a temporary issue. All I did was continue to try. If you can, mark this as resolved or simply delete if you like.

**Comment by Salynne** [comment]
Sorry, I'm not sure what happened but I'll look into it. Glad it's fixed.
