### ISSUE TITLE
Cannot Launch PlusSigma

### ISSUE THREAD

**Issue by axiomaticstatic** [TechnicPack/TechnicLauncher#209]
First off, thanks for making Technic. The fact I can play so many MC mods just from one launcher is awesome.

Okay enough brown nosing, on with the issue.

Recently I found a cool mod called PlusSigma and wanted to add it to Technic... I already have Terrafirmacraft and ScourgeCraft working so I know Technic is set up okay. When I copy in the PlusSigma URL it adds okay, then going to launch it, it gets to the end of natives.jar and i see that it hits extracting files for a brief moment and then I get the error below.

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 218

Stack Trace:
    Exception: MalformedURLException
    Message: null
    Trace:
        java.net.URL.<init>(Unknown Source)
        java.net.URL.<init>(Unknown Source)
        java.net.URL.<init>(Unknown Source)
        org.spoutcraft.launcher.util.Download.<init>(Download.java:55)
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:45)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:435)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:136)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)
        Caused By: (NullPointerException)
            [null]
            java.net.URL.<init>(Unknown Source)
            java.net.URL.<init>(Unknown Source)
            java.net.URL.<init>(Unknown Source)
            org.spoutcraft.launcher.util.Download.<init>(Download.java:55)
            org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:45)
            org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:435)
            org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:136)
##             org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_02 64 bit
    Total Memory: 158 MB
    Max Memory: 910 MB
    Memory Free: 77 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
This is an error with the plus packs, their solder repo is currently not active: http://pluspack.gooncave.com/

Thank you for reporting the issue though, I will make sure that I handle this appropriately and give a message indicating the problem as soon as you try and add a pack with a bad solder.

Leaving the issue open until I fix it.

**Comment by Salynne** [comment]
This should be resolved in builds 219+ of the launcher.
