### ISSUE TITLE
LAUNCHER ERROR READ HERE - Technic Launcher Failed - shouldUsePatch error

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#212]
# ADMIN EDIT: IF YOU ARE RECEIVING THIS ERROR, TRY DOWNLOADING THE LAUNCHER AGAIN FROM www.technicpack.net/download

```
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 221
----------------------------------------------------------------------
Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.technic.rest.RestAPI.shouldUsePatch(RestAPI.java:343)
        org.spoutcraft.launcher.technic.rest.RestAPI.getMinecraftMD5(RestAPI.java:326)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:45)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:325)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)
----------------------------------------------------------------------
System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_04 64 bit
    Total Memory: 197 MB
    Max Memory: 910 MB
    Memory Free: 76 MB
    CPU Cores: 2
```

**Comment by blakekse** [comment]
same problem

**Comment by Salynne** [comment]
Working on solving this right now, I'll update this issue when I have a fix pushed.

**Comment by Salynne** [comment]
A fix has been promoted, please make a new issue if you receive any new errors. Thanks.

Your launcher should now be on build 222 after automatically updating.

Sorry for the inconvenience our website is getting hammered this weekend.

**Comment by KidWithJokes** [comment]
Care to explain how to update? I see no options...

**Comment by aidan810** [comment]
restarted my launcher, still on 221. tried beta launcher, still 221. xD am I doing something wrong here?

**Comment by KidWithJokes** [comment]
same troubles

**Comment by Salynne** [comment]
The auto updater appears to be broken, sorry I didn't notice.

The web guys are out on holiday for the weekend too so the only thing I can do is say to try downloading the launcher again from www.technicpack.net/download and that will be build 222

The website is at a crawl though, I'm trying to get ahold of people to get it resolved.

**Comment by aidan810** [comment]
okay thanks. :D

**Comment by KidWithJokes** [comment]
IT WORKSSS!!!!!!!!!!!!!!!!!!!!!

**Comment by Salynne** [comment]
Auto updating is resolved as well as the website being slow.

Closing this again.
