### ISSUE TITLE
Tekkit Minecraft crash (java stack on RESTApi) on Linux (fedora 18  -- FTB has worked on same PC 

### ISSUE THREAD

**Issue by fwelland** [TechnicPack/TechnicLauncher#214]
(pretty savvy with Linux and Java -- but noob with Minecraft -- my kid is teaching me!!)

Downloaded Tekkit Luancher and ran via: 
# /bin/bash

cd ~/Tekkit
export LD_LIBRARY_PATH=/opt/jdk1.7/jre/lib/amd64
java -jar TechnicLauncher.jar & 

After UI started I selected "Voltz" on left had side of UI and provided my username and pwd and got the error below.   My son insists the issue should go away if I retry enough.   I am on try number 5 -- no dice...  

There is another stacktrace in term window from STDOUT that happens during launcher startup -- that isn't fatal as UI draws -- Don't know if it is relevant...Relevant part:   Timed out accessing URL [http://www.technicpack.net/api/minecraft] 

Error report below.     (just in -- try 8 maybe it works?    No error yet...)

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 221

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.technic.rest.RestAPI.shouldUsePatch(RestAPI.java:343)
        org.spoutcraft.launcher.technic.rest.RestAPI.getMinecraftMD5(RestAPI.java:326)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:45)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:325)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Linux
    Operating System Version: 3.8.4-202.fc18.x86_64
    Operating System Architecture: amd64
    Java version: 1.7.0_15 64 bit
    Total Memory: 238 MB
    Max Memory: 3544 MB
    Memory Free: 186 MB
    CPU Cores: 8

**Comment by Salynne** [comment]
Duplicate #212
