### ISSUE TITLE
problems running tekkit lite and classic

### ISSUE THREAD

**Issue by snivy7733** [TechnicPack/TechnicLauncher#219]
both sometimes come up with the error:
error retriving information from pack : tekkitlite (or whatever)
and the rest of the time it logs in then says

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.technic.rest.RestAPI.shouldUsePatch(RestAPI.java:343)
        org.spoutcraft.launcher.technic.rest.RestAPI.getMinecraftMD5(RestAPI.java:326)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:45)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:325)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

**Comment by ryderz** [comment]
I am getting the same thing

**Comment by Salynne** [comment]
Duplicate #212
