### ISSUE TITLE
technic will not launch tekkitlite

### ISSUE THREAD

**Issue by ryderz** [TechnicPack/TechnicLauncher#220]
help, everytime i try to launch tekkitlite I get this

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.technic.rest.RestAPI.shouldUsePatch(RestAPI.java:343)
        org.spoutcraft.launcher.technic.rest.RestAPI.getMinecraftMD5(RestAPI.java:326)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:45)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:325)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_17 64 bit
    Total Memory: 117 MB
    Max Memory: 910 MB
    Memory Free: 78 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
Duplicate #212
