### ISSUE TITLE
Cant run any packs other than vanilla

### ISSUE THREAD

**Issue by zepenguin** [TechnicPack/TechnicLauncher#222]
I cant run anything other than vanilla. It shows me this everytime i run technic launcher. I dont understand it.

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.technic.rest.RestAPI.shouldUsePatch(RestAPI.java:343)
        org.spoutcraft.launcher.technic.rest.RestAPI.getMinecraftMD5(RestAPI.java:326)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:45)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:325)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

**Comment by Salynne** [comment]
Duplicate #212
