### ISSUE TITLE
Failed to download Tekkit

### ISSUE THREAD

**Issue by hellsedgexx** [TechnicPack/TechnicLauncher#232]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 191

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft!
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_21 64 bit
    Total Memory: 308 MB
    Max Memory: 3633 MB
    Memory Free: 165 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
Redownloading the launcher from http://www.technicpack.net/download/ should resolve your problem. The launcher build you have is an old one that may have had automatic updating broken. In the future it should update itself.

**Comment by Salynne** [comment]
Automatic updating was resolved, so you can also just re-launch your launcher to update it.

**Comment by hellsedgexx** [comment]
Thank you very much
