### ISSUE TITLE
Can't Start Minecraft With Technic Launcher

### ISSUE THREAD

**Issue by itsmeloj** [TechnicPack/TechnicLauncher#233]
http://pastebin.com/pi2vZ96L

**Comment by Salynne** [comment]
Redownloading the launcher from http://www.technicpack.net/download/ should resolve your problem. The launcher build you have is an old one that may have had automatic updating broken. In the future it should update itself.

**Comment by Salynne** [comment]
Automatic updating was resolved, so you can also just re-launch your launcher to update it.
