### ISSUE TITLE
Load modpack information before loading minecraft.

### ISSUE THREAD

**Issue by ruifung** [TechnicPack/TechnicLauncher#235]
The launcher should wait until all modpack information has been loaded before loading minecraft, some of my players have been missing updates because they click the launch button before the data has finished loading.

**Comment by Salynne** [comment]
The issue is that some people would rather play their singleplayer packs before their internet catches up.

I'll think about this, it's a trickier issue to solve than you think.

**Comment by ruifung** [comment]
How about pinging a site like google to check for internet connection?

**Comment by Salynne** [comment]
The issue isn't people with lack of connections, it's people with slow connections. Also, when our website is running slow. (Which hopefully it won't be ever again now but you know things happen)

**Comment by ruifung** [comment]
Oh. I see. Well, maybe put a notification dialog that just tells them that they might miss updates if they launch before it finishes loading. With a "do not show again" check box on it,

**Comment by ilpws422** [comment]
mine doesnt even download the mods!
