### ISSUE TITLE
Updated Pack Logo not shown in Launcher

### ISSUE THREAD

**Issue by dwi** [TechnicPack/TechnicLauncher#239]
When I change/update Pack Logo on technicpack.net, it does not refresh in Launcher. Not even when doing "Reset Pack". Only way to "refresh" logo in launcher is to tell users to delete assets folder in .technic and that is really unfriendly way to update pack logo displayed in Launcher.

**Comment by Salynne** [comment]
I thought I was checking md5, let me confer with sct about this.

**Comment by sct** [comment]
Is it a solder pack? You update those images through Solder.

**Comment by dwi** [comment]
Changed resources/logo_180.png and on technicpack.net as well and it didn't changed in Launcher. Still showing the old one loaded from assets

**Comment by dwi** [comment]
Oh I see now, this is Solder issue. Solder has no interface tools to md5sum logos and such from /slug/resources/

I had to update checksum manually in mysql.
