### ISSUE TITLE
Width/Height/Fullscreen Selector

### ISSUE THREAD

**Issue by Salynne** [TechnicPack/TechnicLauncher#244]
Add the ability to select size of the launched minecraft window, or tell it to start fullscreened.

**Comment by CannibalVox** [comment]
Believe this was done, but not anymore :-O

**Comment by CannibalVox** [comment]
Too used to clicking close when I comment :\

**Comment by CannibalVox** [comment]
-width & -height are available again as command line arguments, and -fullscreen is available as a command line argument pre-1.6.
