### ISSUE TITLE
Launcher crashes when checking for tekkitmain update

### ISSUE THREAD

**Issue by bluetoaster42** [TechnicPack/TechnicLauncher#247]
When loading the new, main instance of Tekkit (not Lite or Classic,) the loading bar gets to 50% when "checking for tekkitmain update" then spits out an error message saying "special characters are not allowed" and I'm forced to close the application. Error message said to report it here.

Full error message: http://pastebin.com/yGwwwddj

**Comment by Salynne** [comment]
How good are you with computers? Could you do me a favor and help me solve this bug?

If you understand these instructions please help me out:
- Open up the folder tekkitmain is in, by clicking the Gear icon under the modpack logo while Tekkit is selected, and clicking Open Folder
- Go into the bin folder
- Right click the file "installed" and open it with a text editor, and copy the contents for me and put them on www.pastie.org and send me the link.

If you don't understand these instructions that's OK, I will be looking into the error anyway and when I figure it out I will let you know. If it does this every time, and you don't understand the instructions, then simply open the modpack options for Tekkit and reset the pack the pack to temporarily fix it.

**Comment by bluetoaster42** [comment]
Opening the "installed" file with Wordpad gives me thirteen boxes. Opening it with Notepad++ gives me thirteen "NUL" characters. Attempting to copy and paste it into pastie.org copies and pastes nothing.

And yes, the launcher gives me this error every time I try to launch the main Tekkit version.

**Comment by Salynne** [comment]
That is bizarre. Okay thank you for the help, just delete that "installed" file and it should update properly. I'll have a proper fix out soon.

(For the record, it should read something like "installed: 1.0.3" in yaml format. Somehow it is rarely being corrupted)

**Comment by bluetoaster42** [comment]
I deleted the "installed" file like you said and it works great now. Thanks very much!
