### ISSUE TITLE
launcher dosen't work help

### ISSUE THREAD

**Issue by leobuffon** [TechnicPack/TechnicLauncher#248]
Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft! Pack: voltz Minecraft version: 1.4.7
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

**Comment by Salynne** [comment]
You left out a bunch of the error message, including the build of the launcher that you have running.

You can still comment on this issue after I close it, I will reopen it if you provide the correct information.

In the meantime, you can try downloading the launcher again from www.technicpack.net/download/ as that fixes many common problems.
