### ISSUE TITLE
launcher dosen't work 

### ISSUE THREAD

**Issue by leobuffon** [TechnicPack/TechnicLauncher#249]
when I launch the launcher the loading window pops up an after a sec it closes and nothing happens

**Comment by Salynne** [comment]
What pack are you launching?

Does your launcher look like the one here?
![luncher](https://f.cloud.github.com/assets/698747/481728/7aad2194-b871-11e2-8fe2-4fd075ccc77f.png)

**Comment by leobuffon** [comment]
yes it dose

**Comment by Salynne** [comment]
Do you use any antivirus programs?

**Comment by leobuffon** [comment]
yes but I tried dis activating it but still didn't work

**Comment by Salynne** [comment]
Is the problem still persisting? What window actually pops up and closes?
