### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Noaaan** [TechnicPack/TechnicLauncher#250]
1.
Technic Launcher Error Report:

 2.
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )

 3.
    Launcher Build: 236
##  4.

 5.
Stack Trace:

 6.
    Exception: NullPointerException

 7.
    Message: null

 8.
    Trace:

 9.
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:125)

 10.
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)
##  11.

 12.
System Information:

 13.
    Operating System: Windows 7

 14.
    Operating System Version: 6.1

 15.
    Operating System Architecture: x86

 16.
    Java version: 1.7.0_21 32 bit

 17.
    Total Memory: 36 MB

 18.
    Max Memory: 989 MB

 19.
    Memory Free: 15 MB

 20.
    CPU Cores: 4

**Comment by Salynne** [comment]
I believe this should now be fixed in the launcher. Report back if the problem persists.
