### ISSUE TITLE
ERROR?

### ISSUE THREAD

**Issue by epiceric2001** [TechnicPack/TechnicLauncher#251]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 236

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:125)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_17 64 bit
    Total Memory: 118 MB
    Max Memory: 910 MB
    Memory Free: 80 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
I believe this should now be fixed in the launcher. Report back if the problem persists.
