### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kat1189** [TechnicPack/TechnicLauncher#254]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 236

Stack Trace:
    Exception: IOException
    Message: The file or directory is corrupted and unreadable
    Trace:
        java.io.WinNTFileSystem.createFileExclusively(Native Method)
        java.io.File.createNewFile(Unknown Source)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:455)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:136)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: x86
    Java version: 1.7.0_21 32 bit
    Total Memory: 67 MB
    Max Memory: 989 MB
    Memory Free: 28 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
What modpack were you attempting to run?

Have you tried resetting or removing and reinstalling the pack? It seems like a file just got corrupted. I haven't seen this before.

**Comment by Kat1189** [comment]
It's not a modpack i'm trying to run it's just the regular minecraft and
i've tried resetting it four or five times

**Comment by Salynne** [comment]
Hmm I'm not really sure what to do about this. If a file or folder is corrupted then there is no way for me to fix it on my end I think. Any other information you can give me?

**Comment by Kat1189** [comment]
I dunno i clicked on the little world thingy next to where you reset it and
just re added the pack and now it's working so i have no idea wat happened

**Comment by Salynne** [comment]
Alright. Sorry about that, I have no idea what happened either except that something got corrupted.

Glad it's working.
