### ISSUE TITLE
NPE in DynamicButton

### ISSUE THREAD

**Issue by nsg** [TechnicPack/TechnicLauncher#255]
I have no idea why but I have two "dynamic button" portraits of my character. I have had this for a few weeks, one with my texture pack and one with the "default steve" texture. Nah, just a minor bug, I have ignored it.

This caused a problem today when the client tried to render this extra "steve textured button" and failed with a NPE.

```
java.lang.NullPointerException
    at org.spoutcraft.launcher.skin.components.DynamicButton.<init>(DynamicButton.java:65)
    at org.spoutcraft.launcher.skin.MetroLoginFrame.initComponents(MetroLoginFrame.java:343)
    at org.spoutcraft.launcher.skin.MetroLoginFrame.<init>(MetroLoginFrame.java:123)
    at org.spoutcraft.launcher.entrypoint.SpoutcraftLauncher.main(SpoutcraftLauncher.java:130)
```

The affected line was

```
this.setSize(icon.getWidth(), icon.getHeight());
```

I made a quick fix in https://github.com/nsg/TechnicLauncher/commit/25a0a0f51c4b4de869be0a33cf4085d1118398e8 this is of course not a good solution because it fixes the symptom, not the cause. Do what you want with this.

**Comment by Salynne** [comment]
Have you tried simply pressing the little delete icon on the steve one?

**Comment by Salynne** [comment]
Ah i see, someone else has reported this issue. Yeah I'm going to borrow your fix until I can figure out the underlying issue.

Thank you for the report.

**Comment by CannibalVox** [comment]
Old launcher issues, please reopen if something similar occurs in the new launcher.
