### ISSUE TITLE
Launching Tekkit Classic

### ISSUE THREAD

**Issue by psygomin** [TechnicPack/TechnicLauncher#257]
Tekkit Launcher opens no problem how ever when i select launch to open Minecraft to play Tekkit Classic i get this error

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 236

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:125)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_21 64 bit
    Total Memory: 153 MB
    Max Memory: 3640 MB
    Memory Free: 114 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
I believe this should now be fixed in the launcher. Report back if the problem persists.
