### ISSUE TITLE
Launcher crashed after starting Tekkit pack.

### ISSUE THREAD

**Issue by Rockmim** [TechnicPack/TechnicLauncher#259]
Hello, I opened up my launcher a few minutes ago and logged in with the new Tekkit modpack (the one with GalacticCraft). After a few minutes of saying connecting to minecraft.net, it crashed. Here is the report I found on it:

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 239

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:125)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows XP
    Operating System Version: 5.1
    Operating System Architecture: x86
    Java version: 1.7.0_17 32 bit
    Total Memory: 41 MB
    Max Memory: 494 MB
    Memory Free: 4 MB
    CPU Cores: 1

**Comment by Salynne** [comment]
I tried to implement another fix, should be fixed if you restart your launcher.
