### ISSUE TITLE
Null Pointer Exception in Launcher

### ISSUE THREAD

**Issue by SkyeOfBreeze** [TechnicPack/TechnicLauncher#261]
Technic Launcher reported an unexpected error when i tried to log into Tekkit Lite.
The full report is here: http://pastebin.com/AHAwZDV5/

**Comment by 13madman** [comment]
same problem hope they fix it

**Comment by Salynne** [comment]
I tried to implement another fix, should be fixed if you restart your launcher.

**Comment by 13madman** [comment]
yes its fixed thank you,  GG Tekkit Team
