### ISSUE TITLE
NullPointerException-Windows 8- Yogbox

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#263]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 239

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:125)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: x86
    Java version: 1.7.0_21 32 bit
    Total Memory: 46 MB
    Max Memory: 989 MB
    Memory Free: 10 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
I tried to implement another fix, should be fixed if you restart your launcher.
