### ISSUE TITLE
Someone help me fix my Minecraft Oasis Modpack Download Failure

### ISSUE THREAD

**Issue by Gremmy** [TechnicPack/TechnicLauncher#265]
So when I put Ihascupquakes Minecraft Oasis on Technic Launcher and launch it it either says "Download Failed, retries remaining"  or something would pop up and say
## Launcher Build: 0

Stack Trace:
    Exception: WrappedIOException
    Message: Failed to download http://darrenkinz.me/mc/ohsis.zip
    Trace:
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:431)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:132)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)
        Caused By: (ConnectException)
            [Connection timed out: connect]
            org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
            org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:431)
            org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:132)
##             org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_21 32 bit
    Total Memory: 112 MB
    Max Memory: 989 MB
    Memory Free: 35 MB
    CPU Cores: 2

PLEASE HELP!!

**Comment by Salynne** [comment]
If your launcher build is 0 you did not download the launcher from www.technicpack.net/download
