### ISSUE TITLE
Error Upon updating Tekkit Pack

### ISSUE THREAD

**Issue by cujomalainey** [TechnicPack/TechnicLauncher#266]
```
Launcher Build: 240
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:419)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:145)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:113)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_21 64 bit
    Total Memory: 116 MB
    Max Memory: 1363 MB
    Memory Free: 31 MB
    CPU Cores: 8

**Comment by Salynne** [comment]
Does this repeatedly occur or was this a one time error?

**Comment by cujomalainey** [comment]
Attempted to replicate it, I was unsuccessful. I was having serious issues though updating the package, it wasn't updating without a fight

**Comment by Salynne** [comment]
Alright, I'll leave the issue open in case someone else has the problem or I figure out a solution. Hope everything keeps working well for you in the future.

**Comment by Salynne** [comment]
Closing this as I didn't investigate before the line numbers didn't match anymore. I believe I might have fixed in various cleanup efforts however, please reopen and give a new stack trace if you receive the error again.
