### ISSUE TITLE
download failed

### ISSUE THREAD

**Issue by sparpo** [TechnicPack/TechnicLauncher#268]
recently when every I launch a new pack it starts downloading and around 20-30% it stops and says download failed. PLEASE help

**Comment by Salynne** [comment]
It can be any of the following reasons:
Bad internet connection
Antivirus applications causing the download to fail
Bad modpack hosting on the part of the modpack author. If it is a platform pack than this is always a possibility, but if it is tekkit, big dig, or any other official packs it is likely an internet or antivrus problem.
