### ISSUE TITLE
Technic Launcher Badness

### ISSUE THREAD

**Issue by thebfactor23** [TechnicPack/TechnicLauncher#269]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 0

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:125)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:109)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.7.5
    Operating System Architecture: x86_64
    Java version: 1.7.0_21 64 bit
    Total Memory: 250 MB
    Max Memory: 910 MB
    Memory Free: 168 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
Please download the launcher from www.technicpack.net/download

The version you have is not an official release.
