### ISSUE TITLE
error when launching tekkit pack

### ISSUE THREAD

**Issue by clj3100** [TechnicPack/TechnicLauncher#270]
http://pastebin.com/UZTn1kgK
This is a repeating problem every time I click launch. 
I am on a mac also

**Comment by Salynne** [comment]
I see an error in the log where it timed out once, but I don't see any errors for all the other times you click launch.

Do you have any description of the error you get when actually launching the pack?

**Comment by CannibalVox** [comment]
Hello, we just put out a big rewrite of the launcher- I hope your issue is fixed, but if it isn't, I'm going to have to ask you resubmit a new error report so we can investigate in the new codebase.
