### ISSUE TITLE
Optifine and Technic Launcher does not work under Mac OSX

### ISSUE THREAD

**Issue by dwi** [TechnicPack/TechnicLauncher#271]
Hello, I noticed that Optifine in combination with Technic Launcher and OSX is not working and stops loading whole game throwing this error

```
[INFO] [STDERR] org.lwjgl.opengl.OpenGLException: Invalid value (1281)
[INFO] [STDERR]     at org.lwjgl.opengl.Util.checkGLError(Util.java:56)
[INFO] [STDERR]     at org.lwjgl.opengl.Display.swapBuffers(Display.java:645)
[INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71357_I(Minecraft.java:518)
[INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:407)
[INFO] [STDERR]     at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
[INFO] [STDERR]     at net.minecraft.client.Minecraft.run(Minecraft.java:733)
[INFO] [STDERR]     at java.lang.Thread.run(Thread.java:680)
[INFO] [STDOUT] Exiting mod pack
```

Using same Java version nad same Forge version on same OS with different launcher (MultiMC) is working without any problems. I made some testing with Technic Launcher and MultiMC for non-optifine/of ultra/of standard and here are logs:

| Instance | View Diff | MultiMC | Technic Launcher |
| --- | --- | :-: | :-: |
| Just Forge | [view](http://diffchecker.com/zsm9deyc) | [view log](https://dl.dropboxusercontent.com/u/75555/OFTEST/MultiMC-No_Optifine.log) | [view log](https://dl.dropboxusercontent.com/u/75555/OFTEST/TechnicLauncher-No_Optifine.log) |
| Optifine Standard | [view](http://diffchecker.com/5wtx1uor) | [view log](https://dl.dropboxusercontent.com/u/75555/OFTEST/MultiMC-Optifine_STANDARD.log) | [view log](https://dl.dropboxusercontent.com/u/75555/OFTEST/TechnicLauncher-Optifine_STANDARD.log) |
| Optifine Ultra | [view](http://diffchecker.com/h4b38b3x) | [view log](https://dl.dropboxusercontent.com/u/75555/OFTEST/MultiMC-Optifine_ULTRA.log) | [view log](https://dl.dropboxusercontent.com/u/75555/OFTEST/TechnicLauncher-Optifine_ULTRA.log) |

**Comment by Salynne** [comment]
Can you check if the lwjgl versions are different betwen multimc and the technic launcher?

**Comment by dwi** [comment]
They are exactly the same. Tried also copy all libs from MultiMC to Technic Launcher folder

**Comment by Salynne** [comment]
Hmm well the 1281 invalid value happens in all of them, except in my launcher + optifine somehow that crashes it.

This is probably going to be impossible for me to actively fix however it might get fixed when I rewrite the way it launches the game. However that has a sort of nebulous turn around time, I'm not sure how long it will take me or what problems I will run into.

If you end up figuring out what the hell the difference is besides multimc/my launcher, let me know. Unfortunately multimc is not even in java so that makes it even more of a headache.

**Comment by arosen32** [comment]
This also happens when use optifine with technic launcher on OSX it, but it doesnt happen when I try to load a similar modpack with optifine in the Feed the Beast launcher.

**Comment by CannibalVox** [comment]
Hello, we just put out a big rewrite of the launcher- I hope your issue is fixed, but if it isn't, I'm going to have to ask you resubmit a new error report so we can investigate in the new codebase.
