### ISSUE TITLE
Error when launching tekkit classic

### ISSUE THREAD

**Issue by kevinmchung** [TechnicPack/TechnicLauncher#272]
I had this error when launching the tekkit classic modpack.
Can anyone help me?
http://pastebin.com/LPLCnTj2

**Comment by Salynne** [comment]
Have you attempted to launch it multiple times? I have fixed this bug already but unfortunately have not released the fix to the public yet. It should only happen on tekkit classic + a bad connection to the technic website from the launcher. You should be able to get it working by trying again multiple times but I will update this issue when the real fix is promoted.

**Comment by Salynne** [comment]
I believe this is now fixed in promoted builds of the launcher. Just restart your launcher and try again. Sorry for the inconvenience.
