### ISSUE TITLE
Big Dig Modpack, Unable To Downgrade

### ISSUE THREAD

**Issue by Meus-Artis** [TechnicPack/TechnicLauncher#273]
http://pastebin.com/Atb9RSBy
updated to play on my friends server, and now when i try to downgrade, i get this.

**Comment by CannibalVox** [comment]
Hello, we just put out a big rewrite of the launcher- I hope your issue is fixed, but if it isn't, I'm going to have to ask you resubmit a new error report so we can investigate in the new codebase.
