### ISSUE TITLE
No Yogbox

### ISSUE THREAD

**Issue by rrenaud70** [TechnicPack/TechnicLauncher#274]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 249

```
Selected Pack: Yogbox
```

Stack Trace:
    Exception: ReaderException
    Message: special characters are not allowed
    Trace:
        org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:93)
        org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:192)
        org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60)
        org.yaml.snakeyaml.Yaml.load(Yaml.java:424)
        org.spoutcraft.launcher.yml.YAMLProcessor.load(YAMLProcessor.java:127)
        org.spoutcraft.launcher.UpdateThread.isModpackUpdateAvailable(UpdateThread.java:246)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:121)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:95)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_21 64 bit
    Total Memory: 113 MB
    Max Memory: 1335 MB
    Memory Free: 63 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
Have you tried the Reset Pack option?

**Comment by rrenaud70** [comment]
How do i do that?

On Wed, Jun 19, 2013 at 3:14 PM, Dalton J Pelc notifications@github.comwrote:

> Have you tried the Reset Pack option?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TechnicPack/TechnicLauncher/issues/274#issuecomment-19721531
> .

## 

~Ronin Renaud

**Comment by Salynne** [comment]
Click the gear next to the modpack you have selected, this will open up options for that pack. Then click "Reset Pack" and save the options and try running it again.

**Comment by rrenaud70** [comment]
Thanks! :)

On Thu, Jun 20, 2013 at 7:40 PM, Dalton J Pelc notifications@github.comwrote:

> Click the gear next to the modpack you have selected, this will open up
> options for that pack. Then click "Reset Pack" and save the options and try
> running it again.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/TechnicPack/TechnicLauncher/issues/274#issuecomment-19795552
> .

## 

~Ronin Renaud
