### ISSUE TITLE
updating hexxit just f*cked some stuff up and now it wont start

### ISSUE THREAD

**Issue by ichi1410** [TechnicPack/TechnicLauncher#276]
1.
Technic Launcher Error Report:

2.
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )

3.
    Launcher Build: 253

4.

5.
    Selected Pack: Hexxit

6.
Stack Trace:

7.
    Exception: NullPointerException

8.
    Message: null

9.
    Trace:

10.
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:360)

11.
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:136)

12.
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:95)

13.

14.
System Information:

15.
    Operating System: Windows 7

16.
    Operating System Version: 6.1

17.
    Operating System Architecture: x86

18.
    Java version: 1.7.0_17 32 bit

19.
    Total Memory: 50 MB

20.
    Max Memory: 989 MB

21.
    Memory Free: 19 MB

22.
    CPU Cores: 4

**Comment by DarkHorseSki** [comment]
Hexxit worked yesterday, this morning it updates and ...

Launcher Build: 253

```
Selected Pack: Hexxit
```

Stack Trace:
    Exception: ReaderException
    Message: special characters are not allowed
    Trace:
        org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:93)
        org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:192)
        org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60)
        org.yaml.snakeyaml.Yaml.load(Yaml.java:424)
        org.spoutcraft.launcher.yml.YAMLProcessor.load(YAMLProcessor.java:127)
        org.spoutcraft.launcher.UpdateThread.isModpackUpdateAvailable(UpdateThread.java:246)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:121)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:95)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_05 64 bit
    Total Memory: 113 MB
    Max Memory: 910 MB
    Memory Free: 58 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
Hello, we just put out a big rewrite of the launcher- I hope your issue is fixed, but if it isn't, I'm going to have to ask you resubmit a new error report so we can investigate in the new codebase.
