### ISSUE TITLE
An unexpected Error has occurred When Updating Mod pack On BigDig

### ISSUE THREAD

**Issue by Stanlehcopter** [TechnicPack/TechnicLauncher#279]
Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:360)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:136)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:95)

**Comment by tadpole89** [comment]
Looks like you are having trouble updating this pack. Have you played it before?

**Comment by CannibalVox** [comment]
Hello, we just put out a big rewrite of the launcher- I hope your issue is fixed, but if it isn't, I'm going to have to ask you resubmit a new error report so we can investigate in the new codebase.
