### ISSUE TITLE
Crashing while trying to start hexxit pack

### ISSUE THREAD

**Issue by Patrickplatinum** [TechnicPack/TechnicLauncher#280]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 253

```
Selected Pack: Hexxit
```

Stack Trace:
    Exception: ReaderException
    Message: special characters are not allowed
    Trace:
        org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:93)
        org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:192)
        org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60)
        org.yaml.snakeyaml.Yaml.load(Yaml.java:424)
        org.spoutcraft.launcher.yml.YAMLProcessor.load(YAMLProcessor.java:127)
        org.spoutcraft.launcher.UpdateThread.isModpackUpdateAvailable(UpdateThread.java:246)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:121)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:95)

System Information:
    Operating System: Windows Vista
    Operating System Version: 6.0
    Operating System Architecture: x86
    Java version: 1.7.0_25 32 bit
    Total Memory: 48 MB
    Max Memory: 989 MB
    Memory Free: 11 MB
    CPU Cores: 2

I go this while trying to launch hexxit.

**Comment by tadpole89** [comment]
I got the same thing but all I had to do was re-install the launcher. Have you tried that? If that didn't work please let me know.

**Comment by Patrickplatinum** [comment]
I have just tried that and now I get a new error. 

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 253

```
Selected Pack: Hexxit
```

Stack Trace:
    Exception: ReaderException
    Message: special characters are not allowed
    Trace:
        org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:93)
        org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:192)
        org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60)
        org.yaml.snakeyaml.Yaml.load(Yaml.java:424)
        org.spoutcraft.launcher.yml.YAMLProcessor.load(YAMLProcessor.java:127)
        org.spoutcraft.launcher.UpdateThread.isModpackUpdateAvailable(UpdateThread.java:246)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:121)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:95)

System Information:
    Operating System: Windows Vista
    Operating System Version: 6.0
    Operating System Architecture: x86
    Java version: 1.7.0_25 32 bit
    Total Memory: 46 MB
    Max Memory: 989 MB
    Memory Free: 7 MB
    CPU Cores: 2

**Comment by tadpole89** [comment]
It looks like Java is having a hard time reading the coding for the launcher on your computer. If you haven't tried reinstalling or updating Java you should give that a try.

**Comment by Patrickplatinum** [comment]
I'm going to try reinstalling java because it said its the recomended version. If it works I will let you know if not I'll say so.

**Comment by tadpole89** [comment]
Okay.

**Comment by Patrickplatinum** [comment]
Still no changes in the error report. Next month I'm upgrading to a newer computer.

**Comment by DarkHorseSki** [comment]
Hexxit worked yesterday.  Today it updated and now this is what comes up.

Launcher Build: 253

```
Selected Pack: Hexxit
```

Stack Trace:
    Exception: ReaderException
    Message: special characters are not allowed
    Trace:
        org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:93)
        org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:192)
        org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60)
        org.yaml.snakeyaml.Yaml.load(Yaml.java:424)
        org.spoutcraft.launcher.yml.YAMLProcessor.load(YAMLProcessor.java:127)
        org.spoutcraft.launcher.UpdateThread.isModpackUpdateAvailable(UpdateThread.java:246)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:121)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:95)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_05 64 bit
    Total Memory: 113 MB
    Max Memory: 910 MB
    Memory Free: 58 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
Hello, we just put out a big rewrite of the launcher- I hope your issue is fixed, but if it isn't, I'm going to have to ask you resubmit a new error report so we can investigate in the new codebase.
