### ISSUE TITLE
can't update tekkit to 1.1.5 because of this issue.

### ISSUE THREAD

**Issue by natereprogle** [TechnicPack/TechnicLauncher#281]
Launcher Build: 253

```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:360)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:136)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:95)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_07 64 bit
    Total Memory: 152 MB
    Max Memory: 3640 MB
    Memory Free: 67 MB
    CPU Cores: 2

**Comment by reggie88** [comment]
So im not alone:)  Geting the same error:(

**Comment by natereprogle** [comment]
Yeah, it sucks hardcore. Although, I haven't been getting it lately...

**Comment by tadpole89** [comment]
I don't know what your problem is, I had no trouble updating.

**Comment by CannibalVox** [comment]
Hello, we just put out a big rewrite of the launcher- I hope your issue is fixed, but if it isn't, I'm going to have to ask you resubmit a new error report so we can investigate in the new codebase.
