### ISSUE TITLE
error retrieving information for selected pack: [Insert Pack Name Here]

### ISSUE THREAD

**Issue by natereprogle** [TechnicPack/TechnicLauncher#282]
Okay so I am having issues with the launcher saying this to all my packs. It seems that if I choose to remember my login before I download the pack, it can't retrieve it. I choose not to remember the login, and it worked just fine. Any ideas WHY?

**Comment by tadpole89** [comment]
Umm... Are you able to add the pack? If so have you tried reseting it? If that doesn't work I would try completely reinstalling the launcher or reseting the launcher. If these tips didn't help let me know. :)

**Comment by natereprogle** [comment]
It's mostly the already added packs. I want to try Hexxit, but can't get it running

**Comment by natereprogle** [comment]
Okay, now it just won't load the packs at all. All of them say "Error retrieving information for selected pack: [Pack Name]" Please fix, as I can't do anything with the launcher, and I can't even load manually loaded packs.

**Comment by tadpole89** [comment]
Ok, have you tried completely reinstalling the launcher? Meaning have you re-downloaded and deleted the .techniclauncher folder. If so, could you enable the console for the launcher and send me the report in it's entirety after you relaunch it after have enabled the console? Also, I would appreciate more information on your operating system, i.e., Java version, OS version, type ( Mac, Linux, Windows, etc....), and ALL of your computer specs, so I can rule out that you have not met the system requirements for the packs/launcher since I have had this problem and my system requirements were not met completely. Thanks, tadpole. P.S. Try reinstalling your DRIVERS. Also if I could get that information ASAP I could be of a bit more help to you.

**Comment by ruifung** [comment]
I'm having this problem too, I know the launcher is fine since my technic platform modpack can load its info just fine. Only the official technic packs cant.

**Comment by tadpole89** [comment]
Have you tried resetting the launcher and the official modpacks? If not try that and get back to me if it did not work.

**Comment by ruifung** [comment]
_sniff_ Yeah it worked. No idea what caused this in the first place though.

**Comment by tadpole89** [comment]
It is a very common error and I don't know what causes it either but I am glad I could help. If you have any more problems let me know and I will see if I can help fix it.

**Comment by The-living10** [comment]
Selected Pack: Bullet Phase's Pokemon Pack
Stack Trace:
    Exception: ReaderException
    Message: special characters are not allowed
    Trace:
        org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:93)
        org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:192)
        org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60)
        org.yaml.snakeyaml.Yaml.load(Yaml.java:424)
        org.spoutcraft.launcher.yml.YAMLProcessor.load(YAMLProcessor.java:127)
        org.spoutcraft.launcher.UpdateThread.isModpackUpdateAvailable(UpdateThread.java:246)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:121)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:95)

System Information:
    Operating System: Windows Vista
    Operating System Version: 6.0
    Operating System Architecture: x86
    Java version: 1.7.0_25 32 bit
    Total Memory: 60 MB
    Max Memory: 989 MB
    Memory Free: 11 MB
    CPU Cores: 2

**Comment by tadpole89** [comment]
Are you having trouble updating or what?

**Comment by CannibalVox** [comment]
Hello, we just put out a big rewrite of the launcher- I hope your issue is fixed, but if it isn't, I'm going to have to ask you resubmit a new error report so we can investigate in the new codebase.
