### ISSUE TITLE
Missed Libraries

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#283]
Hello a find bug & I want to send you pull. But I have problem.
I am using Netbeans & I missed some Libraries.

How to download (which & where)& install missed Libraries?
Is anywhere tutorial on this?

**Comment by tadpole89** [comment]
Can you be a bit more specific with your problem with the launcher? From what this says all I can tell is that you are missing Lib files but I don't know where you are missing them from... please provide more information if you would like help.

**Comment by CannibalVox** [comment]
We've done a big rewrite of the launcher, so the PR is surely out of date by now.
