### ISSUE TITLE
Unexpected error when updating BigDigs

### ISSUE THREAD

**Issue by VyperKannon** [TechnicPack/TechnicLauncher#284]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 253

```
Selected Pack: Big Dig
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.cleanLogs(UpdateThread.java:170)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:141)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:95)

I've downloaded an played the pack before (but on a different computer) and saw a similar issue but there were no comments saying how to fix the problem, so plz comment asap.

**Comment by tadpole89** [comment]
I honestly have no clue what is wrong, respond with a full crash report if you have one and I might be able to solve it for you.

**Comment by CannibalVox** [comment]
Hello, we just put out a big rewrite of the launcher- I hope your issue is fixed, but if it isn't, I'm going to have to ask you resubmit a new error report so we can investigate in the new codebase.
