### ISSUE TITLE
Tekkit Classic Massive bug

### ISSUE THREAD

**Issue by Yomanz** [TechnicPack/TechnicLauncher#285]
I had to restore my PC so I then restored my .technic\tekkit only cos this is the best pack! Please help me! x:100: 

Here is the Code::

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 253

```
Selected Pack: Tekkit Classic
```

Stack Trace:
    Exception: FileNotFoundException
    Message: C:\Users\AdminRulez\AppData\Roaming.technic\tekkit\bin\minecraft.jar (Access is denied)
    Trace:
        java.io.FileOutputStream.open(Native Method)
        java.io.FileOutputStream.<init>(Unknown Source)
        java.io.FileOutputStream.<init>(Unknown Source)
        org.spoutcraft.launcher.util.Utils.copy(Utils.java:280)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:311)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:134)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:95)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_25 64 bit
    Total Memory: 119 MB
    Max Memory: 910 MB
    Memory Free: 47 MB
    CPU Cores: 2

**Comment by tadpole89** [comment]
What exactly is the "Massive Bug"?

**Comment by ruifung** [comment]
This isn't a bug in the launcher, it's a problem with file permissions. Do you have access to C:\Users\AdminRulez\AppData\Roaming.technic\tekkit\bin\minecraft.jar ? Because the launcher is getting access denied for it.

**Comment by CannibalVox** [comment]
Hello, we just put out a big rewrite of the launcher- I hope your issue is fixed, but if it isn't, I'm going to have to ask you resubmit a new error report so we can investigate in the new codebase.
