### ISSUE TITLE
voltz bug

### ISSUE THREAD

**Issue by henriquetd** [TechnicPack/TechnicLauncher#286]
on technic launcher 1.4.7 voltz it says that cant download minecraft

**Comment by tadpole89** [comment]
Crash or Error report??? Without it nobody can fix it.

**Comment by henriquetd** [comment]
Error report

**Comment by henriquetd** [comment]
wrong button

**Comment by CannibalVox** [comment]
The previous user was asking you to attach a crash or error report, as without it nobody can help you.  You have not in two months, so I am closing this.
