### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by Charles24648** [TechnicPack/TechnicLauncher#287]
Launcher Build: 253

```
Selected Pack: Voltz
```

Stack Trace:
    Exception: FileNotFoundException
    Message: /Users/jstraut/Library/Application Support/technic/voltz/cache/lwjgl-natives-osx-2.4.2.zip (Permission denied)
    Trace:
        java.io.FileInputStream.open(Native Method)
        java.io.FileInputStream.<init>(FileInputStream.java:120)
        org.spoutcraft.launcher.util.Utils.copy(Utils.java:279)
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:77)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:341)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:134)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:95)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.8.4
    Operating System Architecture: x86_64
    Java version: 1.6.0_51 64 bit
    Total Memory: 81 MB
    Max Memory: 1015 MB
    Memory Free: 32 MB
    CPU Cores: 4

**Comment by tadpole89** [comment]
Have you tried running as the administrator?

**Comment by Charles24648** [comment]
Sorry for being late about it but thanks

**Comment by tadpole89** [comment]
Exception: FileNotFoundException 

> Message: /Users/jstraut/Library/Application Support/technic/voltz/cache/lwjgl-natives-osx-2.4.2.zip (Permission denied)

The above listed file is not found and is what is making the pack not work. You need to either download that file manually and put it where it needs to go, or completely get rid of the launcher and the  technic folder and reinstall EVERYTHING over again.

**Comment by CannibalVox** [comment]
Hello, we just put out a big rewrite of the launcher- I hope your issue is fixed, but if it isn't, I'm going to have to ask you resubmit a new error report so we can investigate in the new codebase.
