### ISSUE TITLE
Hex it for the techit launcher wasn't starting properly

### ISSUE THREAD

**Issue by daniel1367** [TechnicPack/TechnicLauncher#288]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 253

```
Selected Pack: Hexxit
```

Stack Trace:
    Exception: ReaderException
    Message: special characters are not allowed
    Trace:
        org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:93)
        org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:192)
        org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60)
        org.yaml.snakeyaml.Yaml.load(Yaml.java:424)
        org.spoutcraft.launcher.yml.YAMLProcessor.load(YAMLProcessor.java:127)
        org.spoutcraft.launcher.UpdateThread.isModpackUpdateAvailable(UpdateThread.java:246)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:121)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:95)

System Information:
    Operating System: Windows Vista
    Operating System Version: 6.0
    Operating System Architecture: x86
    Java version: 1.7.0_07 32 bit
    Total Memory: 51 MB
    Max Memory: 989 MB
    Memory Free: 27 MB
    CPU Cores: 2

**Comment by rantvm** [comment]
Having the same problem, here's the report... http://pastebin.com/EM3KAqr5

**Comment by tadpole89** [comment]
Have you tried resetting the pack and launcher?

**Comment by CannibalVox** [comment]
Hello, we just put out a big rewrite of the launcher- I hope your issue is fixed, but if it isn't, I'm going to have to ask you resubmit a new error report so we can investigate in the new codebase.
