### ISSUE TITLE
BIG DIG FAIL!

### ISSUE THREAD

**Issue by immagrape** [TechnicPack/TechnicLauncher#289]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 253

```
Selected Pack: Big Dig
```

Stack Trace:
    Exception: IOException
    Message: There is not enough space on the disk
    Trace:
        java.io.FileOutputStream.writeBytes(Native Method)
        java.io.FileOutputStream.write(Unknown Source)
        org.spoutcraft.launcher.util.Utils.copy(Utils.java:301)
        org.spoutcraft.launcher.util.Utils.copy(Utils.java:281)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:311)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:126)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:95)

System Information:
    Operating System: Windows XP
    Operating System Version: 5.1
    Operating System Architecture: x86
    Java version: 1.7.0_25 32 bit
    Total Memory: 43 MB
    Max Memory: 989 MB
    Memory Free: 21 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
There is not enough space on your disk to install the game. Please remove some data that is no longer wanted.
