### ISSUE TITLE
Hexxit Crash

### ISSUE THREAD

**Issue by PorkeyMedic** [TechnicPack/TechnicLauncher#291]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 253

```
Selected Pack: Hexxit
```

Stack Trace:
    Exception: IOException
    Message: No space left on device
    Trace:
        java.io.FileOutputStream.writeBytes(Native Method)
        java.io.FileOutputStream.write(FileOutputStream.java:318)
        org.spoutcraft.launcher.util.Utils.copy(Utils.java:301)
        org.spoutcraft.launcher.util.Utils.copy(Utils.java:281)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:54)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:309)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:126)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:95)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.8.2
    Operating System Architecture: x86_64
    Java version: 1.7.0_25 64 bit
    Total Memory: 72 MB
    Max Memory: 1125 MB
    Memory Free: 21 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
There is no more space on your computer to install modpacks. Please free up some space and try again.
