### ISSUE TITLE
idk what this means

### ISSUE THREAD

**Issue by buzzyjw** [TechnicPack/TechnicLauncher#292]
Stack Trace:
    Exception: FileNotFoundException
    Message: /Users/christian/cache/minecraft_1.5.2.jar (No such file or directory)
    Trace:
        java.io.FileOutputStream.open(Native Method)
        java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        org.spoutcraft.launcher.util.Utils.copy(Utils.java:280)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:54)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:309)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:126)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:95)

**Comment by CannibalVox** [comment]
Hello, we just put out a big rewrite of the launcher- I hope your issue is fixed, but if it isn't, I'm going to have to ask you resubmit a new error report so we can investigate in the new codebase.
