### ISSUE TITLE
New LauncherCore not on GitHub

### ISSUE THREAD

**Issue by lilyinstarlight** [TechnicPack/TechnicLauncher#294]
While trying to build the new Technic Laucher with LauncherCore, I noticed that net.technicpack.launchercore did not exist but was referenced.  It seems that the code for the new LauncherCore was never added to the master branch.

**Comment by dunem666** [comment]
compile the launcher core separately, place the core into the source for the launcher and re-build it with maven.

dunem666
lifemmo.com

From: Foster McLane
Sent: ‎04‎ ‎October‎ ‎2013 ‎20‎:‎42
To: TechnicPack/TechnicLauncher
Subject: [TechnicLauncher] New LauncherCore not on GitHub (#294)

While trying to build the new Technic Laucher with LauncherCore, I noticed that net.technicpack.launchercore did not exist but was referenced. It seems that the code for the new LauncherCore was never added to the master branch.

**Comment by Salynne** [comment]
https://github.com/TechnicPack/LauncherCore

Right there. :)

**Comment by Nightreaver** [comment]
Where to place the launchercore-1.0.0-SNAPSHOT.jar in TechnicLauncher folder ?
Some hints please

**Comment by Salynne** [comment]
You don't need to place it in the technic launcher folder?

What are you trying to do?

**Comment by Nightreaver** [comment]
what dunem666 has written above.

"compile the launcher core separately, place the core into the source for the launcher and re-build it with maven. "

How to compile the new launcher? 
I always get "could not resolve dependencies[...] net.technicpack.launchercore:jar:1.0.0-SNAPSHOT"

**Comment by Salynne** [comment]
If you do mvn install on the core, it should be able to find the dependency when you mvn install the launcher.

**Comment by Nightreaver** [comment]
ah, i use "mvn clean package" on both.

so that wrong? how to compile a .exe file now?

**Comment by Salynne** [comment]
yeah

Core:
mvn clean install

Launcher:
mvn clean install -P package-win

**Comment by Nightreaver** [comment]
started from ground up, fresh source, removed .m2 folder

i get build failure 

http://pastebin.com/xjJFZMdG

i'm on Windows7 x64

Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 14:51:28+0100)
Maven home: C:\Program Files (x86)\apache-maven\bin..
Java version: 1.7.0_25, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_25\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

**Comment by Salynne** [comment]
Looks like the source isn't actually up to date on your launcher source if it's looking for getBuild in Settings.java. I removed those calls in the current master.

https://github.com/TechnicPack/TechnicLauncher/commit/518b6b7eeffb70aaa5d24b3886f026b08a30cd8b

**Comment by Nightreaver** [comment]
yes, used the 7 days old sources

thanks!
