### ISSUE TITLE
Backup file is wrong version name

### ISSUE THREAD

**Issue by rupertcow** [TechnicPack/TechnicLauncher#30]
For example if I am using the Technic 6.0.3 version and I update to Technic 6.0.4. It will save the backup file of the 6.0.3 version named 6.0.4-backup.zip where the actual backed up version was 6.0.3. So I had made a few backups and when it reverts it returns to that backup. Which is the version before the backup was made so I have to remove backups and download it all again to actually revert versions. 

To my understanding these backups are used to easily change versions but it could also just be a backup for safety of not loosing configurations and saves.

You can reproduce this bug by simply changing versions and watching it save the backup named the following version you are changing to. Reading over the Issues I am not sure if this is described on issue #22

Thanks for reading

**Comment by luisantonioa** [comment]
Cheers Ruppert will have a look into it
