### ISSUE TITLE
Rewrite login gui

### ISSUE THREAD

**Issue by Spyboticsguy** [TechnicPack/TechnicLauncher#300]
Here is my model for a new login gui - this may be implemented by me some time in the future, but for now, this is simply documenting it so that the idea doesn't slip away from me.
- [ ] Add a 'Launch' button that is greyed out unless a player is logged in or the 'play offline' tickbox is checked - this button will launch the game and allow the player to choose a pack post-login
- [ ] Move 'remember' down below the login boxes and add a 'play offline' tickbox -the play offline tickbox will force the game to launch into offline mode and will enable launching without logging in
- [ ] Change 'Launch' to switch to a 'Login' button that becomes a 'logout' button if not logged in
- [ ] Make saved faces activate a login method that refreshes the token and automatically logs out/logs in a player

**Comment by CannibalVox** [comment]
This is interesting, but go ahead and remove the option to play offline, that's not really something we allow.

**Comment by Salynne** [comment]
Offline should function in exactly the same way the Mojang launcher does it, whatever way that currently is. I haven't looked into it lately. Like if it has to time out first or know the auth server is down or something, then allows offline, then go ahead and do it like that. I haven't looked at how they are doing it right now.

**Comment by CannibalVox** [comment]
We rewrote the crap out of this!  You can see it in the beta stream- please open new issues for requested changes to the rewrite.

**Comment by Spyboticsguy** [comment]
Oh, cool, saw the new changes - I still hadn't had time to get around to this, so thanks :+1:

I'll see if THIS weekend permits me to work on that launcher-hider-option-thing.
