### ISSUE TITLE
1.6.4 modpacks wont launch with modpack.jar inside bin folder (forge)

### ISSUE THREAD

**Issue by Nightreaver** [TechnicPack/TechnicLauncher#302]
hey, im trying to get a modpack running with just forge yet. but every time i try to start the modpack with a "modpack.jar" file inside the bin folder, the version.json gets changed and the launcher refuses to launch anything again with that "modpack" (renamed minecraftforge-universal-1.6.4-9.11.1.933.jar)

i think its the "--tweakClass cpw.mods.fml.common.launcher.FMLTweaker"

http://pastebin.com/r1ZEd1QT

but maybe i'm completely wrong with this.
maybe another folder for the modpack or anything?

found error in log

2013/10/18 00:42:16 [SCHWERWIEGEND] Unhandled Exception in Thread[InstallThread,6,main]
java.lang.RuntimeException: Library net.technicpack.launchercore.minecraft.Library@47e9e334 not found.
    at net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:138)
    at net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:88)
    at net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:51)
    at org.spoutcraft.launcher.InstallThread.run(InstallThread.java:54)

actually all the libraries are stored in 
.technic\cache...

so forge should be in 
.technic\cache\net\minecraftforge\minecraftforge\9.11.1.933...

but it fires above error if "launch" is pressed

also this cant be manipulated by modpack .zip files, so the library path should be moved inside each mod folder (or it should look inside both)

so its either

.technic\modpacks[MODPACK]\libraries\net\minecraftforge\minecraftforge\9.11.1.933... (which i prefer)

or

.technic\modpacks[MODPACK]\cache\net\minecraftforge\minecraftforge\9.11.1.933...

or anything else i cant imagine 

another bug: once it gets corrupted not even "reset pack" will make it work again!

**Comment by CannibalVox** [comment]
Hello,

We are supposed to overwrite the version.json with the one inside modpack.jar, that is good.  It should not be failing to run as a result, though.

This issue should be fixed in the beta stream, please change your launcher options to load the beta build of the launcher and verify that this is fixed.  Thank you.
