### ISSUE TITLE
Tekkit is upside down in Technic Launcher (Mac)

### ISSUE THREAD

**Issue by abread** [TechnicPack/TechnicLauncher#305]
For all Mac OS X users Tekkit is showing upside down and mirrored as described in the forums: http://forums.technicpack.net/threads/launched-upside-down-mac-w-lwjgl-fix.43689/

Posting an issue to make sure it is noticed.
The graphics are upside down and mirrored but mouse clicks appear to ignore that.
Gameplay can be possible by entering Full-Screen mode which temporarily fixes the issue (but most mac users like to multitask and you cannot swipe between screens with the Minecraft's built-in full-screen mode, only by pressing the "Mac included" button).

**Comment by CannibalVox** [comment]
Which tekkit?

**Comment by abread** [comment]
The "main" Tekkit (not tekkit lite nor tekkit classic)

**Comment by CannibalVox** [comment]
Can you see if we have this issue fixed in the beta stream?

**Comment by abread** [comment]
Yes. It is fixed! Thanks
Great new UI by the way
