### ISSUE TITLE
1.6.x packs dont launch after installing forge

### ISSUE THREAD

**Issue by disconsented** [TechnicPack/TechnicLauncher#306]
Launcher Version: 292
Operating System: Windows 8 Pro 64 Bit (pre 8.1)
Java Version: V7 Update 9 (build 1.7.0_09-b05)
Antivirus Program: Bit Defender

Description of Problem:
After installing forge for minecraft 1.6.2 the pack refuses to load (click launch, the progress box briefly shows saying "%0" then disappears) .
http://pastie.org/8415404

**Comment by disconsented** [comment]
Okay this appears to be a forge 871 issue only

**Comment by CannibalVox** [comment]
That's good to hear, thank you for keeping us updated.
