### ISSUE TITLE
Load old minecraft modpack

### ISSUE THREAD

**Issue by vavraCZe** [TechnicPack/TechnicLauncher#307]
1. Add modpack
2. Login
3. Download
4. Extracting
5. Running normal mc

Why?! Mods are in mods folder, but minecraft.jar is original... Its a bug in new version launcher.

You can try it: http://www.technicpack.net/modpack/details/customcraftcz.87153

**Comment by CannibalVox** [comment]
This isn't really a bug- it's an issue with your pack which the old launcher was more tolerant of, but we've been very clear about.  The natives, lwjgl, etc. files should not be in your bin folder.  It should be empty except for your modpack.jar, really, unless you've got a very good reason to include other stuff.  We've updated and moved around the other files in the new launcher, so continuing to include them in your bin folder will break your pack.
