### ISSUE TITLE
Unable to paste text into password field.

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#31]
Hello,

Just wanted to try out the launcher right about five minutes ago, but I came to realize that it didn't support for me to paste my password into the login form.

This is a huge problem for me, since I'm using 1Password and have a standard of using 32 character long passwords, and unique. I could type my whole password, which I'm going to do, just to try the launcher.

But I'm reporting this, so that maybe in the future, that a contextual right-click menu and common ctrl/cmd+v commands can work.

Love the work! Thank you.

**Comment by ghost** [comment]
How is this coming around? I would really like to try out Tekkit/Technic a lot more, but having to manually type 32 chars each time I reinstall, is starting to become a hazle.

Thanks.

**Comment by luisantonioa** [comment]
I've not looked into this issue.. I agree its annoying but there are much more pressing issues which need attention first.. you could always try figure out the code yourself and submit a pull request if you can trawl through java code!

**Comment by ghost** [comment]
Thanks for taking the time to reply!

I tried :) But the code from the upstream Spoutcraft launcher has almost the same code, and everything around the password field seemed all the same to me. I'll take another dive into this weekend, and I'll report back if I find any useful.

**Comment by icbat** [comment]
Mindtooth:

Tried to reproduce this today, and I can paste fine. Furthermore, my password manager works fine with auto-input to it. 

Could you provide more details on how to reproduce this? What OS, what version of the launcher, etc.? I'd like to help look in to this.

(I'm on Win 7 SP 1, Launcher 1.0.1.3, Java 7u4, using KeePass as the password manager I tested with).

**Comment by ghost** [comment]
Using Technic Launcher via Mac OS X Lion 10.7.4, with both Java 6 and Java 7.

1.6.0_32-b05-417.jdk
jdk1.7.0_06.jdk

I'm running the latest version of the launcher via the homepage; 1.0.1.3.

Thanks :)

**Comment by icbat** [comment]
It could very well be the Mac =( Not sure, honestly. I don't currently have
an OSX to test with. I can try to get one, but do you have a Windows
VM/Parallels/anything like that?

Sorry I can't be of more direct help.

On Thu, Jun 7, 2012 at 9:42 AM, Birger J. Nordølum <
reply@reply.github.com

**Comment by ghost** [comment]
Yes I have. But won't be able to test before later today. I'll report back then.

**Comment by ghost** [comment]
Believe I found the problem. It doesn't respect the fact that I'm sitting on a Mac, and not honor the CMD+V approach, etc. If I used CTRL+V it were able to paste the text.

**Comment by luisantonioa** [comment]
I wonder if that's a java specific thing or our codebase

**Comment by ghost** [comment]
When using the official launcher, it respects the platform specific way (CMD+V). But right-click doesn't work there either.
