### ISSUE TITLE
POM missing dependency?

### ISSUE THREAD

**Issue by jordandmc** [TechnicPack/TechnicLauncher#310]
When I try to clone the project to start working with it, eclipse tells me that the POM has an error. It says that its "Missing artifact net.technicpack:launchercore:jar:1.0.0-SNAPSHOT". Does this only happen for me? Might I be missing a step when I try to import the project?
![capture01](https://f.cloud.github.com/assets/867312/1440820/bdf44ce4-41a0-11e3-8533-f3a1d1f6584d.PNG)

**Comment by CannibalVox** [comment]
The TechnicLauncher project depends on our other LauncherCore project.  This isn't really an issue with the launcher, but with your environment, so I will close this.
