### ISSUE TITLE
Vanilla Minecraft

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#313]
When I run Vanilla Minecraft to download it shows this

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 0

Stack Trace:
    Exception: WrappedIOException
    Message: Failed to download http://assets.minecraft.net/1_7_2/minecraft.jar
    Trace:
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:46)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:321)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:125)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)
        Caused By: (DownloadException)
            [Unable to download file]
            org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
            org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:46)
            org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:321)
            org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:125)
##             org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_45 64 bit
    Total Memory: 154 MB
    Max Memory: 1820 MB
    Memory Free: 44 MB
    CPU Cores: 4

**Comment by FinnGrimm** [comment]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )

##     Launcher Build: 0

Stack Trace:
    Exception: WrappedIOException
    Message: Failed to download http://assets.minecraft.net/1_7_2/minecraft.jar
    Trace:
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:46)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:321)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:125)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)
        Caused By: (DownloadException)
            [Unable to download file]
            org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
            org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:46)
            org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:321)
            org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:125)

##             org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_17 32 bit
    Total Memory: 37 MB
    Max Memory: 989 MB
    Memory Free: 11 MB
    CPU Cores: 2 

Same happens to me

**Comment by GenPage** [comment]
It just means that the file was not able to be downloaded from Mojang. If you try the link yourself, you will notice the error. http://assets.minecraft.net/1_7_2/minecraft.jar 

``` xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>1_7_2/minecraft.jar</Key>
<RequestId>70960C7FCED4419C</RequestId>
<HostId>
adBlXFnBNDFc51GXwguc/vRjKfogwZlf8i4zByXs7MHswnrX58nsv6Mj2KF0Rsng
</HostId>
</Error>
```

It should properly go through assets.minecraft.net, but the direct links to the AWS store are here: http://pastebin.com/U2U5WMTP

I'll leave that up to @CannibalVox

**Comment by Kobata** [comment]
You're using a version of the launcher which doesn't support 1.6 or 1.7, try downloading a new copy.

**Comment by ghost** [comment]
On Saturday, November 2, 2013 2:58 AM, Dylan Page notifications@github.com wrote:

It just means that the file was not able to be downloaded from Mojang. If you try the link yourself, you will notice the error. http://assets.minecraft.net/1_7_2/minecraft.jar 

NoSuchKey
The specified key does not exist.
1_7_2/minecraft.jar
70960C7FCED4419C

adBlXFnBNDFc51GXwguc/vRjKfogwZlf8i4zByXs7MHswnrX58nsv6Mj2KF0Rsng

It should properly go through assets.minecraft.net, but the direct links to the AWS store are here: http://pastebin.com/U2U5WMTP
I'll leave that up to @CannibalVox
—
Reply to this email directly or view it on GitHub.

Where do I put the .jar file, and then what else do I do?

**Comment by GenPage** [comment]
Make sure to check what Kobata said

**Comment by CannibalVox** [comment]
All of the issues in this task are from a version of the launcher that was weeks out of date when this was posted.  I have no idea how you're still using this version of the launcher, but you need to let it update, or re-download the launcher if it's not doing so on its own.
