### ISSUE TITLE
Launcher not launching`

### ISSUE THREAD

**Issue by antman56** [TechnicPack/TechnicLauncher#317]
The launcher is not launching and finally came up with this message:

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 344

```
Selected Pack: Shape Shifter Z+Too Many Items
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.InstalledPack.loadCachedImage(InstalledPack.java:272)
        net.technicpack.launchercore.install.InstalledPack.loadImage(InstalledPack.java:261)
        net.technicpack.launchercore.install.InstalledPack.getLogo(InstalledPack.java:236)
        org.spoutcraft.launcher.skin.components.PackButton.setPack(PackButton.java:72)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:145)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:201)
        org.spoutcraft.launcher.Launcher.refreshPack(Launcher.java:279)
        net.technicpack.launchercore.install.InstalledPack$1.run(InstalledPack.java:308)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_45 32 bit
    Total Memory: 59 MB
    Max Memory: 247 MB
    Memory Free: 16 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
The pack is this one?  http://www.technicpack.net/modpack/details/shape-shifter-152.106320

**Comment by angeltera01** [comment]
Hi i have the same issue and it came up with a similar error message:

```
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 349

    Selected Pack: Hexxit
Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:85)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_45 32 bit
    Total Memory: 53 MB
    Max Memory: 247 MB
    Memory Free: 28 MB
    CPU Cores: 4
```

sorry for the huge msg but i really need help as im an admin on a server that is about to switch to hexit. Please
help.

**Comment by CannibalVox** [comment]
Hi, angeltera01,

Thank you for reporting this issue- you are currently on the beta build, so any time you are in a rush to get a working launcher, try switching to the stable build temporarily.  I appreciate you finding this issue with our beta launcher, though, and I'll have a fix posted momentarily.

**Comment by angeltera01** [comment]
Thank you very much, however when i switch to stable build it comes up with the same error msg or just doesnt load. But thank you so much for getting back to me straight away

**Comment by CannibalVox** [comment]
Well I've promoted a fixed beta launcher, if you continue to have issues, please repost your error.

**Comment by angeltera01** [comment]
Ok thank you very much, if it keeps crashing out at 0% version.json without giving me an error msg would you recommend deleting the technic launcher and re installing it? Have just tried beta version and stable version still stopping and not loading any futher but not giving me error messages. Luckily the server will not be updated till tomorrow will try restarting my computer.

**Comment by CannibalVox** [comment]
I would go to the cogwheel in the top right hand corner, click it, in the menu that pops up, click "show console".  Then attempt to start hexxit again.  After it gets stuck, copy the contents of the console here so I can read it

**Comment by angeltera01** [comment]
Did i post you the console log?

**Comment by angeltera01** [comment]
Thank you ever so much, i restarted my computer and have got the launcher working, lots of love to you <3 and thanks for working so hard. There were a few warnings in the console pannel but its working so im happy. Thank you for listening and helping me.

**Comment by CannibalVox** [comment]
Np, I'm glad you're up and running!

**Comment by antman56** [comment]
All good... In the end, after I restarted my computer, It started working again... Thanks!!
