### ISSUE TITLE
Wrong update mechanism

### ISSUE THREAD

**Issue by vavraCZe** [TechnicPack/TechnicLauncher#318]
Update mods folder mods/1.6.4 is impossible. Previous lib files is not removed after the update. Why? 

Older containing are mistake and now I can´t update to the new.

**Comment by CannibalVox** [comment]
er, wha

What modpack are you having trouble with

**Comment by dunem666** [comment]
put the new libs in your bin with your modpack. 

but yes he is correct, the new launcher doesnt think about replacing and updating anyother libraries in the modpack folder, (providing you have old one installed)

i discovered this issue when players could not update my modpack from 1.5.2 to 1.6.4

**Comment by CannibalVox** [comment]
What libs are you talking about?

**Comment by vavraCZe** [comment]
https://dl.dropboxusercontent.com/u/8167722/blabla.png << these libs

and... its update from 1.6.4 to 1.6.4 :) ... My modpack :) 
http://www.technicpack.net/modpack/details/customcraftcz.87153

**Comment by CannibalVox** [comment]
Those files belong in the mods folder.

**Comment by CannibalVox** [comment]
Oh, man, I misunderstood you guys.  Yes, we have an open pull request to fix this, I'm just trying to get a couple changes to it before I pull.
