### ISSUE TITLE
It said submit this crash report.  So I am.  javax.swing.text.BadLocationException: Length must be positive

### ISSUE THREAD

**Issue by keenerb** [TechnicPack/TechnicLauncher#321]
http://pastebin.com/aGvxt7Hn

Exception: StateInvariantError
    Message: GlyphView: Stale view: javax.swing.text.BadLocationException: Length must be positive

**Comment by CannibalVox** [comment]
Do me a favor and update your java to the latest version and see if this still occurs.  If it still does, post the new crash report.

**Comment by CannibalVox** [comment]
Another user with the latest java reported this same issue, so I'm closing this one as a dupe and preferencing the other report.
