### ISSUE TITLE
Crash Report to Submit!

### ISSUE THREAD

**Issue by rowanquigley** [TechnicPack/TechnicLauncher#322]
http://pastebin.com/AqQsVXZb

Just attempted to start my Technic Launcher and it said to generate a crash report, I did so and it also directed me to this page to post so I thought I would.

**Comment by CannibalVox** [comment]
When you restart your launcher and try again, does it happen again?

**Comment by rowanquigley** [comment]
Seems not, must be just a bug, oh well. Thanks for the help.

**Comment by CannibalVox** [comment]
Yeah, this issue has happened to others randomly and I've had a hard time tracking down exactly what it is.  It seems to only happen to people who have selected platform packs.  I'm going to leave this issue open as a placeholder, so I can remember to do more research into this.  Thanks for the report!

**Comment by CannibalVox** [comment]
This should be fixed in beta 362- switch your launcher to beta and open a new issue if you have problems.
