### ISSUE TITLE
RuntimeException, Library not found

### ISSUE THREAD

**Issue by sirenman2000** [TechnicPack/TechnicLauncher#324]
Got an error in the launcher, as follows. Also at http://pastebin.com/T4PDsmX7

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 354

```
Selected Pack: BinaryPack [1.6.4]
```

Stack Trace:
    Exception: RuntimeException
    Message: Library net.minecraftforge:forge:1.6.4-9.11.1.964 not found.
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:152)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:71)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_25 64 bit
    Total Memory: 245 MB
    Max Memory: 3640 MB
    Memory Free: 147 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Can you link me to this pack?

**Comment by CannibalVox** [comment]
This should be fixed in the new update.
