### ISSUE TITLE
nullpointerexseption

### ISSUE THREAD

**Issue by domrj** [TechnicPack/TechnicLauncher#325]
1.
Technic Launcher Error Report:

2.
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )

3.
    Launcher Build: 354

4.

5.
    Selected Pack: null

6.
Stack Trace:

7.
    Exception: NullPointerException

8.
    Message: null

9.
    Trace:

10.
        java.io.File.<init>(Unknown Source)

11.
        net.technicpack.launchercore.install.InstalledPack.getInstalledDirectory(InstalledPack.java:179)

12.
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:56)

13.
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:60)

14.

15.
System Information:

16.
    Operating System: Windows 7

17.
    Operating System Version: 6.1

18.
    Operating System Architecture: amd64

19.
    Java version: 1.7.0_10 64 bit

20.
    Total Memory: 134 MB

21.
    Max Memory: 890 MB

22.
    Memory Free: 82 MB

23.
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Could you provide some information about what you were doing?

**Comment by CannibalVox** [comment]
At the very least, this should no longer crash in the new update (although based on our conversation, it sounds like you have an issue to resolve before you can play your pack).
