### ISSUE TITLE
Technic Launcher Error Report

### ISSUE THREAD

**Issue by weylinwulf** [TechnicPack/TechnicLauncher#326]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 358

```
Selected Pack: Tekkit Classic
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:60)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:60)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_45 64 bit
    Total Memory: 123 MB
    Max Memory: 1820 MB
    Memory Free: 53 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
This should be fixed in beta 364.  Please try it out and open a new issue if you have problems still.
