### ISSUE TITLE
StateInvariantError

### ISSUE THREAD

**Issue by rcmaehl** [TechnicPack/TechnicLauncher#327]
http://pastebin.com/jQ7RqLq4

P.S. This error opened ~100 windows all containing the same error. If you could fix that, that'd be just great.

**Comment by CannibalVox** [comment]
You are a beautiful unicorn running the latest version of java and I thank you for that.  Can you get me the log of this incident from .technic/logs?  The entire log file.

**Comment by rcmaehl** [comment]
Yeah, I'll do it when I wake up. My desktop is off for the day n

**Comment by CannibalVox** [comment]
We've moved this issue to #338 so I'm closing this as a dupe.  Important fact, though: I rolled out a fix in beta build 360 that should prevent a zillion windows from opening and ideally make this error more helpful, so let me know what happens.
