### ISSUE TITLE
Error on first time boot.

### ISSUE THREAD

**Issue by EntranceJew** [TechnicPack/TechnicLauncher#330]
http://pastebin.com/cUz7cbC7

I just installed my OS and Java.
I installed technic and Java in their own custom folders, if that has any impact on things.
I hadn't rebooted since installing Java.

I was hoping to kill some time while I waited for windows updates to set in. :U

**Comment by hightec123** [comment]
ThaWhat I'm Having A Problem With

**Comment by CannibalVox** [comment]
First: are you sure you're supposed to have a 32-bit operating system?

Second: This should be fixed in beta 364.  Please try it out and open a new issue if you have problems still.
