### ISSUE TITLE
Error on first boot

### ISSUE THREAD

**Issue by whiskey07** [TechnicPack/TechnicLauncher#332]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 358

```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.skin.components.PackButton.setPack(PackButton.java:72)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:145)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:201)
        org.spoutcraft.launcher.Launcher$3.run(Launcher.java:124)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_25 32 bit
    Total Memory: 58 MB
    Max Memory: 247 MB
    Memory Free: 30 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
After some investigation, this crash is the same as the one reported in #322 - for some reason getLogo() is very rarely returning null here even though that should never happen.  I"m going to close this as a dupe, but thank you for your report
