### ISSUE TITLE
Getting malformed error with downloaded custom mod packs

### ISSUE THREAD

**Issue by Dooglesmile** [TechnicPack/TechnicLauncher#342]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 358

```
Selected Pack: DooglesWorld1.6.4
```

Stack Trace:
    Exception: IllegalArgumentException
    Message: MALFORMED
    Trace:
        java.util.zip.ZipCoder.toString(Unknown Source)
        java.util.zip.ZipFile.getZipEntry(Unknown Source)
        java.util.zip.ZipFile.access$900(Unknown Source)
        java.util.zip.ZipFile$1.nextElement(Unknown Source)
        java.util.zip.ZipFile$1.nextElement(Unknown Source)
        net.technicpack.launchercore.util.ZipUtils.unzipFile(ZipUtils.java:140)
        net.technicpack.launchercore.util.ZipUtils.unzipFile(ZipUtils.java:114)
        net.technicpack.launchercore.install.ModpackInstaller.installMod(ModpackInstaller.java:146)
        net.technicpack.launchercore.install.ModpackInstaller.installModpack(ModpackInstaller.java:131)
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:77)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:60)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_21 64 bit
    Total Memory: 154 MB
    Max Memory: 1820 MB
    Memory Free: 78 MB
    CPU Cores: 4

Link to modpack is http://www.dooglesworld.co.uk/games/modpack.zip
Works fine if I download it and install it manually.

**Comment by CannibalVox** [comment]
First: update your java to 1.7.0_45.
Second: This issue should be fixed in beta 365

Please open a new issue if the problem persists or you have other problems, after updating your java.

**Comment by Dooglesmile** [comment]
Thanks for that. doing those things got rid of the malformed error. Still didn't load the pack though, but I tracked that down to the Millinaire mod having a corrupted file in the languages/zh_tw folder called õ¢+þö¿Þ¬¬µÿÄ.txt. I removed that and re-uploaded the mod pack and it is now working properly.
Thanks again for the help.
