### ISSUE TITLE
Launcher crashing report below

### ISSUE THREAD

**Issue by XXDRAGON8ORNXX** [TechnicPack/TechnicLauncher#345]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 358

```
Selected Pack: Hack Slash Mine
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.skin.components.PackButton.setPack(PackButton.java:72)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:151)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:201)
        org.spoutcraft.launcher.Launcher.refreshPack(Launcher.java:279)
        net.technicpack.launchercore.install.InstalledPack$1.run(InstalledPack.java:309)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_40 64 bit
    Total Memory: 122 MB
    Max Memory: 1813 MB
    Memory Free: 67 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
This should be fixed in beta 362- switch your launcher to beta and open a new issue if you have problems.
