### ISSUE TITLE
So i was gona play some hexxit and got this

### ISSUE THREAD

**Issue by Erthix** [TechnicPack/TechnicLauncher#346]
http://pastebin.com/0LA86pzX

**Comment by CannibalVox** [comment]
This should be fixed in beta 364.  Please try it out and open a new issue if you have problems still.

**Comment by CannibalVox** [comment]
Additionally, please update your java to 1.7.0_45 before opening a new issue.

**Comment by Erthix** [comment]
I downloaded that update and reinstalled my whole technic pack and i got it to working now so thanks for helping me with this problem.
