### ISSUE TITLE
bad mod pack

### ISSUE THREAD

**Issue by powersoldier11** [TechnicPack/TechnicLauncher#347]
1.
Technic Launcher Error Report:

2.
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )

3.
    Launcher Build: 358

4.

5.
    Selected Pack: RageTech

6.
Stack Trace:

7.
    Exception: NullPointerException

8.
    Message: null

9.
    Trace:

10.
        org.spoutcraft.launcher.skin.components.PackButton.setPack(PackButton.java:72)

11.
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:127)

12.
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:201)

13.
        org.spoutcraft.launcher.Launcher.refreshPack(Launcher.java:279)

14.
        net.technicpack.launchercore.install.InstalledPack$1.run(InstalledPack.java:309)

15.

16.
System Information:

17.
    Operating System: Windows 7

18.
    Operating System Version: 6.1

19.
    Operating System Architecture: amd64

20.
    Java version: 1.7.0_05 64 bit

21.
    Total Memory: 122 MB

22.
    Max Memory: 1818 MB

23.
    Memory Free: 56 MB

24.
    CPU Cores: 4

**Comment by CannibalVox** [comment]
This issue is fixed in the current beta build- if you need help changing streams to use the beta, please let me know.
