### ISSUE TITLE
Can't Start Launcher.

### ISSUE THREAD

**Issue by CloudThwWolf** [TechnicPack/TechnicLauncher#349]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 358

```
Selected Pack: Wolf Quest Mod Pack [1.6.4]
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.skin.components.PackButton.setPack(PackButton.java:72)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:151)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:201)
        org.spoutcraft.launcher.Launcher.refreshPack(Launcher.java:279)
        net.technicpack.launchercore.install.InstalledPack$1.run(InstalledPack.java:309)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_40 64 bit
    Total Memory: 95 MB
    Max Memory: 853 MB
    Memory Free: 38 MB
    CPU Cores: 3

**Comment by CannibalVox** [comment]
This is fixed in the current beta version.
