### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by abalabahaha** [TechnicPack/TechnicLauncher#351]
When leaving Tekkit Classic on overnight, and the console open, the console ate 4.6GB of ram and 91% of my i7-3770K overclocked processor. No errors, just annoying mouse lag and heat.

**Comment by CannibalVox** [comment]
First: thanks for this issue!
Second: Does it occur reliably
Third: Does it occur with the console closed?
Fourth: Does it occur with the console closed but the launcher left open (you can configure the launcher to not hide in the cogwheel menu on the upper right of the launcher).

**Comment by abalabahaha** [comment]
It occurs every time I leave Tekkit Classic with console open but launcher frame closed on, usually for 3+ hours of AFK.

I will test the Third and Fourth, and monitor it.

EDIT: And try it out with the new version

**Comment by abalabahaha** [comment]
Statistics:

Launcher beta 365 - No console, no launcher window. After closing Tekkit Classic, launcher window appears as a blank white square, not responding, 3.95GB RAM 89% CPU.

Launcher beta 365 - Yes console, no launcher window. Tekkit Classic itself is 4% CPU. The launcher/console process is 4.8GB RAM, 91% CPU

EDIT: Launcher beta 365 - No console, yes launcher window. Still 4ish GB RAM, 90%cpu

**Comment by CannibalVox** [comment]
Unfortunately I can't seem to reproduce this when the profiler is running- the pack menu over the course of an hour stayed under 150Mb. Are you running the pack with any special arguments?

**Comment by CannibalVox** [comment]
Is this still occurring?  Sorry I've been so slack about this.

**Comment by abalabahaha** [comment]
Nah it's fixed, thanks!
