### ISSUE TITLE
Crashes When Installing BusinessElite Modpack

### ISSUE THREAD

**Issue by pyrogamer6** [TechnicPack/TechnicLauncher#352]
This is the webpage with the crash report.
http://pastebin.com/xj3Ft91b

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 358

```
Selected Pack: BusinessElite
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.ModpackInstaller.installOldForgeLibs(ModpackInstaller.java:97)
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:62)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:60)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.8.5
    Operating System Architecture: x86_64
    Java version: 1.7.0_45 64 bit
    Total Memory: 156 MB
    Max Memory: 910 MB
    Memory Free: 106 MB
    CPU Cores: 4

---

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 358

```
Selected Pack: BusinessElite
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.ModpackInstaller.installOldForgeLibs(ModpackInstaller.java:97)
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:62)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:60)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.8.5
    Operating System Architecture: x86_64
    Java version: 1.7.0_45 64 bit
    Total Memory: 156 MB
    Max Memory: 910 MB
    Memory Free: 106 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
This should be fixed in beta 364.  Please try it out and open a new issue if you have problems still.
