### ISSUE TITLE
Technic help

### ISSUE THREAD

**Issue by tylerperry18** [TechnicPack/TechnicLauncher#356]
ok so iv been trying to open hexxit on line and i keep getting this error message can someone helpme 

stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:60)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:60)

**Comment by CannibalVox** [comment]
You get it every single time?  What if you wait awhile after opening before you click PLAY.

**Comment by tylerperry18** [comment]
ya i get it every time so fare

**Comment by CannibalVox** [comment]
Can you put your entire .technic folder into a zip file and post it on mediafire, and link me to it?  If you're not sure how, please ask someone in your household for help.  This will help me figure out why this error happens so I can fix it for you and everyone.

**Comment by tylerperry18** [comment]
http://www.mediafire.com/download/7cby3ncq9i97j9y/New%20Compressed%20(zipped)%20Folder.zip

**Comment by abalabahaha** [comment]
tylerperry18 that's not the correct one.
If you're on windows, press the Windows key and "R" on the keyboard. Type %APPDATA%, then you should see a .technic. Zip and upload that.
If it's a mac, Shift-Command-G on the keyboard, type "~/Library/Application Support/" and zip the "technic" folder

**Comment by tylerperry18** [comment]
sorry i think this is it 
http://www.mediafire.com/view/9a9ginh6dfn07fk/Getting%20Started%20with%20MediaFire.pdf

**Comment by CannibalVox** [comment]
That is a tutorial of how to use mediafire.

**Comment by tylerperry18** [comment]
http://www.mediafire.com/download/qisb5m5tr6b7iiw/New%20Compressed%20(zipped)%20Folder.zip

**Comment by CannibalVox** [comment]
That's what I need... although I'm not seeing any reason for your trouble here.

**Comment by DarkNight8008** [comment]
I think i'm having the same problem it started with just saying packs off line in red writing but then I shut my PC down and restarted it and it gave me this. 
"Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:60)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:60)" please help )-:........

**Comment by CannibalVox** [comment]
This should be fixed in beta 369 - please post a new crash report if not.
