### ISSUE TITLE
Problem downloading a modpack

### ISSUE THREAD

**Issue by Tomefan** [TechnicPack/TechnicLauncher#357]
I was having trouble downloading the minecraft moonquest modpack. I deleted it from the modpacks folder, and i have this error report
http://pastebin.com/uqcXzeTK

**Comment by CannibalVox** [comment]
First: Update your java!  You're going to collect so many viruses with a version that old!
Second: In the future, use the red delete button under the pack logo to remove modpacks.
Third:  Thank you for this information, this will help me track down this bug!

**Comment by Tomefan** [comment]
Thanks for the quick response, i'm not quite sure what I did but i managed to get it to work. and I will take your advice and update my java. Thanks for the advice!
