### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ajaxjoey** [TechnicPack/TechnicLauncher#358]
Stack Trace:
    Exception: NoSuchFieldError
    Message: newReadCipher
    Trace:
        sun.security.ssl.SSLSocketImpl.getEnabledCipherSuites(Unknown Source)
        javax.net.ssl.SSLSocket.getSSLParameters(Unknown Source)
        sun.security.ssl.SSLSocketImpl.getSSLParameters(Unknown Source)
        sun.security.ssl.SSLAlgorithmConstraints.<init>(Unknown Source)
        sun.security.ssl.Handshaker.init(Unknown Source)
        sun.security.ssl.Handshaker.<init>(Unknown Source)
        sun.security.ssl.ClientHandshaker.<init>(Unknown Source)
        sun.security.ssl.SSLSocketImpl.initHandshaker(Unknown Source)
        sun.security.ssl.SSLSocketImpl.doneConnect(Unknown Source)
        sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
        sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
        sun.net.NetworkClient.doConnect(Unknown Source)
        sun.net.www.http.HttpClient.openServer(Unknown Source)
        sun.net.www.http.HttpClient.openServer(Unknown Source)
        sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
        sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
        sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
        sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        sun.net.www.protocol.http.HttpURLConnection.getHeaderField(Unknown Source)
        sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderField(Unknown Source)
        net.technicpack.launchercore.util.DownloadUtils.getETag(DownloadUtils.java:50)
        net.technicpack.launchercore.install.ModpackInstaller.installLibrary(ModpackInstaller.java:211)
        net.technicpack.launchercore.install.ModpackInstaller.installVersionLibs(ModpackInstaller.java:200)
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:82)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:60)

**Comment by CannibalVox** [comment]
This is not the entire crash report.  Please post the whole thing.

**Comment by CannibalVox** [comment]
Please re-open if you return.
