### ISSUE TITLE
Minor login annoyance

### ISSUE THREAD

**Issue by abalabahaha** [TechnicPack/TechnicLauncher#361]
When starting up the Technic Launcher, even if remember this account is checked, the password won't save, and you have to retype it every time you start the launcher.

**Comment by CannibalVox** [comment]
This is not something I've experienced.  I suppose the yggdrasil verify could be having trouble, but have you copied your technic folder around anywhere?

**Comment by abalabahaha** [comment]
Umm, what do you mean copied around anywhere? it's happening on my desktop
and laptop. I'll try backing up and installing fresh.

**Comment by CannibalVox** [comment]
As in, it should work fine on your desktop & laptop provided that they have unique client ID's, but if you copied your technic folder from one to the other, you're gonna have a bad time.

**Comment by abalabahaha** [comment]
No. Seperate installs, I still have to retype my password, but not my
Minecraft username, every time i start the launcher up

**Comment by abalabahaha** [comment]
Ok. apparently, if you login to the Technic Launcher, then quit, then open it, it automatically logs you in. If you login to Technic, then Minecraft/FTB/watevr on the same computer, it requires your password. If you login to Technic, then Technic/Minecraft/FTB/watevr on another computer, it needs your password.

**Comment by CannibalVox** [comment]
That's weird, we did some initial testing and that wasn't generally the case.  Do the other launchers react the same way?

**Comment by abalabahaha** [comment]
Minecraft does not react the same way. FTB I will test. It's fine if it
can't be fixed, just a minor annoyance of more key presses.

**Comment by CannibalVox** [comment]
Don't bother with FTB- they're not on the new auth system yet, so who knows what happens when you log in with them.  I will do some testing and try and fix this.

**Comment by CannibalVox** [comment]
After sifting through the mojang auth code, it appears that the validate verb on the auth server is not supposed to be used for authentication purposes, but rather for future servers to check wither an access token should be let onto the server.  So it only responds successfully for a user's most recent auth token.  We'll remove the use of that verb and transition to instead using the refresh verb for auth purposes.

**Comment by CannibalVox** [comment]
This should be fixed in beta 368.

**Comment by abalabahaha** [comment]
Thank you. Issue is now non-reproducible.

**Comment by abalabahaha** [comment]
Never mind that. Back

**Comment by CannibalVox** [comment]
Is it precisely how it was?  Sorry to have to ask, but are you still on the beta stream? :-P

**Comment by abalabahaha** [comment]
Beta 368, happening in ftb and technic

**Comment by CannibalVox** [comment]
You mean that you log into technic, close technic, log into ftb, close ftb, and the open technic and it prompts you for a password?

**Comment by abalabahaha** [comment]
Yes. same thing happens in reverse. might just be an unfixable bug

**Comment by CannibalVox** [comment]
You mean logging into technic unlogged you from FTB?

**Comment by abalabahaha** [comment]
Yes

**Comment by CannibalVox** [comment]
WAIIIIIT I just remember I told you not to mess with FTB.  Like I said, FTB doesn't use the new system, who knows what'll happen when you log into FTB.  What about Technic & the vanilla launcher and Technic & Technic on another computer?

**Comment by abalabahaha** [comment]
For at least one of those, yes. i forgot. will retest

**Comment by abalabahaha** [comment]
Wait this also causes Bad Login when joining servers. Same thing right?

**Comment by CannibalVox** [comment]
Only the most recently logged-in client for a particular user should be able to play online.  If the most recent login can't play, then that may be another legacy session server failure on mojang's part- the server's been jacking up in periods of high traffic lately.

**Comment by abalabahaha** [comment]
Hmmmmmm it's not coming back. Probably was unlucky when logging ins. Thanks for the help

**Comment by CannibalVox** [comment]
Just FYI a couple days ago slowpoke announced that they'd have a 1.6-compatible launcher out soon,  so you should be able to log into FTB properly soon.

**Comment by vanitasvitae** [comment]
This happens to me very frequently. The folder is in a stable location and I did not tinker with it in any way. Still the launcher asks me for password and username quite often.
I'm on latest Arch Linux with openjdk version "1.8.0_144"
This is the log output:
```
[B#353] Expected MD5: 94a9d4cbcb9ceaa25000fa303fa81acc Calculated MD5: 94a9d4cbcb9ceaa25000fa303fa81acc
[B#353] Expected MD5: b62087eb4b11746987c800c0512890ef Calculated MD5: b62087eb4b11746987c800c0512890ef
[B#353] Expected MD5: EBF34784444ABCB976F77C9E23692057 Calculated MD5: ebf34784444abcb976f77c9e23692057
[B#353] OS: linux
[B#353] Identified as linux
[B#353] Starting download of http://www.gravatar.com/avatar/4c9b9cd817e62d043070a821551c04f0?s=60&d=retro, with 3 tries remaining
[B#353] Starting download of http://www.gravatar.com/avatar/07b1950664b5569324a88727516e761d?s=60&d=retro, with 3 tries remaining
[B#353] Starting download of http://www.gravatar.com/avatar/417979e451a4ed37c22f5340a9c3cd4a?s=60&d=retro, with 3 tries remaining
[B#353] Analytics Response [runLauncher]: 200
[B#353] Starting download of http://crafatar.com/avatars/12089091bc784c74aa7daa3ff191e440?size=100&helm, with 3 tries remaining
[B#353] Starting download of http://cdn.technicpack.net/platform2/pack-logos/1060474.png?1503079916, with 3 tries remaining
[B#353] Starting download of http://www.gravatar.com/avatar/ac3c93c9e57b466e9ffbbb6eac184250?s=60&d=retro, with 3 tries remaining
[B#353] Starting download of http://www.gravatar.com/avatar/ac3c93c9e57b466e9ffbbb6eac184250?s=60&d=retro, with 3 tries remaining
[B#353] Starting download of http://cdn.technicpack.net/platform2/pack-backgrounds/1060474.jpg?1503079916, with 3 tries remaining
[B#353] Starting download of http://cdn.technicpack.net/platform2/pack-icons/1060474.png?1503079916, with 3 tries remaining
```
