### ISSUE TITLE
Not Able to Download New Mod Packs (Error Code)

### ISSUE THREAD

**Issue by futuregatorkid01** [TechnicPack/TechnicLauncher#362]
1.Technic Launcher Error Report:

2.( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
1.    Launcher Build: 365
3.    Selected Pack: null

6.Stack Trace:
1.    Exception: InternalError
2.    Message: Could not initialize shell library
3.    Trace:
4. ```
      sun.awt.shell.Win32ShellFolder2.initIDs(Native Method)
   ```
5. ```
      sun.awt.shell.Win32ShellFolder2.<clinit>(Unknown Source)
   ```
6. ```
      sun.awt.shell.Win32ShellFolderManager2.getStandardViewButton(Unknown Source)
   ```
7. ```
      sun.awt.shell.Win32ShellFolderManager2.get(Unknown Source)
   ```
8. ```
      sun.awt.shell.ShellFolder.get(Unknown Source)
   ```
9. ```
      com.sun.java.swing.plaf.windows.WindowsLookAndFeel$LazyWindowsIcon.createValue(Unknown Source)
   ```
10. ```
       javax.swing.UIDefaults.getFromHashtable(Unknown Source)
    ```
11. ```
       javax.swing.UIDefaults.get(Unknown Source)
    ```
12. ```
       javax.swing.MultiUIDefaults.get(Unknown Source)
    ```
13. ```
       javax.swing.UIDefaults.getIcon(Unknown Source)
    ```
14. ```
       javax.swing.UIManager.getIcon(Unknown Source)
    ```
15. ```
       javax.swing.plaf.basic.BasicFileChooserUI.installIcons(Unknown Source)
    ```
16. ```
       javax.swing.plaf.basic.BasicFileChooserUI.installDefaults(Unknown Source)
    ```
17. ```
       javax.swing.plaf.basic.BasicFileChooserUI.installUI(Unknown Source)
    ```
18. ```
       com.sun.java.swing.plaf.windows.WindowsFileChooserUI.installUI(Unknown Source)
    ```
19. ```
       javax.swing.JComponent.setUI(Unknown Source)
    ```
20. ```
       javax.swing.JFileChooser.updateUI(Unknown Source)
    ```
21. ```
       javax.swing.JFileChooser.setup(Unknown Source)
    ```
22. ```
       javax.swing.JFileChooser.<init>(Unknown Source)
    ```
23. ```
       javax.swing.JFileChooser.<init>(Unknown Source)
    ```
24. ```
       org.spoutcraft.launcher.skin.options.ImportOptions.initComponents(ImportOptions.java:149)
    ```
25. ```
       org.spoutcraft.launcher.skin.options.ImportOptions.<init>(ImportOptions.java:99)
    ```
26. ```
       org.spoutcraft.launcher.skin.ModpackSelector.action(ModpackSelector.java:225)
    ```
27. ```
       org.spoutcraft.launcher.skin.ModpackSelector.actionPerformed(ModpackSelector.java:215)
    ```
28. ```
       javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    ```
29. ```
       javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    ```
30. ```
       javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    ```
31. ```
       javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    ```
32. ```
       javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
    ```
33. ```
       java.awt.Component.processMouseEvent(Unknown Source)
    ```
34. ```
       javax.swing.JComponent.processMouseEvent(Unknown Source)
    ```
35. ```
       java.awt.Component.processEvent(Unknown Source)
    ```
36. ```
       java.awt.Container.processEvent(Unknown Source)
    ```
37. ```
       java.awt.Component.dispatchEventImpl(Unknown Source)
    ```
38. ```
       java.awt.Container.dispatchEventImpl(Unknown Source)
    ```
39. ```
       java.awt.Component.dispatchEvent(Unknown Source)
    ```
40. ```
       java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    ```
41. ```
       java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    ```
42. ```
       java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    ```
43. ```
       java.awt.Container.dispatchEventImpl(Unknown Source)
    ```
44. ```
       java.awt.Window.dispatchEventImpl(Unknown Source)
    ```
45. ```
       java.awt.Component.dispatchEvent(Unknown Source)
    ```
46. ```
       java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    ```
47. ```
       java.awt.EventQueue.access$200(Unknown Source)
    ```
48. ```
       java.awt.EventQueue$3.run(Unknown Source)
    ```
49. ```
       java.awt.EventQueue$3.run(Unknown Source)
    ```
50. ```
       java.security.AccessController.doPrivileged(Native Method)
    ```
51. ```
       java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    ```
52. ```
       java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    ```
53. ```
       java.awt.EventQueue$4.run(Unknown Source)
    ```
54. ```
       java.awt.EventQueue$4.run(Unknown Source)
    ```
55. ```
       java.security.AccessController.doPrivileged(Native Method)
    ```
56. ```
       java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    ```
57. ```
       java.awt.EventQueue.dispatchEvent(Unknown Source)
    ```
58. ```
       java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    ```
59. ```
       java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    ```
60. ```
       java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    ```
61. ```
       java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    ```
62. ```
       java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    ```
63. ```
       java.awt.EventDispatchThread.run(Unknown Source)
    ```

71.System Information:
1.    Operating System: Windows 7
2.    Operating System Version: 6.1
3.    Operating System Architecture: x86
4.    Java version: 1.7.0_45 32 bit
5.    Total Memory: 57 MB
6.    Max Memory: 247 MB
7.    Memory Free: 30 MB
8.    CPU Cores: 2

**Comment by CannibalVox** [comment]
This error occurs when one on of a handful of windows DLLs on your system is either not available or missing key exports.  This is not an issue with technic, unfortunately.  It is either a corrupted java install or a corrupted windows install.  I would strongly recommend engaging anti-virus software.
