### ISSUE TITLE
Crash on opening

### ISSUE THREAD

**Issue by Toestik** [TechnicPack/TechnicLauncher#363]
When I open TechnicLauncher, it shortly shows up and crashes with this report:

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.restful.RestObject.getRestObject(RestObject.java:60)
        net.technicpack.launchercore.restful.solder.SolderPackInfo.getSolderPackInfo(SolderPackInfo.java:148)
        org.spoutcraft.launcher.Launcher$4.run(Launcher.java:148)

**Comment by Toestik** [comment]
Sorry, heres the full log(i think :3)
http://pastebin.com/hB21Hikc

**Comment by Toestik** [comment]
Solved it, lost all my packs, but soved it:3

**Comment by CannibalVox** [comment]
I'm reopening this- the core problem was a brief Platform outage, but getRestObject() should never crash with a NullPointerException, even in case of outage.  So I will address that in this task.

**Comment by CannibalVox** [comment]
Fixed in beta 366.
