### ISSUE TITLE
Hexxit launching problem! :(

### ISSUE THREAD

**Issue by xJoey** [TechnicPack/TechnicLauncher#364]
# When im launching hexxit, this what it says:

1.Technic Launcher Error Report:

2.( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
1.    Launcher Build: 0

4.----------------------------------------------------------------------

5.Stack Trace:
1.    Exception: IOException
2.    Message: Failed to download Minecraft! Pack: hexxit Minecraft version: 1.5.2
3.    Trace:
4. ```
      org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
   ```
5. ```
      org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:319)
   ```
6. ```
      org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:123)
   ```
7. ```
      org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:108)
   ```

13.----------------------------------------------------------------------

14.System Information:
1.    Operating System: Windows 7
2.    Operating System Version: 6.1
3.    Operating System Architecture: amd64
4.    Java version: 1.7.0_45 64 bit
5.    Total Memory: 131 MB
6.    Max Memory: 910 MB
7.    Memory Free: 92 MB
8.    CPU Cores: 2
# 

Please help me with this problem!

**Comment by CannibalVox** [comment]
Er, you're running.. build 0 of the launcher?

**Comment by vavraCZe** [comment]
"Er, you're running.. build 0 of the launcher?" 

It´s warez :D https://dl.dropboxusercontent.com/u/8167722/heh.png 

He is stupid :D

**Comment by CannibalVox** [comment]
Oh what the hell.  Thanks vavracze.
