### ISSUE TITLE
Custom pack won't launch

### ISSUE THREAD

**Issue by IminhaK** [TechnicPack/TechnicLauncher#369]
Hi, i don't have much to say except that my pack won't run. It installs everything, the window disappears then reappears after like .05 of a second and nothing happens. Platform Url: http://www.technicpack.net/api/modpack/treecrafty

**Comment by CannibalVox** [comment]
Go to the cogwheel menu in the upper right and click "show console".  Your pack is crashing because of an error in the way you've set it up.  You can see the error message in the console, or in the forge log (ForgeModLoader-Client-0 in your pack's folder).

**Comment by IminhaK** [comment]
It says something about an invalid signature and i don't know that that means
here is the console from "Running" to the end of the error:
Running /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java -Xdock:name=Treecrafty -Xmx1024m -XX:MaxPermSize=128m -Djava.library.path=/Users/bloop428/Library/Application Support/technic/modpacks/treecrafty/bin/natives -Dfml.core.libraries.mirror=http://mirror.technicpack.net/Technic/lib/fml/%s -Dminecraft.applet.TargetDirectory=/Users/bloop428/Library/Application Support/technic/modpacks/treecrafty -cp /Users/bloop428/Library/Application Support/technic/cache/net/minecraft/launchwrapper/1.8/launchwrapper-1.8.jar:/Users/bloop428/Library/Application Support/technic/cache/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar:/Users/bloop428/Library/Application Support/technic/cache/org/scala-lang/scala-library/2.10.2/scala-library-2.10.2.jar:/Users/bloop428/Library/Application Support/technic/cache/org/scala-lang/scala-compiler/2.10.2/scala-compiler-2.10.2.jar:/Users/bloop428/Library/Application Support/technic/cache/lzma/lzma/0.0.1/lzma-0.0.1.jar:/Users/bloop428/Library/Application Support/technic/cache/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar:/Users/bloop428/Library/Application Support/technic/cache/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/Users/bloop428/Library/Application Support/technic/cache/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/Users/bloop428/Library/Application Support/technic/cache/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/Users/bloop428/Library/Application Support/technic/cache/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:/Users/bloop428/Library/Application Support/technic/cache/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/Users/bloop428/Library/Application Support/technic/cache/argo/argo/2.25_fixed/argo-2.25_fixed.jar:/Users/bloop428/Library/Application Support/technic/cache/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar:/Users/bloop428/Library/Application Support/technic/cache/com/google/guava/guava/14.0/guava-14.0.jar:/Users/bloop428/Library/Application Support/technic/cache/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar:/Users/bloop428/Library/Application Support/technic/cache/commons-io/commons-io/2.4/commons-io-2.4.jar:/Users/bloop428/Library/Application Support/technic/cache/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/Users/bloop428/Library/Application Support/technic/cache/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/Users/bloop428/Library/Application Support/technic/cache/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar:/Users/bloop428/Library/Application Support/technic/cache/org/lwjgl/lwjgl/lwjgl/2.9.0/lwjgl-2.9.0.jar:/Users/bloop428/Library/Application Support/technic/cache/org/lwjgl/lwjgl/lwjgl_util/2.9.0/lwjgl_util-2.9.0.jar:/Users/bloop428/Library/Application Support/technic/modpacks/treecrafty/bin/modpack.jar:/Users/bloop428/Library/Application Support/technic/modpacks/treecrafty/bin/minecraft.jar net.minecraft.launchwrapper.Launch --username bloop428 --session token:5e0c61661dd5428d8142c0ec57c9b8a4:c2f808094327475b82bfe92eb3d5d434 --version 1.6.4-Forge9.11.1.953 --gameDir /Users/bloop428/Library/Application Support/technic/modpacks/treecrafty --assetsDir /Users/bloop428/Library/Application Support/technic/assets --tweakClass cpw.mods.fml.common.launcher.FMLTweaker --title Treecrafty --icon /Users/bloop428/Library/Application Support/technic/assets/packs/treecrafty/icon.png
Analytics Response [runModpack]: 200
 Dec 8, 2013 4:55:38 PM net.minecraft.launchwrapper.LogWrapper log
 INFO: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
 Dec 8, 2013 4:55:38 PM net.minecraft.launchwrapper.LogWrapper log
 SEVERE: Unable to launch
 java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
    at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:219)
    at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:174)
    at java.util.jar.JarVerifier.processEntry(JarVerifier.java:288)
    at java.util.jar.JarVerifier.update(JarVerifier.java:199)
    at java.util.jar.JarFile.initializeVerifier(JarFile.java:327)
    at java.util.jar.JarFile.getInputStream(JarFile.java:395)
    at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:708)
    at sun.misc.Resource.cachedInputStream(Resource.java:61)
    at sun.misc.Resource.getByteBuffer(Resource.java:144)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:256)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:102)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

**Comment by CannibalVox** [comment]
This is not the place to seek help with composing your modpacks- take it to the forums.
