### ISSUE TITLE
help with launcher, i got this after it said "download failed"

### ISSUE THREAD

**Issue by ilpws422** [TechnicPack/TechnicLauncher#373]
Selected Pack: Voltz
Stack Trace:
    Exception: RuntimeException
    Message: Library net.sf.jopt-simple:jopt-simple:4.5 not found.
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:153)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

**Comment by CannibalVox** [comment]
Fixed in Stable 373.
