### ISSUE TITLE
Error occurs when I tried to download my friend's mod pack. 

### ISSUE THREAD

**Issue by jerichoi224** [TechnicPack/TechnicLauncher#377]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 373

```
Selected Pack: SirTwinkles 11/13
```

Stack Trace:
    Exception: RuntimeException
    Message: Library net.minecraft:launchwrapper:1.8 not found.
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:153)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_45 64 bit
    Total Memory: 211 MB
    Max Memory: 1760 MB
    Memory Free: 72 MB
    CPU Cores: 8

**Comment by CannibalVox** [comment]
Fixed in Stable 373.
