### ISSUE TITLE
hexxit installation error.

### ISSUE THREAD

**Issue by Whywould** [TechnicPack/TechnicLauncher#378]
Selected Pack: Hexxit
Stack Trace:
    Exception: RuntimeException
    Message: Library net.sf.jopt-simple:jopt-simple:4.5 not found.
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:153)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_45 64 bit
    Total Memory: 125 MB
    Max Memory: 1817 MB
    Memory Free: 78 MB
    CPU Cores: 4

Does anyone know what to do?

**Comment by dzeni** [comment]
As I see then pretty much everyone has the same problem now. Looks like we just have to wait.

**Comment by CannibalVox** [comment]
Fixed in Stable 373.
