### ISSUE TITLE
Technic Launcher Error Hexxit

### ISSUE THREAD

**Issue by Almori** [TechnicPack/TechnicLauncher#379]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 373

```
Selected Pack: Hexxit
```

Stack Trace:
    Exception: RuntimeException
    Message: Library net.sf.jopt-simple:jopt-simple:4.5 not found.
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:153)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.9
    Operating System Architecture: x86_64
    Java version: 1.6.0_65 64 bit
    Total Memory: 81 MB
    Max Memory: 123 MB
    Memory Free: 53 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Fixed in Stable 373.
