### ISSUE TITLE
Installing tekkit help

### ISSUE THREAD

**Issue by jerm1812** [TechnicPack/TechnicLauncher#380]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 373

```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: RuntimeException
    Message: Library net.sf.jopt-simple:jopt-simple:4.5 not found.
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:153)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_45 64 bit
    Total Memory: 206 MB
    Max Memory: 1637 MB
    Memory Free: 134 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Fixed in Stable 373.
