### ISSUE TITLE
Cant launch Tekkit classic

### ISSUE THREAD

**Issue by jacob1801** [TechnicPack/TechnicLauncher#382]
![udklip](https://f.cloud.github.com/assets/6144242/1706271/d0c678ae-60ec-11e3-8ac9-99b71baea90e.PNG)

**Comment by CannibalVox** [comment]
Fixed in Stable 373.

**Comment by jacob1801** [comment]
So where do i download 373? there is only 374 on their webside and i have google'd some time now after 373
And thx for the answer

**Comment by CannibalVox** [comment]
Sorry I meant 374- restarting your launcher should fix it.

**Comment by jacob1801** [comment]
Yes it didt work 2-3 hours ago you just fixed it now? 
And thank you so much for the quick help :)

**Comment by CannibalVox** [comment]
I did fix it just a little while ago, yeah.  No problem, have fun!
