### ISSUE TITLE
Can't launch any modpack

### ISSUE THREAD

**Issue by ViridianFan** [TechnicPack/TechnicLauncher#383]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 373

```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: RuntimeException
    Message: Library net.sf.jopt-simple:jopt-simple:4.5 not found.
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:153)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_10 32 bit
    Total Memory: 59 MB
    Max Memory: 247 MB
    Memory Free: 22 MB
    CPU Cores: 2
## 

Please help :)

**Comment by CannibalVox** [comment]
Fixed in Stable 373.
