### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by gruflz** [TechnicPack/TechnicLauncher#392]
echnic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 374

```
Selected Pack: null
```

Stack Trace:
    Exception: NoSuchMethodError
    Message: skipInputBytes
    Trace:
        com.sun.imageio.plugins.jpeg.JPEGImageReader.initReaderIDs(Native Method)
        com.sun.imageio.plugins.jpeg.JPEGImageReader.<clinit>(Unknown Source)
        com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi.createReaderInstance(Unknown Source)
        javax.imageio.spi.ImageReaderSpi.createReaderInstance(Unknown Source)
        javax.imageio.ImageIO$ImageReaderIterator.next(Unknown Source)
        javax.imageio.ImageIO$ImageReaderIterator.next(Unknown Source)
        javax.imageio.ImageIO.read(Unknown Source)
        javax.imageio.ImageIO.read(Unknown Source)
        net.technicpack.launchercore.util.ResourceUtils.getIcon(ResourceUtils.java:80)
        org.spoutcraft.launcher.skin.components.BackgroundImage.<init>(BackgroundImage.java:49)
        org.spoutcraft.launcher.skin.LauncherFrame.<init>(LauncherFrame.java:105)
        org.spoutcraft.launcher.Launcher.<init>(Launcher.java:86)
        org.spoutcraft.launcher.entrypoint.SpoutcraftLauncher.main(SpoutcraftLauncher.java:90)
        org.spoutcraft.launcher.entrypoint.Start.launch(Start.java:136)
        org.spoutcraft.launcher.entrypoint.Start.main(Start.java:41)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: x86
    Java version: 1.7.0_17 32 bit
    Total Memory: 15 MB
    Max Memory: 247 MB
    Memory Free: 6 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Hello, this issue can be fixed by updating your java to the latest: 1.7.0_45.  Thanks!
