### ISSUE TITLE
TechnicLauncher Not working

### ISSUE THREAD

**Issue by codeviper828** [TechnicPack/TechnicLauncher#394]
Technic Launcher Error Report:

```
Launcher Build: 377

Selected Pack: Automaticraft
```

Stack Trace:
    Exception: RuntimeException
    Message: Library org.ow2.asm:asm-all:4.1 not found.
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:153)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

System Information:
    Operating System: Windows XP
    Operating System Version: 5.1
    Operating System Architecture: x86
    Java version: 1.7.0_45 32 bit
    Total Memory: 54 MB
    Max Memory: 247 MB
    Memory Free: 17 MB
    CPU Cores: 2

**Comment by nipstoyou** [comment]
mine wont work either

**Comment by CannibalVox** [comment]
This is fixed in the current beta.
