### ISSUE TITLE
[Bug] Technic Launcher Problems

### ISSUE THREAD

**Issue by artdude543** [TechnicPack/TechnicLauncher#397]
I have found two problems lately which are proving to be a pain when getting people to install my mod-pack. As it needs to not run from inside "appdata"so my pack is told to ask users where to install the pack, of which most select their "Documents" folder but the launcher is ignoring this fact. One way to fix this is to select the cog for the pack and change it there, but this only works for one session. It seems to either forget to save the changes or keep creating the settings upon each launcher launch.

As soon as you re-launcher the launcher it defaults back to ".technic/modpack/%modpack%" which is wrong as this is not what we have set our pack direcorys.

Another bug is changing the install for Technic (On Fresh Installs) the launcher is not download/coping over the assets from Minecraft, so you end up having to do this manually from ".minecraft" I have temp fixed this by forcing the launcher to use a directory.

**Comment by CannibalVox** [comment]
Thank you for reporting these issues- I know I've been slacking on these, but these are actually dupes of #388 and #384 respectively.  I'll get to work on them!
