### ISSUE TITLE
Technic Crashes when I click "Add New Modpack"

### ISSUE THREAD

**Issue by Deeklz** [TechnicPack/TechnicLauncher#398]
http://pastebin.com/6ba1FXH3

I really need this to be fixed, as it is now the only way I can get on one of my absolute top priority servers. It hasn't worked before, and I tried redownloading.

**Comment by CannibalVox** [comment]
Hi, you are on an incredibly old version of java.  The latest is 1.7.0_45, and I recommend you update to that..  If for some reason you must remain on java 1.6, the latest version of java 1.6 is 1.6.0_45.
