### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by angeltera01** [TechnicPack/TechnicLauncher#404]
We recently converted the server to Hexxit and i had some trouble logging in which CannibalVox helped me get sorted :) . However as we've been exploring and enjoying the adventure of Hexxit we have run into a few problems. Hawken Scythe is spamming our console with severe errors, so we have taken away member use of the blocks and tried to disable it with our host severs help but no dice. Luckily it only crashes server like once a week at the max so its ok. We haven't been able to find a disguise plugin that works, as we wanted to use it for filming but are trying out the scepters that control mobs for now. We have had to remove wireless redstone as it was not only spamming console with severe errors but has also is causing huge streams of lags, crashing server. Any help?

**Comment by CannibalVox** [comment]
A few things: Hawken Scythe's spamming is annoying but usually benign.  Unfortunately it tries to create souls based on any entity that dies, and sometimes entities are used for things other than mobs, it's very silly.

To use plugins, you'll want to install MCPC+.  It allows plugins to be used alongside forge mods, which is nice. However, it's for advanced users and we don't support it.  THe MCPC+ forums probably have a lot of assistance for people who are trying to use plugins with Hexxit, though, so I'd check them out.

I can't really provide support for mods we didn't add ourselves.  You could try reaching out to the wireless redstone community for help, I have no idea what could be causing your issues, though.
