### ISSUE TITLE
Tekkit Classic will not launch Unexpected Error (pleazzz help)

### ISSUE THREAD

**Issue by XWinterWolf** [TechnicPack/TechnicLauncher#405]
pleazzz someone help me all my other modpack work anything would be a help thanks

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 377

```
Selected Pack: Tekkit Classic
```

Stack Trace:
    Exception: StringIndexOutOfBoundsException
    Message: String index out of range: -1
    Trace:
        java.lang.String.substring(Unknown Source)
        net.technicpack.launchercore.install.InstalledPack.setPackDirectory(InstalledPack.java:200)
        net.technicpack.launchercore.install.InstalledPack.getInstalledDirectory(InstalledPack.java:180)
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:56)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:61)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_45 32 bit
    Total Memory: 54 MB
    Max Memory: 247 MB
    Memory Free: 18 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Fixed in the latest beta.
