### ISSUE TITLE
told to submit this please help

### ISSUE THREAD

**Issue by ghostlygunner43** [TechnicPack/TechnicLauncher#409]
1.
Technic Launcher Error Report:

2.
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )

3.
    Launcher Build: 378

4.

5.
    Selected Pack: Octopia ModPack

6.
Stack Trace:

7.
    Exception: RuntimeException

8.
    Message: Library net.sf.jopt-simple:jopt-simple:4.5 not found.

9.
    Trace:

10.
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:153)

11.
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)

12.
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)

13.
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

14.

15.
System Information:

16.
    Operating System: Windows 7

17.
    Operating System Version: 6.1

18.
    Operating System Architecture: x86

19.
    Java version: 1.7.0_45 32 bit

20.
    Total Memory: 79 MB

21.
    Max Memory: 247 MB

22.
    Memory Free: 38 MB
1.
Technic Launcher Error Report:

2.
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )

3.
    Launcher Build: 378

4.

5.
    Selected Pack: Octopia ModPack

6.
Stack Trace:

7.
    Exception: RuntimeException

8.
    Message: Library net.sf.jopt-simple:jopt-simple:4.5 not found.

9.
    Trace:

10.
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:153)

11.
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)

12.
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)

13.
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

14.

15.
System Information:

16.
    Operating System: Windows 7

17.
    Operating System Version: 6.1

18.
    Operating System Architecture: x86

19.
    Java version: 1.7.0_45 32 bit

20.
    Total Memory: 79 MB

21.
    Max Memory: 247 MB

22.
    Memory Free: 38 MB

**Comment by CannibalVox** [comment]
This is fixed in the latest beta.
