### ISSUE TITLE
cant launch tekkit HELP!

### ISSUE THREAD

**Issue by MarkGL** [TechnicPack/TechnicLauncher#410]
when i want to launch my tekkit it pops up a message saying: unexpected error
Stack Trace:
    Exception: RuntimeException
    Message: Library net.sf.jopt-simple:jopt-simple:4.5 not found.
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:153)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

please help!

**Comment by CannibalVox** [comment]
This is fixed in the latest beta.
