### ISSUE TITLE
Buildcraft with voltz error

### ISSUE THREAD

**Issue by AnotherNeko** [TechnicPack/TechnicLauncher#414]
I put buildcraft in the mods folder, and made sure the vesions were compatible, then it crashed.

Crash report:
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 378

```
Selected Pack: Voltz
```

Stack Trace:
    Exception: RuntimeException
    Message: Minecraft not installed for this pack: InstalledPack{info=SolderPackInfo{name='voltz', display_name='Voltz', url='http://www.technicpack.net/voltz', icon_md5='820ad79798bf8fce3317ad7bb6302384', logo_md5='57bab00b470b738898084b29b541a3e7', background_md5='e9111ee2909af2bc0fa78a50812b1c0a', recommended='2.0.4', latest='2.0.4', builds=[1.0.13, 1.0.12, 1.0.11, 1.0.10, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.1.2, 1.1.3, 1.1.4, 2.0.1, 2.0.2, 2.0.4], solder=net.technicpack.launchercore.restful.solder.Solder@140037d}, name='voltz', platform=false, build='recommended', directory='%MODPACKS%\voltz'}
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:174)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_45 32 bit
    Total Memory: 70 MB
    Max Memory: 247 MB
    Memory Free: 37 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
This is fixed in the latest beta.
