### ISSUE TITLE
Modified version.json support.

### ISSUE THREAD

**Issue by ruifung** [TechnicPack/TechnicLauncher#416]
This is required as when using both liteloader and forge in combination, they both need a --tweakClass parameter passed to the launchWrapper. The problem is, the launcher overwrites the version.json each launch. Is there a way to make.. like a pack.json that can be bundled with the modpack and be used instead of the regular version.json that is downloaded automatically?

Or at least changing the minecraftArguments and mainClass options.

**Comment by CannibalVox** [comment]
If there's a version.json at the root of modpack.jar, it will overwrite version.json with that one.  By default, this tends to be forge's version.json, but you can edit it.

**Comment by ruifung** [comment]
Oh.

**Comment by ruifung** [comment]
You should have better documentation on the workings of the launcher.
