### ISSUE TITLE
tekkit lite not starting up

### ISSUE THREAD

**Issue by apcie** [TechnicPack/TechnicLauncher#420]
when i try to start up my tekkit-lite i get this eror can somone help me?

http://pastebin.com/c8UTdm7j

**Comment by CannibalVox** [comment]
Hey, can you pastebin the contents of %appdata%.technic\assets\indexes\legacy.json

**Comment by apcie** [comment]
i cant open that

**Comment by apcie** [comment]
i cant open that

**Comment by CannibalVox** [comment]
Delete it and try to start tekkit-lite again

**Comment by apcie** [comment]
thanks alot it worked

2014/1/7 Cannibal Vox notifications@github.com

**Comment by CannibalVox** [comment]
This is fixed in the latest beta btw.
