### ISSUE TITLE
Won't work in school

### ISSUE THREAD

**Issue by AvronTheBeastBoy** [TechnicPack/TechnicLauncher#421]
Launcher Build: 0

```
Selected Pack: Hexxit
```

Stack Trace:
    Exception: RuntimeException
    Message: Library net.sf.jopt-simple:jopt-simple:4.5 not found.
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:153)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_21 32 bit
    Total Memory: 64 MB
    Max Memory: 247 MB
    Memory Free: 21 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
This is fixed in the latest beta.
