### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by augustas656** [TechnicPack/TechnicLauncher#422]
When I launch tekkit lite I get the error when loading, I tried resetting the pack, but still the error was just delayed.

```
Selected Pack: Tekkit Lite
```

Stack Trace:
    Exception: JsonSyntaxException
    Message: java.io.EOFException: End of input at line 1218 column 1
    Trace:
        com.google.gson.Gson.fromJson(Gson.java:813)
        com.google.gson.Gson.fromJson(Gson.java:768)
        com.google.gson.Gson.fromJson(Gson.java:717)
        com.google.gson.Gson.fromJson(Gson.java:689)
        net.technicpack.launchercore.install.tasks.GetAssetsIndexTask.runTask(GetAssetsIndexTask.java:53)
        net.technicpack.launchercore.install.tasks.InstallTasksQueue.RunAllTasks(InstallTasksQueue.java:33)
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:103)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:61)
        Caused By: (EOFException)
            [End of input at line 1218 column 1]
            com.google.gson.Gson.fromJson(Gson.java:813)
            com.google.gson.Gson.fromJson(Gson.java:768)
            com.google.gson.Gson.fromJson(Gson.java:717)
            com.google.gson.Gson.fromJson(Gson.java:689)
            net.technicpack.launchercore.install.tasks.GetAssetsIndexTask.runTask(GetAssetsIndexTask.java:53)
            net.technicpack.launchercore.install.tasks.InstallTasksQueue.RunAllTasks(InstallTasksQueue.java:33)
            net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:103)
            org.spoutcraft.launcher.InstallThread.run(InstallThread.java:61)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_45 64 bit
    Total Memory: 123 MB
    Max Memory: 1820 MB
    Memory Free: 60 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
Hey, can you delete all the files in %appdata%.technic\assets\indexes and try to run again?

**Comment by CannibalVox** [comment]
This is fixed in the latest beta.
