### ISSUE TITLE
trouble with opening modpacks with technic launcher

### ISSUE THREAD

**Issue by skywalkar101** [TechnicPack/TechnicLauncher#423]
everytime i try to open a modpack this appears Stack Trace:
    Exception: JsonSyntaxException
    Message: java.io.EOFException: End of input at line 1218 column 1
    Trace:
        com.google.gson.Gson.fromJson(Gson.java:813)
        com.google.gson.Gson.fromJson(Gson.java:768)
        com.google.gson.Gson.fromJson(Gson.java:717)
        com.google.gson.Gson.fromJson(Gson.java:689)
        net.technicpack.launchercore.install.tasks.GetAssetsIndexTask.runTask(GetAssetsIndexTask.java:53)
        net.technicpack.launchercore.install.tasks.InstallTasksQueue.RunAllTasks(InstallTasksQueue.java:33)
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:103)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:61)
        Caused By: (EOFException)
            [End of input at line 1218 column 1]
            com.google.gson.Gson.fromJson(Gson.java:813)
            com.google.gson.Gson.fromJson(Gson.java:768)
            com.google.gson.Gson.fromJson(Gson.java:717)
            com.google.gson.Gson.fromJson(Gson.java:689)
            net.technicpack.launchercore.install.tasks.GetAssetsIndexTask.runTask(GetAssetsIndexTask.java:53)
            net.technicpack.launchercore.install.tasks.InstallTasksQueue.RunAllTasks(InstallTasksQueue.java:33)
            net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:103)
            org.spoutcraft.launcher.InstallThread.run(InstallThread.java:61)

**Comment by CannibalVox** [comment]
This is fixed in the latest beta.
