### ISSUE TITLE
Error when starting custom modpack

### ISSUE THREAD

**Issue by heletrobe** [TechnicPack/TechnicLauncher#425]
OK so i made a custom modpack for a friend and it extracts fine if i goto my modpacks folder i see it and it has all the assets. But when i try to run i get a message 
"Error extracting file from pack: [Packname]; error extracting zip file; please contact a modpack author"

The loading bar says "Retrieving modpack versions"

plz explain?

**Comment by CannibalVox** [comment]
It's pretty self-explanatory.  If you want more information, I need more information- go to the cogwheel in the upper right hand corner, click that, click "show console" and get me the error out of the console when this message occurs.
