### ISSUE TITLE
TechnicLauncher Error Report because(?) bad internet connection

### ISSUE THREAD

**Issue by CasparGAErnst** [TechnicPack/TechnicLauncher#428]
(note: before the Launcher worked fine)

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 383

```
Selected Pack: Hexxit
```

Stack Trace:
    Exception: JsonSyntaxException
    Message: com.google.gson.stream.MalformedJsonException: Unterminated string at line 2417 column 26
    Trace:
        com.google.gson.Gson.fromJson(Gson.java:818)
        com.google.gson.Gson.fromJson(Gson.java:768)
        com.google.gson.Gson.fromJson(Gson.java:717)
        com.google.gson.Gson.fromJson(Gson.java:689)
        net.technicpack.launchercore.install.tasks.GetAssetsIndexTask.runTask(GetAssetsIndexTask.java:53)
        net.technicpack.launchercore.install.tasks.InstallTasksQueue.RunAllTasks(InstallTasksQueue.java:33)
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:103)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:61)
        Caused By: (MalformedJsonException)
            [Unterminated string at line 2417 column 26]
            com.google.gson.Gson.fromJson(Gson.java:818)
            com.google.gson.Gson.fromJson(Gson.java:768)
            com.google.gson.Gson.fromJson(Gson.java:717)
            com.google.gson.Gson.fromJson(Gson.java:689)
            net.technicpack.launchercore.install.tasks.GetAssetsIndexTask.runTask(GetAssetsIndexTask.java:53)
            net.technicpack.launchercore.install.tasks.InstallTasksQueue.RunAllTasks(InstallTasksQueue.java:33)
            net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:103)
            org.spoutcraft.launcher.InstallThread.run(InstallThread.java:61)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_45 64 bit
    Total Memory: 122 MB
    Max Memory: 1810 MB
    Memory Free: 62 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Hey, can you delete all the files in %appdata%.technic\assets\indexes and try to run again?

**Comment by CannibalVox** [comment]
This is fixed in the latest beta.

**Comment by CasparGAErnst** [comment]
Problem solved, 143 Viruses =O
CasparGAErnst

```
    Gesendet: Dienstag, 14. Januar 2014 um 21:36 UhrVon: "Cannibal Vox" <notifications@github.com>An: TechnicPack/TechnicLauncher <TechnicLauncher@noreply.github.com>Cc: CasparGAErnst <ernstcaspar@web.de>Betreff: Re: [TechnicLauncher] TechnicLauncher Error Report because(?) bad internet connection (#428)


    Hey, can you delete all the files in %appdata%.technic\assets\indexes and try to run again?
```
