### ISSUE TITLE
Technic Launcher Error Report

### ISSUE THREAD

**Issue by Kiamusze** [TechnicPack/TechnicLauncher#430]
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 383

```
Selected Pack: Hexxit
```

Stack Trace:
    Exception: StackOverflowError
    Message: null

System Information:
    Operating System: Windows Vista
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.6.0_07 32 bit
    Total Memory: 37 MB
    Max Memory: 63 MB
    Memory Free: 9 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Hi, you have an insanely old version of java on your computer.  I'd recommend updating to 1.7.0_51, the latest version.  Hopefully that will fix this issue.  If it does not, please open a new bug with the new crash data.
