### ISSUE TITLE
Launcher Error Upon Opening

### ISSUE THREAD

**Issue by MeteorNate** [TechnicPack/TechnicLauncher#431]
This is the error given:

Stack Trace:
    Exception: NoSuchMethodError
    Message: sun.security.internal.spec.TlsRsaPremasterSecretParameterSpec.getEncodedSecret()[B
    Trace:
        com.sun.crypto.provider.TlsRsaPremasterSecretGenerator.engineGenerateKey(TlsRsaPremasterSecretGenerator.java:75)
        javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:530)
        sun.security.ssl.RSAClientKeyExchange.<init>(Unknown Source)
        sun.security.ssl.ClientHandshaker.serverHelloDone(Unknown Source)
        sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
        sun.security.ssl.Handshaker.processLoop(Unknown Source)
        sun.security.ssl.Handshaker.process_record(Unknown Source)
        sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
        sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
        sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
        net.technicpack.launchercore.auth.AuthenticationService.postJson(AuthenticationService.java:66)
        net.technicpack.launchercore.auth.AuthenticationService.requestRefresh(AuthenticationService.java:43)
        org.spoutcraft.launcher.skin.LoginFrame.verifyExistingLogin(LoginFrame.java:399)
        org.spoutcraft.launcher.skin.LoginFrame.attemptStartup(LoginFrame.java:83)
        org.spoutcraft.launcher.entrypoint.SpoutcraftLauncher.main(SpoutcraftLauncher.java:95)
        org.spoutcraft.launcher.entrypoint.Start.launch(Start.java:136)
        org.spoutcraft.launcher.entrypoint.Start.main(Start.java:41)

**Comment by CannibalVox** [comment]
Need the whole report.

**Comment by MeteorNate** [comment]
That was all of it, but in fact it was something on my part, an old java uninstalling incorrectly, leaving me with no java, and causing a whole slew of errors I had to work out. Sorry, no error on the technic side.
