### ISSUE TITLE
Technic Launcher Error Report

### ISSUE THREAD

**Issue by minerguy341** [TechnicPack/TechnicLauncher#432]
Launcher Build: 383

```
Selected Pack: MoonQuest (YOGSCAST Inspired)
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.InstalledPack.loadCachedImage(InstalledPack.java:278)
        net.technicpack.launchercore.install.InstalledPack.loadImage(InstalledPack.java:263)
        net.technicpack.launchercore.install.InstalledPack.getLogo(InstalledPack.java:238)
        org.spoutcraft.launcher.skin.components.PackButton.setPack(PackButton.java:72)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:151)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:201)
        org.spoutcraft.launcher.Launcher.refreshPack(Launcher.java:258)
        net.technicpack.launchercore.install.InstalledPack$1.run(InstalledPack.java:314)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_45 64 bit
    Total Memory: 127 MB
    Max Memory: 843 MB
    Memory Free: 84 MB
    CPU Cores: 2

**Comment by ShadrachJ** [comment]
We've all been referenced here but that's kind of useless. All issues shown here have the same Amd64 operating structure. A fix would have to be established for whatever is causing it there.

**Comment by CannibalVox** [comment]
You've been referenced here because it doesn't help anyone to have 8 open issues for the same bug.  Anyway this is fixed in the latest beta.
