### ISSUE TITLE
Launcher error

### ISSUE THREAD

**Issue by Mctitch-CraftSM** [TechnicPack/TechnicLauncher#434]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: SG
```

Stack Trace:
    Exception: IllegalArgumentException
    Message: java.security.NoSuchAlgorithmException: MD5 MessageDigest not available
    Trace:
        org.apache.commons.codec.digest.DigestUtils.getDigest(DigestUtils.java:70)
        org.apache.commons.codec.digest.DigestUtils.getMd5Digest(DigestUtils.java:98)
        org.apache.commons.codec.digest.DigestUtils.md5(DigestUtils.java:274)
        org.apache.commons.codec.digest.DigestUtils.md5Hex(DigestUtils.java:310)
        net.technicpack.launchercore.util.MD5Utils.getMD5(MD5Utils.java:33)
        net.technicpack.launchercore.install.InstalledPack.loadCachedImage(InstalledPack.java:278)
        net.technicpack.launchercore.install.InstalledPack.loadImage(InstalledPack.java:263)
        net.technicpack.launchercore.install.InstalledPack.getBackground(InstalledPack.java:343)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:118)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:201)
        org.spoutcraft.launcher.Launcher$3.run(Launcher.java:124)
        Caused By: (NoSuchAlgorithmException)
            [MD5 MessageDigest not available]
            org.apache.commons.codec.digest.DigestUtils.getDigest(DigestUtils.java:70)
            org.apache.commons.codec.digest.DigestUtils.getMd5Digest(DigestUtils.java:98)
            org.apache.commons.codec.digest.DigestUtils.md5(DigestUtils.java:274)
            org.apache.commons.codec.digest.DigestUtils.md5Hex(DigestUtils.java:310)
            net.technicpack.launchercore.util.MD5Utils.getMD5(MD5Utils.java:33)
            net.technicpack.launchercore.install.InstalledPack.loadCachedImage(InstalledPack.java:278)
            net.technicpack.launchercore.install.InstalledPack.loadImage(InstalledPack.java:263)
            net.technicpack.launchercore.install.InstalledPack.getBackground(InstalledPack.java:343)
            org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:118)
            org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:201)
            org.spoutcraft.launcher.Launcher$3.run(Launcher.java:124)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_51 64 bit
    Total Memory: 113 MB
    Max Memory: 1324 MB
    Memory Free: 51 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Please use the launcher downloaded from www.technicpack.net/ to receive support.
