### ISSUE TITLE
Minecraft Crashes

### ISSUE THREAD

**Issue by burnsey96** [TechnicPack/TechnicLauncher#437]
I got the technic launcher to run but now, when i click play on Hexxit, it loads up and Minecraft crashes. This is the crash report: 

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 19/01/14 20:39
Description: Failed to start game

java.lang.IllegalArgumentException: Duplicate enchantment id!
    at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:111)
    at jds.bibliocraft.EnchantmentReading.<init>(EnchantmentReading.java:12)
    at jds.bibliocraft.items.ItemLoader.initItems(ItemLoader.java:45)
    at jds.bibliocraft.BiblioCraft.load(BiblioCraft.java:85)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:494)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:192)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:172)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:103)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:213)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:448)
    at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
    at net.minecraft.client.Minecraft.run(Minecraft.java:733)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.5.2
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 88920448 bytes (84 MB) / 186281984 bytes (177 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024m -XX:MaxPermSize=128m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.51 FML v5.2.23.737 Minecraft Forge 7.8.1.737 68 mods loaded, 68 mods active
    mcp{7.51} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{5.2.23.737} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{7.8.1.737} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{0.8.7.3} [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized
    CoFHFramework{1.5.2.5} [CoFH Framework](coremods) Unloaded->Constructed->Pre-initialized->Initialized
    ImmibisMicroblocks{55.0.7} [Immibis's Microblocks](coremods) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughItems{1.5.2.28} [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized
    mod_bspkrsCore{v2.09(1.5.2)} [bspkrsCore]([1.5.2]bspkrsCorev2.09.zip) Unloaded->Constructed->Pre-initialized->Initialized
    TreeCapitator{Forge 1.5.2.r14} [TreeCapitator]([1.5.2]TreeCapitator.Forge.1.5.2.r14.Uni.CoreMod.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CoFHCore{1.5.2.5} [CoFHCore](CoFHCore-1.5.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CoFHWorld{1.5.2.5} [CoFHWorld](CoFHCore-1.5.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CustomLAN{2.2} [Custom LAN Mod](CustomPortForge.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ImmibisMicroblocksInstallCheck{55.0.7} [Immibis's Microblocks (Checks for incorrect installation, ignore this)](immibis-microblocks-55.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DamageIndicatorsMod{2.7.0.1} [Damage Indicators](1.5.2 DamageIndicators v2.7.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized
    AsgardShield_Core{2.0.4} [AsgardShield](1.5.2AsgardShield_Core_2.0.4Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ASAddon_Hallowed{2.0.0} [AS Addon- Hallowed](1.5.2ASAddonHallowed_v2.0.0Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized
    HarkenScythe_Core{2.1.6} [HarkenScythe](1.5.2HarkenScythe_v2.1.6Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ASAddon_HarkenScythe{2.0.0} [AS Addon- HarkenScythe](1.5.2ASAddonHarkenScythe_v2.0.0Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ASAddon_NetherEnder{2.0.0} [AS Addon- Nether-Ender](1.5.2ASAddonNetherEnder_v2.0.0Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ASAddon_ColorAPI{1.0.0} [ASAddon_ColorAPI](1.5.2AsgardShield_Core_2.0.4Forge.zip) Unloaded->Constructed->Pre-initialized->Initialized
    BetterStorage{0.6.2.23-hotfix2} [BetterStorage]([1.5.2]BetterStorage_0.6.2.23-hotfix2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    mod_ArmorBarMod{0.7.1} [Armor Bar Mod](ArmorBarv0.7.1.zip) Unloaded->Constructed->Pre-initialized->Initialized
    Artifice{1.5.2R1.1.2} [Artifice](Artifice-1.1.2-182.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ArtificeCompat|Chisel{1.5.2R1.1.2} [Artifice Compat: Chisel](Artifice-1.1.2-182.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ArtificeCompat|EE3{1.5.2R1.1.2} [Artifice Compat: EE3](Artifice-1.1.2-182.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ArtificeCompat|Forestry{1.5.2R1.1.2} [Artifice Compat: Forestry](Artifice-1.1.2-182.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ArtificeCompat|MFR{1.5.2R1.1.2} [Artifice Compat: MFR](Artifice-1.1.2-182.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ArtificeCompat|Railcraft{1.5.2R1.1.2} [Artifice Compat: Railcraft](Artifice-1.1.2-182.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ArtificeCompat|Vanilla{1.5.2R1.1.2} [Artifice Compat: Vanilla](Artifice-1.1.2-182.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Backpack{1.12.13} [Backpack](backpack-1.12.13-1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    mod_BackTools{1.5.2v1} [mod_BackTools](BackTools1.5.2v1.zip) Unloaded->Constructed->Pre-initialized->Initialized
    BattleTowers{1.3.4} [Battle Towers](BattleTowers_1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    BetterDungeons{1.8} [Better dungeons](BetterDungeons.zip) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioCraft{1.3.3} [BiblioCraft](BiblioCraft[v1.3.3].zip) Unloaded->Constructed->Pre-initialized->Errored
    mod_BuffBarMod{0.7.1} [Buff Bar Mod](BuffBarv0.7.1.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ChestTransporter{1.1.6} [Chest Transporter](chestTransporter_1.1.6_Universal.zip) Unloaded->Constructed->Pre-initialized->Initialized
    DimDoors{1.5.2R1.4.1RC1} [Dimensional Doors](DimensionalDoors-1.5.2R1.4.1RC1-194.zip) Unloaded->Constructed->Pre-initialized->Initialized
    eplus{1.15.4} [Enchanting Plus](EnchantingPlus-1.15.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtrabiomesXL{3.13.4} [ExtrabiomesXL](ExtrabiomesXL-universal-1.5.2-3.13.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    hexxitgear{1.5.2R1.0} [Hexxit Gear](HexxitGear-1.0-23.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ImmibisCore{55.1.6} [Immibis Core](immibis-core-55.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    InfernalMobs{1.3.1} [Infernal Mobs](InfernalMobs_1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.54b} [Inventory Tweaks](InventoryTweaks-1.54b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MapWriter{2.0} [MapWriter](mapwriter-2.0.5.zip) Unloaded->Constructed->Pre-initialized->Initialized
    Meteors{2.10.2} [Falling Meteors](Meteors Mod V2.10.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    More Bows{1.5_v1} [More Bows mod](More bows 1.5.2_2 Forge.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Natura{2.1.5} [Natura](Natura_1.5.2_2.1.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Natura|CompatMineFactoryReloaded{0.1} [Natura compat: MFR](Natura_1.5.2_2.1.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIPlugins{1.0.9.3} [NEI Plugins](NEIPlugins-1.0.9.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    LegendGear{1.5.2} [LegendGear](NMcCoy-LegendGear-1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ObsidiPlates{1.5.0} [Obsidian Pressure Plates](obsidiplates-1.5.2-universal-1.5.0.13.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OffLawn{1.0} [offLawn](OffLawn-1.5.1.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ProjectZulu|Core{1.0.3.8} [Project Zulu Core](ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ProjectZulu|Blocks{1.0.3.8} [Project Zulu Block and Items](ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ProjectZulu|Dungeon{1.0.3.8} [Project Zulu Mobs](ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ProjectZulu|Mobs{1.0.3.8} [Project Zulu Mobs](ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ProjectZulu|World{1.0.3.8} [Project Zulu World](ProjectZuluCompletev1.0.3.8.zip) Unloaded->Constructed->Pre-initialized->Initialized
    QuantumCraft{1.01} [qCraft](qCraft1.01.zip) Unloaded->Constructed->Pre-initialized->Initialized
    xreliquary{1.5.2} [Xeno's Reliquary](Reliquary1.0.6d.zip) Unloaded->Constructed->Pre-initialized->Initialized
    rftl{1.0} [RottenFleshToLeather](RottenFleshToLeather-1.5.1.zip) Unloaded->Constructed->Pre-initialized->Initialized
    AS_Ruins{10.3} [Ruins Spawning System](Ruins_1.5.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    secretroomsmod{4.6.0} [SecretRoomsMod](SecretRoomsMod-universal-4.6.0.283.zip) Unloaded->Constructed->Pre-initialized->Initialized
    SoulShards{1.0.16} [Soul Shards](SoulShards-1.0.36-universal-srg.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct{1.5.2_1.4.3d7} [Tinkers' Construct](TConstruct_1.5.2_1.4.3.final.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct|CompatMineFactoryReloaded{0.1} [TConstruct Compat: MFR](TConstruct_1.5.2_1.4.3.final.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TwilightForest{1.18.1} [The Twilight Forest](twilightforest-1.18.1.zip) Unloaded->Constructed->Pre-initialized->Initialized
    WildCaves3{0.4.2} [Wild Caves 3](WildCaves3-0.4.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    chococraft{2.8.8} [Torojima's ChocoCraft](zzzChococraft_2.8.8.zip) Unloaded->Constructed->Pre-initialized->Initialized
    LWJGL: 2.9.0
    OpenGL: GeForce GT 650M/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Texture Pack: Default
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by ruifung** [comment]
Looks like a duplicate enchantment ID. This isn't a launcher issue....

**Comment by CannibalVox** [comment]
It is not.  Two of the mods have a conflicting enchantment ID by default, so it looks like you didn't get the config files right, though.  I'd reset the pack and try again.
