### ISSUE TITLE
Technic Launcher Crashing

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#439]
Technic Launcher Error Report:
    Launcher Build: 383

```
Selected Pack: MoonQuest Modpack
```

Stack Trace:
    Exception: JsonSyntaxException
    Message: java.io.EOFException: End of input at line 1811 column 2
    Trace:
        com.google.gson.Gson.fromJson(Gson.java:813)
        com.google.gson.Gson.fromJson(Gson.java:768)
        com.google.gson.Gson.fromJson(Gson.java:717)
        com.google.gson.Gson.fromJson(Gson.java:689)
        net.technicpack.launchercore.install.tasks.GetAssetsIndexTask.runTask(GetAssetsIndexTask.java:53)
        net.technicpack.launchercore.install.tasks.InstallTasksQueue.RunAllTasks(InstallTasksQueue.java:33)
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:103)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:61)
        Caused By: (EOFException)
            [End of input at line 1811 column 2]
            com.google.gson.Gson.fromJson(Gson.java:813)
            com.google.gson.Gson.fromJson(Gson.java:768)
            com.google.gson.Gson.fromJson(Gson.java:717)
            com.google.gson.Gson.fromJson(Gson.java:689)
            net.technicpack.launchercore.install.tasks.GetAssetsIndexTask.runTask(GetAssetsIndexTask.java:53)
            net.technicpack.launchercore.install.tasks.InstallTasksQueue.RunAllTasks(InstallTasksQueue.java:33)
            net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:103)
            org.spoutcraft.launcher.InstallThread.run(InstallThread.java:61)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_51 32 bit
    Total Memory: 61 MB
    Max Memory: 247 MB
    Memory Free: 33 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Go to %appdata%.technic\assets\indexes and delete all the files in that folder, and try again.

**Comment by ghost** [comment]
Umm there was only one file, called legacy.json i think. Gonna try again now

**Comment by ghost** [comment]
Thank you! :) Works perfectly fine
