### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by stargold12** [TechnicPack/TechnicLauncher#441]
Launcher Build: 383

```
Selected Pack: Mob Talker 2
```

Stack Trace:
    Exception: RuntimeException
    Message: Minecraft not installed for this pack: InstalledPack{info=PlatformPackInfo{name='mob-talker-2', displayName='Mob Talker 2', url='https://dl.dropboxusercontent.com/u/180512869/Game%20Related/Mob%20Talker%201.6.4.zip', icon=null, logo=net.technicpack.launchercore.restful.Resource@11e831, background=net.technicpack.launchercore.restful.Resource@1a2f02e, minecraft='1.6.4', forge='null', version='Final', solder='', forceDir=false}, name='mob-talker-2', platform=true, build='recommended', directory='%MODPACKS%\mob-talker-2'}
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:191)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.6.0_20 32 bit
    Total Memory: 53 MB
    Max Memory: 247 MB
    Memory Free: 29 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
This is fixed in the latest beta.
