### ISSUE TITLE
Stack Trace Error. Won't let me download any modpacks, not even vanilla

### ISSUE THREAD

**Issue by TofuChris** [TechnicPack/TechnicLauncher#443]
Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.tasks.InstallModpackTask.deleteMods(InstallModpackTask.java:57)
        net.technicpack.launchercore.install.tasks.InstallModpackTask.runTask(InstallModpackTask.java:34)
        net.technicpack.launchercore.install.tasks.InstallTasksQueue.RunAllTasks(InstallTasksQueue.java:33)
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:103)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:61)

**Comment by Breadedginger** [comment]
Yeah, umm what do I do when this happens? Do I just wish to the god damn pixies? You guys should sort this total bull-crap...

**Comment by CannibalVox** [comment]
Closing this in favor #447 because it has more info.
