### ISSUE TITLE
Minecraft Guerra 5 - what's happened?

### ISSUE THREAD

**Issue by wksp68** [TechnicPack/TechnicLauncher#444]
Stack Trace:
    Exception: RuntimeException
    Message: Minecraft not installed for this pack: InstalledPack{info=PlatformPackInfo{name='minecraft-guerra-oficial', displayName='Minecraft Guerra (Oficial)', url='https://dl-web.meocloud.pt/dlweb/download/Modpacks/Mine%20Guerra/MineGuerra-5-Release-Client-1.2.6.zip?public=aab73f5a-a2f6-453c-96ab-26bfd938934a', icon=null, logo=net.technicpack.launchercore.restful.Resource@fffd2c, background=net.technicpack.launchercore.restful.Resource@466cd5, minecraft='1.6.4', forge='null', version='1.2.6', solder='', forceDir=false}, name='minecraft-guerra-oficial', platform=true, build='recommended', directory='%MODPACKS%\minecraft-guerra-oficial'}
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:191)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

**Comment by CannibalVox** [comment]
This is fixed in the latest beta.
