### ISSUE TITLE
Launcher Error upon opening

### ISSUE THREAD

**Issue by gluff95** [TechnicPack/TechnicLauncher#445]
As soon as I open the launcher, I get the following crash:
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 15, Size: 15
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        net.technicpack.launchercore.install.AvailablePackList.getOffsetPack(AvailablePackList.java:98)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:160)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:211)
        org.spoutcraft.launcher.skin.ModpackSelector.updatePack(ModpackSelector.java:118)
        net.technicpack.launchercore.install.AvailablePackList.triggerUpdateListeners(AvailablePackList.java:55)
        net.technicpack.launchercore.install.AvailablePackList$2$1.run(AvailablePackList.java:149)
        java.awt.event.InvocationEvent.dispatch(Unknown Source)
        java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        java.awt.EventQueue.access$200(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue.dispatchEvent(Unknown Source)
        java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.run(Unknown Source)

This only occurs when I am using the beta build of the launcher; the stable builds work fine.

**Comment by CannibalVox** [comment]
Closing this in favor of #453  because it has more info.
