### ISSUE TITLE
Hexxit problems

### ISSUE THREAD

**Issue by NoNameCreeper** [TechnicPack/TechnicLauncher#448]
I'm trying to play hexxit with my cousin we have a server and when i try to open it and it says an error has occured under it is                                                                                       Stack Trace:
    Exception: StringIndexOutOfBoundsException
    Message: String index out of range: -1
    Trace:
        java.lang.String.substring(Unknown Source)
        net.technicpack.launchercore.install.InstalledPack.setPackDirectory(InstalledPack.java:200)
        net.technicpack.launchercore.install.InstalledPack.getInstalledDirectory(InstalledPack.java:180)
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:67)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:63)

**Comment by CannibalVox** [comment]
Closing this as a dupe of #405
