### ISSUE TITLE
Attack of the B-Team Version Changing

### ISSUE THREAD

**Issue by rcmaehl** [TechnicPack/TechnicLauncher#454]
http://pastebin.com/t2L02VwQ

Clicked gear under Attack of the B-Team.
Chose Manually select a build.
Don't remember if I clicked the drop down or not, just that the build was blank.

**Comment by CannibalVox** [comment]
There was a lot going on with this bug, but to the extent that it was the launcher's fault, this is a dupe of #393.  Will work it as that task.
