### ISSUE TITLE
A little error

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#455]
1.Technic Launcher Error Report:

2.( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
1.    Launcher Build: 393
3.    Selected Pack: The Mining Dead Server Pack

6.Stack Trace:
1.    Exception: ArrayIndexOutOfBoundsException
2.    Message: 2
3.    Trace:
4. ```
      net.technicpack.launchercore.minecraft.Library.getArtifactBaseDir(Library.java:87)
   ```
5. ```
      net.technicpack.launchercore.minecraft.Library.getArtifactPath(Library.java:79)
   ```
6. ```
      net.technicpack.launchercore.install.tasks.HandleVersionFileTask.runTask(HandleVersionFileTask.java:62)
   ```
7. ```
      net.technicpack.launchercore.install.tasks.InstallTasksQueue.RunAllTasks(InstallTasksQueue.java:33)
   ```
8. ```
      net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:104)
   ```
9. ```
      org.spoutcraft.launcher.InstallThread.run(InstallThread.java:63)
   ```

17.System Information:
1.    Operating System: Windows 8.1
2.    Operating System Version: 6.3
3.    Operating System Architecture: amd64
4.    Java version: 1.8.0-ea 64 bit
5.    Total Memory: 89 MB
6.    Max Memory: 1817 MB
7.    Memory Free: 65 MB

Ill push a fix for this.

**Comment by CannibalVox** [comment]
We don't support experimental java releases.
