### ISSUE TITLE
Technic Launcher Crashed as Soon as I Opened It.

### ISSUE THREAD

**Issue by davima5950** [TechnicPack/TechnicLauncher#457]
A pastebin like to the error report : http://pastebin.com/zGEEhy7A

Really i just double clicked the technic launcher.exe and that showed up.
So i dont really know what i did wrong.

**Comment by Planther** [comment]
Same here: http://pastebin.com/wyXCXMsg

**Comment by chan200** [comment]
Same here too don't know what is happening http://pastebin.com/M3ZEmw4Z

**Comment by raburden** [comment]
Same problem. Error Report here. http://pastebin.com/kV9sFjPW

Think that when this happened to me before, re-downloading the launcher solved the problem, admittedly at the potential for lost data.

**Comment by CannibalVox** [comment]
These 4 error reports are all completely different, but they're all also dupes of other open issues, so I'm closing this.
