### ISSUE TITLE
Major Glitch/Bug with Ultra Modded Survival

### ISSUE THREAD

**Issue by PristineOasis** [TechnicPack/TechnicLauncher#469]
I have a major problem. While playing Ultra Modded Survival (with all of CaptainSparklez mods) I keep encountering this glitch/bug. I appear to be on the inside of various mobs (most often Creepers and Zombies) that block my vision. Sometimes, but not always, I can look away from that specific spot and it will go away, but as soon as I look back it is still there. This glitch/bug also makes items look as though they have disappeared (mainly noted with chests and water though I was not able to screenshot these occurrences). This happens all the time and sometimes gets so bad that I just stop playing for a while but that hasn't seemed to help either. This happens when I am morphed and when I am not morphed; even if I start the game not morphed it will happen whether I have changed into anything yet or not. It seems like it happens in darker areas more, but that could be attributed to the fact that I spend more of my time playing in dark areas. I don't think that this has anything to do with NEI and magnet mode because it happens with and without them. My personal theory is that it has something to do with the Dismemberment Mod; but to be clear, this does not only happen when I kill things or when I have recently killed something. If you have any theories or can possibly help please contact me here or at FPSradioactive@gmail.com

![2014-02-05_22 17 58](https://f.cloud.github.com/assets/6599863/2095522/854a46a6-8ee8-11e3-8be4-419f89b4f92d.png)
![2014-02-05_22 18 08](https://f.cloud.github.com/assets/6599863/2095523/8837e760-8ee8-11e3-814e-149d791bea6a.png)
![2014-02-05_22 20 09](https://f.cloud.github.com/assets/6599863/2095524/8a0e2d06-8ee8-11e3-8c5a-00a3d3a5022d.png)
![2014-02-05_22 20 13](https://f.cloud.github.com/assets/6599863/2095525/91768106-8ee8-11e3-98b0-e078f0fce2dd.png)
![2014-02-05_22 20 16](https://f.cloud.github.com/assets/6599863/2095526/9656c244-8ee8-11e3-8b65-fd886c968cf7.png)
![2014-02-05_22 20 34](https://f.cloud.github.com/assets/6599863/2095527/9c4a5a26-8ee8-11e3-8745-c75701fc93de.png)
![2014-02-05_22 23 27](https://f.cloud.github.com/assets/6599863/2095528/a2b58ba6-8ee8-11e3-982d-7603bc336379.png)
![2014-02-05_22 23 36](https://f.cloud.github.com/assets/6599863/2095529/a64b7b86-8ee8-11e3-887f-3be3481c4a54.png)
![2014-02-05_22 23 42](https://f.cloud.github.com/assets/6599863/2095532/aaa02466-8ee8-11e3-80b9-56529947deff.png)
![2014-02-05_22 23 04](https://f.cloud.github.com/assets/6599863/2095534/ae3bf8b6-8ee8-11e3-9de4-44900dbd2513.png)

**Comment by CannibalVox** [comment]
This is a place to report bugs with the launcher, not to report bugs with modpacks.
