### ISSUE TITLE
HELP Attack of the B-Team

### ISSUE THREAD

**Issue by crews738** [TechnicPack/TechnicLauncher#470]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 395

```
Selected Pack: Attack of the B-Team
```

Stack Trace:
    Exception: JsonSyntaxException
    Message: com.google.gson.stream.MalformedJsonException: Unterminated string at line 3601 column 50
    Trace:
        com.google.gson.Gson.fromJson(Gson.java:818)
        com.google.gson.Gson.fromJson(Gson.java:768)
        com.google.gson.Gson.fromJson(Gson.java:717)
        com.google.gson.Gson.fromJson(Gson.java:689)
        net.technicpack.launchercore.install.tasks.GetAssetsIndexTask.runTask(GetAssetsIndexTask.java:53)
        net.technicpack.launchercore.install.tasks.InstallTasksQueue.RunAllTasks(InstallTasksQueue.java:33)
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:104)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:63)
        Caused By: (MalformedJsonException)
            [Unterminated string at line 3601 column 50]
            com.google.gson.Gson.fromJson(Gson.java:818)
            com.google.gson.Gson.fromJson(Gson.java:768)
            com.google.gson.Gson.fromJson(Gson.java:717)
            com.google.gson.Gson.fromJson(Gson.java:689)
            net.technicpack.launchercore.install.tasks.GetAssetsIndexTask.runTask(GetAssetsIndexTask.java:53)
            net.technicpack.launchercore.install.tasks.InstallTasksQueue.RunAllTasks(InstallTasksQueue.java:33)
            net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:104)
            org.spoutcraft.launcher.InstallThread.run(InstallThread.java:63)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.9.1
    Operating System Architecture: x86_64
    Java version: 1.6.0_65 64 bit
    Total Memory: 1015 MB
    Max Memory: 1015 MB
    Memory Free: 938 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Hi, this is fixed in the latest beta.  You can use it now by going to the cogwheel menu in the upper right hand, selecting "use beta builds", and restarting the launcher.

**Comment by crews738** [comment]
Dang y'all are quick!! Thanks so much :D
