### ISSUE TITLE
MoonQuest Error

### ISSUE THREAD

**Issue by MonsterMetroid** [TechnicPack/TechnicLauncher#472]
here is the report

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 395

```
Selected Pack: MoonQuest Modpack
```

Stack Trace:
    Exception: RuntimeException
    Message: Minecraft not installed for this pack: InstalledPack{info=SolderPackInfo{name='moonquest-yogscast-inspired', display_name='MoonQuest (YOGSCAST Inspired)', url='null', icon_md5='1844c730780882768b5c77b587cc0661', logo_md5='694031bf314e0d1e6fa2656cf1d6d884', background_md5='7014d97e891195a562f421d453a28d17', recommended='v2.1.5.2', latest='v2.1.6', builds=[v2.1.6, v2.1.6.0.1, v2.1.5.2, v2.1.6.0.2], solder=net.technicpack.launchercore.restful.solder.Solder@6d1b5ecf}, name='moonquest-yogscast-inspired', platform=true, build='recommended', directory='%MODPACKS%\moonquest-yogscast-inspired'}
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:191)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:74)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_45 64 bit
    Total Memory: 134 MB
    Max Memory: 1811 MB
    Memory Free: 66 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
This should be fixed in the latest beta version.  Go to the top right cogwheel menu and switch the launcher to always use beta builds, restart your launcher, and try again.
