### ISSUE TITLE
Technic Launcher Error Report

### ISSUE THREAD

**Issue by amouat20000** [TechnicPack/TechnicLauncher#473]
Launcher Build: 395

```
Selected Pack: Tekkit Classic
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.InstalledPack.loadCachedImage(InstalledPack.java:278)
        net.technicpack.launchercore.install.InstalledPack.loadImage(InstalledPack.java:263)
        net.technicpack.launchercore.install.InstalledPack.getLogo(InstalledPack.java:238)
        org.spoutcraft.launcher.skin.components.PackButton.setPack(PackButton.java:72)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:155)
        org.spoutcraft.launcher.skin.ModpackSelector.redraw(ModpackSelector.java:211)
        org.spoutcraft.launcher.skin.ModpackSelector.updatePack(ModpackSelector.java:118)
        net.technicpack.launchercore.install.AvailablePackList.triggerUpdateListeners(AvailablePackList.java:55)
        net.technicpack.launchercore.install.AvailablePackList$3$1.run(AvailablePackList.java:188)
        java.awt.event.InvocationEvent.dispatch(Unknown Source)
        java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        java.awt.EventQueue.access$200(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue.dispatchEvent(Unknown Source)
        java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.run(Unknown Source)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_25 64 bit
    Total Memory: 121 MB
    Max Memory: 883 MB
    Memory Free: 58 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
This is fixed in the latest beta build.

**Comment by CannibalVox** [comment]
You can use it by going to the cogwheel menu in the top right and selecting "always use beta builds" then restarting your launcher.  We're probably going to be promoting the build to stable tomorrow, though.
