### ISSUE TITLE
tekkit log in crashes

### ISSUE THREAD

**Issue by mcawesome6799** [TechnicPack/TechnicLauncher#476]
```
Selected Pack: null
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.AvailablePackList.reloadAllPacks(AvailablePackList.java:122)
        net.technicpack.launchercore.install.AvailablePackList.userChanged(AvailablePackList.java:42)
        net.technicpack.launchercore.install.user.UserModel.triggerAuthListeners(UserModel.java:39)
        net.technicpack.launchercore.install.user.UserModel.setCurrentUser(UserModel.java:30)
        org.spoutcraft.launcher.skin.LoginFrame.attemptNewLogin(LoginFrame.java:441)
        org.spoutcraft.launcher.skin.LoginFrame.attemptLogin(LoginFrame.java:347)
        org.spoutcraft.launcher.skin.LoginFrame.actionPerformed(LoginFrame.java:468)
        javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        java.awt.Component.processMouseEvent(Unknown Source)
        javax.swing.JComponent.processMouseEvent(Unknown Source)
        java.awt.Component.processEvent(Unknown Source)
        java.awt.Container.processEvent(Unknown Source)
        java.awt.Component.dispatchEventImpl(Unknown Source)
        java.awt.Container.dispatchEventImpl(Unknown Source)
        java.awt.Component.dispatchEvent(Unknown Source)
        java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        java.awt.Container.dispatchEventImpl(Unknown Source)
        java.awt.Window.dispatchEventImpl(Unknown Source)
        java.awt.Component.dispatchEvent(Unknown Source)
        java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        java.awt.EventQueue.access$200(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue$4.run(Unknown Source)
        java.awt.EventQueue$4.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue.dispatchEvent(Unknown Source)
        java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.run(Unknown Source)

**Comment by CannibalVox** [comment]
Looks like your InstalledPacks file is corrupted.  You can fix this immediately by deleting %appdata%.technic\installedPacks and restarting the launcher.  I'll put some better error handling for this.

**Comment by CannibalVox** [comment]
This should be fixed in the latest stable version.
