### ISSUE TITLE
32-Bit, 1GB; Why Not 2GB?

### ISSUE THREAD

**Issue by dcrockwell** [TechnicPack/TechnicLauncher#477]
32-bit Java seems to support up to 3GB of RAM, so I'm wondering why MAX_32_BIT_MEMORY = 1024 instead of 2048?

Are there other limitations that prevent this?

**Comment by CannibalVox** [comment]
The largest Xmx value I've heard of 32-bit java supporting is 1200M.

**Comment by CannibalVox** [comment]
http://www.oracle.com/technetwork/java/hotspotfaq-138619.html#gc_heap_32bit

Keep in mind that we also have to allocate space for the permanent generation, which ends up bringing the max below 1400 in many cases if we want to support all windows systems.

**Comment by dcrockwell** [comment]
You're absolutely correct. The material I was reading was unreliable. Thank you for the explanation, it helps me tremendously in helping users with 32-bit machines.
