### ISSUE TITLE
IndexOutOfBoundsException when launching

### ISSUE THREAD

**Issue by SNiLD** [TechnicPack/TechnicLauncher#480]
I got this error message when I launched TechnicLauncher:

http://pastebin.com/9agd0bte

Sounds weird that index 13 would be out of bounds for an array of size 14.

Launching the application second time did not give this error.

**Comment by CannibalVox** [comment]
It is weird, isn't it?  This is due to a concurrency issue that we believe is fixed in the latest beta.
