### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by oliwer123** [TechnicPack/TechnicLauncher#485]
http://pastebin.com/GYHjvB8p

**Comment by CannibalVox** [comment]
Can you close the launcher, go to %appdata%.technic\settings.json, open it, set showConsole to true, save & close that.  Try to start the launcher & log in again, and when it crashes, copy me what the console says in it?

**Comment by oliwer123** [comment]
![image](https://f.cloud.github.com/assets/6641874/2128863/38b33988-9280-11e3-98a2-e26f770948d9.png)

**Comment by CannibalVox** [comment]
Don't close it! Still need to fix it.  :-P

**Comment by oliwer123** [comment]
dont close it? :D

**Comment by CannibalVox** [comment]
I need to fix it first.

**Comment by oliwer123** [comment]
ok then i dont close anything :p

**Comment by oliwer123** [comment]
solved it :D

**Comment by CannibalVox** [comment]
Sounds like it was a bad username issue.  Thank you!
