### ISSUE TITLE
Cant Login D:

### ISSUE THREAD

**Issue by deeno212** [TechnicPack/TechnicLauncher#486]
Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.skin.LoginFrame.attemptNewLogin(LoginFrame.java:420)
        org.spoutcraft.launcher.skin.LoginFrame.attemptLogin(LoginFrame.java:345)
        org.spoutcraft.launcher.skin.LoginFrame.actionPerformed(LoginFrame.java:466)
        javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        java.awt.Component.processMouseEvent(Unknown Source)
        javax.swing.JComponent.processMouseEvent(Unknown Source)
        java.awt.Component.processEvent(Unknown Source)
        java.awt.Container.processEvent(Unknown Source)
        java.awt.Component.dispatchEventImpl(Unknown Source)
        java.awt.Container.dispatchEventImpl(Unknown Source)
        java.awt.Component.dispatchEvent(Unknown Source)
        java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        java.awt.Container.dispatchEventImpl(Unknown Source)
        java.awt.Window.dispatchEventImpl(Unknown Source)
        java.awt.Component.dispatchEvent(Unknown Source)
        java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        java.awt.EventQueue.access$200(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue$4.run(Unknown Source)
        java.awt.EventQueue$4.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue.dispatchEvent(Unknown Source)
        java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.run(Unknown Source)

**Comment by CannibalVox** [comment]
Can you give me the whole crash report?  Build number, the whole thing?

**Comment by git-commit** [comment]
Also experienced this issue today. http://pastebin.com/yrJV5cRu

**Comment by CannibalVox** [comment]
Okay, thank you.  Another user verified to me that this issue is what I thought it was.  The fix is simple, but my concern is determining what the "null" response actually means.  I believe it represents a mojang outage at the moment.

**Comment by git-commit** [comment]
Try putting in any username. I tried "asdf" and different other names I'm sure are not taken. Maybe Mojang is now returning null if the login does not exist.

Also providing a valid login worked for me.

**Comment by CannibalVox** [comment]
That's good to know, thanks you.  I rolled out an emergency fix for this that indicates it as a mojang outage.  I'll update that to indicate it as a bad username.

**Comment by deeno212** [comment]
So Does It Work Now?

**Comment by CannibalVox** [comment]
Should, yeah.

**Comment by deeno212** [comment]
Thanks <3

**Comment by deeno212** [comment]
Now To Remember My Password..... XD

**Comment by deeno212** [comment]
Got It

**Comment by deeno212** [comment]
CannibalVox do you play any modpacks?
