### ISSUE TITLE
If you clone this repo and try to build it, the build will fail.

### ISSUE THREAD

**Issue by git-commit** [TechnicPack/TechnicLauncher#487]
net.technicpack.launchercore:1.0.0-SNAPSHOT dependency is not automatically resolved. Thus the build fails.

**Comment by CannibalVox** [comment]
Launcher core is another github repository under this same user.  This is where issues with the launcher are reported, it is not a helpdesk for building the launcher.

**Comment by git-commit** [comment]
As I was saying.

Following the directions in the README in THIS repository, the build of the launcher will fail, because Launcher Core is not in the maven repos.

Could you please provide complete instructions on how to get your code built? I was going to look into the login error #486 .
