### ISSUE TITLE
Kingdom Hearts 1.6.4

### ISSUE THREAD

**Issue by VentusHearts** [TechnicPack/TechnicLauncher#493]
tried to start my kh 1.6.4 and it gave me this

Stack Trace:
    Exception: RuntimeException
    Message: Minecraft not installed for this pack: InstalledPack{info=PlatformPackInfo{name='kingdom-hearts-pack-164', displayName='Kingdom Hearts Pack 1.6.4', url='https://dl.dropboxusercontent.com/s/enzkb936d3av183/Kingdom%20Hearts%20Modpack.zip?dl=1&token_hash=AAGzYhfQPG02-u3WvNMGM73HI52rf-GtISSiMxac_JWSYw', icon=null, logo=net.technicpack.launchercore.restful.Resource@42a6f5df, background=net.technicpack.launchercore.restful.Resource@5f5825a8, minecraft='1.6.4', forge='null', version='1.0', solder='', forceDir=false}, name='kingdom-hearts-pack-164', platform=true, build='recommended', directory='%MODPACKS%\kingdom-hearts-pack-164'}
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:198)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:106)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:74)

**Comment by CannibalVox** [comment]
Um, use the real launcher and not a cracked one.

**Comment by CannibalVox** [comment]
Alternatively, restart your launcher because we rolled out a fix for this this morning and you've apparently been running your launcher this whole time.

**Comment by VentusHearts** [comment]
yah, ok 1, i don't know what the crap I'm doing, 2, i don't know what you just said, i just tried to redownload it, 3 attack of the b team got to the mojang screen and froze, and 4, its still doin it
did i mention i don't know what I'm doing?
