### ISSUE TITLE
Selective downloading of mods.

### ISSUE THREAD

**Issue by ruifung** [TechnicPack/TechnicLauncher#496]
Allow users to deselect packages they do not wish to download, similar to how the FTB Launcher allows users to pick what mods they do not want. This would only apply to solder packs for obvious reasons. Or maybe with improvements to solder, allow for optional packages that can be deselected...

**Comment by CannibalVox** [comment]
Naw, this isn't gonna happen.  We are generally opposed to splitting communities in this manner.

**Comment by ruifung** [comment]
@CannibalVox What do you mean splitting communities?
