### ISSUE TITLE
Voltz, Tekkit, Hexxit, and Big Dig are all upside down.

### ISSUE THREAD

**Issue by Mohinder-Suresh** [TechnicPack/TechnicLauncher#497]
I see that this was fixed three months ago or so, but it's a problem once again.  When I go into fullscreen, it works perfectly fine, but I can't see my battery percentage and I can't switch between windows, which are two things I like to do whilst playing Minecraft. Help?

**Comment by CannibalVox** [comment]
Have you updated to the free OSX "Mavericks" updated?

**Comment by Mohinder-Suresh** [comment]
Due to this being a school-owned machine, I can't.

**Comment by kubilay77** [comment]
.
