### ISSUE TITLE
techinic wont work

### ISSUE THREAD

**Issue by abhijeetko** [TechnicPack/TechnicLauncher#538]
Stack Trace:
    Exception: RuntimeException
    Message: Library net.minecraft:launchwrapper:1.8 not found.
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:153)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:99)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:55)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:72)

this happened while opening new tekkit

**Comment by CannibalVox** [comment]
You have either an old or a cracked version of the launcher.  Get the latest at technicpack.net

**Comment by abhijeetko** [comment]
Ok ill update my launcher thnx :)
