### ISSUE TITLE
HOW DO I FIX THIS! MINECRAFT KEEPS CRASHING!

### ISSUE THREAD

**Issue by destroyrenumber2** [TechnicPack/TechnicLauncher#543]
41 mods loaded
Optifine OptiFine_1.2.5_HD_S_C6
Minecraft Forge 3.3.8.164
FML v2.2.106.176
Forge Mod Loader version 2.2.106.176 for Minecraft 1.2.5
    mod_CodeChickenCore : Initialized (modpack.jar)
    mod_MinecraftForge : Initialized (modpack.jar)
    mod_NotEnoughItems : Initialized (modpack.jar)
    mod_ReiMinimap : Initialized ([1.2.5]ReiMinimap_v3.2_04.zip)
    mod_IC2 : Initialized (industrialcraft-2-client_1.97.jar)
    mod_IC2AdvancedMachines : Initialized (AdvancedMachines_4.0_client.zip)
    mod_BuildCraftCore : Initialized (buildcraft-client-A-core-2.2.14.zip)
    mod_BuildCraftBuilders : Initialized (buildcraft-client-B-builders-2.2.14.zip)
    mod_BuildCraftEnergy : Initialized (buildcraft-client-B-energy-2.2.14.zip)
    mod_BuildCraftFactory : Initialized (buildcraft-client-B-factory-2.2.14.zip)
    mod_BuildCraftTransport : Initialized (buildcraft-client-B-transport-2.2.14.zip)
    mod_AdditionalPipes : Initialized (buildcraft-client-DA-additionalpipes-2.1.3.zip)
    mod_ComputerCraft : Initialized (ComputerCraft)
    mod_RedPowerMachine : Initialized (RedPowerMachine-2.0pr5b2.zip)
    mod_ccSensors : Initialized (ccSensors-client-MC125-B017pr1.zip)
    mod_CCTurtle : Initialized (ComputerCraft)
    mod_EE : Initialized (EE2ClientV1.4.6.5.jar)
    mod_EnderStorage : Initialized (EnderStorage-Client 1.1.3.zip)
    mod_IC2NuclearControl : Initialized (IC2NuclearControl_client_v1.1.10b.zip)
    mod_ImmibisCore : Initialized (immibis-core_49.1.1_for_1.2.5-client.jar)
    mod_InvTweaks : Initialized (InvTweaks-1.41b-1.2.4.zip)
    mod_MAtmos_forModLoader : Initialized (MAtmos_packaged.zip)
    mod_ModularForceFieldSystem : Initialized (mffs_rev7_for_1.2.5-client.zip)
    mod_IC2_ChargingBench : Initialized (mod_chargingbench-client-1.95b-1.2.5-r1.zip)
    mod_CompactSolars : Initialized (mod_compactsolars-client-2.3.2.10.zip)
    mod_IronChest : Initialized (mod_ironchests-client-3.8.0.40.zip)
    mod_RedPowerCore : Initialized (RedPowerCore-2.0pr5b2.zip)
    mod_NetherOres : Initialized (NetherOres_Client_1.2.1.zip)
    mod_PowerConverters : Initialized (PowerConverters_Client_1.3.4.zip)
    mod_Railcraft : Initialized (Railcraft_Client_5.3.3.zip)
    mod_RedPowerControl : Initialized (RedPowerControl-2.0pr5b2.zip)
    mod_RedPowerLighting : Initialized (RedPowerLighting-2.0pr5b2.zip)
    mod_RedPowerLogic : Initialized (RedPowerLogic-2.0pr5b2.zip)
    mod_RedPowerWiring : Initialized (RedPowerWiring-2.0pr5b2.zip)
    mod_RedPowerWorld : Initialized (RedPowerWorld-2.0pr5b2.zip)
    mod_TubeStuff : Initialized (tubestuff_49.1.2_for_1.2.5-client.jar)
    Balkon's WeaponMod : Initialized (WeaponMod.zip)
    mod_WirelessRedstoneCore : Initialized (WR-CBE Core-Client 1.2.2.3.zip)
    mod_WirelessRedstoneAddons : Initialized (WR-CBE Addons-Client 1.2.2.3.zip)
    mod_WirelessRedstoneRedPower : Initialized (WR-CBE RedPower-Client 1.2.2.1.zip)
    mod_ImmiChunkLoaders : Pre-initialized (zdimensional-anchor_rev3.2_for_1.2.5-client.jar)

```
  Minecraft has crashed!      
  ----------------------      
```

Minecraft has stopped running because it encountered a problem.

--- BEGIN ERROR REPORT 83860155 --------
Generated 12/03/14 19:53

Minecraft: Minecraft 1.2.5
OS: Windows 8 (x86) version 6.2
Java: 1.7.0_45, Oracle Corporation
VM: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
LWJGL: 2.9.0
OpenGL: GeForce GT 635M/PCIe/SSE2 version 4.2.0, NVIDIA Corporation

java.lang.IllegalArgumentException: Slot 4095 is already occupied by ic2.common.BlockScaffold@14ab5b8 when adding immibis.chunkloader.BlockChunkLoader@1e049d9
    at pb.<init>(Block.java:251)
    at agy.<init>(BlockContainer.java:7)
    at immibis.core.BlockCombined.<init>(BlockCombined.java:35)
    at immibis.chunkloader.BlockChunkLoader.<init>(BlockChunkLoader.java:12)
    at immibis.chunkloader.Main$1.registerBlock(Main.java:107)
    at immibis.core.CoreProxy.RegisterBlockID(CoreProxy.java:31)
    at immibis.chunkloader.Main.load(Main.java:104)
    at cpw.mods.fml.common.modloader.ModLoaderModContainer.init(ModLoaderModContainer.java:356)
    at cpw.mods.fml.common.Loader.modInit(Loader.java:273)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:628)
    at cpw.mods.fml.client.FMLClientHandler.onLoadComplete(FMLClientHandler.java:223)
    at net.minecraft.client.Minecraft.a(Minecraft.java:429)
    at net.minecraft.client.Minecraft.run(Minecraft.java:738)
    at java.lang.Thread.run(Unknown Source)
--- END ERROR REPORT 3b3f9204 ----------

**Comment by CannibalVox** [comment]
It appears to be tekkit classic, someone probably touched something they shouldn't have..  Click the cogwheel under the pack and click "reset pack".  Regardless, this isn't a launcher issue so I'm closing.
