### ISSUE TITLE
Technic Packs not loading 

### ISSUE THREAD

**Issue by tyler489** [TechnicPack/TechnicLauncher#551]
none of my packs are loading they all say loading running java 64bit on a 64bit system 
when i was running 32 bit everything worked fine error message

( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 431
    Selected Pack: null
Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        java.io.File.<init>(Unknown Source)
        net.technicpack.launchercore.install.InstalledPack.getInstalledDirectory(InstalledPack.java:186)
        org.spoutcraft.launcher.skin.LauncherFrame.action(LauncherFrame.java:411)
        org.spoutcraft.launcher.skin.LauncherFrame.actionPerformed(LauncherFrame.java:399)
        javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        java.awt.Component.processMouseEvent(Unknown Source)
        javax.swing.JComponent.processMouseEvent(Unknown Source)
        java.awt.Component.processEvent(Unknown Source)
        java.awt.Container.processEvent(Unknown Source)
        java.awt.Component.dispatchEventImpl(Unknown Source)
        java.awt.Container.dispatchEventImpl(Unknown Source)
        java.awt.Component.dispatchEvent(Unknown Source)
        java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        java.awt.Container.dispatchEventImpl(Unknown Source)
        java.awt.Window.dispatchEventImpl(Unknown Source)
        java.awt.Component.dispatchEvent(Unknown Source)
        java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        java.awt.EventQueue.access$200(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue$4.run(Unknown Source)
        java.awt.EventQueue$4.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue.dispatchEvent(Unknown Source)
        java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.run(Unknown Source)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_51 64 bit
    Total Memory: 58 MB
    Max Memory: 866 MB
    Memory Free: 22 MB
    CPU Cores: 2

**Comment by tyler489** [comment]
i was getting an error of all my packs being offline i tried reinstalling and this happened
http://gyazo.com/b615f09f598ff4702ec26340488f4bb2
system has 32 and 64 os 
i have 64 bit java istalled so i can devote more memory to the launcher.
need anything else let me know

**Comment by CannibalVox** [comment]
This happens when your computer is unable to communicate over IPV6.  Check in programs/features for a program called "relevant knowledge" and uninstall it, it is malware.

**Comment by tyler489** [comment]
i just uninstalled java 64bit and now it worked ?? bug with the 64 bit java?

**Comment by tyler489** [comment]
i dont have that program

**Comment by ToasterShark** [comment]
I don't have relevant knowledge either, so you installed 32 bit instead?
