### ISSUE TITLE
Bug with Mirrors file download

### ISSUE THREAD

**Issue by agrus** [TechnicPack/TechnicLauncher#56]
Mirrors file download stops on second item in MIRRORS_URL, if first is not reacheble

on fisrt Main.isOffline sets to true
then download skips by if (Main.isOffline) return false;

adding Main.isOffline = false; into downloadMirrorsYmlFile before downloadYmlFile will fix it

**Comment by vidplace7** [comment]
@agrus Submit a PR then ;)
