### ISSUE TITLE
[REQ] Custom JVM args.

### ISSUE THREAD

**Issue by ruifung** [TechnicPack/TechnicLauncher#602]
Most launchers, including the FTB launcher, vanilla launcher, multimc and so on allow custom JVM arguments to be used. Can this be implemented?

**Comment by CannibalVox** [comment]
It is implemented for pack creators- inside modpack.jar, you can add a version.json file to be used for your modpack (a version.json file already comes included if you are using Forge as your modpack.jar).  You can add a string field javaArguments with your additional JVM args.
