### ISSUE TITLE
JAC Pixelmon shuts down randomly when I'm on it

### ISSUE THREAD

**Issue by TeamPlasma** [TechnicPack/TechnicLauncher#666]
When I'm on a server of a personal world, I'll be playing Pixelmon and it will close the window randomly. It's sooooo annoying and I can't fix it.

**Comment by TeamPlasma** [comment]
http://pastebin.com/Yc20wQk0# is the link to paste bin

**Comment by CannibalVox** [comment]
Your java is way, way out of date.  Update it here: http://www.java.com/en/download/manual.jsp
