### ISSUE TITLE
Cant open techniclauncher

### ISSUE THREAD

**Issue by Fevol** [TechnicPack/TechnicLauncher#681]
Launcher Build: 439
    Selected Pack: null
Stack Trace:
    Exception: NoClassDefFoundError
    Message: com/sun/imageio/plugins/common/ReaderUtil (wrong name: com/sun?imageio/plugins/common/ReaderUtil)
    Trace:
        com.sun.imageio.plugins.png.PNGImageReader.decodePass(Unknown Source)
        com.sun.imageio.plugins.png.PNGImageReader.decodeImage(Unknown Source)
        com.sun.imageio.plugins.png.PNGImageReader.readImage(Unknown Source)
        com.sun.imageio.plugins.png.PNGImageReader.read(Unknown Source)
        javax.imageio.ImageIO.read(Unknown Source)
        javax.imageio.ImageIO.read(Unknown Source)
        net.technicpack.launchercore.util.ResourceUtils.getImage(ResourceUtils.java:71)
        net.technicpack.launchercore.install.AddPack.<clinit>(AddPack.java:28)
        org.spoutcraft.launcher.launcher.InstalledPacks.load(InstalledPacks.java:49)
        org.spoutcraft.launcher.launcher.Launcher.<init>(Launcher.java:70)
        org.spoutcraft.launcher.entrypoint.SpoutcraftLauncher.main(SpoutcraftLauncher.java:94)
        org.spoutcraft.launcher.entrypoint.Start.launch(Start.java:141)
        org.spoutcraft.launcher.entrypoint.Start.main(Start.java:46)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: x86
    Java version: 1.7.0_25 32 bit
    Total Memory: 15 MB
    Max Memory: 494 MB
    Memory Free: 12 MB
    CPU Cores: 2

**Comment by HomelessTR** [comment]
Me too Pls Help me i can't connect  plssss help
