### ISSUE TITLE
Crash with Solder

### ISSUE THREAD

**Issue by CromAr** [TechnicPack/TechnicLauncher#687]
I just got Solder to run with my Modpack, even i dont have the Modpack build up in Solder. I linked the Solder with Technic site and if i run the Launcher and click on play this happens:

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: Team-k.OS
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:70)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:63)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_55 64 bit
    Total Memory: 154 MB
    Max Memory: 1799 MB
    Memory Free: 106 MB
    CPU Cores: 4

**Comment by prodkid** [comment]
i also have a similar issue.

**Comment by prodkid** [comment]
FIgured out solution. You need to have at least one build to be Recommended. Derp.

**Comment by CromAr** [comment]
Ok will try when im home again ... THX ;)

**Comment by prodkid** [comment]
No problem, I think if you manually select the build as well that should fix it too, if it's published but I haven't checked that myself. What is going on is that the launcher is loading up the modpack, however, with no builds as the default one, its just null.

**Comment by CromAr** [comment]
Ok, tested it now with giving a new Buildnumber and it worked :+1:
