### ISSUE TITLE
Unexpected Error!

### ISSUE THREAD

**Issue by DawsPls** [TechnicPack/TechnicLauncher#717]
I'm trying to play attack of the b-team. Gives me this error

( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439
    Selected Pack: null
Stack Trace:
    Exception: Error
    Message: posix_spawn is not a supported process launch mechanism on this platform.
    Trace:
        java.lang.UNIXProcess$1.run(UNIXProcess.java:104)
        java.lang.UNIXProcess$1.run(UNIXProcess.java:93)
        java.security.AccessController.doPrivileged(Native Method)
        java.lang.UNIXProcess.<clinit>(UNIXProcess.java:91)
        java.lang.ProcessImpl.start(ProcessImpl.java:130)
        java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:70)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:74)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.9.4
    Operating System Architecture: x86_64
    Java version: 1.7.0_67 64 bit
    Total Memory: 132 MB
    Max Memory: 910 MB
    Memory Free: 48 MB
    CPU Cores: 2

**Comment by juminho** [comment]
bvcx

**Comment by CannibalVox** [comment]
What on earth?

First of all, you're not on the latest build.  Your auto-updater isn't working.  Now the reason why it's not working probably has to do with the fact that ProcessBuilder isn't working on your java, which is a basic java utility and should always be working for everyone.  You won't be able to launch packs or update automatically until that's fixed.

Now that said, you can fix the version by updating to the latest manually at http://www.technicpack.net/ but that's not going to fix the core problem, the only thing I can think of is maybe updating your java.

**Comment by CannibalVox** [comment]
Oh, this was 4 months old and was bumped by someone posting gibberish.
