### ISSUE TITLE
ser_1411999293354

### ISSUE THREAD

**Issue by TSchellien** [TechnicPack/TechnicLauncher#727]
http://pastebin.com/HLAP0MqL

**Comment by eren123123** [comment]
Teknik Launcher Hata Raporu:
( Lütfen https://github.com/technicpack/techniclauncher/issues bu rapor gönder )
Başlatıcı Oluştur: 0

Seçili Paketi: Yogbox
Yığın İzleme:
Özel Durum: İndexOutOfBoundsException
Mesaj: Dizin: 0, Size: 0
İzleme:
java.açıklama.ArrayList.rangeCheck(Bilinmeyen Kaynak)
java.açıklama.ArrayList.(Bilinmeyen Kaynak)
org.spoutcraft.başlatıcısı.cilt.NewsComponent.setupArticles(NewsComponent.:60 java)
org.spoutcraft.başlatıcısı.cilt.NewsComponent.loadArticles(NewsComponent.:46 java)
org.spoutcraft.başlatıcısı.Launcher 2 dolar.Çalıştır(Başlatıcısı.:105 java)

Sistem Bilgisi:
İşletim Sistemi: Windows 7
İşletim Sistemi Versiyon: 6.1
İşletim Sistemi Mimarisi: 86
Java sürümü: 1.8.0_31 32 bit
Toplam Bellek: 47)
Max Bellek: 247 MB
Boş bellek: 20 MB
CPU Çekirdek: 2
klon bu hamur

**Comment by eren123123** [comment]
Teknik Launcher Hata Raporu:
( Lütfen https://github.com/technicpack/techniclauncher/issues bu rapor gönder )
Başlatıcı Oluştur: 0

Seçili Paketi: Yogbox
Yığın İzleme:
Özel Durum: İndexOutOfBoundsException
Mesaj: Dizin: 0, Size: 0
İzleme:
java.açıklama.ArrayList.rangeCheck(Bilinmeyen Kaynak)
java.açıklama.ArrayList.(Bilinmeyen Kaynak)
org.spoutcraft.başlatıcısı.cilt.NewsComponent.setupArticles(NewsComponent.:60 java)
org.spoutcraft.başlatıcısı.cilt.NewsComponent.loadArticles(NewsComponent.:46 java)
org.spoutcraft.başlatıcısı.Launcher 2 dolar.Çalıştır(Başlatıcısı.:105 java)

Sistem Bilgisi:
İşletim Sistemi: Windows 7
İşletim Sistemi Versiyon: 6.1
İşletim Sistemi Mimarisi: 86
Java sürümü: 1.8.0_31 32 bit
Toplam Bellek: 47)
Max Bellek: 247 MB
Boş bellek: 20 MB
CPU Çekirdek: 2
klon bu hamur

**Comment by eren123123** [comment]
Teknik Launcher Hata Raporu: ( Lütfen https://github.com/technicpack/techniclauncher/issues bu rapor gönder ) Başlatıcısı İnşa: 0 Seçili Pack: Yığın İzleme Yogbox: özel Durum: İndexOutOfBoundsException İletisi: Dizin: 0, Boyut: 0 İz: java.açıklama.ArrayList.(Bilinmeyen Kaynak) rangeCheck java.açıklama.ArrayList.(Bilinmeyen Kaynak) org.spoutcraft.başlatıcısı.cilt.NewsComponent.setupArticles(NewsComponent.:60 java) org.spoutcraft.başlatıcısı.cilt.NewsComponent.loadArticles(NewsComponent.:46 java) org.spoutcraft.başlatıcısı.Launcher 2 dolar.Çalıştır(Başlatıcısı.java:105) Sistem Bilgileri İşletim Sistemi: Windows 7 İşletim Sistemi Versiyon: 6.1 İşletim Sistemi Mimarisi: 86 Java sürümü: 1.8.0_31 32 bit Toplam Bellek: 47 MB Max Bellek: 247 MB boş Bellek: 20 MB CPU Çekirdek: 2

**Comment by eren123123** [comment]
Teknik Launcher Hata Raporu: ( Lütfen https://github.com/technicpack/techniclauncher/issues bu rapor gönder ) Başlatıcısı İnşa: 0 Seçili Pack: Yığın İzleme Yogbox: özel Durum: İndexOutOfBoundsException İletisi: Dizin: 0, Boyut: 0 İz: java.açıklama.ArrayList.(Bilinmeyen Kaynak) rangeCheck java.açıklama.ArrayList.(Bilinmeyen Kaynak) org.spoutcraft.başlatıcısı.cilt.NewsComponent.setupArticles(NewsComponent.:60 java) org.spoutcraft.başlatıcısı.cilt.NewsComponent.loadArticles(NewsComponent.:46 java) org.spoutcraft.başlatıcısı.Launcher 2 dolar.Çalıştır(Başlatıcısı.java:105) Sistem Bilgileri İşletim Sistemi: Windows 7 İşletim Sistemi Versiyon: 6.1 İşletim Sistemi Mimarisi: 86 Java sürümü: 1.8.0_31 32 bit Toplam Bellek: 47 MB Max Bellek: 247 MB boş Bellek: 20 MB CPU Çekirdek: 2
