### ISSUE TITLE
ser_1412278691533

### ISSUE THREAD

**Issue by ImAnAutie** [TechnicPack/TechnicLauncher#728]
http://pastebin.com/tU9pE6fR

**Comment by BlueKingMaster** [comment]
Selected Pack: Attack of the B-Team
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows XP
    Operating System Version: 5.1
    Operating System Architecture: x86
    Java version: 1.8.0_31 32 bit
    Total Memory: 56 MB
    Max Memory: 245 MB
    Memory Free: 31 MB
    CPU Cores: 2

**Comment by eren123123** [comment]
Teknik Launcher Hata Raporu: ( Lütfen https://github.com/technicpack/techniclauncher/issues bu rapor gönder ) Başlatıcısı İnşa: 0 Seçili Pack: Yığın İzleme null: özel Durum: İndexOutOfBoundsException İletisi: Dizin: 0, Boyut: 0 İz: java.açıklama.ArrayList.(Bilinmeyen Kaynak) rangeCheck java.açıklama.ArrayList.(Bilinmeyen Kaynak) org.spoutcraft.başlatıcısı.cilt.NewsComponent.setupArticles(NewsComponent.:60 java) org.spoutcraft.başlatıcısı.cilt.NewsComponent.loadArticles(NewsComponent.:46 java) org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105) Sistem Bilgileri İşletim Sistemi: Windows 7 İşletim Sistemi Versiyon: 6.1 İşletim Sistemi Mimarisi: 86 Java sürümü: 1.8.0_31 32 bit Toplam Bellek: 38 MB Max Bellek: 247 MB boş Bellek: 12 MB İŞLEMCİ Çekirdeği: 2

**Comment by eren123123** [comment]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_31 32 bit
    Total Memory: 38 MB
    Max Memory: 247 MB
    Memory Free: 12 MB

**Comment by eren123123** [comment]
Teknik Launcher Hata Raporu:
( Lütfen https://github.com/technicpack/techniclauncher/issues bu rapor gönder )
Başlatıcı Oluştur: 0

Seçili Paketi: null
Yığın İzleme:
Özel Durum: İndexOutOfBoundsException
Mesaj: Dizin: 0, Size: 0
İzleme:
java.açıklama.ArrayList.rangeCheck(Bilinmeyen Kaynak)
java.açıklama.ArrayList.(Bilinmeyen Kaynak)
org.spoutcraft.başlatıcısı.cilt.NewsComponent.setupArticles(NewsComponent.:60 java)
org.spoutcraft.başlatıcısı.cilt.NewsComponent.loadArticles(NewsComponent.:46 java)
org.spoutcraft.başlatıcısı.Launcher 2 dolar.Çalıştır(Başlatıcısı.:105 java)

Sistem Bilgisi:
İşletim Sistemi: Windows 7
İşletim Sistemi Versiyon: 6.1
İşletim Sistemi Mimarisi: 86
Java sürümü: 1.8.0_31 32 bit
Toplam Hafıza: 38 MB
Max Bellek: 247 MB
Boş bellek: 12 MB
CPU Çekirdek: 2

**Comment by eren123123** [comment]
Teknik Launcher Hata Raporu: ( Lütfen https://github.com/technicpack/techniclauncher/issues bu rapor gönder ) Başlatıcısı İnşa: 0 Seçili Pack: Yığın İzleme Yogbox: özel Durum: İndexOutOfBoundsException İletisi: Dizin: 0, Boyut: 0 İz: java.açıklama.ArrayList.(Bilinmeyen Kaynak) rangeCheck java.açıklama.ArrayList.(Bilinmeyen Kaynak) org.spoutcraft.başlatıcısı.cilt.NewsComponent.setupArticles(NewsComponent.:60 java) org.spoutcraft.başlatıcısı.cilt.NewsComponent.loadArticles(NewsComponent.:46 java) org.spoutcraft.başlatıcısı.Launcher 2 dolar.Çalıştır(Başlatıcısı.java:105) Sistem Bilgileri İşletim Sistemi: Windows 7 İşletim Sistemi Versiyon: 6.1 İşletim Sistemi Mimarisi: 86 Java sürümü: 1.8.0_31 32 bit Toplam Bellek: 47 MB Max Bellek: 247 MB boş Bellek: 20 MB CPU Çekirdek: 2

**Comment by eren123123** [comment]
Teknik Launcher Hata Raporu:
( Lütfen https://github.com/technicpack/techniclauncher/issues bu rapor gönder )
Başlatıcı Oluştur: 0

Seçili Paketi: Yogbox
Yığın İzleme:
Özel Durum: İndexOutOfBoundsException
Mesaj: Dizin: 0, Size: 0
İzleme:
java.açıklama.ArrayList.rangeCheck(Bilinmeyen Kaynak)
java.açıklama.ArrayList.(Bilinmeyen Kaynak)
org.spoutcraft.başlatıcısı.cilt.NewsComponent.setupArticles(NewsComponent.:60 java)
org.spoutcraft.başlatıcısı.cilt.NewsComponent.loadArticles(NewsComponent.:46 java)
org.spoutcraft.başlatıcısı.Launcher 2 dolar.Çalıştır(Başlatıcısı.:105 java)

Sistem Bilgisi:
İşletim Sistemi: Windows 7
İşletim Sistemi Versiyon: 6.1
İşletim Sistemi Mimarisi: 86
Java sürümü: 1.8.0_31 32 bit
Toplam Bellek: 47)
Max Bellek: 247 MB
Boş bellek: 20 MB
CPU Çekirdek: 2

**Comment by eren123123** [comment]
1 kere girior 2 inciyi girmior onuda ayarlarmısın

**Comment by ImAnAutie** [comment]
Whats the reason for the closing?

**Comment by CannibalVox** [comment]
We released a massive update in December that makes this bug report moot and it had collected about a dozen comments from people with cracked launchers.  If you're still having the exact same error, then download the new launcher from http://www.technicpack.net/

**Comment by ImAnAutie** [comment]
Thanks, looks like i need to update
