### ISSUE TITLE
HELP ME PLEASE!!!

### ISSUE THREAD

**Issue by SoulsInRuins** [TechnicPack/TechnicLauncher#735]
Launcher Build: 439

```
Selected Pack: null
```

Stack Trace:
    Exception: RuntimeException
    Message: Library net.minecraft:launchwrapper:1.11 not found.
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:178)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:107)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:56)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:74)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_67 64 bit
    Total Memory: 137 MB
    Max Memory: 882 MB
    Memory Free: 87 MB
    CPU Cores: 2.

^^ THE REPORT! PLEASE HELP ME!!

**Comment by CannibalVox** [comment]
This is the old launcher, so hopefully things are working better for you now.
