### ISSUE TITLE
Error with attack of the B-team

### ISSUE THREAD

**Issue by CliffordH123** [TechnicPack/TechnicLauncher#740]
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439
    Selected Pack: null
Stack Trace:
    Exception: RuntimeException
    Message: Minecraft not installed for this pack: InstalledPack{info=SolderPackInfo{name='attack-of-the-bteam', display_name='Attack of the B-Team', url='null', icon_md5='3db51b868b451756bba459d52d29a88d', logo_md5='b922d87141cfaa9575fc117a8310e1b8', background_md5='42e28642ada94e92902a23f1708e7dda', recommended='1.0.12a', latest='1.0.13c', builds=[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.6a, 1.0.7, 1.0.7a, 1.0.8, 1.0.9b, 1.0.9c, 1.0.10, 1.0.10a, 1.0.10b, 1.0.11, 1.0.11a, 1.0.12, 1.0.12a, 1.0.13b, 1.0.13c], solder=net.technicpack.launchercore.restful.solder.Solder@45df70e9}, name='attack-of-the-bteam', platform=false, build='latest', directory='%MODPACKS%\attack-of-the-bteam'}
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:199)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:107)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:56)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:74)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.8.0_25 64 bit
    Total Memory: 261 MB
    Max Memory: 3616 MB
    Memory Free: 230 MB
    CPU Cores: 8

HELP!!!

**Comment by WCHD** [comment]
Attack of the B-Team does work too, i thing we must wait for a Launcher update :(

**Comment by CannibalVox** [comment]
Hi, CliffordH123, it looks like your launcher has had a problem auto-updating to the latest version.  You can get the new version of the launcher at http://www.technicpack.net/ and you won't have this problem anymore.
