### ISSUE TITLE
Crash on launcher startup

### ISSUE THREAD

**Issue by FevenKitsune** [TechnicPack/TechnicLauncher#742]
I started the launcher from terminal using

java -jar TechnicLauncher.jar

and I recieved this:

( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439
    Selected Pack: null
Stack Trace:
    Exception: UnsatisfiedLinkError
    Message: com.sun.imageio.plugins.jpeg.JPEGImageReader.initReaderIDs(Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;)V
    Trace:
        com.sun.imageio.plugins.jpeg.JPEGImageReader.initReaderIDs(Native Method)
        com.sun.imageio.plugins.jpeg.JPEGImageReader.<clinit>(JPEGImageReader.java:96)
        com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi.createReaderInstance(JPEGImageReaderSpi.java:85)
        javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320)
        javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:529)
        javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:513)
        javax.imageio.ImageIO.read(ImageIO.java:1443)
        javax.imageio.ImageIO.read(ImageIO.java:1352)
        net.technicpack.launchercore.util.ResourceUtils.getImage(ResourceUtils.java:71)
        net.technicpack.launchercore.install.AddPack.<clinit>(AddPack.java:30)
        org.spoutcraft.launcher.launcher.InstalledPacks.load(InstalledPacks.java:49)
        org.spoutcraft.launcher.launcher.Launcher.<init>(Launcher.java:70)
        org.spoutcraft.launcher.entrypoint.SpoutcraftLauncher.main(SpoutcraftLauncher.java:94)
        org.spoutcraft.launcher.entrypoint.Start.launch(Start.java:141)
        org.spoutcraft.launcher.entrypoint.Start.main(Start.java:46)

System Information:
    Operating System: Linux
    Operating System Version: 3.16.0-24-generic
    Operating System Architecture: amd64
    Java version: 1.8.0_40-internal 64 bit
    Total Memory: 88 MB
    Max Memory: 1301 MB
    Memory Free: 69 MB
    CPU Cores: 4

I am running Ubuntu 14.10 64-bit, using OpenJDK 8.

Runs fine under Windows 8.1 partition.

**Comment by leonardo22** [comment]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Attack of the B-Team
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 52 MB
    Max Memory: 247 MB
    Memory Free: 23 MB
    CPU Cores: 2

**Comment by Zombo96** [comment]
Selected Pack: Tekkit
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_31 32 bit
    Total Memory: 40 MB
    Max Memory: 247 MB
    Memory Free: 5 MB
    CPU Cores: 4
