### ISSUE TITLE
Folder Deleted *very very sad*

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#746]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: null
```

Stack Trace:
    Exception: IllegalComponentStateException
    Message: component must be showing on the screen to determine its location
    Trace:
        java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2054)
        java.awt.Component.getLocationOnScreen(Component.java:2028)
        javax.swing.JPopupMenu.show(JPopupMenu.java:948)
        javax.swing.plaf.basic.BasicComboPopup.show(BasicComboPopup.java:207)
        javax.swing.plaf.basic.BasicComboPopup.togglePopup(BasicComboPopup.java:1127)
        javax.swing.plaf.basic.BasicComboPopup$Handler.mousePressed(BasicComboPopup.java:824)
        java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
        java.awt.Component.processMouseEvent(Component.java:6522)
        javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
        java.awt.Component.processEvent(Component.java:6290)
        java.awt.Container.processEvent(Container.java:2234)
        java.awt.Component.dispatchEventImpl(Component.java:4881)
        java.awt.Container.dispatchEventImpl(Container.java:2292)
        java.awt.Component.dispatchEvent(Component.java:4703)
        java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
        java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530)
        java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
        java.awt.Container.dispatchEventImpl(Container.java:2278)
        java.awt.Window.dispatchEventImpl(Window.java:2739)
        java.awt.Component.dispatchEvent(Component.java:4703)
        java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
        java.awt.EventQueue.access$400(EventQueue.java:97)
        java.awt.EventQueue$3.run(EventQueue.java:697)
        java.awt.EventQueue$3.run(EventQueue.java:691)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
        java.awt.EventQueue$4.run(EventQueue.java:719)
        java.awt.EventQueue$4.run(EventQueue.java:717)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
        java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.9.5
    Operating System Architecture: x86_64
    Java version: 1.8.0_25 64 bit
    Total Memory: 224 MB
    Max Memory: 1820 MB
    Memory Free: 119 MB
    CPU Cores: 4

**Comment by MyNickIsBetter** [comment]
Delete .technic and try again with CTL 8
