### ISSUE TITLE
Crash on EXTREMELY fresh install of everything (Linux)

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#748]
I just re-installed Ubuntu, then re-installed openjdk-jdk-8, then I downloaded and ran technic (almost first thing), before getting this on the first run. http://pastebin.com/Ra1Ry1Am

Default location settings, nothing edited in ANYWHERE.

**Comment by ghost** [comment]
Uninstalling and installing jdk 7 worked. Please fix!

**Comment by ruifung** [comment]
This crash isn't even related to the launcher, it was your java that was broken.

**Comment by ghost** [comment]
I somehow doubt a fresh install on a new computer of an official release from the highly monitored repositories is broken, ESPECIALLY when it's happened to MULTIPLE people on THIS program specifically, and STILL fails when one reinstalls.

**Comment by ruifung** [comment]
It's definitely a JDK issue.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=760926

Try the oracle JDK from the webupd8 ppa http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html . Or if you prefer the openjdk variants, use openjdk7 instead.

The method throwing the error is part of the JDK/JRE and based on the error it throws (https://docs.oracle.com/javase/7/docs/api/java/lang/UnsatisfiedLinkError.html) not even remotely related to the launcher at all.

**Comment by ghost** [comment]
May or may not be openJDK issue. Will re-open if not fixed for JDK8 within 4 months.
