### ISSUE TITLE
When I try to launch the TechnicLauncher i get this error

### ISSUE THREAD

**Issue by MrGreenTea** [TechnicPack/TechnicLauncher#753]
http://pastebin.com/exywrGGS

**Comment by matin007** [comment]
yeah

**Comment by GeekHokage** [comment]
also happens that to me

**Comment by Th3Tobi** [comment]
Also happened to me dont know what to do now :-1:

**Comment by Th3Tobi** [comment]
I also tried to reinstall Java 7 but also dont work...

**Comment by ggfgg** [comment]
this not works

**Comment by Dat-Ngu** [comment]
yea It happen to me toooooo

**Comment by JarekKusak** [comment]
help it happen to me too!!!
