### ISSUE TITLE
I can't launch tekkit classic

### ISSUE THREAD

**Issue by Snickers64** [TechnicPack/TechnicLauncher#754]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: Tekkit Classic
```

Stack Trace:
    Exception: RuntimeException
    Message: Minecraft not installed for this pack: InstalledPack{info=SolderPackInfo{name='tekkit', display_name='Tekkit Classic', url='http://www.technicpack.net/tekkit-classic', icon_md5='aefa89c377dcb217fdf99988f6e25b8f', logo_md5='b94c1ec5d65e7dac4c191c597f2e7cab', background_md5='41cf738eacf5db3cfd7e3eb505357c6e', recommended='3.1.2', latest='3.1.3', builds=[3.1.3, 3.1.2, 3.1.1, 3.1.0, 3.0.5, 3.0.3, 3.0.2, 3.0.1, 3.0.0], solder=net.technicpack.launchercore.restful.solder.Solder@4cd163cf}, name='tekkit', platform=false, build='recommended', directory='%MODPACKS%\tekkit'}
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:199)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:107)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:56)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:74)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_67 64 bit
    Total Memory: 182 MB
    Max Memory: 2699 MB
    Memory Free: 78 MB
    CPU Cores: 8

**Comment by Sooner123** [comment]
Have you tried playing in offline mode Turn your wifi off on your pc!!!!

**Comment by CannibalVox** [comment]
Hi, your launcher doesn't seem to be auto updating for some reason and is on a very old version. Please head over to http://TechnicPack.net to get the latest version.
