### ISSUE TITLE
Launcher crash error - instructions said to post here

### ISSUE THREAD

**Issue by DwellerBenthos** [TechnicPack/TechnicLauncher#755]
Here's the pastebin

http://pastebin.com/0ntBbnKS

Launcher ran fine the next time I tried it, so one-off glitch?

**Comment by ryanvade** [comment]
Same:
http://pastebin.com/1nCKCCWL

Arch Linux

**Comment by CannibalVox** [comment]
You guys are both on really old versions of the launcher- get the latest at http://www.technicpack.net/

**Comment by DwellerBenthos** [comment]
I'm pretty sure it was the current version when I posted that 3 months ago...... obviously no longer an issue at this point.

**Comment by CannibalVox** [comment]
Ah yeah, sorry, the necro threw me.
