### ISSUE TITLE
News and Updates

### ISSUE THREAD

**Issue by castlerush** [TechnicPack/TechnicLauncher#756]
How do i create my own news api to use for this launcher and how do i make my own launcher update api/portal to use with this client

**Comment by CannibalVox** [comment]
Stop this.

**Comment by castlerush** [comment]
i need to know the .json file name in http://www.technicpack.net/api/news thats all i need :(

**Comment by CannibalVox** [comment]
I know, and it's such a nonsensical question that it's really apparent that you can't be helped.  But more importantly, this is not an okay place to get help with writing a website!
