### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by zhangweijie0328** [TechnicPack/TechnicLauncher#757]
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439
    Selected Pack: null
Stack Trace:
    Exception: RuntimeException
    Message: Minecraft not installed for this pack: InstalledPack{info=SolderPackInfo{name='tekkitmain', display_name='Tekkit', url='http://www.technicpack.net/tekkit', icon_md5='1dd87c03268a7144411bb8cbe8bf7326', logo_md5='2f9625f8343cd1aaa35d3dd631ad64e1', background_md5='f39ae618809383451f6832e4d2a738fe', recommended='1.2.9e', latest='1.2.10c', builds=[1.0.2, 1.0.3, 1.0.5, 1.0.6, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.5b, 1.2.5c, 1.2.5d, 1.2.6, 1.2.6b, 1.2.7, 1.2.7b, 1.2.8, 1.2.8b, 1.2.8c, 1.2.8d, 1.2.8e, 1.2.9, 1.2.9b, 1.2.9c, 1.2.9d, 1.2.9e, 1.2.10, 1.2.10c], solder=net.technicpack.launchercore.restful.solder.Solder@3f5aa9}, name='tekkitmain', platform=false, build='recommended', directory='%MODPACKS%\tekkitmain'}
    Trace:
        net.technicpack.launchercore.launch.MinecraftLauncher.buildClassPath(MinecraftLauncher.java:199)
        net.technicpack.launchercore.launch.MinecraftLauncher.buildCommands(MinecraftLauncher.java:107)
        net.technicpack.launchercore.launch.MinecraftLauncher.launch(MinecraftLauncher.java:56)
        org.spoutcraft.launcher.InstallThread.run(InstallThread.java:74)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 58 MB
    Max Memory: 247 MB
    Memory Free: 28 MB
    CPU Cores: 4

**Comment by zhangweijie0328** [comment]
who help me ?thx

**Comment by csabaasztalos** [comment]
Sorry my tekkit classic donts not work....

**Comment by CannibalVox** [comment]
open your own issue with your own problems
