### ISSUE TITLE
Modpack Issue

### ISSUE THREAD

**Issue by TheMinecraftVault** [TechnicPack/TechnicLauncher#762]
Launcher Build: 439
    Selected Pack: null
Stack Trace:
    Exception: ExceptionInInitializerError
    Message: null
    Trace:
        javax.crypto.JceSecurityManager.<clinit>(JceSecurityManager.java:65)
        javax.crypto.Cipher.getConfiguredPermission(Cipher.java:2543)
        javax.crypto.Cipher.getMaxAllowedKeyLength(Cipher.java:2567)
        sun.security.ssl.CipherSuite$BulkCipher.isAvailable(Unknown Source)
        sun.security.ssl.CipherSuite$BulkCipher.isAvailable(Unknown Source)
        sun.security.ssl.CipherSuite.isAvailable(Unknown Source)
        sun.security.ssl.SSLContextImpl.getApplicableCipherSuiteList(Unknown Source)
        sun.security.ssl.SSLContextImpl.getDefaultCipherSuiteList(Unknown Source)
        sun.security.ssl.SSLSocketImpl.init(Unknown Source)
        sun.security.ssl.SSLSocketImpl.<init>(Unknown Source)
        sun.security.ssl.SSLSocketFactoryImpl.createSocket(Unknown Source)
        sun.net.www.protocol.https.HttpsClient.createSocket(Unknown Source)
        sun.net.NetworkClient.doConnect(Unknown Source)
        sun.net.www.http.HttpClient.openServer(Unknown Source)
        sun.net.www.http.HttpClient.openServer(Unknown Source)
        sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
        sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
        sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
        sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
        sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
        sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
        net.technicpack.launchercore.auth.AuthenticationService.postJson(AuthenticationService.java:65)
        net.technicpack.launchercore.auth.AuthenticationService.requestLogin(AuthenticationService.java:99)
        org.spoutcraft.launcher.skin.LoginFrame.attemptNewLogin(LoginFrame.java:417)
        org.spoutcraft.launcher.skin.LoginFrame.attemptLogin(LoginFrame.java:345)
        org.spoutcraft.launcher.skin.LoginFrame.actionPerformed(LoginFrame.java:468)
        javax.swing.JTextField.fireActionPerformed(Unknown Source)
        javax.swing.JTextField.postActionEvent(Unknown Source)
        javax.swing.JTextField$NotifyAction.actionPerformed(Unknown Source)
        javax.swing.SwingUtilities.notifyAction(Unknown Source)
        javax.swing.JComponent.processKeyBinding(Unknown Source)
        javax.swing.JComponent.processKeyBindings(Unknown Source)
        javax.swing.JComponent.processKeyEvent(Unknown Source)
        java.awt.Component.processEvent(Unknown Source)
        java.awt.Container.processEvent(Unknown Source)
        java.awt.Component.dispatchEventImpl(Unknown Source)
        java.awt.Container.dispatchEventImpl(Unknown Source)
        java.awt.Component.dispatchEvent(Unknown Source)
        java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
        java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
        java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
        java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
        java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
        java.awt.Component.dispatchEventImpl(Unknown Source)
        java.awt.Container.dispatchEventImpl(Unknown Source)
        java.awt.Window.dispatchEventImpl(Unknown Source)
        java.awt.Component.dispatchEvent(Unknown Source)
        java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        java.awt.EventQueue.access$400(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.awt.EventQueue$3.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue$4.run(Unknown Source)
        java.awt.EventQueue$4.run(Unknown Source)
        java.security.AccessController.doPrivileged(Native Method)
        java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        java.awt.EventQueue.dispatchEvent(Unknown Source)
        java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        java.awt.EventDispatchThread.run(Unknown Source)
        Caused By: (SecurityException)
            [Can not initialize cryptographic mechanism]
            javax.crypto.JceSecurityManager.<clinit>(JceSecurityManager.java:65)
            javax.crypto.Cipher.getConfiguredPermission(Cipher.java:2543)
            javax.crypto.Cipher.getMaxAllowedKeyLength(Cipher.java:2567)
            sun.security.ssl.CipherSuite$BulkCipher.isAvailable(Unknown Source)
            sun.security.ssl.CipherSuite$BulkCipher.isAvailable(Unknown Source)
            sun.security.ssl.CipherSuite.isAvailable(Unknown Source)
            sun.security.ssl.SSLContextImpl.getApplicableCipherSuiteList(Unknown Source)
            sun.security.ssl.SSLContextImpl.getDefaultCipherSuiteList(Unknown Source)
            sun.security.ssl.SSLSocketImpl.init(Unknown Source)
            sun.security.ssl.SSLSocketImpl.<init>(Unknown Source)
            sun.security.ssl.SSLSocketFactoryImpl.createSocket(Unknown Source)
            sun.net.www.protocol.https.HttpsClient.createSocket(Unknown Source)
            sun.net.NetworkClient.doConnect(Unknown Source)
            sun.net.www.http.HttpClient.openServer(Unknown Source)
            sun.net.www.http.HttpClient.openServer(Unknown Source)
            sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
            sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
            sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
            sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
            sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
            sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
            sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
            sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
            sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
            net.technicpack.launchercore.auth.AuthenticationService.postJson(AuthenticationService.java:65)
            net.technicpack.launchercore.auth.AuthenticationService.requestLogin(AuthenticationService.java:99)
            org.spoutcraft.launcher.skin.LoginFrame.attemptNewLogin(LoginFrame.java:417)
            org.spoutcraft.launcher.skin.LoginFrame.attemptLogin(LoginFrame.java:345)
            org.spoutcraft.launcher.skin.LoginFrame.actionPerformed(LoginFrame.java:468)
            javax.swing.JTextField.fireActionPerformed(Unknown Source)
            javax.swing.JTextField.postActionEvent(Unknown Source)
            javax.swing.JTextField$NotifyAction.actionPerformed(Unknown Source)
            javax.swing.SwingUtilities.notifyAction(Unknown Source)
            javax.swing.JComponent.processKeyBinding(Unknown Source)
            javax.swing.JComponent.processKeyBindings(Unknown Source)
            javax.swing.JComponent.processKeyEvent(Unknown Source)
            java.awt.Component.processEvent(Unknown Source)
            java.awt.Container.processEvent(Unknown Source)
            java.awt.Component.dispatchEventImpl(Unknown Source)
            java.awt.Container.dispatchEventImpl(Unknown Source)
            java.awt.Component.dispatchEvent(Unknown Source)
            java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
            java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
            java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
            java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
            java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
            java.awt.Component.dispatchEventImpl(Unknown Source)
            java.awt.Container.dispatchEventImpl(Unknown Source)
            java.awt.Window.dispatchEventImpl(Unknown Source)
            java.awt.Component.dispatchEvent(Unknown Source)
            java.awt.EventQueue.dispatchEventImpl(Unknown Source)
            java.awt.EventQueue.access$400(Unknown Source)
            java.awt.EventQueue$3.run(Unknown Source)
            java.awt.EventQueue$3.run(Unknown Source)
            java.security.AccessController.doPrivileged(Native Method)
            java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
            java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
            java.awt.EventQueue$4.run(Unknown Source)
            java.awt.EventQueue$4.run(Unknown Source)
            java.security.AccessController.doPrivileged(Native Method)
            java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
            java.awt.EventQueue.dispatchEvent(Unknown Source)
            java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
            java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
            java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
            java.awt.EventDispatchThread.pumpEvents(Unknown Source)
            java.awt.EventDispatchThread.pumpEvents(Unknown Source)
            java.awt.EventDispatchThread.run(Unknown Source)
            Caused By: (SecurityException)
                [The jurisdiction policy files are not signed by a trusted signer!]
                javax.crypto.JceSecurityManager.<clinit>(JceSecurityManager.java:65)
                javax.crypto.Cipher.getConfiguredPermission(Cipher.java:2543)
                javax.crypto.Cipher.getMaxAllowedKeyLength(Cipher.java:2567)
                sun.security.ssl.CipherSuite$BulkCipher.isAvailable(Unknown Source)
                sun.security.ssl.CipherSuite$BulkCipher.isAvailable(Unknown Source)
                sun.security.ssl.CipherSuite.isAvailable(Unknown Source)
                sun.security.ssl.SSLContextImpl.getApplicableCipherSuiteList(Unknown Source)
                sun.security.ssl.SSLContextImpl.getDefaultCipherSuiteList(Unknown Source)
                sun.security.ssl.SSLSocketImpl.init(Unknown Source)
                sun.security.ssl.SSLSocketImpl.<init>(Unknown Source)
                sun.security.ssl.SSLSocketFactoryImpl.createSocket(Unknown Source)
                sun.net.www.protocol.https.HttpsClient.createSocket(Unknown Source)
                sun.net.NetworkClient.doConnect(Unknown Source)
                sun.net.www.http.HttpClient.openServer(Unknown Source)
                sun.net.www.http.HttpClient.openServer(Unknown Source)
                sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
                sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
                sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
                sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
                sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
                sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
                sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
                sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
                sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
                net.technicpack.launchercore.auth.AuthenticationService.postJson(AuthenticationService.java:65)
                net.technicpack.launchercore.auth.AuthenticationService.requestLogin(AuthenticationService.java:99)
                org.spoutcraft.launcher.skin.LoginFrame.attemptNewLogin(LoginFrame.java:417)
                org.spoutcraft.launcher.skin.LoginFrame.attemptLogin(LoginFrame.java:345)
                org.spoutcraft.launcher.skin.LoginFrame.actionPerformed(LoginFrame.java:468)
                javax.swing.JTextField.fireActionPerformed(Unknown Source)
                javax.swing.JTextField.postActionEvent(Unknown Source)
                javax.swing.JTextField$NotifyAction.actionPerformed(Unknown Source)
                javax.swing.SwingUtilities.notifyAction(Unknown Source)
                javax.swing.JComponent.processKeyBinding(Unknown Source)
                javax.swing.JComponent.processKeyBindings(Unknown Source)
                javax.swing.JComponent.processKeyEvent(Unknown Source)
                java.awt.Component.processEvent(Unknown Source)
                java.awt.Container.processEvent(Unknown Source)
                java.awt.Component.dispatchEventImpl(Unknown Source)
                java.awt.Container.dispatchEventImpl(Unknown Source)
                java.awt.Component.dispatchEvent(Unknown Source)
                java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
                java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
                java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
                java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
                java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
                java.awt.Component.dispatchEventImpl(Unknown Source)
                java.awt.Container.dispatchEventImpl(Unknown Source)
                java.awt.Window.dispatchEventImpl(Unknown Source)
                java.awt.Component.dispatchEvent(Unknown Source)
                java.awt.EventQueue.dispatchEventImpl(Unknown Source)
                java.awt.EventQueue.access$400(Unknown Source)
                java.awt.EventQueue$3.run(Unknown Source)
                java.awt.EventQueue$3.run(Unknown Source)
                java.security.AccessController.doPrivileged(Native Method)
                java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
                java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
                java.awt.EventQueue$4.run(Unknown Source)
                java.awt.EventQueue$4.run(Unknown Source)
                java.security.AccessController.doPrivileged(Native Method)
                java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
                java.awt.EventQueue.dispatchEvent(Unknown Source)
                java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
                java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
                java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
                java.awt.EventDispatchThread.pumpEvents(Unknown Source)
                java.awt.EventDispatchThread.pumpEvents(Unknown Source)
                java.awt.EventDispatchThread.run(Unknown Source)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: amd64
    Java version: 1.8.0_25 64 bit
    Total Memory: 243 MB
    Max Memory: 3611 MB
    Memory Free: 198 MB
    CPU Cores: 8

**Comment by MyNickIsBetter** [comment]
Please uninstall the Java 8 and download and install the Java 7 update 55 because the Java 8 is giving bug in Minecraft and forge mod loader. If you prefer to search for '' incompatibility with Java 8 in Forge Mod Loader '', so you will have to download .jar files to be able to play Minecraft with their ModPacks. Hope this helps :smiley:

**Comment by CannibalVox** [comment]
Launcher version is now 4.256.
