### ISSUE TITLE
Help!! My technic crashed!!

### ISSUE THREAD

**Issue by Mahgm** [TechnicPack/TechnicLauncher#770]
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439
    Selected Pack: null
Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: amd64
    Java version: 1.8.0_11 64 bit
    Total Memory: 125 MB
    Max Memory: 1340 MB
    Memory Free: 87 MB
    CPU Cores: 4

**Comment by minoljeukt** [comment]
I got the same thing

( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
Launcher Build: 439
Selected Pack: null
Stack Trace:
Exception: NullPointerException
Message: null
Trace:
org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
Operating System: Windows 7
Operating System Version: 6.1
Operating System Architecture: amd64
Java version: 1.8.0_25 64 bit
Total Memory: 123 MB
Max Memory: 1808 MB
Memory Free: 93 MB
CPU Cores: 4

WTF am i supposed to do with this
first my attack of the b-team won't load and now this... this is f*cked up

**Comment by DF1229** [comment]
calm down... just retry, works fine for me now

**Comment by Mahgm** [comment]
I already tried open but still the same problem

**Comment by minoljeukt** [comment]
well i already tried it 15 times 
and still doesn't work + i get that stupid message ^^^

**Comment by Mahgm** [comment]
Now starts but all my mods have the tag offline Y.Y at least it's opening something

**Comment by CannibalVox** [comment]
We're in the middle of a rollout- in an hour the new launcher and platform will be live but the servers are going through maintenance atm and stuff might not work.

**Comment by minoljeukt** [comment]
so actually over an hour everything will be fine?

**Comment by Mahgm** [comment]
I hope so!

**Comment by minoljeukt** [comment]
same D:
