### ISSUE TITLE
Technic issues

### ISSUE THREAD

**Issue by Cakenation101** [TechnicPack/TechnicLauncher#771]
Please help this popped up when I opened technic 

PASTEBIN |  #1 paste tool since 2002    create new paste
tools
api
archive
faq

PASTEBIN     

 create new paste      trending pastes 
sign up
login
my alerts
my settings
my profile

 This week only. Pastebin PRO Accounts Christmas Special! Don't miss out!Want more features on Pastebin? Sign Up, it's FREE!

Public Pastes

ser_1419517633591
12 sec ago

ser_1419517637805
1 sec ago

ser_1419517622042
20 sec ago

ser_1419517630999
15 sec ago

ser_1419517510406
30 sec ago

ser_1419517611028
30 sec ago

Untitled
29 sec ago

ser_1419517615411
25 sec ago

0

0

Guest   

ser_1419517633591 

By: a guest on Dec 25th, 2014  |  syntax: None  |  size: 0.72 KB  |  views: 0  |  expires: Never

download  |  raw  |  embed  |  report abuse  |  print

1.Technic Launcher Error Report:

2.( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
1.    Launcher Build: 439
3.    Selected Pack: null

6.Stack Trace:
1.    Exception: NullPointerException
2.    Message: null
3.    Trace:
4. ```
      org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
   ```
5. ```
      org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
   ```
6. ```
      org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)
   ```

14.System Information:
1.    Operating System: Windows 8
2.    Operating System Version: 6.2
3.    Operating System Architecture: x86
4.    Java version: 1.7.0_51 32 bit
5.    Total Memory: 56 MB
6.    Max Memory: 247 MB
7.    Memory Free: 24 MB
8.    CPU Cores: 4

clone this paste RAW Paste Data 

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: null
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: x86
    Java version: 1.7.0_51 32 bit
    Total Memory: 56 MB
    Max Memory: 247 MB
    Memory Free: 24 MB
    CPU Cores: 4 

Pastebin.com Tools & Applications

iPhone/iPad Windows Firefox Chrome WebOS Android Mac Opera Click.to UNIX WinPhone 

create new paste  |  api  |  trends  |  syntax languages  |  faq  |  tools  |  privacy  |  cookies  |  contact  |  dmca  |  advertise on pastebin  |  go pro 
Follow us: pastebin on facebook  |  pastebin on twitter  |  pastebin in the news 
Dedicated Server Hosting by Steadfast
Pastebin v3.11 rendered in: 0.005 seconds 

  Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: null
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: x86
    Java version: 1.7.0_51 32 bit
    Total Memory: 56 MB
    Max Memory: 247 MB
    Memory Free: 24 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
We're in the middle of a rollout- in an hour the new launcher and platform will be live but the servers are going through maintenance atm and stuff might not work.
