### ISSUE TITLE
TechnicLauncher Error Report (25-12-2014)

### ISSUE THREAD

**Issue by DF1229** [TechnicPack/TechnicLauncher#773]
http://pastebin.com/Rw11e5aX

**Comment by TopiCube** [comment]
Have the same problem when i openned the launcher 2-3 minutes ago D:

**Comment by ProfessorMaple** [comment]
Pretty sure I'm having the same problem too

**Comment by CannibalVox** [comment]
We're in the middle of a rollout- in an hour the new launcher and platform will be live but the servers are going through maintenance atm and stuff might not work.
