### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by klspiegs** [TechnicPack/TechnicLauncher#775]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: Attack of the B-Team
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.10.1
    Operating System Architecture: x86_64
    Java version: 1.6.0_65 64 bit
    Total Memory: 81 MB
    Max Memory: 123 MB
    Memory Free: 53 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
We're in the middle of a rollout- in an hour the new launcher and platform will be live but the servers are going through maintenance atm and stuff might not work.
