### ISSUE TITLE
Tekkit launcher won't start.

### ISSUE THREAD

**Issue by UmbraDator** [TechnicPack/TechnicLauncher#777]
Technic Launcher Error Report:

 Launcher Build: 439

```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: amd64
    Java version: 1.7.0_72 64 bit
    Total Memory: 367 MB
    Max Memory: 5456 MB
    Memory Free: 316 MB
    CPU Cores: 4

No idea what to do.

**Comment by CannibalVox** [comment]
We're in the middle of a rollout- in an hour the new launcher and platform will be live but the servers are going through maintenance atm and stuff might not work.
