### ISSUE TITLE
Launcher error

### ISSUE THREAD

**Issue by MaPaFreSch** [TechnicPack/TechnicLauncher#780]
```
Launcher Build: 439
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_25 64 bit
    Total Memory: 154 MB
    Max Memory: 1816 MB
    Memory Free: 65 MB
    CPU Cores: 8

**Comment by CannibalVox** [comment]
We're in the middle of a rollout- in an hour the new launcher and platform will be live but the servers are going through maintenance atm and stuff might not work.
