### ISSUE TITLE
Cant open Launcher 

### ISSUE THREAD

**Issue by ryannbell** [TechnicPack/TechnicLauncher#782]
Launcher Build: 439
    Selected Pack: null
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 54 MB
    Max Memory: 247 MB
    Memory Free: 12 MB
    CPU Cores: 8

**Comment by CannibalVox** [comment]
We're in the middle of a rollout- in an hour the new launcher and platform will be live but the servers are going through maintenance atm and stuff might not work.

**Comment by OliveOliveOlive** [comment]
why cant i get my vanilla minecraft to open? everything else works just fine. i dont get an error pop up or anything, it just acts like its gonna load then puts me back at the lauch screen.

**Comment by CannibalVox** [comment]
There's an error in the console: open it by going to launcher options & checking the box to show the console.  Also, please open your own issue instead of commenting on an issue that's already been closed.

**Comment by supercat111** [comment]
i have a same problem, plz help
