### ISSUE TITLE
Technic Launcher Issue

### ISSUE THREAD

**Issue by Unicorps** [TechnicPack/TechnicLauncher#783]
I decided to play some games via Technic Launcher, but when I launched it, I believe it crashed or it did something I'm unfamiliar with. I have the report via link: http://pastebin.com/eUK5BP2L - Hopefully we can get this solved. Please, and thank you for your time.

**Comment by CannibalVox** [comment]
We're in the middle of a rollout- in an hour the new launcher and platform will be live but the servers are going through maintenance atm and stuff might not work.
