### ISSUE TITLE
Technic Launcher Issues 

### ISSUE THREAD

**Issue by Minecraps999** [TechnicPack/TechnicLauncher#785]
I opened up tekkit after crashing the other day but then it wouldnt load up the minecraft thing... aka it stayed on the launcher (nothing happened when I clicked play). I have the paste bin link right here:
http://pastebin.com/MAmRAFRv
Thanks,
            Minecraps999

**Comment by CannibalVox** [comment]
We're in the middle of a rollout- in an hour the new launcher and platform will be live but the servers are going through maintenance atm and stuff might not work.

**Comment by Minecraps999** [comment]
Okay thank you :3
