### ISSUE TITLE
Technic launcher not starting

### ISSUE THREAD

**Issue by Petrock26** [TechnicPack/TechnicLauncher#787]
```
Launcher Build: 439
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows XP
    Operating System Version: 5.1
    Operating System Architecture: x86
    Java version: 1.7.0_72 32 bit
    Total Memory: 46 MB
    Max Memory: 247 MB
    Memory Free: 26 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
We're in the middle of a rollout- in an hour the new launcher and platform will be live but the servers are going through maintenance atm and stuff might not work.
