### ISSUE TITLE
Launcher won't start up

### ISSUE THREAD

**Issue by deluzion** [TechnicPack/TechnicLauncher#788]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_67 64 bit
    Total Memory: 121 MB
    Max Memory: 1799 MB
    Memory Free: 91 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
We're in the middle of a rollout- in an hour the new launcher and platform will be live but the servers are going through maintenance atm and stuff might not work.
