### ISSUE TITLE
The Launcher Crashed before i even logged in

### ISSUE THREAD

**Issue by MegafanGaming** [TechnicPack/TechnicLauncher#789]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 36 MB
    Max Memory: 247 MB
    Memory Free: 9 MB
    CPU Cores: 8

Why is this happening

**Comment by CannibalVox** [comment]
We're in the middle of a rollout- in an hour the new launcher and platform will be live but the servers are going through maintenance atm and stuff might not work.

**Comment by MegafanGaming** [comment]
okay thanks i just got a new computer and i just want it to start working
so all my apps are the same
