### ISSUE TITLE
Technic lanucher does not run

### ISSUE THREAD

**Issue by GyulaMasa** [TechnicPack/TechnicLauncher#790]
Hi I have the following error message when I want to start the technic launcher:
http://pastebin.com/yZujaFvh
Previously Java 8 used to cause problems, but I downgraded to 7.72 and the launcher worked.
The strange thing is, that choosing "run as administrator" from the roll down menu helps starting it.
And after this it works normally too...

**Comment by CannibalVox** [comment]
We're in the middle of a rollout- in an hour the new launcher and platform will be live but the servers are going through maintenance atm and stuff might not work.

**Comment by GyulaMasa** [comment]
THX!
Now it works.
