### ISSUE TITLE
Help launcher wont open 3:

### ISSUE THREAD

**Issue by Minecraps999** [TechnicPack/TechnicLauncher#792]
Launcher Build: 439

```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: amd64
    Java version: 1.8.0_11 64 bit
    Total Memory: 121 MB
    Max Memory: 1792 MB
    Memory Free: 94 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
We're in the middle of a rollout- in an hour the new launcher and platform will be live but the servers are going through maintenance atm and stuff might not work.

**Comment by Minecraps999** [comment]
You said that an hour ago...

**Comment by CannibalVox** [comment]
I know, things are taking longer than we expected.  We've nearly got the website stable, and the new launcher will go live shortly after that.

**Comment by Minecraps999** [comment]
Okay thanks :3
