### ISSUE TITLE
Technic Launcher won't let me play

### ISSUE THREAD

**Issue by imniro** [TechnicPack/TechnicLauncher#796]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.8.0_25 64 bit
    Total Memory: 150 MB
    Max Memory: 1751 MB
    Memory Free: 78 MB
    CPU Cores: 4

**Comment by BatmanPlays** [comment]
Same thing, 

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: TerraFirmaCraft
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_60 64 bit
    Total Memory: 174 MB
    Max Memory: 1250 MB
    Memory Free: 139 MB
    CPU Cores: 4

**Comment by RebornAshHole** [comment]
Same,

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: amd64
    Java version: 1.7.0_72 64 bit
    Total Memory: 156 MB
    Max Memory: 1817 MB
    Memory Free: 69 MB
    CPU Cores: 8

**Comment by imniro** [comment]
Yeah I looked around the web and it seems a lot of people have the same if not similar problems, Maybe we will have to wait until technic releases an update or bug fix for the launcher. Unless someone knows how to fix this problem. If so please let us know. We are dying to play our Minecraft.

**Comment by kaito1121** [comment]
I habe also similar problem,  please help and let me know how can I play my MINECRAFT again.

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: Hexxit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 58 MB
    Max Memory: 247 MB
    Memory Free: 10 MB
    CPU Cores: 4

**Comment by ck17350** [comment]
The following changes resolved the issue for me after getting the same error.
I opened up the java configuration tool and went to the  Temporary Internet Files settings under the general tab.  Click the button at the bottom that says "Delete Files" and make sure to check "Installed applications and applets".  **WARNING** while these are temp files and should be replaced when an application is launched, please be aware that you are removing files.  Don't to do this unless you are confident the data being removed is safe to do so.

**Comment by imniro** [comment]
Thanks but that didn't work for me. :/ I deleted the whole thing and tried to re-download it but their website is also down which totally sucks because re-downloading it probably won't fix the problem anyway..

**Comment by rugabi94** [comment]
Same here, any solution ?
It's not working, that you wrote @ck17350

**Comment by DiovaneKelvin** [comment]
Sorry my bad English. North American'm not.
  But I found a solution for me. I open the technic and before giving the error I click on any mod quickly. When it will open a mod of an error, just ignore and click again the play.

For me it worked.

**Comment by rugabi94** [comment]
So you open the launcher before it gives the error you clicked the play button and worked. I tried this but not works for me. You cant ignore the error, because you can click only the error.

**Comment by DiovaneKelvin** [comment]
I also excludes the java files, as ck17350 spoke just above.

**Comment by Alphagammabeta** [comment]
you are the guy @jerrylarryberry

**Comment by Duartebm** [comment]
Love you @jerrylarryberry

**Comment by CannibalVox** [comment]
This is fixed now.

**Comment by McMagicorw** [comment]
CAra :( vc é muito foda bela
 JerryLarryBerry

**Comment by tslimanyak** [comment]
Hi guys
I found a certain Solution for this problem.
First download the folder(link is at final of my words) and try to enter game. you can write asdasd for email and password.
If you had a problem it means you have a 64 bit PC you should remove Java and install 32 bit java believe me it works.


here the folder: https://drive.google.com/file/d/0B21HIUjJ3sXSa0QwVU5odktyUFE/view

**Comment by mateo120** [comment]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by failsave255** [comment]
Go to Windows Firewall Advanced Settings
Create new outbound rule 
Choose your Technic Launcher exe 
Block tcp port 80
Enjoy Minecraft
