### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by ojoman** [TechnicPack/TechnicLauncher#797]
I opened it up, got this:

 Selected Pack: null
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(ArrayList.java:635)
        java.util.ArrayList.get(ArrayList.java:411)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.10.1
    Operating System Architecture: x86_64
    Java version: 1.7.0_67 64 bit
    Total Memory: 123 MB
    Max Memory: 1820 MB
    Memory Free: 62 MB
    CPU Cores: 4

Didn't click anything, came up on open.

never happened before. ;-;

**Comment by CannibalVox** [comment]
This is fixed now.
