### ISSUE TITLE
Unexpected Error! - Windows 7

### ISSUE THREAD

**Issue by batmap** [TechnicPack/TechnicLauncher#799]
Though the error window popped up, minecraft v1.6.4 still starts and works as normal. Of note, last night will playing minecraft the server was very laggy and I stopped play after multiple disconnects and finally a death after a disc.

Below is the info from the error popup window:

( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439
    Selected Pack: null
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_71 64 bit
    Total Memory: 156 MB
    Max Memory: 1820 MB
    Memory Free: 58 MB
    CPU Cores: 6

**Comment by CannibalVox** [comment]
This is fixed now.
