### ISSUE TITLE
Technic launcher error

### ISSUE THREAD

**Issue by fireychickengod** [TechnicPack/TechnicLauncher#800]
Launcher Build: 439

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.8.0_25 64 bit
    Total Memory: 123 MB
    Max Memory: 1820 MB
    Memory Free: 81 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
This is fixed now.
