### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by djm78** [TechnicPack/TechnicLauncher#801]
hnic Launcher Error Report:

2.( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
1.    Launcher Build: 439
3.    Selected Pack: Attack of the B-Team

6.Stack Trace:
1.    Exception: IndexOutOfBoundsException
2.    Message: Index: 0, Size: 0
3.    Trace:
4. ```
      java.util.ArrayList.rangeCheck(Unknown Source)
   ```
5. ```
      java.util.ArrayList.get(Unknown Source)
   ```
6. ```
      org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
   ```
7. ```
      org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
   ```
8. ```
      org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)
   ```

16.System Information:
1.    Operating System: Windows 8.1
2.    Operating System Version: 6.3
3.    Operating System Architecture: x86
4.    Java version: 1.8.0_25 32 bit
5.    Total Memory: 57 MB
6.    Max Memory: 247 MB
7.    Memory Free: 12 MB
8.    CPU Cores: 8

**Comment by CannibalVox** [comment]
This is fixed now.
