### ISSUE TITLE
New launcher's icon stays on screen so i cant play

### ISSUE THREAD

**Issue by EmoVampiressRBLX** [TechnicPack/TechnicLauncher#803]
No matter what screen I go to, the icon stays in the middle of it and it leaves the screen only when I close the launcher and when i play tekkit its in the middle of the screen so it's hard to play...

![](http://i.imgur.com/YqYjVZc.png)

How do I get rid of the icon?

**Comment by EmoVampiressRBLX** [comment]
Help?

**Comment by Jomrj** [comment]
I think that're all in trouble in the launcher, some not take another prescisam of report, talves tomorrow shouldnt take, or at least think ...: \

**Comment by Jomrj** [comment]
sorry if not understand, do not speak English, but Portuguese, but try the google translate

**Comment by CannibalVox** [comment]
This was fixed shortly after it was reported, I apologize for now being more diligent about responding.
