### ISSUE TITLE
Technic Launcher Issue

### ISSUE THREAD

**Issue by Arceaus98** [TechnicPack/TechnicLauncher#807]
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439
    Selected Pack: null
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_67 32 bit
    Total Memory: 57 MB
    Max Memory: 247 MB
    Memory Free: 19 MB
    CPU Cores: 8

**Comment by CannibalVox** [comment]
This is fixed now.
