### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ProWarrior** [TechnicPack/TechnicLauncher#812]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(ArrayList.java:635)
        java.util.ArrayList.get(ArrayList.java:411)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Linux
    Operating System Version: 3.13.0-37-generic
    Operating System Architecture: amd64
    Java version: 1.7.0_65 64 bit
    Total Memory: 73 MB
    Max Memory: 853 MB
    Memory Free: 31 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
This is fixed now.
