### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ghost** [TechnicPack/TechnicLauncher#815]
http://pastebin.com/jwQ2YZCy
Err so... was told to put this here?

**Comment by MyNickIsBetter** [comment]
My Technic Launcher  have same problem. The solution is wait :/

**Comment by CannibalVox** [comment]
This is fixed now.

**Comment by MyNickIsBetter** [comment]
@CanibbalVox the problem is fixed? What? My Technic Launcher is not fixed, the error continues

**Comment by CannibalVox** [comment]
Then you should buy minecraft.
