### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by dixiebhm** [TechnicPack/TechnicLauncher#816]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: amd64
    Java version: 1.7.0_71 64 bit
    Total Memory: 155 MB
    Max Memory: 1813 MB
    Memory Free: 92 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
