### ISSUE TITLE
Attack of the B-Team, Launcher Error Report

### ISSUE THREAD

**Issue by BennyCayey** [TechnicPack/TechnicLauncher#818]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: Attack of the B-Team
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_72 64 bit
    Total Memory: 127 MB
    Max Memory: 1340 MB
    Memory Free: 72 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
This is fixed now.
