### ISSUE TITLE
deu erro no meu escola de bruxos

### ISSUE THREAD

**Issue by Zetta15** [TechnicPack/TechnicLauncher#819]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Minecraft A Serie
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_71 64 bit
    Total Memory: 114 MB
    Max Memory: 455 MB
    Memory Free: 30 MB
    CPU Cores: 4

**Comment by MyNickIsBetter** [comment]
O meu deu o mesmo problema. Aconselho que espere os responsáveis consertarem esse erro e não faça alterações no seu sistema, como por exemplo: atualizações do java, adobe flash player e etc

My Technic launcher has the same problem. I advise you to wait those responsible mend this error and make no changes to your system, such as: java updates, adobe flash player and etc.

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
