### ISSUE TITLE
Launcher fails to download/launch latest Voltz

### ISSUE THREAD

**Issue by Altair357** [TechnicPack/TechnicLauncher#82]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 188

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft!
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.7.4
    Operating System Architecture: x86_64
    Java version: 1.6.0_33 64 bit
    Total Memory: 81 MB
    Max Memory: 3055 MB
    Memory Free: 51 MB
    CPU Cores: 8

**Comment by luetzj** [comment]
I have the same problem, but I'm on windows 8.

**Comment by Salynne** [comment]
This is an issue with the latest Voltz. Try selecting a different build in the options for now, it's being looked into.

**Comment by sct** [comment]
This should be resolved now. Enjoy!
