### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by zackxd** [TechnicPack/TechnicLauncher#820]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: amd64
    Java version: 1.7.0_71 64 bit
    Total Memory: 88 MB
    Max Memory: 784 MB
    Memory Free: 43 MB
    CPU Cores: 4

**Comment by NikolasPlhal** [comment]
Jsem Czech prosim pomozte mi mam neocekavanou chybu v technik launchleru

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
