### ISSUE TITLE
Technic Launcher Crash Report

### ISSUE THREAD

**Issue by robie509** [TechnicPack/TechnicLauncher#821]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_72 64 bit
    Total Memory: 123 MB
    Max Memory: 901 MB
    Memory Free: 71 MB
    CPU Cores: 4

**Comment by robie509** [comment]
Issue solved. :)

**Comment by MyNickIsBetter** [comment]
@robie509 i have this issue, not solved :/
