### ISSUE TITLE
Error, error :(

### ISSUE THREAD

**Issue by pablo59** [TechnicPack/TechnicLauncher#825]
Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: x86
    Java version: 1.7.0_71 32 bit
    Total Memory: 52 MB
    Max Memory: 247 MB
    Memory Free: 27 MB
    CPU Cores: 4

**Comment by rugabi94** [comment]
Man, as you see a lot of people having this problem and you opens another topic....

**Comment by MyNickIsBetter** [comment]
@Rugabi94 i have this problem, the solution is wait the staff fix that problem

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
