### ISSUE TITLE
Launcher Crashes At Login

### ISSUE THREAD

**Issue by milesrotaru** [TechnicPack/TechnicLauncher#83]
The launcher crashes with a Java exception message as soon as I click the login button.

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 191

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:118)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_15 64 bit
    Total Memory: 124 MB
    Max Memory: 910 MB
    Memory Free: 70 MB
    CPU Cores: 8

**Comment by sct** [comment]
This is an issue with the latest Tekkit Lite build. Will be resolved soon.

**Comment by sct** [comment]
This has been resolved.
