### ISSUE TITLE
Evil bug on my Technic, what i need to do?

### ISSUE THREAD

**Issue by ArthurKotaki** [TechnicPack/TechnicLauncher#831]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_09 32 bit
    Total Memory: 44 MB
    Max Memory: 247 MB
    Memory Free: 17 MB
    CPU Cores: 2

**Comment by ArthurKotaki** [comment]
Please Help Me!!

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
