### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by EthanAustin** [TechnicPack/TechnicLauncher#835]
When opening the techniclauncher this error came up, and force shut down the launcher.
I've never had this before.
Thanks Ethan,

http://pastebin.com/1LNvtubQ

**Comment by tijntjuh** [comment]
I have the same problem and I really want to know how I can solve this. Please people, help!

**Comment by CannibalVox** [comment]
This is fixed now (for those who haven't pirated minecraft)
