### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by andreighinea1** [TechnicPack/TechnicLauncher#837]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by tijntjuh** [comment]
I think I have the same problem. How can we solve this?

**Comment by MyNickIsBetter** [comment]
I have the same problem, but my Minecraft is pirate(no-premium)

**Comment by andreighinea1** [comment]
I don't know, I post this on this site because I don't know how to solve this
And I am still waiting for an answer

**Comment by marco-chho** [comment]
I have the same problem T-T

**Comment by CannibalVox** [comment]
Don't pirate minecraft.

**Comment by andreighinea1** [comment]
you need a new version

2014-12-27 10:48 GMT+02:00 Cannibal Vox notifications@github.com:

**Comment by tijntjuh** [comment]
I have cracked too. I donwloaded another cracked launcher and the problem was solved.

**Comment by tijntjuh** [comment]
By the way "cracked" is the same as what you call "pirate"
