### ISSUE TITLE
technic launcher 4.0 error (not the common error)

### ISSUE THREAD

**Issue by timakro** [TechnicPack/TechnicLauncher#838]
I'm really angry about your new design. My technic launcher just updatet without asking me. I saw no way to get the old version of technic launcher back. So I installed the new version via the portable install method. Even if i close the install window i get an error! It feels like there was tested NOTHING. But here's the log i get when running the technic launcher installed using the portable install method.

```
[B#191] 2014/12/26 16:34:08 [INFO] Console Mode Activated
[B#191] 2014/12/26 16:34:08 [INFO] Launching command: 'java -Xmx256m -Djava.net.preferIPv4Stack=true -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -cp /home/tim/Desktop/Minecraft/Technic/TechnicLauncher.jar net.technicpack.launcher.LauncherMain '
[B#191] 2014/12/26 16:34:09 [INFO] Console Mode Activated
[B#191] 2014/12/26 16:34:14 [SCHWERWIEGEND] java.lang.IllegalArgumentException: The window must use a translucency-compatible graphics configuration
[B#191] 2014/12/26 16:34:14 [SCHWERWIEGEND]     at java.awt.Window.setOpaque(Window.java:3421)
[B#191] 2014/12/26 16:34:14 [SCHWERWIEGEND]     at java.awt.Window$1.setOpaque(Window.java:388)
[B#191] 2014/12/26 16:34:14 [SCHWERWIEGEND]     at com.sun.awt.AWTUtilities.setWindowOpaque(AWTUtilities.java:360)
[B#191] 2014/12/26 16:34:14 [SCHWERWIEGEND]     at net.technicpack.ui.controls.installation.SplashScreen.<init>(SplashScreen.java:82)
[B#191] 2014/12/26 16:34:14 [SCHWERWIEGEND]     at net.technicpack.launcher.LauncherMain.startLauncher(LauncherMain.java:207)
[B#191] 2014/12/26 16:34:14 [SCHWERWIEGEND]     at net.technicpack.launcher.LauncherMain.updateAndRelaunch(LauncherMain.java:307)
[B#191] 2014/12/26 16:34:14 [SCHWERWIEGEND]     at net.technicpack.launcher.LauncherMain.main(LauncherMain.java:150)
[B#191] 2014/12/26 16:34:14 [SCHWERWIEGEND] Unhandled Exception in Thread[main,5,main]
java.lang.IllegalArgumentException: The window must use a translucency-compatible graphics configuration
    at java.awt.Window.setOpaque(Window.java:3421)
    at java.awt.Window$1.setOpaque(Window.java:388)
    at com.sun.awt.AWTUtilities.setWindowOpaque(AWTUtilities.java:360)
    at net.technicpack.ui.controls.installation.SplashScreen.<init>(SplashScreen.java:82)
    at net.technicpack.launcher.LauncherMain.startLauncher(LauncherMain.java:207)
    at net.technicpack.launcher.LauncherMain.updateAndRelaunch(LauncherMain.java:307)
    at net.technicpack.launcher.LauncherMain.main(LauncherMain.java:150)
```

I'm on Linux Debian and I'm running the techic launcher 4.0. I tried to register at your forum to report this bug but I got no activation email. Then I tried to register at http://www.technicpack.net but when i clicked the link in the activation email and logged in it still said I need to click the link in the activation email. Also the websites are offline every few minutes which makes it really hard to register. I tried to register on the website and on the forum with the accounts "bschutim" and "bschutim2". Now they are both unuseable because there is no way to get a activation email with a working link. Finally I found your github repo to report this bug. I'm really disappointed about the technic launcher now. I would mainly like to get the old launcher back. Ofcourse I would use the new launcher when all bugs are fixed.

**Comment by timakro** [comment]
ah i understand, its fixed for non-cracked players. but i have a different issue and i have bought minecraft. ill reopen this issue.

**Comment by CannibalVox** [comment]
You are correct!  I've deleted the non-germane comments and re-opened this issue.

**Comment by bezaban** [comment]
I'm getting this on Debian 7.7, openjdk 1.6.0._33.
Switching to openjdk 1.7.0_65 (currently provided by openjdk-7-jre) fixes it for me.

**Comment by CannibalVox** [comment]
I'd even switch to 1.8, if not now, maybe in a month, if you can.  We're cleaning up the number of packs on the launcher that can't handle java 8 now that there's several solutions available for pack authors.

Our linux testing was confined to ubunutu/unity with the latest available openjdk and I'd honestly prefer not to support anything else too actively, because you start getting into factorial explosion in terms of what works/doesn't work on different shells/flavors/everythings.
