### ISSUE TITLE
Can't load certain mods with latest verion of Voltz

### ISSUE THREAD

**Issue by Everstang** [TechnicPack/TechnicLauncher#84]
## Launcher Build: 191

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft!
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.6.8
    Operating System Architecture: x86_64
    Java version: 1.6.0_39 64 bit
    Total Memory: 81 MB
    Max Memory: 1019 MB
    Memory Free: 41 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
Duplicate issue #82
