### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by tijntjuh** [TechnicPack/TechnicLauncher#842]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 38 MB
    Max Memory: 247 MB
    Memory Free: 10 MB
    CPU Cores: 2

**Comment by MyNickIsBetter** [comment]
I have this problem

**Comment by tijntjuh** [comment]
Yes but how can we solve this? @MyNickIsBetter

**Comment by GenPage** [comment]
Hey guys, I would suggest getting the new launcher, located here: http://technicpack.net/download

As a heads-up we are dealing with a massive amount of traffic, so please be patient.

**Comment by MyNickIsBetter** [comment]
@GenPage Hey guy, this is only for users who have the original Minecraft

**Comment by MyNickIsBetter** [comment]
@tijntjuh the solution is wait for new posts

**Comment by Aleksa234** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa sta kako aaaaaaaaaaa molim aaaaaaa

**Comment by CratorCZ** [comment]
I have same probllem, but i don't have original minecraft. What should I do? :) Thanks for feedback :+1:

**Comment by daten-shi** [comment]
but will it be long before they fix this error ??

**Comment by MyNickIsBetter** [comment]
@daten-shi play other game waiting for the fix. Feedback :+1:

**Comment by daten-shi** [comment]
@MyNickIsBetter and right and the way but hopefully come back soon

**Comment by daten-shi** [comment]
why is this happening ??

**Comment by daten-shi** [comment]
@MyNickIsBetter  @tijntjuh  @GenPage  @Aleksa234  @CratorCZ  returned

**Comment by daten-shi** [comment]
Galley giving error again for you guys too well ta ??

**Comment by MyNickIsBetter** [comment]
The problem continues :warning: now is offline and i'm can't play with my friends, anyone help?

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
