### ISSUE TITLE
Unespected error

### ISSUE THREAD

**Issue by GmasterGamer** [TechnicPack/TechnicLauncher#843]
Meu minecraft deu um error q se chama Unespected Error e aparece essa mensagem

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: amd64
    Java version: 1.7.0_71 64 bit
    Total Memory: 115 MB
    Max Memory: 1333 MB
    Memory Free: 68 MB
    CPU Cores: 2

Se consiguirem me ajudar agradeço :p

**Comment by MyNickIsBetter** [comment]
Hi, I am brazilian too. I do not know if it is allowed to speak in Portuguese that site, as it is in English, but by the middle of the questions put the topic in English also

Oi, eu sou brasileiro também. Não sei se é permitido falar em português nesse site, já que é um site em inglês, mas pelo meio das dúvidas coloque o tópico em inglês também

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
