### ISSUE TITLE
liu

### ISSUE THREAD

**Issue by liucraft** [TechnicPack/TechnicLauncher#846]
Technic Launcher Error Report:
    Launcher Build: 0

```
Selected Pack: DC vs Marvel
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_71 32 bit
    Total Memory: 37 MB
    Max Memory: 247 MB
    Memory Free: 11 MB
    CPU Cores: 2

**Comment by MyNickIsBetter** [comment]
There are many people having the same problem. I advise not to change anything on your computer, not even make updates or adjust settings on your computer. Those responsible for Technic Launcher will fix this error

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
