### ISSUE TITLE
Multiplayer not working(Technic Launcher)

### ISSUE THREAD

**Issue by MyNickIsBetter** [TechnicPack/TechnicLauncher#847]
I followed the instructions from a forum user and could access the Technic Launcher without giving error, but when I log in to a server is this:
http://prntscr.com/5l7zrq

I have java 7 update 65. Not forgetting that the server is running, but can not login. In vanilla Minecraft'm able to access the multiplayer servers quietly, except Technic Launcher, which is giving this error

Prntscr.com is a reliable site photos

**Comment by benlau109** [comment]
my java is 8

**Comment by MyNickIsBetter** [comment]
Problem solved. Thanks all
