### ISSUE TITLE
Technic Launcher Error Report:

### ISSUE THREAD

**Issue by Craftandoooo** [TechnicPack/TechnicLauncher#848]
Launcher Build: 0

```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows NT (unknown)
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_05 64 bit
    Total Memory: 118 MB
    Max Memory: 883 MB
    Memory Free: 44 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Don't pirate minecraft.

**Comment by LPleonardo** [comment]
???????????

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by matei223** [comment]
de ce nu merge tecitul asta tampi
