### ISSUE TITLE
Technic Launcher Error Report:

### ISSUE THREAD

**Issue by DavidGamer55** [TechnicPack/TechnicLauncher#849]
Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 40 MB
    Max Memory: 247 MB
    Memory Free: 6 MB
    CPU Cores: 4

**Comment by marco-chho** [comment]
me too

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
