### ISSUE TITLE
Can't download mod packs!

### ISSUE THREAD

**Issue by BorderTerrier** [TechnicPack/TechnicLauncher#85]
Hey guys i can't download Aegis Anarchy because this screen pops up saying unexpected error! and stuff anyone help me?

**Comment by Salynne** [comment]
"and stuff" is not at all helpful. Please post actual logs there is a button for making a pastebin of them right on the error dialog.

**Comment by Salynne** [comment]
Fixed in latest beta build.

**Comment by BorderTerrier** [comment]
ok thanks!
