### ISSUE TITLE
wont let me play (unexpected error)

### ISSUE THREAD

**Issue by FangMRider** [TechnicPack/TechnicLauncher#853]
this is what it gives me 
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)
help me here please it worked fine before but i just got my internet back and the n it gives me this

**Comment by CannibalVox** [comment]
Don't pirate minecraft.

**Comment by FangMRider** [comment]
How to fix this

**Comment by FangMRider** [comment]
And what do you me don't pirate minecraft

**Comment by CannibalVox** [comment]
I mean that everyone who is using a non-cracked copy of our launcher got an auto-update that fixed this issue already.
