### ISSUE TITLE
Help Me

### ISSUE THREAD

**Issue by hoangnam1234** [TechnicPack/TechnicLauncher#859]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Hexxit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 50 MB
    Max Memory: 247 MB
    Memory Free: 22 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Don't pirate minecraft.

**Comment by hoangnam1234** [comment]
Im not pirate minecraft Im don't understand because im vietnamese

**Comment by hoangnam1234** [comment]
Plz I want play minecraft hexxit :((((

**Comment by CannibalVox** [comment]
If you didn't pirate minecraft, then redownload your launcher from http://www.technicpack.net/ because you somehow magically ended up with a version of the launcher that identifies itself in error messages as pirated.
