### ISSUE TITLE
Technic Launcher Error

### ISSUE THREAD

**Issue by shidorki** [TechnicPack/TechnicLauncher#86]
I want to try Aegis Anarchy pack

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 191

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:153)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows XP
    Operating System Version: 5.1
    Operating System Architecture: x86
    Java version: 1.7.0_15 32 bit
    Total Memory: 37 MB
    Max Memory: 742 MB
    Memory Free: 18 MB
    CPU Cores: 1

**Comment by Salynne** [comment]
Fixed in latest beta build.
