### ISSUE TITLE
Unexpected Error!

### ISSUE THREAD

**Issue by ggcool4720** [TechnicPack/TechnicLauncher#862]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

I seriousy dont understand whats the problem with this thing now. This is the error above. Please if anyone knows how to fix this tell me.

**Comment by benlau109** [comment]
i did not play hexxit

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
