### ISSUE TITLE
HELP me this error :(

### ISSUE THREAD

**Issue by Iquak998** [TechnicPack/TechnicLauncher#863]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by Iquak998** [comment]
Please help

**Comment by scarpion** [comment]
me too, it happened last morning until last evening, i played last night and this error happended again this morning ultil now i still can play....

**Comment by Adelixis** [comment]
Hi, well I have this problem since this morning ...
then I came here as it was recommended to you and I realized that they are not the only one up to now we are 4/5.
However, if you find a solution let me know.
Thank You

**Comment by benlau109** [comment]
plese help

**Comment by scarpion** [comment]
now i only can put my hope on the Admins or someone...

**Comment by Beetee14** [comment]
The admins told all other people with this error to not pirate Minecraft.

**Comment by CannibalVox** [comment]
Don't pirate minecraft.

**Comment by scarpion** [comment]
^ this guy is Admin?

**Comment by GenPage** [comment]
Yes

**Comment by scarpion** [comment]
so why did he wont let us play?

**Comment by CannibalVox** [comment]
Because you should buy minecraft.

**Comment by Adelixis** [comment]
Yes, you should do, but not everyone can afford it, then what's the harm?

**Comment by scarpion** [comment]
no~ i got minecraft, i bought it, i already bought it one year ago but my friend said hexxit's has more fun two mouths ago and i tried, more fun.

**Comment by CannibalVox** [comment]
Hexxit is great, but using cracked launchers is not so great.  Use the actual, legitimate Technic launcher downloaded from http://technicpack.net/ and you will not have this issue.

**Comment by scarpion** [comment]
ok thanks for the info, im gonna back to minecraft and raping my friend's sever and giving them some heart brokens >:)
