### ISSUE TITLE
erenn

### ISSUE THREAD

**Issue by ernglcmn** [TechnicPack/TechnicLauncher#864]
ben minecraft oynuyorum fren x gammit hexxitten mert diye bi cocugun videosundan izleyip sitesinden indirdim baslarda sıkıntı yoktu simdi ise surekli error verip duruyor bu sorunun en kısa zamanda hallolmasını istiyorum tesekkür ederim

**Comment by ernglcmn** [comment]
özelliklede unexpected erorr veriyor

**Comment by benlau109** [comment]
this is unexpected erorr

**Comment by antoniok** [comment]
```
Selected Pack: Tekkit Classic
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 52 MB
    Max Memory: 247 MB
    Memory Free: 21 MB
    CPU Cores: 2

**Comment by antoniok** [comment]
my tekkit luncher didn't work it is some eror on it pleas fix it

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
