### ISSUE TITLE
Cannot open launcher.

### ISSUE THREAD

**Issue by BarniiLV** [TechnicPack/TechnicLauncher#867]
When i open my launcher it shows this - http://pastebin.com/R8stqjnc
http://prntscr.com/5lh9rs
Can someone help?

**Comment by oskarPeterson** [comment]
I had the same problem quite recently. The stack traces were nearly identical. Only difference was the last item under trace. Mine was slightly different (I had
      org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)
instead of 
     org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)
.)

**Comment by CannibalVox** [comment]
Don't pirate minecraft.

**Comment by oskarPeterson** [comment]
I have purchased Minecraft.

**Comment by CannibalVox** [comment]
The guy who posted the issue has not- that is why you no longer have the problem and he does.

**Comment by oskarPeterson** [comment]
I see. Thank you.
