### ISSUE TITLE
Launcher Error

### ISSUE THREAD

**Issue by Saron** [TechnicPack/TechnicLauncher#87]
Im trying to launch Voltz, but the same error appears whatever pack i choose:

```
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 191
----------------------------------------------------------------------
Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:118)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)
----------------------------------------------------------------------
System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_15 64 bit
    Total Memory: 245 MB
    Max Memory: 7281 MB
    Memory Free: 195 MB
    CPU Cores: 8
```

BTW duno why it says amd64, i have an Inteli7

**Comment by ghost** [comment]
Just to add to the list, I do get the same error, but only when trying to download Voltz 1.1.0, though my System Information is a bit different, nothing major.

@Saron The amd64 is your OS Architecture, not your CPU.

**Comment by Saron** [comment]
just read a bit on that, and yes amd64 is just what Windows 7 64bit is defined as. Anyway, few more details. When i click Launcher, it says connecting to minecraft.net, and after a few seconds it pops up with the above mentioned error. It hasnt been able to download any of the packs. 
I havnt played minecraft since September so this is the first time with the new launcher, and to make sure it was fresh, i backed up my worlds, then deleted the technic folders. Ive disabled my firewal software incase that was causing problems, seeing as the errors seem to be something to do with update, but no luck.

**Comment by Salynne** [comment]
Voltz 1.1.0 was broken. It has since been fixed.

As for getting it on every pack I don't know what to tell you. That error is because the launcher was unable to get build information from the web. I made the error more clear in the latest beta build, you can try going in your launcher options and switching to Beta builds and then restarting.
