### ISSUE TITLE
Não consigo se quer logar o erro é instantâneo, logo ao abrir. Por favor me ajudem!

### ISSUE THREAD

**Issue by 12121212121212** [TechnicPack/TechnicLauncher#870]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: amd64
    Java version: 1.7.0_71 64 bit
    Total Memory: 75 MB
    Max Memory: 883 MB
    Memory Free: 20 MB
    CPU Cores: 2

**Comment by 12121212121212** [comment]
choro;-;

**Comment by adrianohand** [comment]
eu estou na mesma stuação

**Comment by MyNickIsBetter** [comment]
@12121212121212 @adrianohand Pessoal, baixem o CTL 8 por enquanto. Deletem toda a pasta .technic, mas atenção: faça o backup dos seus ModPacks e saves e depois coloquem tudo de volta na pasta ModPacks, depois abram o Technic Launcher novamente e me avisem se resolveu o problema

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
