### ISSUE TITLE
Can`t start my technic launcher

### ISSUE THREAD

**Issue by scheunendrescher123** [TechnicPack/TechnicLauncher#876]
always when i start my technic Launcher this error displays...please help (sorry for my bad english)

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Hosencorp
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_13 64 bit
    Total Memory: 243 MB
    Max Memory: 3619 MB
    Memory Free: 179 MB
    CPU Cores: 8

**Comment by scheunendrescher123** [comment]
ok if i turn my Internet off it seems to work

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
