### ISSUE TITLE
ctl 11

### ISSUE THREAD

**Issue by irmantas88** [TechnicPack/TechnicLauncher#877]
Launcher.java:105)

**Comment by hackerforallgames** [comment]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Tha Apple: The Food Modpack
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_51 32 bit
    Total Memory: 50 MB
    Max Memory: 247 MB
    Memory Free: 21 MB
    CPU Cores: 2

**Comment by hackerforallgames** [comment]
DUDES PLZ IF ANYBODY KNOWS HOW TO REPAIR THE TECHNIC LAUNCHER I WILL CREATE A YOUTUBE ACCOUNT,POST A VIDEO ABOUT THE PACK AND SHOUT YOU OUT.TRUST ME I NEVER LIE.AT THE END,THIS IS WHY THE WEBSITE IS FOR,NOW IS IT?

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
