### ISSUE TITLE
Launcher Error

### ISSUE THREAD

**Issue by tetrisdev** [TechnicPack/TechnicLauncher#88]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 191

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft!
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.8.2
    Operating System Architecture: x86_64
    Java version: 1.6.0_41 64 bit
    Total Memory: 81 MB
    Max Memory: 3063 MB
    Memory Free: 41 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
I've updated the launcher to add more details to this error message.
