### ISSUE TITLE
help !

### ISSUE THREAD

**Issue by muratfatih** [TechnicPack/TechnicLauncher#880]
Stack Trace:
Exception: IndexOutOfBoundsException
Message: Index: 0, Size: 0
Trace:
java.util.ArrayList.rangeCheck(Unknown Source)
java.util.ArrayList.get(Unknown Source)
org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by ChiLLzx** [comment]
Yea, me too. :( PLS HELP US! :(
- http://prntscr.com/5ls0jv

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
