### ISSUE TITLE
Ajudaa!!

### ISSUE THREAD

**Issue by AlexGamerPt** [TechnicPack/TechnicLauncher#885]
Technic Relatar erro Launcher:
(Por favor, envie este relatório para https://github.com/TechnicPack/TechnicLauncher/issues)
    Lançador de construção: 0

```
Pacote Selecionado: Tekkit
```

Stack Trace:
    Exceção: IndexOutOfBoundsException
    Mensagem: Index: 0, Tamanho: 0
    Trace:
        java.util.ArrayList.rangeCheck (origem desconhecida)
        java.util.ArrayList.get (origem desconhecida)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles (NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles (NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher $ 2.run (Launcher.java:105)

Informações sobre o sistema:
    Sistema operacional: Windows 7
    Versão do sistema operacional: 6.1
    Sistema operacional Arquitetura: x86
    Java versão: 1.7.0_71 32 bit
    Memória Total: 38 MB
    Max Memória: 247 MB
    Memória livre: 6 MB
    Núcleo do processador: 2

O que eu faço??

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
