### ISSUE TITLE
Technic Launcher Problem Launcher:439

### ISSUE THREAD

**Issue by BourgonLaurent** [TechnicPack/TechnicLauncher#886]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 439

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_72 64 bit
    Total Memory: 114 MB
    Max Memory: 1701 MB
    Memory Free: 56 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
It sounds like your launcher is not auto-updating for some reason.  Download the new version of launcher from the website.
