### ISSUE TITLE
launcher crashed

### ISSUE THREAD

**Issue by j2ghz** [TechnicPack/TechnicLauncher#89]
http://pastebin.com/QCtSaK1i
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 191

Stack Trace:
    Exception: WrappedIOException
    Message: Failed to download https://dl.dropbox.com/s/l4a434cqxse71t3/Roots.zip?token_hash=AAEeT5P1XB7pn2g5ZldaYX7oeM0aOQo6xKCnq1TeWKAZ2Q&dl=1
    Trace:
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:428)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)
        Caused By: (DownloadException)
            [Unable to download file]
            org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:70)
            org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:428)
            org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
##             org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows Vista
    Operating System Version: 6.0
    Operating System Architecture: x86
    Java version: 1.7.0_15 32 bit
    Total Memory: 56 MB
    Max Memory: 989 MB
    Memory Free: 28 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
This is a problem with the roots pack. His dropbox was temporarily disabled due to extreme bandwidth.
