### ISSUE TITLE
Launcher crash

### ISSUE THREAD

**Issue by misuto** [TechnicPack/TechnicLauncher#891]
How to reproduce: Start launcer
Crash report: http://pastebin.com/tRsDaYvf
OS: Antergos
Java: java version "1.7.0_71"
OpenJDK Runtime Environment (IcedTea 2.5.3) (Arch Linux build 7.u71_2.5.3-3-x86_64)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

**Comment by CannibalVox** [comment]
For some strange reason your launcher didn't auto-update.  You can download the latest version from our website.

**Comment by misuto** [comment]
I have tried that aswell. And in that version TPPI wont start.

**Comment by CannibalVox** [comment]
Well that's a different error, feel free to open an issue for that.
