### ISSUE TITLE
suddenly no longer working

### ISSUE THREAD

**Issue by smurdd** [TechnicPack/TechnicLauncher#892]
So for a while the launcher has been working fine, then just 2 days ago I starting getting an error on start-up. Sometimes It wouldn't pop up and I could make it through and play, but sounds weren't working. And now I only get the error at start-up. 
http://pastebin.com/n0hdGnEt

**Comment by CannibalVox** [comment]
It  looks like for whatever strange reason your launcher isn't auto-updating.  We rolled out a new version, and you can download it manually from technicpack.net
