### ISSUE TITLE
Technic Launcher Error Report

### ISSUE THREAD

**Issue by Revu** [TechnicPack/TechnicLauncher#895]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: DeliciaPack - A Era Ancestral
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_55 64 bit
    Total Memory: 135 MB
    Max Memory: 905 MB
    Memory Free: 86 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Don't pirate minecraft.

**Comment by Revu** [comment]
I have no money to buy the original minecraft

**Comment by CannibalVox** [comment]
Okay well go complain at the people who made your cracked launcher, not us.
