### ISSUE TITLE
Unexpected Error! People help me solve it !!!

### ISSUE THREAD

**Issue by Igor11001** [TechnicPack/TechnicLauncher#898]
Before worked normal, already tried to download again and not vain, I want to help please!...

Error:

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by BarniiLV** [comment]
I know how to get into modpacks, you have to turn off your internet and go to modpack, hit play and turn internet back, if modpack is not installet you have to fast go into launcher without nickname and press play onto that modpack which you want.

**Comment by CannibalVox** [comment]
Don't pirate minecraft.
