### ISSUE TITLE
Started Getting this error when try to launch Technic. Anyone know what's happened?

### ISSUE THREAD

**Issue by Dannnyyyc123** [TechnicPack/TechnicLauncher#900]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Base Modpack 1.6.4
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_71 64 bit
    Total Memory: 84 MB
    Max Memory: 681 MB
    Memory Free: 54 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
What happened is you're using a cracked launcher and need to stop doing that.
