### ISSUE TITLE
 Hexxit Mod won't start

### ISSUE THREAD

**Issue by derfette** [TechnicPack/TechnicLauncher#904]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_55 32 bit
    Total Memory: 44 MB
    Max Memory: 247 MB
    Memory Free: 19 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
Please don't pirate minecraft. :(  Use the real launcher instead of a cracked launcher and this won't happen.
