### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Lecrash12** [TechnicPack/TechnicLauncher#905]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Hexxit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_65 32 bit
    Total Memory: 45 MB
    Max Memory: 247 MB
    Memory Free: 20 MB
    CPU Cores: 2

**Comment by Lecrash12** [comment]
help please

**Comment by CannibalVox** [comment]
Solution: don't use cracked launchers, use the actual Technic launcher.

**Comment by CannibalVox** [comment]
Or, failing that, don't report issues with your cracked launcher in the Technic launcher github!

**Comment by Lecrash12** [comment]
i dont have

**Comment by CannibalVox** [comment]
If you don't have a cracked launcher but instead a legitimate launcher that magically for no reason at all fails to auto-update and also identifies itself as cracked in its error reports, please head to http://technicpack.net/ where you can download the latest version which does not have this issue.
