### ISSUE TITLE
Cracked Technic launcher 15 !

### ISSUE THREAD

**Issue by MrOlolosh** [TechnicPack/TechnicLauncher#907]
Please ..help me :( ! I got this Error :
1.Technic Launcher Error Report:
2.( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
3.    Launcher Build: 0
4. 
5.    Selected Pack: Attack of the B-Team
6.Stack Trace:
7.    Exception: IndexOutOfBoundsException
8.    Message: Index: 0, Size: 0
1.    Trace:
2.        java.util.ArrayList.rangeCheck(Unknown Source)
3.        java.util.ArrayList.get(Unknown Source)
4.        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
5.        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
6.        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)
7. 

16.System Information:
17.    Operating System: Windows 7
18.    Operating System Version: 6.1
19.    Operating System Architecture: amd64
20.    Java version: 1.7.0_09 64 bit
21.    Total Memory: 122 MB
22.    Max Memory: 666 MB
23.    Memory Free: 81 MB
24.    CPU Cores: 4

**Comment by CannibalVox** [comment]
Don't use cracked launchers.  We are not the makers of the cracked launcher, we are the makers of the not-cracked launcher and are really tired of hearing about all the problems the cracked launcher has.
