### ISSUE TITLE
  java.util.ArrayList.rangeCheck(Unknown Source)         java.util.ArrayList.get(Unknown Source)         org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)         org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)         org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

### ISSUE THREAD

**Issue by Radka-f** [TechnicPack/TechnicLauncher#908]
java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
Please stop reporting issues with your cracked launcher.  We didn't make it, we made the launcher they cracked.
