### ISSUE TITLE
The Issue

### ISSUE THREAD

**Issue by Awesomehaloguy** [TechnicPack/TechnicLauncher#909]
```
Launcher Build: 0

Selected Pack: Tekkit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 38 MB
    Max Memory: 247 MB
    Memory Free: 5 MB
    CPU Cores: 4

What is the problem?

**Comment by CannibalVox** [comment]
The problem is you're using a cracked launcher, and the fact that it doesn't work is not my problem.
