### ISSUE TITLE
Launcher crashed when trying to update to latest voltz

### ISSUE THREAD

**Issue by mateimatheo** [TechnicPack/TechnicLauncher#91]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 191

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft!
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_10 64 bit
    Total Memory: 147 MB
    Max Memory: 910 MB
    Memory Free: 99 MB
    CPU Cores: 4

**Comment by skill4kill** [comment]
I am having the same issue.

**Comment by Asavira** [comment]
Same issue....

**Comment by Salynne** [comment]
I updated the launcher to give this a more clear error message. The latest version of Voltz has been having some issues as well.
