### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by gabmilanesi** [TechnicPack/TechnicLauncher#913]
```
Launcher Build: 0

Selected Pack: Official Crafting Dead
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: x86
    Java version: 1.7.0_71 32 bit
    Total Memory: 39 MB
    Max Memory: 247 MB
    Memory Free: 4 MB
    CPU Cores: 2
help me please

**Comment by CannibalVox** [comment]
Don't use cracked launchers.  They're bad and break a lot.
