### ISSUE TITLE
Started Getting this Error:

### ISSUE THREAD

**Issue by CreeperBros123** [TechnicPack/TechnicLauncher#915]
http://pastebin.com/KuFbhPZa

**Comment by knightairon** [comment]
Selected Pack: Attack of the B-Team
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
Stop using cracked launchers, use the legitimate technic launcher and you won't have this problem.
