### ISSUE TITLE
Technic Launcher Unexpected error

### ISSUE THREAD

**Issue by Bilakor** [TechnicPack/TechnicLauncher#916]
![screenshot_2](https://cloud.githubusercontent.com/assets/10346075/5585861/74911536-906f-11e4-807e-8ffc19517bdc.png)

I got this unexpected error all the sudden. It was fine before but all the sudden it started showing this and i cant even log in. Right when i open it this suddenly pops up. Can someone please help me?

**Comment by wesleyrian** [comment]
staff not emcontrei how to resolve this error please emtrem contact me by skype: chapolinnryann

**Comment by CannibalVox** [comment]
Your launcher is cracked. That is why it doesn't work.
