### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by kristupas098** [TechnicPack/TechnicLauncher#917]
error:
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Tekkit Classic
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 53 MB
    Max Memory: 247 MB
    Memory Free: 15 MB
    CPU Cores: 4

on technic launcher says:
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

please help!

**Comment by CannibalVox** [comment]
Your launcher is cracked so you should stop using it, or ask the people who cracked the launcher for help instead of the people whose launcher they cracked.
