### ISSUE TITLE
minecraft error

### ISSUE THREAD

**Issue by Bilakor** [TechnicPack/TechnicLauncher#919]
![screenshot_3](https://cloud.githubusercontent.com/assets/10346075/5591561/09e39e34-911e-11e4-8937-8f09f747deee.png)

i have this error that occurs now. It was fine but now it doesn't work.

**Comment by mesutRSTR** [comment]
help :(

**Comment by CannibalVox** [comment]
Bliakor, your java version is extremely old.  Could you try updating it?
