### ISSUE TITLE
IDK

### ISSUE THREAD

**Issue by kurozypher** [TechnicPack/TechnicLauncher#92]
What does this mean and how do i solve it?
Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:118)
        org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

**Comment by Salynne** [comment]
This error message shouldn't be happening anymore.
