### ISSUE TITLE
I have a problem with is...

### ISSUE THREAD

**Issue by Iamloki7bro** [TechnicPack/TechnicLauncher#921]
```
Launcher Build: 0

Selected Pack: Hack Slash Mine
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8.1
    Operating System Version: 6.3
    Operating System Architecture: amd64
    Java version: 1.8.0_25 64 bit
    Total Memory: 129 MB
    Max Memory: 1799 MB
    Memory Free: 91 MB
    CPU Cores: 4

**Comment by Iamloki7bro** [comment]
So, What i do now...

**Comment by CannibalVox** [comment]
Buy minecraft, download the legitimate technic launcher, stop using cracked launchers.
