### ISSUE TITLE
Please help Technic launcher unexpected error

### ISSUE THREAD

**Issue by Paul1122** [TechnicPack/TechnicLauncher#922]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_55 64 bit
    Total Memory: 115 MB
    Max Memory: 887 MB
    Memory Free: 66 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
Don't use cracked launchers, problem solved.

**Comment by Paul1122** [comment]
So why everybody can use cracked technic and i can't ?

**Comment by CannibalVox** [comment]
Nobody can use cracked technic.  Everybody can use regular technic from technicpack.net/
