### ISSUE TITLE
Technic Launcher Unexpected Error

### ISSUE THREAD

**Issue by Maligelisim** [TechnicPack/TechnicLauncher#923]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

What can I do for open the Technic Launcher? Please help me!

**Comment by slenderdark** [comment]
Stack Trace:
Exception: IndexOutOfBoundsException
Message: Index: 0, Size: 0
Trace:
java.util.ArrayList.rangeCheck(Unknown Source)
java.util.ArrayList.get(Unknown Source)
org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

What can I do for open the Technic Launcher? Please help me!

**Comment by CannibalVox** [comment]
Stop using cracked launchers.
