### ISSUE TITLE
eror please update my version!!!!

### ISSUE THREAD

**Issue by nejmajncraftletsplayer** [TechnicPack/TechnicLauncher#925]

**Comment by KillerRex97** [comment]
-_-

**Comment by Rodrigooooo** [comment]
Selected Pack: Minecraft A Serie 02
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_71 32 bit
    Total Memory: 52 MB
    Max Memory: 247 MB
    Memory Free: 27 MB
    CPU Cores: 4

**Comment by nmiki56002** [comment]
me to how to open a tehnic ancher pls help

**Comment by CannibalVox** [comment]
We have updated the Tehnic Launcher.  A week ago now.  You are using a cracked launcher- either start using the real one or stop bothering us when it doesn't work.
