### ISSUE TITLE
Unexpected Error!  Wtf? Please help me 

### ISSUE THREAD

**Issue by M3triXxX** [TechnicPack/TechnicLauncher#926]
when i open thechnicpack they tell me that : 
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

PLEASE HELP ME

**Comment by batuhan4029** [comment]
helllppppp

**Comment by Highplayers** [comment]
I have the same problem please help  usssssssssssssssssssssssssssssss
hurry up!!!!

**Comment by CannibalVox** [comment]
You all have cracked launchers.  We don't make your cracked launchers, we make the real one.  Go bother somebody else.
