### ISSUE TITLE
I have an error on my Technic Launcher

### ISSUE THREAD

**Issue by TailstheFox** [TechnicPack/TechnicLauncher#928]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)
 I don't understand if they tell me

**Comment by slenderdark** [comment]
Stack Trace:
Exception: IndexOutOfBoundsException
Message: Index: 0, Size: 0
Trace:
java.util.ArrayList.rangeCheck(Unknown Source)
java.util.ArrayList.get(Unknown Source)
org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)
I don't understand if they tell me

**Comment by ilyasan** [comment]
help guys it s saying to me Stack Trace:
Exception: IndexOutOfBoundsException
Message: Index: 0, Size: 0
Trace:
java.util.ArrayList.rangeCheck(Unknown Source)
java.util.ArrayList.get(Unknown Source)
org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)
I don't understand if they tell me

**Comment by Gamer3000** [comment]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
Stop bothering us about your cracked launcher.  We don't care if your cracked launcher stops working, we make the real one.
