### ISSUE TITLE
Issue with updating voltz

### ISSUE THREAD

**Issue by skill4kill** [TechnicPack/TechnicLauncher#93]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 191

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft!
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_09 32 bit
    Total Memory: 38 MB
    Max Memory: 989 MB
    Memory Free: 2 MB
    CPU Cores: 2

**Comment by tadpole89** [comment]
Same problem D:

**Comment by sct** [comment]
Open the Voltz options. Switch it to latest or recommended and hit save. Then try again.

**Comment by skill4kill** [comment]
The thing is, I run latest fine, but most of the servers require 1.1.0 which is a manual select. That is where this error comes up.

I also run recommended fine aswell.

**Comment by Asavira** [comment]
I have the exact same problem...

**Comment by Salynne** [comment]
Voltz has had some issues lately. We'll get it fixed.
