### ISSUE TITLE
Error - Technic Launcher

### ISSUE THREAD

**Issue by Gibon123** [TechnicPack/TechnicLauncher#931]
Help please!! Technic Launcher Error = An unexpacted error has occured - Please report to https://github.com/TechnicPack/TechnicLauncher/issues

What should I do ???!!

**Comment by CannibalVox** [comment]
report the issue instead of asking about reporting the issue?  I need to see what it says.

**Comment by leonardo14702162** [comment]
Hello ifron is brazil. may help me my problem is my techniclauncher not open. and opens this mensage could help me
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by belliamk** [comment]
sgsdg

**Comment by Gibon123** [comment]
Exactly this: 
Stack Trace:
Exception: IndexOutOfBoundsException
Message: Index: 0, Size: 0
Trace:
java.util.ArrayList.rangeCheck(Unknown Source)
java.util.ArrayList.get(Unknown Source)
org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

Help please :D :/

**Comment by CannibalVox** [comment]
You're using a cracked launcher.  Stop doing that.
