### ISSUE TITLE
hi, someone please help me !!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by SkyEucalipt** [TechnicPack/TechnicLauncher#932]
help me !!!! I'm getting angry about it !!!!!!!! please help meeee!!!!!!!!!!!
Photos : 
![image](https://cloud.githubusercontent.com/assets/10367122/5593531/d3898456-91fa-11e4-94b5-a31ddc672024.png)

**Comment by CannibalVox** [comment]
Stop using cracked launchers, start using the official technic launcher from http://technicpack.net/ and you won't have this problem anymore.
