### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by leonardo14702162** [TechnicPack/TechnicLauncher#934]
Hello ifron is brazil. may help me my problem is my techniclauncher not open. and opens this mensage could help me
Stack Trace:
Exception: IndexOutOfBoundsException
Message: Index: 0, Size: 0
Trace:
java.util.ArrayList.rangeCheck(Unknown Source)
java.util.ArrayList.get(Unknown Source)
org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
Stop using cracked launchers.  Use our legitimate launcher from http://www.technicpack.net/

**Comment by leonardo14702162** [comment]
tanks
