### ISSUE TITLE
Technic Launcher Error Report

### ISSUE THREAD

**Issue by IceAssassin11** [TechnicPack/TechnicLauncher#937]
Launcher Build: 0

```
Selected Pack: Tekkit Classic
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.8.0_25 64 bit
    Total Memory: 77 MB
    Max Memory: 900 MB
    Memory Free: 28 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
Stop using cracked launchers.  Instead use the legitimate launcher from http://www.technicpack.net
