### ISSUE TITLE
Technic Laucher 

### ISSUE THREAD

**Issue by maskeren** [TechnicPack/TechnicLauncher#938]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: PixelMon C 3.3.2
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_45 64 bit
    Total Memory: 111 MB
    Max Memory: 883 MB
    Memory Free: 38 MB
    CPU Cores: 4

**Comment by LOLZ324324235** [comment]
same

**Comment by CannibalVox** [comment]
Don't use cracked launchers. Get the real launcher from http://www.technicpack.net/

**Comment by maskeren** [comment]
I dont have the money to buy it......
:(
