### ISSUE TITLE
neet help!!!

### ISSUE THREAD

**Issue by agusindrapratama** [TechnicPack/TechnicLauncher#940]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0
    Selected Pack: Tekkit
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)
System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 56 MB
    Max Memory: 247 MB
    Memory Free: 31 MB
    CPU Cores: 8

**Comment by LOLZ324324235** [comment]
i have the same

**Comment by CannibalVox** [comment]
Don't use cracked launchers. Get the real launcher from http://www.technicpack.net/
