### ISSUE TITLE
Technic Launcher Error

### ISSUE THREAD

**Issue by icaroSL** [TechnicPack/TechnicLauncher#945]
![technic erro](https://cloud.githubusercontent.com/assets/10376526/5600677/a3fc7924-92c6-11e4-9f22-ed5f0e290b50.png)

Error

**Comment by CannibalVox** [comment]
DOGG YOU'VE GOT THE CRACKED LAUNCHER MARK RIGHT THERE IN YOUR PICTURE.

IT'S RIGHT THERE.

ARE YOU EVEN TRYING DOGG.
