### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by decade111** [TechnicPack/TechnicLauncher#948]
When i open Technic Launcher this happen:
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.RangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
Stop using cracked launcher and instead use the legitimate Technic Launcher from http://www.technicpack.net/
