### ISSUE TITLE
Tekkit wont launch!

### ISSUE THREAD

**Issue by Asavira** [TechnicPack/TechnicLauncher#95]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 191

Stack Trace:
    Exception: IOException
    Message: Failed to download Minecraft!
    Trace:
        org.spoutcraft.launcher.util.MinecraftDownloadUtils.downloadMinecraft(MinecraftDownloadUtils.java:93)
        org.spoutcraft.launcher.UpdateThread.updateMinecraft(UpdateThread.java:318)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:122)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.8.0-ea 64 bit
    Total Memory: 77 MB
    Max Memory: 989 MB
    Memory Free: 14 MB
    CPU Cores: 2

**Comment by Salynne** [comment]
I've added more information to this error. Report it if you get it again.
