### ISSUE TITLE
Unexpected error 

### ISSUE THREAD

**Issue by RageIP** [TechnicPack/TechnicLauncher#951]
a window of "Unexpected error" keep showing every time i open the launcher and i cant start any game

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: sky factory
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_72 64 bit
    Total Memory: 121 MB
    Max Memory: 1799 MB
    Memory Free: 61 MB
    CPU Cores: 8

RAW Paste Data
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: sky factory 
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.7.0_72 64 bit
    Total Memory: 121 MB
    Max Memory: 1799 MB
    Memory Free: 61 MB
    CPU Cores: 8

**Comment by CannibalVox** [comment]
Stop using cracked launchers and get the legitimate launcher at http://www.technicpack.net/

**Comment by RageIP** [comment]
but i got my account not long ago and i don't want to lose my world

**Comment by CannibalVox** [comment]
Back up your .technic folder, download the new launcher, re-install the pack, and then copy over your world into the updated .technic folder.

**Comment by CannibalVox** [comment]
It should work automatically but some users have reported problems so I wouldn't take any chances.  It might just work and your world will be unharmed, though.

**Comment by RageIP** [comment]
thank you i will try

**Comment by RageIP** [comment]
thank you very much. all good now

**Comment by CannibalVox** [comment]
Glad to hear it- have fun!
