### ISSUE TITLE
Help...

### ISSUE THREAD

**Issue by Chubix** [TechnicPack/TechnicLauncher#952]
Selected Pack: Tekkit
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
Stop using cracked launchers and get the legitimate launcher from http://www.technicpack.net/

**Comment by Chubix** [comment]
thank u for the link

**Comment by Chubix** [comment]
Wait,do i need to have premium minecraft to have it ?? :|

**Comment by CannibalVox** [comment]
Yeah, bro.

**Comment by Chubix** [comment]
pffffffffff not eve worth then.

**Comment by CannibalVox** [comment]
lol good luck then
