### ISSUE TITLE
technic launcher error 

### ISSUE THREAD

**Issue by deralbaner** [TechnicPack/TechnicLauncher#953]
Technic Launcher Error Report:

Selected Pack: Hexxit
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_51 32 bit
    Total Memory: 45 MB
    Max Memory: 247 MB
    Memory Free: 17 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
Stop using cracked launchers and get the legitimate technic launcher http://www.technicpack.net/
