### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by MRBaroosh911** [TechnicPack/TechnicLauncher#957]
1.Technic Launcher Error Report:

2.( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
1.    Launcher Build: 0
3.    Selected Pack: Hexxit

6.Stack Trace:
1.    Exception: IndexOutOfBoundsException
2.    Message: Index: 0, Size: 0
3.    Trace:
4. ```
      java.util.ArrayList.rangeCheck(Unknown Source)
   ```
5. ```
      java.util.ArrayList.get(Unknown Source)
   ```
6. ```
      org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
   ```
7. ```
      org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
   ```
8. ```
      org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)
   ```

16.System Information:
1.    Operating System: Windows 7
2.    Operating System Version: 6.1
3.    Operating System Architecture: amd64
4.    Java version: 1.7.0_51 64 bit
5.    Total Memory: 111 MB
6.    Max Memory: 423 MB
7.    Memory Free: 49 MB
8.    CPU Cores: 4

**Comment by CannibalVox** [comment]
Stop using cracked launchers- download the legitimate technic launcher from http://www.technicpack.net/

**Comment by MRBaroosh911** [comment]
thanks you my friend (=
