### ISSUE TITLE
Minecraft has crashed PLEASE HELP ME!!!!

### ISSUE THREAD

**Issue by KaWerIchBin** [TechnicPack/TechnicLauncher#959]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
Stop using cracked launchers.  Get the legitimate technic launcher from http://www.technicpack.net/
