### ISSUE TITLE
Unexpected Error! What to do?

### ISSUE THREAD

**Issue by KirbyFreak** [TechnicPack/TechnicLauncher#961]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 53 MB
    Max Memory: 247 MB
    Memory Free: 13 MB
    CPU Cores: 4

**Comment by KirbyFreak** [comment]
This Error comes, when i click anywhere on the Launcher startup. Without Internet i am able to enter a Name then go further, but when i connect to Internet again, and try to install a pack it says that it is corrupted or something.

**Comment by karolis1115** [comment]
hm same here :( but it defenetly has to do something with java or the internet

**Comment by CannibalVox** [comment]
Stop using cracked launchers and get the legitimate launcher at http://www.technicpack.net/
