### ISSUE TITLE
help tenhiclauncher unexpected error (linux mint 17.1 cinamon) 

### ISSUE THREAD

**Issue by karolis1115** [TechnicPack/TechnicLauncher#962]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(ArrayList.java:635)
        java.util.ArrayList.get(ArrayList.java:411)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Linux
    Operating System Version: 3.13.0-37-generic
    Operating System Architecture: amd64
    Java version: 1.7.0_65 64 bit
    Total Memory: 100 MB
    Max Memory: 652 MB
    Memory Free: 38 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Stop using cracked launchers and get the legitimate launcher at http://www.technicpack.net/

**Comment by karolis1115** [comment]
i am using the leginament shut up if you dont know that

**Comment by CannibalVox** [comment]
Your error report says it's a cracked launcher, but if it's started reporting itself as cracked, magically, for no reason, then downloading the new launcher from the website above will fix it.
