### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by oyuncu457** [TechnicPack/TechnicLauncher#963]
java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
Stop using cracked launchers and get the legitimate launcher at http://www.technicpack.net/
