### ISSUE TITLE
technic error

### ISSUE THREAD

**Issue by LDFGamer** [TechnicPack/TechnicLauncher#964]
everytime when i open the technic appear this error

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.RangeCheck(ArrayList.java:547)
        java.util.ArrayList.get(ArrayList.java:322)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

and i don't know what to do
please anyone help me

**Comment by CannibalVox** [comment]
Stop using cracked launchers and get the legitimate launcher at http://www.technicpack.net/
