### ISSUE TITLE
help tenhiclauncher unexpected error (linux mint 17.1 cinamon)

### ISSUE THREAD

**Issue by karolis1115** [TechnicPack/TechnicLauncher#965]
i dont get it when im disconected from the internet

echnic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Tekkit Classic
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(ArrayList.java:635)
        java.util.ArrayList.get(ArrayList.java:411)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Linux
    Operating System Version: 3.13.0-37-generic
    Operating System Architecture: amd64
    Java version: 1.7.0_65 64 bit
    Total Memory: 89 MB
    Max Memory: 652 MB
    Memory Free: 28 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
You already opened an issue for this and I already responded.
