### ISSUE TITLE
Technic Launcher

### ISSUE THREAD

**Issue by theboss306** [TechnicPack/TechnicLauncher#966]
Selected Pack: Tekkit Classic
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 53 MB
    Max Memory: 247 MB
    Memory Free: 23 MB
    CPU Cores: 2

This is the problem....

**Comment by CannibalVox** [comment]
Stop using cracked launchers and get the legitimate launcher at http://www.technicpack.net/
