### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lukasz12** [TechnicPack/TechnicLauncher#967]
Selected Pack: Yogbox
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.8.0_25 64 bit
    Total Memory: 120 MB
    Max Memory: 910 MB
    Memory Free: 76 MB
    CPU Cores: 2

Help

**Comment by CannibalVox** [comment]
Stop using cracked launchers and get the legitimate launcher at http://www.technicpack.net/
