### ISSUE TITLE
error after some updates

### ISSUE THREAD

**Issue by ruffo1970** [TechnicPack/TechnicLauncher#968]
Last time I launched technicLauncher I was asked to perform some updates. From that time on I always get this error:

Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_65 32 bit
    Total Memory: 51 MB
    Max Memory: 247 MB
    Memory Free: 29 MB
    CPU Cores: 6

Any suggestion?
Thanks

**Comment by CannibalVox** [comment]
That's interesting- your launcher is identifying as a  cracked launcher, and also didn't update to the new launcher.  You can get the new one at http://www.technicpack.net/
