### ISSUE TITLE
I always help of this unfortunate error with any technic q I try baxa.

### ISSUE THREAD

**Issue by Ghoul5** [TechnicPack/TechnicLauncher#971]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

**Comment by CannibalVox** [comment]
Download the new version of the launcher from http://www.technicpack.net/
