### ISSUE TITLE
Error Please HELP!

### ISSUE THREAD

**Issue by sino585** [TechnicPack/TechnicLauncher#972]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Official Crafting Dead
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.RangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.6.0_18-ea 64 bit
    Total Memory: 74 MB
    Max Memory: 682 MB
    Memory Free: 33 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
Download the newest version of the technic launcher from http://www.technicpack.net/
