### ISSUE TITLE
Debian Wheezy: IndexOutOfBoundsException in launcher

### ISSUE THREAD

**Issue by andy-twosticks** [TechnicPack/TechnicLauncher#974]
I ran the launcher as normal, and got an exception. I can't use the launcher now, this is all I get.

```
 Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(ArrayList.java:571)
        java.util.ArrayList.get(ArrayList.java:349)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.launcher.Launcher$1.run(Launcher.java:82)
```

I've just done an update to get steam working that involved pulling an updated libgc from Sid, and probably some other bits too. I didn't think my Java updated, but all the same this is my best guess as to what changed since I last ran the launcher.  

The whole error report is automatcially on pastebin of course (clever idea!) at http://pastebin.com/0zYVwrd0.  If you need anything else, just say.

**Comment by CannibalVox** [comment]
Hi, it looks like you're having a problem auto-updating your launcher, since this one's a couple weeks old.  We made a pretty massive update on Christmas and this older version is trying to communicate with an API that no longer exists.  Go ahead and head over to http://www.technicpack.net/ and download the updated version.

**Comment by andy-twosticks** [comment]
Hi, thanks for the response.  I'm sorry that you closed this because while your response was helpful I still can't use the launcher:

```
andy@blake[~/andy/INBOX]%: java -jar TechnicLauncher.jar 
Settings for exe: /home/andy/andy/INBOX/TechnicLauncher.jar
Portable settings dir: /home/andy/andy/INBOX/technic
Setting up logging
andy@blake[~/andy/INBOX]%: 
```

That's all the output I get. No UI, no launcher, nothing.  And my daughter has the same problem -- that's actually what I was trying to fix when I found the problem I raised above.

I think maybe this is still an open issue?  But if I get no response by morning (GMT) I'll raise it as a seperate ticket.

**Comment by CannibalVox** [comment]
Hi, Andy,

This has been an issue on Linux in cases where the Linux window manager does not have transparent/translucent window support enabled.  You can verify this by checking the most recent logs in ~/andy/.technic/logs

While the instructions for enabling that support vary from flavor to flavor and manager to manager, we've noticed a few things:
- On Unity desktop shell, you can verify that support is active by attempting to alt+scroll to change the opacity of your current window.  If it is not active, apt-getting the compiz configuration app will allow you to activate it.
- On some linux operating systems, starting the launcher from a command line interface attempts to run the launcher in a fundamentally different environment than starting the launcher by clicking it on the desktop.  From the command line interface, many key capabilities are actually missing.  Some users have had success by starting the launcher from the desktop.

**Comment by andy-twosticks** [comment]
Hi again,

Yes, that seems to be the problem here, too:

```
java.lang.IllegalArgumentException: The window must use a translucency-compatible graphics configuration 
        at java.awt.Window.setOpaque(Window.java:3421)
        at java.awt.Window$1.setOpaque(Window.java:388)
        at com.sun.awt.AWTUtilities.setWindowOpaque(AWTUtilities.java:360)
        at net.technicpack.ui.controls.installation.SplashScreen.<init>(SplashScreen.java:82)
        at net.technicpack.launcher.LauncherMain.startLauncher(LauncherMain.java:208)
        at net.technicpack.launcher.LauncherMain.updateAndRelaunch(LauncherMain.java:309)
        at net.technicpack.launcher.LauncherMain.main(LauncherMain.java:151)
```

As far as I am concerned, though, I _do_ have transparency enabled. I'm running compiz, and other apps with translucent options work fine (and not fake transparency either: dragging around a terminal window, for example, shows the view behind the window at all times, not just when I stop dragging).

When you say "start the launcher from the desktop, what exactly are we talking about here? What command should the desktop shortcut execute?  (I'm actually running Openbox so I don't _have_ desktop shortcuts, but really that shouldn't make any difference...)

**Comment by andy-twosticks** [comment]
Ah. Perhaps part of the problem is that I am _not_ running Compiz, but Compton instead.  This is the default for CrunchBang, and it may be the default for Debian, too, FAIK.

Making transparency a dependancy for the new launcher is going to cause pain to a lot of Linux users, IMO.

**Comment by andy-twosticks** [comment]
**IMPORTANT INFORMATION:** I have resolved the issue at this end. It has _nothing_ to do with transparency or with how you launch java.  The error in the log file was (in my case at least) something of a red herring.

**I was able to run the technic launcher once I upgraded JRE to 1.7.**

On Debian I just did a:

```
sudo apt-get install openjdk-7-jre
```

I have Debian Sid -- Unstable -- in my repository list, so other users _might_ need to do that too. Dunno.

Hope that helps someone...

**Comment by CannibalVox** [comment]
Were you previously on oracle or openjdk?

**Comment by CannibalVox** [comment]
Before the upgrade, I mean.

**Comment by andy-twosticks** [comment]
OpenJdk.

**Comment by CannibalVox** [comment]
You were on 6 previously, or 8?  Or just an older version of 7?

**Comment by andy-twosticks** [comment]
Looks as if I was on what Debian calls "7u3-2.1.7-1".  I am now on 7u71-2.5.3-2. I have no idea whether that makes sense to anyone outside of Debian, though.

**Comment by CannibalVox** [comment]
Yeah, it does.  the 7u3/7u71 are java terminology.

**Comment by CannibalVox** [comment]
Forgot to update this, but the launcher has supported non-translucent window managers for a few weeks now.

**Comment by eren123123** [comment]
Teknik Launcher Hata Raporu: ( Lütfen https://github.com/technicpack/techniclauncher/issues bu rapor gönder ) Başlatıcısı İnşa: 0 Seçili Pack: Yığın İzleme null: özel Durum: İndexOutOfBoundsException İletisi: Dizin: 0, Boyut: 0 İz: java.açıklama.ArrayList.(Bilinmeyen Kaynak) rangeCheck java.açıklama.ArrayList.(Bilinmeyen Kaynak) org.spoutcraft.başlatıcısı.cilt.NewsComponent.setupArticles(NewsComponent.:60 java) org.spoutcraft.başlatıcısı.cilt.NewsComponent.loadArticles(NewsComponent.:46 java) org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105) Sistem Bilgileri İşletim Sistemi: Windows 7 İşletim Sistemi Versiyon: 6.1 İşletim Sistemi Mimarisi: 86 Java sürümü: 1.8.0_31 32 bit Toplam Bellek: 38 MB Max Bellek: 247 MB boş Bellek: 12 MB İŞLEMCİ Çekirdeği: 2

**Comment by eren123123** [comment]
Teknik Launcher Hata Raporu:
( Lütfen https://github.com/technicpack/techniclauncher/issues bu rapor gönder )
Başlatıcı Oluştur: 0

Seçili Paketi: null
Yığın İzleme:
Özel Durum: İndexOutOfBoundsException
Mesaj: Dizin: 0, Size: 0
İzleme:
java.açıklama.ArrayList.rangeCheck(Bilinmeyen Kaynak)
java.açıklama.ArrayList.(Bilinmeyen Kaynak)
org.spoutcraft.başlatıcısı.cilt.NewsComponent.setupArticles(NewsComponent.:60 java)
org.spoutcraft.başlatıcısı.cilt.NewsComponent.loadArticles(NewsComponent.:46 java)
org.spoutcraft.başlatıcısı.Launcher 2 dolar.Çalıştır(Başlatıcısı.:105 java)

Sistem Bilgisi:
İşletim Sistemi: Windows 7
İşletim Sistemi Versiyon: 6.1
İşletim Sistemi Mimarisi: 86
Java sürümü: 1.8.0_31 32 bit
Toplam Hafıza: 38 MB
Max Bellek: 247 MB
Boş bellek: 12 MB
CPU Çekirdek: 2
