### ISSUE TITLE
No me deja entrar al juego :~

### ISSUE THREAD

**Issue by 123IgnacioCapo** [TechnicPack/TechnicLauncher#975]
Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(ArrayList.java:635)
        java.util.ArrayList.get(ArrayList.java:411)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Linux
    Operating System Version: 3.8.0-35-generic
    Operating System Architecture: amd64
    Java version: 1.7.0_45 64 bit
    Total Memory: 91 MB
    Max Memory: 418 MB
    Memory Free: 62 MB
    CPU Cores: 2
clone this paste

**Comment by CannibalVox** [comment]
This is a cracked launcher.  Retrieve the legitimate technic launcher from http://www.technicpack.net/
