### ISSUE TITLE
wont open 

### ISSUE THREAD

**Issue by RobIce3** [TechnicPack/TechnicLauncher#978]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Official Crafting Dead
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(ArrayList.java:635)
        java.util.ArrayList.get(ArrayList.java:411)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.9.5
    Operating System Architecture: x86_64
    Java version: 1.7.0_55 64 bit
    Total Memory: 121 MB
    Max Memory: 910 MB
    Memory Free: 56 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
You are using a cracked launcher.  To fix this issue, download the legitimate launcher from http://www.technicpack.net/
