### ISSUE TITLE
Crashed custom pack

### ISSUE THREAD

**Issue by oVexlz** [TechnicPack/TechnicLauncher#98]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
##     Launcher Build: 195

Stack Trace:
    Exception: MalformedURLException
    Message: no protocol: Custom Pack 1
    Trace:
        java.net.URL.<init>(Unknown Source)
        java.net.URL.<init>(Unknown Source)
        java.net.URL.<init>(Unknown Source)
        org.spoutcraft.launcher.util.Download.<init>(Download.java:55)
        org.spoutcraft.launcher.util.DownloadUtils.downloadFile(DownloadUtils.java:44)
        org.spoutcraft.launcher.UpdateThread.updateModpack(UpdateThread.java:428)
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:129)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: amd64
    Java version: 1.6.0_38 64 bit
    Total Memory: 151 MB
    Max Memory: 2730 MB
    Memory Free: 88 MB
    CPU Cores: 8

Thats my error it crashes when its loading

**Comment by Salynne** [comment]
I have no idea what you did to cause this. Can you give me more details?

**Comment by Salynne** [comment]
This is an issue with the modpack you tried installing. I have fixed it from crashing the launcher, it will tell them to fix their zip url on the website soon too.
