### ISSUE TITLE
can not work well ????????????!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Dat-Ngu** [TechnicPack/TechnicLauncher#982]
Launcher Build: 0

```
Selected Pack: null
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.RangeCheck(ArrayList.java:547)
        java.util.ArrayList.get(ArrayList.java:322)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.9.5
    Operating System Architecture: x86_64
    Java version: 1.6.0_65 64 bit
    Total Memory: 81 MB
    Max Memory: 123 MB
    Memory Free: 42 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
Download the latest launcher from http://www.technicpack.net/ to fix this.
