### ISSUE TITLE
Minecraft TechnicLauncher " Unexpected Error ! "

### ISSUE THREAD

**Issue by Zeeed123456789** [TechnicPack/TechnicLauncher#985]
Hello when I use the TechnicLauncher than appear a new window : 

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

And the options To Generate Report And Close Application 

Pls Help :(

**Comment by ahmed14** [comment]
you can play on offline

**Comment by Zeeed123456789** [comment]
i Play only on offline mode

**Comment by s3km** [comment]
Launcher Build: 0

```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 37 MB
    Max Memory: 247 MB
    Memory Free: 4 MB
    CPU Cores: 2
HELP PLS

**Comment by s3km** [comment]
Launcher Build: 0

```
Selected Pack: Tekkit
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.8.0_25 32 bit
    Total Memory: 37 MB
    Max Memory: 247 MB
    Memory Free: 4 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
cracked

**Comment by s3km** [comment]
what? cracked

**Comment by CannibalVox** [comment]
Your error log has indications that you are using a cracked launcher.  We are not responsible for cracking that launcher, we make the launcher that was cracked.  You should discuss any issues you encounter with the individuals who you downloaded the cracked launcher from, not us.
