### ISSUE TITLE
Unexpexted Error!

### ISSUE THREAD

**Issue by SkyJohnson4466** [TechnicPack/TechnicLauncher#988]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Attack of the B-Team
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(ArrayList.java:635)
        java.util.ArrayList.get(ArrayList.java:411)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Mac OS X
    Operating System Version: 10.9.5
    Operating System Architecture: x86_64
    Java version: 1.7.0_71 64 bit
    Total Memory: 156 MB
    Max Memory: 1820 MB
    Memory Free: 74 MB
    CPU Cores: 4

**Comment by CannibalVox** [comment]
cracked
