### ISSUE TITLE
Crash on startup Tekkit

### ISSUE THREAD

**Issue by F4ll0ut** [TechnicPack/TechnicLauncher#99]
It asked for a update, i clicked yes, then it keeps crashing.

http://pastebin.com/rgpnevZa

---

Stack Trace:
    Exception: NullPointerException
    Message: null
    Trace:
        org.spoutcraft.launcher.UpdateThread.runTasks(UpdateThread.java:118)
##         org.spoutcraft.launcher.UpdateThread.run(UpdateThread.java:107)

System Information:
    Operating System: Windows 8
    Operating System Version: 6.2
    Operating System Architecture: amd64
    Java version: 1.7.0_11 64 bit
    Total Memory: 152 MB
    Max Memory: 1797 MB
    Memory Free: 95 MB
    CPU Cores: 4

**Comment by Salynne** [comment]
This error message shouldn't be happening anymore.
