### ISSUE TITLE
Unexpected Error!

### ISSUE THREAD

**Issue by benas999** [TechnicPack/TechnicLauncher#990]
Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

Please Help Me This Is On Minecraft Teckit launcher

**Comment by Sharp982** [comment]
I am haveing the same problem.I tried almost everything and nothing seemd to work for me.Please if you know the answear to this error post it

**Comment by WCHD** [comment]
This error i have to. I like to play a cool modpack and then this come:

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

I hope i can play mods, of course found i a cool modpack. I speak german also i dont can english so good but help me when you find out the Problem PLS!!!!

**Comment by WCHD** [comment]
Ok i found out the problem
You must play offline and launch your mod then you can play with internet first.

**Comment by CannibalVox** [comment]
cracked
