### ISSUE TITLE
crash when i try opening a game or a modapack

### ISSUE THREAD

**Issue by PanzerVII** [TechnicPack/TechnicLauncher#997]
Technic Launcher Error Report:
( Please submit this report to https://github.com/TechnicPack/TechnicLauncher/issues )
    Launcher Build: 0

```
Selected Pack: Voltz
```

Stack Trace:
    Exception: IndexOutOfBoundsException
    Message: Index: 0, Size: 0
    Trace:
        java.util.ArrayList.rangeCheck(Unknown Source)
        java.util.ArrayList.get(Unknown Source)
        org.spoutcraft.launcher.skin.NewsComponent.setupArticles(NewsComponent.java:60)
        org.spoutcraft.launcher.skin.NewsComponent.loadArticles(NewsComponent.java:46)
        org.spoutcraft.launcher.Launcher$2.run(Launcher.java:105)

System Information:
    Operating System: Windows 7
    Operating System Version: 6.1
    Operating System Architecture: x86
    Java version: 1.7.0_71 32 bit
    Total Memory: 36 MB
    Max Memory: 247 MB
    Memory Free: 1 MB
    CPU Cores: 2

**Comment by CannibalVox** [comment]
cracked

**Comment by PanzerVII** [comment]
it sometimes works

**Comment by CannibalVox** [comment]
It always works if you don't use a cracked launcher.
