### ISSUE TITLE
How to fix the unexepcted Error

### ISSUE THREAD

**Issue by WCHD** [TechnicPack/TechnicLauncher#998]
You can fix it so: You turn off WLAN. An start TechnicLauncher. Launch your Modpack. When you play with your Modpack you can turn your WLAN on. I was so happy i found so a cool Modpack an then TechnicLauncher don't work, but now with this Trick i can Play :).  
PS: I speak German, of course i can not so good english, but i hope my english isn't to bad to check it
LG WolfCrafterHD

**Comment by WCHD** [comment]
This is for all they have this error, i hope it help you :)

**Comment by CannibalVox** [comment]
Other solutions: STOP USING CRACKED LAUNCHERS
